TencentBlueKing/bk-cmdb

- src/common/definitions.go
- src/scene_server/topo_server/topo_service/actions/inst/inst.go
- src/scene_server/topo_server/topo_service/actions/inst/inst_asst.go
- src/scene_server/topo_server/topo_service/ccapi.go
- src/source_controller/api/metadata/object.go
- src/source_controller/common/commondata/data.go
- src/source_controller/common/instdata/object.go
修改底层维护实例关联关系的 api  close #238
update:增加查询条件，在关联查询的时候在查询条件中没有自己条件的情况下，内置一个无效的条件 close #233
抽离公共方法处理关联字段 close #239
> 修改实例关联查询逻辑

- src/scene_server/host_server/host_service/actions/phpapi/host.go
1. 解决通过agent安装的机器，主机详情的录入方式显示空白
> v2 api updatehostbyappid add host not import_from value   close #526

- src/web_server/application/controllers/host.go
- src/web_server/application/controllers/inst.go
- src/web_server/application/controllers/object.go
- src/web_server/application/logics/httpheader.go
#621 
- 把拼写错误的函数名 GetLanugaeByHTTPRequest 修正为 GetLanguageByHTTPRequest
> fixbug: 修正拼写错误的函数名  #621

- src/web_server/application/middleware/auth/public.go
- src/web_server/application/middleware/types/types.go
> 1. 修复有权限账号不能查看关联topo的bug

- src/common/condition/condition.go
- src/common/mapstr/mapstr.go
- src/common/metadata/object_controller.go
- src/scene_server/topo_server/core/model/object.go
- src/scene_server/topo_server/core/operation/association_mainline_object.go
- src/scene_server/topo_server/core/operation/group.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/inst_business.go
- src/scene_server/topo_server/core/operation/inst_module.go
- src/scene_server/topo_server/core/operation/inst_set.go
- src/scene_server/topo_server/core/operation/supplementary_audit.go
- src/scene_server/topo_server/core/privilege/group.go
- src/scene_server/topo_server/core/privilege/privilege.go
- src/scene_server/topo_server/core/privilege/role.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/inst_business.go
- src/scene_server/topo_server/service/inst_module.go
- src/scene_server/topo_server/service/inst_set.go
- 导入实例时多关联字段允许为空
- 修改录入操作审计的bug
- 修复批量更新实例失败的bug
- 修改分组排序
- bk_inst_name 字段ispre 设置为true
- 修复查询实例查询条件不生效的bug
- 修复业务列表排序不生效的的问题
- 恢复默认添加集群和模块的 default 字段
- 修复业务角色授权不生效的bug
- 修复用户角色权限绑定的bug
- 解决角色绑定用户失败的bug
- 查询普通模型拓扑时屏蔽主线模型
> 修复自测的一些列问题

- src/api_server/service/plat.go
- src/scene_server/host_server/service/phpapi.go
- http://{{.apiserver}}/api/v2/Plat/add 新增云区域时如果添加的 platName 重名，返回的报错是“http request failed”，而不是“数据重复”。
> 修复 /api/v2/Plat/add 没有数据重复提示

- src/scene_server/host_server/logics/log.go
- src/scene_server/host_server/service/module.go
- xxxx
- xxxx
- 批量转移主机模块，操作审计日志只记录了第一个机器的数据
close #979
> 批量转移主机模块，操作审计日志只记录了第一个机器的数据

- src/web_server/application/controllers/login.go
- src/web_server/application/middleware/login.go
- xxxx
- 跳转到登录页面时， HTTP 状态使用302而不是301 
- xxxx
close #1027
> LoginPage跳转时使用302而不是301 

- src/scene_server/host_server/logics/host.go
- src/scene_server/host_server/logics/object.go
- xxxx
- xxxx
- 修复资源池根据云区域查询已分配主机无效
close #1040
> 修复资源池根据云区域查询已分配主机无效 

- src/ui/src/api/axios.js
> update: siteUrl use location.origin

- src/scene_server/topo_server/core/operation/inst.go
- 实例关联字段，组织数据时补充 id 取值为 bk_inst_id 值一样
> fixbug: 解决保存实例时候 实例关联字段值被清空的bug

- src/scene_server/host_server/logics/phpapi_host.go
- xxxx
- xxxx
- [v2兼容接口] 获取主机展示模块，集群的名字重复 
close #1157
> [v2兼容接口] 获取主机展示模块，集群的名字重复

- src/scene_server/admin_server/command/import.go
- src/scene_server/admin_server/command/types.go
- src/scene_server/event_server/identifier/identifier.go
- 解决推送主机身份缺少进程信息问题
- 解决导入拓扑进程模块映射表缺少开发商字段问题
> cherry-pick 3.1.1

- src/scene_server/topo_server/core/model/object.go
- src/scene_server/topo_server/core/operation/association_mainline_object.go
- fix a bug when delete mainline object association, which may lead to association chain broken, because of the wrong parent object.
> bugfix: fix a bug when delete mainline object association

- src/ui/src/components/hosts/filter/_filter.vue
- src/ui/src/views/topology/index.vue
- 修复主机筛选切换属性时部分情况下会丢失operator参数的问题
> 修复主机筛选operator参数丢失的问题

- src/apimachinery/toposerver/object/obj.go
POST method in createobject should put obj in body, otherwise method
call in handler.go in datacollection will get error invalid
classification() for the object() when create model from discover
when use datacollection discover func, it will call createobject to create model, and in 
cmdb_datacollection log will find error "invalid classification() for the object()" and can
not create model
> POST method in createobject should put obj in body

- src/scene_server/topo_server/core/operation/import_association.go
- src/web_server/middleware/login.go
- 导入实例，源-目标约束1:1的时候，如果已经存在关联关系，不可在进行关联操作
- xxxx
-  修复用户没有权限，返回两段JSON格式数据给前端的问题
close #1460  #1458 
@breezelxp
> V3.2.x  关联关系导入调整

- src/scene_server/validator/valid_unique.go
- 修复更新实例时的唯一性检查当ID不存在的会panic的问题
> fix: getInstDataByID  should return not found error if the id not exists

- src/scene_server/topo_server/core/operation/association_mainline_object.go
> fix: 新建主线模型时，主线拓扑实例中缺少默认的实例字段属性 #1562

- src/scene_server/topo_server/core/inst/association.go
- src/scene_server/topo_server/core/inst/inst.go
- src/scene_server/topo_server/core/model/object.go
- src/scene_server/topo_server/core/model/types.go
- xxxx
- when the two objects associated with different object kind if a object instance is associated with only one another object, the search instance topo api should return only one instance.
- xxxx
close #1592
> optimize: optimize the search object instance association api.

- src/ui/src/views/model-topology/index.vue
> fix: 模型拓扑箭头未按照关联类型正确展示 to v3.2.x

- src/ui/src/components/relation/_topology.vue
- src/ui/src/components/relation/_update.vue
- src/ui/src/components/relation/index.vue
- src/ui/src/components/ui/form/date.vue
- src/ui/src/components/ui/form/time.vue
- src/ui/src/utils/tools.js
- src/ui/src/views/custom-query/preview.vue
- src/ui/src/views/model-manage/children/field.vue
- src/ui/src/views/model-manage/children/index.vue
- src/ui/src/views/model-manage/index.vue
- 调整模型下的部分字体颜色
- 模型过多时，滚动悬浮顶部按钮
- 实例关联管理放开源模型限制
- 修复实例拓扑图例操作UI显示异常的问题
- 修复模型字段是否必填UI显示错误的问题
- 修复实例已有的关联状态显示错误的问题
- 修复创建拓扑节点时间、日期类型传参错误的问题
- 修复模型名称太长时UI异常的问题
- 修复模型分组出现多余的箭头的问题
- 修复动态分组预览云区域显示不正确的问题
> 3.2.x bugfix

- scripts/init.py
- src/scene_server/admin_server/upgrader/x18.12.05.01/addswitchAssociation.go
- src/scene_server/admin_server/upgrader/x18.12.05.01/pkg.go
- fix: solve init.py for coreservice
- fix: should ignore "ns not found" error when drop table
> fix: solve init.py for coreservice

- src/scene_server/topo_server/core/model/object.go
- src/scene_server/topo_server/core/operation/association_mainline_object.go
- xxxx
- 优化新加拓扑层级，失败错误提示
- 修复新建模型icon可以为空问题
close #1716  close #1715 
@breezelxp
> V3.2.x 修复新建模型icon可以为空问题， 优化新加拓扑层级，失败错误提示

- src/scene_server/topo_server/core/operation/association_mainline_object.go
- create mainline object 测试用例运行失败，增加 ClassificationID 为空的校验
> create mainline测试用例运行失败处理：新增 bk_classification_id 为空的校验

- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
- src/scene_server/event_server/distribution/start.go
- xxxx
- xxxx
- fix: 迁移事件ID到mongoDB时，忽略重复提示的错误
> fix: ignore duplicated error

- src/source_controller/hostcontroller/logics/logics.go
- xxxx
- xxxx
- 修复主机转移到空闲机/故障机模块。当主机属于多个模块的时候，主机的模块没有清除掉
@hoffermei
> fix:host transfer default module ,can has other module issue #1978

- src/ui/src/views/model-manage/children/index.vue
- src/ui/src/views/model-manage/index.vue
- src/ui/src/views/process/index.vue
- 进程保存按钮权限
- 返回模型页面重新拉取数据
- 模型删除按钮鉴权
> 进程保存按钮和模型删除按钮鉴权修改，模型页面数据刷新

- src/common/paraparse/app.go
- src/common/paraparse/host.go
修复的问题：
- search_host接口无法使用"^"符号正则搜索数据 
issue:
#2111
> search_host接口无法使用"^"符号正则搜索数据 

- src/scene_server/topo_server/core/operation/inst.go
- 设置关联字段如果传入整形时，cc_InstAsst表中没有创建对应的关联关系记录
- 设置关联字段如果传入整形时，cc_ObjectBase表中实例关联属性字段保存成了整形（应该统一为,分割的字符串）
close #2165
>  设置关联字段参数处理逻辑问题

- src/source_controller/objectcontroller/service/role_action.go
- object controller中get privilege接口在没有权限数据时返回格式与有权限时格式不一致
close #2250
> object controller中get privilege接口在没有权限数据时返回格式与有权限时格式不一致 #2250

- vendor/github.com/boj/redistore/redistore.go
> 日志中打印redis等明文密码 不安全 #1986

- src/apimachinery/discovery/server.go
- src/common/definitions.go
- src/common/types/serverInfo.go
- src/scene_server/synchronize_server/app/options/options.go
- src/scene_server/synchronize_server/app/server.go
- src/scene_server/synchronize_server/logics/background_synchronize.go
- src/scene_server/synchronize_server/logics/synchronize.go
- src/source_controller/coreservice/core/datasynchronize/find.go
- src/source_controller/coreservice/core/datasynchronize/model.go
- src/source_controller/coreservice/core/datasynchronize/util.go
- src/source_controller/coreservice/service/data_synchronize.go
-  多个cmdb之间同步支持不同模型
- 多个cmdb直接同步模型的定义，模型的字段，模型字段分组，模型分组支持按唯一标识合并
- 过滤配置文件空白配置
- 服务发现支持同步服务模块
- xxxx
issue #1780  #2247
> feature: sync data between multiple bk-cmdb

- src/scene_server/topo_server/core/operation/inst.go
- 如下所示实例查询时路径参数`core_switch`没有加入到过滤条件，最终把`bk_weblogic`之类的实例全部查询出来了
- `/api/v3/inst/search/owner/0/object/core_switch`
close #2166
> 实例查询没有按path参数指定的类型过滤 #2166

- src/apimachinery/hostserver/apis.go
- src/apimachinery/hostserver/hostserver.go
- src/apiserver/core/compatiblev2/service/plat.go
- src/scene_server/host_server/logics/app.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/phpapi.go
-  
- 优化创建云区域接口返回值
- 代码格式
- 修复v2 api 穿件云区域，返回值没有新建的云区域ID问题
- 修复获取不存在主机未提示错误的问题
- 修复mapstr未nil，set 值的panic的问题
> V3.4.x 测试用例问题修复

- scripts/init.py
- src/auth/authcenter/adaptor.go
- src/auth/extensions/classification.go
- src/auth/extensions/instance.go
- src/auth/parser/host.go
- src/auth/parser/topolatest.go
- src/auth/parser/topology.go
- src/common/metadata/metadata.go
- src/scene_server/admin_server/synchronizer/handler/classification.go
- src/scene_server/admin_server/synchronizer/meta/types.go
- src/scene_server/admin_server/synchronizer/producer.go
- src/scene_server/admin_server/synchronizer/worker.go
- src/scene_server/topo_server/core/operation/classification.go
- src/scene_server/topo_server/service/association.go
- src/scene_server/topo_server/service/inst.go
> 主机，主线模型权限优化修复

- src/common/metadata/metadata.go
- src/common/metadata/process.go
- src/source_controller/coreservice/core/process/process.go
- src/source_controller/coreservice/core/process/process_instance_relation.go
- src/source_controller/coreservice/core/process/process_template.go
- src/source_controller/coreservice/core/process/service_category.go
- src/source_controller/coreservice/core/process/service_instance.go
- src/source_controller/coreservice/core/process/service_template.go
- 回滚：coreservice中进程模块metadata采用结构体替换mapstr
> 回滚：coreservice中进程模块metadata采用结构体替换mapstr #2439

- src/apimachinery/coreservice/process/api.go
- src/apimachinery/coreservice/process/process.go
- src/common/metadata/core_service.go
- src/common/metadata/process.go
- src/scene_server/proc_server/service/category.go
- src/scene_server/proc_server/service/processtemplate.go
- src/scene_server/proc_server/service/service.go
- src/scene_server/proc_server/service/serviceinstance.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/process/process_template.go
- src/source_controller/coreservice/core/process/service_category.go
- src/source_controller/coreservice/core/process/service_instance.go
- src/source_controller/coreservice/core/process/service_template.go
- src/source_controller/coreservice/service/process_template.go
1. 进程模版新增start_param_regex字段;
2. 根据模块过滤服务实例不生效问题；
3. 字段重命名 module_id -> bk_module_id; host_id -> bk_host_id
4. code refactor: 进程模板接口过滤参数该用统一option结构
5. 新增：根据服务实例查询进程实例接口 
6. 服务分类信息带上使用量
close #2490
> V3.5.x 新增进程模板相关功能

- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
> 移除升级到3.2.x时遗留的脏数据

- src/common/eventclient/eventclient.go
- src/common/metadata/process.go
- src/source_controller/coreservice/core/process/process_instance_relation.go
- src/ui/src/store/modules/api/process-template.js
- 事件推送功能中新增的对比差异逻辑有点问题，编辑进程实例时出现panic，暂时关闭事件对比功能
- 后端http path变更了，前端有两个前端url没有调整过来
> 暂时关闭事件对比功能

- src/ui/src/api/index.js
- src/ui/src/components/hosts/transfer/index.vue
- src/ui/src/components/ui/tree/_tree-layout.js
- src/ui/src/components/ui/tree/_tree-node.vue
- src/ui/src/components/ui/tree/tree.vue
- src/ui/src/dictionary/auth.js
- src/ui/src/directives/cursor.js
- src/ui/src/setup/afterload.js
- src/ui/src/store/modules/api/auth.js
- src/ui/src/store/modules/view/host-details.js
- src/ui/src/views/business/archived.vue
- src/ui/src/views/host-details/children/association-list-table.vue
- src/ui/src/views/host-details/children/association-list.vue
- src/ui/src/views/host-details/children/association.vue
- src/ui/src/views/host-details/children/history.vue
- src/ui/src/views/host-details/children/property.vue
- src/ui/src/views/host-details/index.vue
- src/ui/src/views/host-details/router.config.js
- src/ui/src/views/model-manage/children/field.vue
- src/ui/src/views/model-manage/children/index.vue
- src/ui/src/views/model-manage/children/verification.vue
- src/ui/src/views/model-manage/router.config.js
- src/ui/src/views/model-topology/index.old.vue
- src/ui/src/views/model-topology/router.config.js
- src/ui/src/views/topology/index.vue
- xxxx
- 拓扑视图编辑按钮鉴权调整
- 业务模型禁止添加业务私有字段
- 去除主机关联全部展开的半选状态
- 修复主机详情页面未对具体主机实例做鉴权的问题
- 修复归档UI鉴权判断反了的问题
- 修复转移主机到资源池鉴权参数缺少业务id的问题
- 修复转移主机资源池鉴权错误的问题
- 修复删除模型鉴权错误的问题
- 修复主机变更记录选择日期时筛选传参不正确的问题
> V3.4.x 权限回归

- src/ui/src/views/audit/index.vue
> v3.4.x：  fix: 操作审计业务不可搜索 && 类型选中后不可清楚选中

- src/storage/dal/mongo/mongo.go
- mongodb用户名密码包括特殊字符导致拼接的URI无法连接到mongodb
close #2690
>  fix: mongodb用户名密码包括特殊字符导致拼接的URI无法连接到mongodb issue #2690

- src/apimachinery/toposerver/inst/api.go
- src/apimachinery/toposerver/inst/inst.go
- src/common/metadata/toposerver.go
- xapimachinery的SelectInstsByAssociation函数的返回值与/inst/association/search/owner/%s/object/%s接口的返回值不匹配
> V3.2.x 修复查询指定模型的指定实例关联top报错

- src/apimachinery/toposerver/inst/api.go
- src/apimachinery/toposerver/inst/inst.go
- src/common/metadata/toposerver.go
- apimachinery的SelectInstsByAssociation函数的返回值与/inst/association/search/owner/%s/object/%s接口的返回值不匹配
> V3.2.4 修复查询指定模型的指定实例关联top报错

- src/common/metadata/time.go
- metadata.Time 支持更多的string格式的时间反序列化
- xxxx
- xxxx
> feature: metadata.Time  支持string 反序列化  issue #2833

- src/ui/src/components/hosts/table/index.vue
> fix:ui: 修复切换资源池已分配/未分配主机切换时参数不正确的问题

- src/scene_server/topo_server/service/association.go
- src/source_controller/coreservice/service/model_attribute_test.go
- 删除查询关联关系类型，不返回业务主线拓扑模型
- 删除侧泳用例的IP
- xxxx
- xxxx
> 删除查询关联关系类型，不返回业务主线拓扑模型

- src/source_controller/objectcontroller/service/inst_action.go
- src/source_controller/validator/valid_unique.go
- create_inst批量接口的操作审计全部是新增操作，包括更新的操作审计
> 添加create_inst接口的操作审计

- src/source_controller/objectcontroller/service/process.go
- 根据模块名获取绑定进程信息bugfix
close #3082
> 根据模块名获取绑定进程信息bugfix

- src/scene_server/topo_server/core/operation/import_association.go
> fix:import association bug issue #3126

- src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
不符合json格式了
- BKHostOuterIPField
> 去掉BKHostOuterIPField

- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/x18.12.12.07/pkg.go
- src/scene_server/admin_server/upgrader/x18.12.12.07/update_ip_regex.go
- 降低migrate文件版本号 
版本号从 x19.08.30.01 ==> x18.12.12.07
#3163
> 降低migrate文件版本号 #3163

- src/common/definitions.go
- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- 调整longchar字段类型最大长度为 15000
close #3176
> 调整longchar字段类型最大长度为 15000

- src/common/mapstr/mapstr.go
- src/common/mapstr/mapstr_test.go
- mapstr的String(key string)函数使用fmt.Sprintf("%v", t)转换float数据时，由于%v对应float类型的%g占位符，在数据过长时可能会转换为科学计数法
> v3.5.x mapstr的String(key string)函数问题修复

- scripts/generate.py
- generate.py生成dockerfile的时候复制文件少了个'/'
> fix: generate.py生成dockerfile的时候复制文件少了个'/'

- src/common/paraparse/host.go
- 主机查询中的$multilike操作符值为空时，不执行查询动作，否则mongodb无法正常进行查询。
> optimize: a  operator in mongodb can not be empty in search host api.

- src/common/metadata/common.go
-操作审计，根据时间查询日志，由于UTC时区问题，导致查询结果错误
> fix: 操作审计，根据时间查询日志，由于UTC时区问题，导致查询结果错误

- src/common/metadata/association.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/service_initfunc.go
- 要求根据实例信息（实例的模型ID，实例ID）和模型ID（关联关系中的源，目的模型ID） 返回实例关联或者被关联模型实例得数据。
- xxxx
- xxxx
close #3282
> 查询实例关联关系API 

- src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
- src/scene_server/proc_server/service/serviceinstance.go
- 进程升级到3.5时进程实例supplier account必须与服务实例保持一致
- 进程实例没找到时空指针异常规避
> 进程升级到3.5时进程实例supplier account与服务实例保持一致

- src/source_controller/validator/util.go
- src/source_controller/validator/valid_basic.go
- excel导入实例时，有枚举字段会导入失败
- 原因：解析枚举字段的Option没考虑validator.EnumOption这个类型
> fix: excel import enum field fail

- src/scene_server/host_server/service/host.go
- 主机删除的操作审计日志中设置了当前值和删除前的值相同导致操作审计日志未添加进数据库
> fix: 查看主机删除历史页面查看不到被删除的主机记录

- src/auth/parser/topology.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/service_initfunc.go
- 查询实例关联拓扑apiserver parser正则重复
- SearchInstChildTopo关联的2个url的路径参数命名不同
> fix: 查询实例关联拓扑apiserver parser正则重复

- src/common/metadata/process.go
- 通过模板同步进程实例属性时，进程实例属性bind_ip原始值nil时同步的bind_ip没有转换成ip地址bugfix(模板中的值为1, 2)
> 通过模板同步进程实例属性时，进程实例属性bind_ip原始值nil时同步的bind_ip没有转换成ip地址bugfix(模板中的值为1, 2)

- src/auth/parser/topology.go
- create_object_attribute 接口权限解析无layer信息
> 修复 create_object_attribute 接口权限解析无layer信息

- src/common/metrics/gauge.go
- src/common/metrics/metrics.go
- metrics使用RequestURI导致不同请求参数生成多个handler记录
- 拼写错误
> 修复metrics不同请求参数生成多个handler记录

- src/common/auth/auth.go
- src/common/util/flags.go
- auth在blog的flag没有赋值完成的时候调用导致blog的部分flag不生效
> 修复auth在blog的flag没有赋值完成的时候调用导致blog的部分flag不生效

- src/ui/src/views/model-topology/index.new.vue
> 修复模型拓扑默认图标缩放太小和鼠标滚轮缩放比例太大问题

- src/scene_server/admin_server/upgrader/x19.04.16.02/pkg.go
- src/scene_server/admin_server/upgrader/x19.04.16.02/updateFranceName.go
- xxxx
- xxxx
-修复版本升级主机bk_state_name被删除后，升级失败的问题
close #3545
> 修复版本升级主机bk_state_name被删除后，升级失败

- src/test/util/fail.go
- 测试用例错误时提示信息位置错误
- 实例查询鉴权未关联实例ID
> 修复测试用例错误时提示信息位置错误和实例查询鉴权未关联实例ID的问题

- src/apiserver/service/filter.go
- src/auth/authcenter/adaptor.go
- src/auth/parser/topolatest.go
- src/auth/parser/util.go
- 无权限提示信息resourceID错误
- 模型实例关联权限对特殊模型的实例鉴权类型错误
> 模型实例关联权限bugfix

- src/scene_server/topo_server/core/operation/inst.go
> fix: 修复模型唯一校验更改后，execel导入仍有实例名唯一校验的问题 issue #3601

- src/scene_server/topo_server/service/inst_business.go
> 业务搜索增加除角色属性以外的字段模糊匹配查询

- src/auth/extensions/attribute.go
- src/auth/extensions/attributegroup.go
- src/auth/extensions/audit.go
- src/auth/extensions/business.go
- src/auth/extensions/classification.go
- src/auth/extensions/dynamicgroup.go
- src/auth/extensions/host.go
- src/auth/extensions/modelunique.go
- src/common/tablenames.go
- src/common/tablenames_test.go
- src/scene_server/admin_server/upgrader/y3.6.201911141516/obj_host_add_field_type_list.go
- src/source_controller/coreservice/core/association/model_crud.go
- src/source_controller/coreservice/service/hostuser.go
- src/test/topo_server/object_test.go
- GetInstTableName转换表名中使用表名作为object ID
- 场景层使用读实例接口读非实例数据
close #3559
> 去除GetInstTableName转换表名中使用表名作为object ID的逻辑

- src/apimachinery/coreservice/coreservice.go
- src/apimachinery/coreservice/system/api.go
- src/apimachinery/coreservice/system/system.go
- src/apiserver/service/url.go
- src/auth/authcenter/permit/permit.go
- src/auth/meta/resource.go
- src/auth/parser/host.go
- src/common/metadata/adminserver.go
- src/common/paraparse/app.go
- src/scene_server/admin_server/service/flag.go
- src/scene_server/admin_server/service/service.go
- src/scene_server/host_server/logics/module.go
- src/scene_server/host_server/logics/special.go
- src/scene_server/host_server/service/service.go
- src/scene_server/host_server/service/special.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/system/system.go
- src/source_controller/coreservice/service/service.go
- src/source_controller/coreservice/service/service_initfunc.go
- src/source_controller/coreservice/service/system.go
-  删除查询的时候关于字符“-”的转移
- cmdb_adminserver 配置蓝鲸业务可编辑
- cmdb_hostserver 提供查询蓝鲸业务是否可编辑接口 
- xxxx
- xxxx
> 允许前端页面修改蓝鲸业务

- src/scene_server/operation_server/app/options/options.go
- src/scene_server/operation_server/app/server.go
- src/scene_server/operation_server/service/service.go
- cmdb_operation解析权限数据失败导致周期性任务无法执行
> cmdb_operation启动失败bugfix

- docs/overview/installation.md
- 部署文档mongodb版本调整为v3.6以上，mongodb 3.4版本开始支持$count，使用低版本mongodb在唯一校验时会报错
close #3689
> 部署文档mongodb版本调整为v3.6以上

- src/scene_server/admin_server/upgrader/y3.6.201912241627/sort_bk_property_index.go
- src/scene_server/topo_server/service/object_attribute.go
- #3656 
- fix: 模型属性分组为none或“”时，migrate设置为default，更新模型属性不可更新分组
> fix: 模型属性分组为none或“”时，migrate设置为default，更新模型属性不可更新分组

- src/source_controller/coreservice/core/model/attribute_curd.go
- src/source_controller/coreservice/core/model/model.go
- src/source_controller/coreservice/core/model/validator_util.go
- 考虑到后续按模型拆分collection，需要限制模型字段名的字符，以满足mongo对collection名和字段名的限制要求
issue #3698
> 模型名其及字段名增加符合mongo表名及其字段名的限制

- src/common/metadata/attribute.go
- src/source_controller/coreservice/core/instances/validator_attr.go
> 已赋值的实例日期和时间类型字段允许置空

- src/apimachinery/coreservice/hostapplyrule/api.go
- src/test/host_server/host_apply_test.go
- 修复url有参数拼接时，metrics会采集多个不同url的问题 #3722
> fix: 修复url有参数拼接时，metrics会采集多个不同url的问题 #3722

- src/common/metadata/result.go
- src/source_controller/coreservice/core/association/kind.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/service/association.go
- src/source_controller/coreservice/service/translate.go
> fix: 增加模型关联类型的英文翻译 issue #3783

- src/common/metadata/object.go
> 修复get_biz_internal_module接口bson的tag缺双引号导致json序列化ModuleName错误的问题

- src/auth/parser/topology.go
- src/source_controller/coreservice/core/model/attribute_curd.go
- 更新模型属性接口添加模型分组是否存在的校验
- 更新和删除模型属性接口权限解析中获取objectID方式错误
> 更新模型属性接口添加模型分组是否存在的校验

- src/apimachinery/coreservice/operation/api.go
- src/apimachinery/coreservice/operation/operation.go
- src/auth/parser/operationstatistics.go
- src/scene_server/operation_server/service/operation.go
- src/scene_server/operation_server/service/service.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/operation/operation.go
- src/source_controller/coreservice/service/operation.go
- src/source_controller/coreservice/service/service_initfunc.go
- src/ui/src/store/modules/api/operation-chart.js
- xxxx
- 命名规范，此次将operator（运营统计）部分的url从以前的“search“或”read”更正为“find”
- xxxx
> 统一运营分析url规范化

- src/common/backbone/backbone.go
修复的问题：
- 其他第三方组件创建backbone实例时的srvinfo参数里没有设置registerip导致服务不可用
close issue #3955
> 在backbone里对无值的registerip设默认值

- src/scene_server/admin_server/upgrader/y3.7.202002231026/add_bk_port_enable_property.go
- xxxx
- xxxx
- migrate  bk_enable_port的时候time类型字段encode错误
> fix: migrate bk enable port time encode error issue #3973

- src/ui/src/views/audit/index.vue
- 修复操作审计中选择模型下拉列表没有主机选项的bug
- #3970
> fix: 修复操作审计中选择模型下拉列表没有主机选项的bug

- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/types.go
- 删除自定义业务拓扑层级后，集群模板中仍可见被删除节点下的集群实例
close  #4021
> 删除业务自定义拓扑的同时删除集群同步状态

- src/common/metadata/process.go
- 将服务模版字段清空后进行同步出现异常，实际是拉起间隔字段的空指针异常导致的问题
> 修复同步服务模版时的异常

- src/scene_server/host_server/logics/host.go
- 该接口业务id可以不传，因此当接口参数传入为空时，报相应的错误
> 主机模块关系接口调整参数为空时的返回错误

- src/common/definitions.go
- src/common/paraparse/app.go
- src/scene_server/topo_server/service/inst_business.go
- src/web_server/service/object.go
- 查找主机的高级筛选里支持集群、模块等模型属性值忽略大小写的模糊匹配
> 查找主机的高级筛选里支持集群、模块等模型属性值忽略大小写的模糊匹配

- src/source_controller/coreservice/core/process/service_template.go
- xxxx
- 查询服务实例时，如果服务实例列表为空，则不进行查询。 
- xxxx
> 查询服务实例时，如果服务实例列表为空，则不进行查询

- src/source_controller/objectcontroller/service/inst_action.go
- 修复map为nil时赋值的panic而引起导入模型实例不全的问题
> 修复map为nil时赋值的panic而引起导入模型实例不全的问题

- src/scene_server/host_server/logics/hostsearch.go
- src/test/host_server/host_abnormal_test.go
- src/test/host_server/host_test.go
- 删除主机查询时的重复操作,以去掉返回结果里的重复数据
- 调整主机topo集成测试用例，防止偶发的因序列化后的结构体成员顺序不同，而和正则不匹配错误
> 删除主机查询时的重复操作，调整集成测试用例

- src/apimachinery/coreservice/host/api.go
- src/apimachinery/coreservice/host/host.go
- src/common/metadata/hostserver.go
- src/common/metadata/page.go
- src/common/querybuilder/types.go
- src/scene_server/host_server/service/findhost.go
- src/source_controller/coreservice/core/host/searcher/searcher.go
- src/test/host_server/host_abnormal_test.go
- src/test/host_server/host_test.go
- 查询主机列表的接口支持传入host 的字段列表，只返回列表里的字段数,以加速接口请求和减少网络流量传输
close issue #4136
> 查询主机列表的接口支持传入host 的字段列表，只返回列表里的字段数

- src/common/metadata/hostserver.go
- src/scene_server/host_server/logics/findhost.go
- find_host_by_module接口支持传入host 的字段列表，只返回列表里的字段数,加速接口请求和减少网络流量传输
> find_host_by_module接口支持传入host 的字段列表，只返回列表里的字段数

- scripts/init.py
- src/scene_server/datacollection/app/options/options.go
- src/scene_server/datacollection/app/server.go
- src/scene_server/datacollection/datacollection/datacollection.go
- datacollection 新加配置文件配置，可以指定所使用的业务名，用该业务名查对应的业务ID，不指定，默认是"蓝鲸"
> datacollection 新加默认业务名配置

- src/storage/driver/redis/redis.go
- xxxx
- xxxx
- 修复无法通过redis 在配置文件的前缀获取对应redis 实例的问题
> 修复无法通过redis 在配置文件的前缀获取对应redis 实例的问题

- src/source_controller/objectcontroller/service/inst_action.go
> 修复因类型转换失败导致的Excel更新模型实例不全的问题

- src/ui/src/components/hosts/table/index.vue
- src/ui/src/router/query.js
- src/ui/src/views/business-topology/index.vue
- 修复query为空时不会调用立即执行的RouterQuery.watch的问题
> ui: 修复query为空时不会调用立即执行的RouterQuery.watch的问题

- src/apimachinery/coreservice/cache/api.go
- src/apimachinery/coreservice/cache/cache.go
- src/scene_server/event_server/app/server.go
- src/scene_server/event_server/distribution/start.go
- src/scene_server/event_server/identifier/hostcache.go
- src/scene_server/event_server/identifier/identifier.go
- src/source_controller/coreservice/cache/business/client.go
- src/source_controller/coreservice/cache/business/client_logic.go
- src/source_controller/coreservice/cache/cache.go
- src/source_controller/coreservice/service/cache.go
- src/source_controller/coreservice/service/service_initfunc.go
- 添加主机身份使用的cache相关接口
- 主机身份事件推送使用coreservice的cache
- 修复业务和集群缓存错误的问题
- 修复自定义层级panic的问题
> 主机身份事件推送使用coreservice的cache

- src/ui/src/views/business/archived.vue
- 目前用户搜索查询已归档业务时，区分了大小写，这样不对；已修改为忽略大小写。
close #4250
> fix: 查询已归档业务时，忽略大小写

- src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
> 主机快照在bk_cpu_mhz上下波动不超过100时判断为不变

- src/scene_server/topo_server/service/inst_set.go
> 修复批量创建集群的空指针引用错误

- src/common/rdapi/rdfunc.go
- src/scene_server/datacollection/datacollection/hostsnap/filter.go
- src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
- 主机快照上报不支持IPV6, 新增对未注册到cmdb的主机快照过滤，降低缓存穿透。
> optoptimize: 主机快照上报不支持IPV6, 新增对未注册到cmdb的主机快照过滤，降低缓存穿透。

- src/auth/parser/netcollector.go
- 调整netcollector更新设备接口鉴权url的api版本
> 调整netcollector更新设备接口鉴权url的api版本

- src/common/definitions.go
- src/scene_server/proc_server/logics/processinstance.go
- src/source_controller/coreservice/core/process/process_instance_relation.go
- 补全进程实例与模版同步中差异对比所缺失的网管代理字段
- 修正获取进程实例关系的数量返回值
> 补全进程实例与模版同步中差异对比所缺失的网管代理字段，修正获取进程实例关系的数量返回值

- src/auth/parser/host.go
> 修复导入excel更新主机时需要全局主机编辑权限的问题

- src/scene_server/datacollection/app/server.go
- src/test/host_server/host_test.go
- 修复datacollection模块因全局CCError对象未能正确初始化产生panic的问题
> fix: PANIC by global cc error object in datacollection issue #4313

- src/source_controller/coreservice/core/host/transfer/manager.go
- src/web_server/service/index.go
- PaasDomainUrl支持URL末尾有无/的写法
- 修复查询主机关系时fields不生效的问题
> 修复查询主机关系时fields不生效的问题，PaasDomainUrl支持URL末尾有无/的写法

- src/apimachinery/coreservice/transaction/client.go
> 修复事务嵌套导致的主机转移失败问题

- src/scene_server/admin_server/upgrader/y3.8.202006241144/change_host_ip_user_to_array.go
- src/storage/dal/mongo/local/mongo.go
> 修复校验主机IP只能为数组导致升级失败的问题

- src/apimachinery/coreservice/settemplate/api.go
- src/apimachinery/coreservice/settemplate/settemplate.go
- src/common/http/rest/contexts.go
- src/common/lock/lock_key.go
- src/common/util/lib.go
- src/scene_server/topo_server/app/server.go
- src/scene_server/topo_server/core/settemplate/settemplate.go
- src/scene_server/topo_server/core/settemplate/sync_status.go
- src/scene_server/topo_server/service/set_template.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/settemplate/sync_status.go
- src/source_controller/coreservice/service/service_set_template_initfunc.go
- src/source_controller/coreservice/service/set_template.go
- 使用redis driver 初始化缓存
- 使用redis lock 对任务隔离
- 在查询集群模板同步状态的时候，执行对正在同步集群的状态更新
- 对rest.Contexts, rest.Kit 新派生新的rest.Contexts, rest.Kit 和header 对象
- xxxx
- xxxx
close #4395
> 集群同步相关问题修改

- src/scene_server/datacollection/datacollection/hostsnap/ginkgo_parseSetter_test.go
- src/scene_server/datacollection/datacollection/hostsnap/ginkgo_parsesetter_test.go
- src/scene_server/datacollection/datacollection/hostsnap/ginkgo_suite_test.go
- src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
- 主机快照硬盘计算优化，让disk先计算再进行求和，否则可能溢出。
- disk和mem数据类型从int64改为uint64
> v3.5.x 主机快照硬盘计算优化

- src/scene_server/datacollection/collections/hostsnap/ginkgo_parseSetter_test.go
- src/scene_server/datacollection/collections/hostsnap/ginkgo_parsesetter_test.go
- src/scene_server/datacollection/collections/hostsnap/ginkgo_suite_test.go
- src/scene_server/datacollection/collections/hostsnap/hostsnap.go
- 主机快照硬盘计算优化，让disk先计算再进行求和，否则可能溢出。
- disk和mem数据类型从int64改为uint64
- 格式化字符串中int64数据couldID使用了%s输出，现修改为%d
> v3.8.x主机快照硬盘计算优化

- src/common/util/conv.go
- src/common/util/ginkgo_conv_test.go
- src/common/util/ginkgo_util_suite_test.go
- src/source_controller/coreservice/core/host/transfer/manager.go
- src/storage/dal/mongo/local/mongo.go
- src/storage/dal/mongo/local/mongo_test.go
- src/storage/dal/types/types.go
变更Distinct函数接口形式，让其支持string和bool类型的查询，并返回[]interface{}。
对于转化成具体类型：如转化为int64使用SliceInterfaceToInt64函数，转化成string需要SliceInterfaceToString函数，转化成SliceInterfaceToBool函数
如果查询结果为空，那么返回长度为0的的[]interface{}
修改的文件：
- `conv.go`  增添了三个函数：
- `SliceInterfaceToInt64(faceSlice []interface{}) ([]int64,error)`  将interface切片转化为int64切片,且interface的真实类型可以是任何整数类型
- `SliceInterfaceToString(faceSlice []interface{}) ([]string,error)`  将interface切片转化为string切片
- `SliceInterfaceToBool(faceSlice []interface{}) ([]bool,error)` 将interface切片转化为bool切片
- `mongo.go`  Distinct接口的修改
- `manager.go`  为了兼容Distinct接口所作的修改
- `mongo_test.go`  为了兼容Distinct接口所作的修改，并测试DIstinct函数
- `types.go`   为了兼容Distinct接口所作的修改，并更改Distinct接口注释
增加的文件：
- `ginkgo_util_suite_test.go` 在util包内ginkgo测试框架的的测试入口，`ginkgo_conv_test.go`的前置文件
- …
> v3.8.x 修改Distinct函数接口形式，并让其支持string和bool类型的查询

- src/source_controller/coreservice/core/model/attribute_curd.go
> 用户创建的模型属性禁止使用"_bk_"和"bk_"前缀

- src/scene_server/host_server/logics/import.go
- src/scene_server/host_server/service/host.go
- src/test/host_server/host_abnormal_test.go
- 新加add host 接口修改主机的，不能修改运区域的
- 新加批量修改主机的接口， 忽略运区域
- 
-  修复add host 接口新加主机的时候，可以使用不存在运区域的问题
-  修复add host 接口新加主机的时候，云区域ID为字符串的问题
> V3.5.x host cloudarea type

- src/web_server/service/index.go
> 修复在未配置paas URL的情况下配置了新版人员选择器URL导致使用新版人员选择器的问题

- src/scene_server/host_server/logics/import.go
- src/scene_server/host_server/service/host.go
- src/test/host_server/host_abnormal_test.go
- 新加add host 接口修改主机的，不能修改运区域的
- 新加批量修改主机的接口， 忽略运区域
- 
-  修复add host 接口新加主机的时候，可以使用不存在运区域的问题
-  修复add host 接口新加主机的时候，云区域ID为字符串的问题
close  #4435
> 修改主机实例属性api 无法修改运区域

- src/scene_server/admin_server/upgrader/util.go
- src/scene_server/admin_server/upgrader/y3.6.201911141516/obj_host_add_field_type_list.go
- src/scene_server/admin_server/upgrader/y3.7.202002231026/add_bk_port_enable_property.go
- src/scene_server/admin_server/upgrader/y3.8.202004151435/add_proc_gateway_attr.go
- src/scene_server/admin_server/upgrader/y3.8.202005201015/add_host_attr.go
- 升级程序创建属性时进行唯一校验，防止重复创建
close #4416
> 升级程序创建属性时进行唯一校验，防止重复创建

- src/common/metadata/attribute.go
- src/scene_server/proc_server/service/servicetemplate.go
- src/web_server/logics/excel_util.go
- 修复excel导入主机时，组织类型字段参数校验失败的问题
- 解决新建的服务模板与已建模板的名称重复时，提示语不清晰的问题
> 修复excel导入主机时，组织类型字段参数校验失败的问题

- src/apimachinery/apiserver/api.go
> 修复excel导入模型实例失败的问题

- src/source_controller/coreservice/core/model/attribute_curd.go
- 模型表格存在内置字段时，导入模型表格会报错。
修改逻辑是，见到内置字段，丢弃就好了；其余的字段可以正常执行。
这个问题在3.8已经处理好了，本次处理3.5。
close #4347
> fix:模型表格存在内置字段时，导入模型表格会报错。

- src/scene_server/topo_server/core/operation/inst_module.go
- src/scene_server/topo_server/core/operation/inst_set.go
- 禁止用模版来创建集群和模块时，默认集群和模块不受此限制，防止创建业务失败
> 禁止用模版来创建集群和模块时，默认集群和模块不受此限制

- src/scene_server/host_server/service/transfer.go
- src/scene_server/proc_server/service/processinstance.go
- 更新进程实例时增加进程数是否为0的判断，防止后续多余的操作
> 更新进程实例时增加进程数是否为0的判断，防止后续多余的操作

- src/ac/iam/gen_id.go
- 修复权限资源转换时验证了ID的存在性导致模糊鉴权报错的问题
> 权限资源转换兼容模糊鉴权，ID未设置时返回仅包含类型的权限资源

- src/common/backbone/configcenter/viper.go
- 在获取配置的时候，由于redis和mongodb的配置是异步加载，如果程序直接获取配置，可能配置还没有获取到，产生报错的现象，解决方式为在获取配置时如果配置为空，则睡眠一秒等待配置加入
close #4528
> 修复获取redis和mongo的配置产生异常

- scripts/init.py
- src/common/backbone/configcenter/viper.go
- 让admin_server启动时指定的migrate路径带上.yaml后缀,通过设置文件时把后缀去掉即可
close #4539
> 让admin_server启动时指定的migrate路径带上.yaml后缀

- src/scene_server/host_server/service/findhost.go
- 修复find_module_host_relation接口没有主机时未返回的问题
> 修复find_module_host_relation接口没有主机时未返回的问题

- src/scene_server/host_server/service/findhost.go
- 修复 list_biz_host_topo 接口入参fields没有bk_host_id字段时报错的问题
> list_biz_host_topo 接口查询主机时添加bk_host_id字段，防止获取主机关系失败

- src/web_server/service/host.go
- 修复ListenIPOptions接口没指定feilds而查询主机失败的问题
> 修复ListenIPOptions接口没指定feilds而查询主机失败的问题

- src/scene_server/host_server/service/host.go
- 当没有快照数据时，返回数据值为null，以保证前端显示正常
> 当没有快照数据时，返回数据值为null

- src/apimachinery/coreservice/association/api.go
- src/apimachinery/coreservice/association/association.go
- src/auth/parser/topology.go
- src/common/metadata/association.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/service/association.go
- src/scene_server/topo_server/service/service_business_initfunc.go
- src/scene_server/topo_server/service/service_initfunc.go
- src/source_controller/coreservice/core/association/instance.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/service/association.go
- src/source_controller/coreservice/service/service_initfunc.go
- 新增查询实例所有关联接口（依照bk_obj_id和bk_inst_id确认实例，找出所有关联）
- 新增删除实例所有关联接口（依照bk_obj_id和bk_inst_id确认实例，删除所有关联）
close #4595
> V3.5.x add search/delete inst associations api.

- src/common/metadata/hostcontroller.go
- src/scene_server/host_server/service/host.go
> 调整批量查询主机快照的数量限制为200

- src/common/metadata/process.go
> 服务模版绑定IP为内外网IP， 但主机没有相应的IP时，进程绑定127.0.0.1

- src/common/metadata/process_bind_info.go
- xxxx
- xxxx
- 修复进程同步和进程对比数据不一致的情况
> fix: sync  proc bind info and diff bind info not equal  issue #4468

- src/scene_server/host_server/service/host.go
- 修复当主机没有安装agent时，快照实时页面显示不对的问题
> 修复当主机没有安装agent时，快照实时页面显示不对的问题

- src/common/definitions.go
- src/common/http/rest/contexts.go
- src/common/http/rest/rest.go
- src/common/util/lib.go
- src/scene_server/auth_server/service/service.go
- src/scene_server/host_server/service/findhost.go
- src/storage/dal/mongo/local/mongo.go
- 将authserver中操作的查询数据方法放到mongodb的secondary 节点中执行
- 将 /api/v3/hosts/list_hosts_without_app 操作的查询数据方法放到mongodb的secondary 节点中执行
- xxxx
- xxxx
> feature: send query command to secondary  nodes by scenario issue #4663

- src/common/metadata/cloud.go
- src/common/metadata/toposerver.go
- src/scene_server/cloud_server/logics/synctask.go
- src/scene_server/cloud_server/service/account.go
- src/scene_server/host_server/service/cloudarea.go
- src/scene_server/topo_server/service/resource_directory.go
- src/test/cloud_server/cloud_account_test.go
- src/test/cloud_server/cloud_sync_task_test.go
- src/test/host_server/cloudarea_test.go
- src/test/topo_server/resource_dir_test.go
- 不指定模糊查询的情况下，查询云区域、云账户、云同步任务、云同步历史记录、资源池目录的接口默认使用精确匹配查询
> 查询接口默认使用精确匹配

- src/apimachinery/discovery/discovery.go
- src/common/types/manager.go
- 服务发现支持动态服务发现 
- xxxx
实现思路:
- 服务发现实现按需发现服务的能力
通过再代码中定义依赖的服务，然后服务发现发现服务的地址， 最后通过定义规则转发。 
1. src/common/types/manager.go中的AddDiscoveryService 方法用来设置当前服务需要发现的服务。 （已提交pr）
2.  src/apimachinery/discovery/discovery.go 新加支持根据服务名发现服务。 （未开始）
3. 支持根据规则转发请求 （未开始）
功能的优点：
- 按需发现，减少资源浪费
- 服务依赖更明确
- 模块化设计， 减少代码
- 为后续apiserver， sdk 支持非标准组件做准备
> feature: add dynamic service discoery issue #4675

- src/scene_server/admin_server/app/server.go
- src/scene_server/admin_server/command/command.go
- src/scene_server/datacollection/app/server.go
- src/scene_server/event_server/app/server.go
- src/scene_server/topo_server/app/server.go
- src/source_controller/coreservice/core/association/mock_test.go
- src/source_controller/coreservice/core/instances/mock_test.go
- src/source_controller/coreservice/core/model/mock_test.go
- src/source_controller/coreservice/service/service.go
- src/storage/dal/mongo/config.go
- src/storage/dal/mongo/local/mongo.go
- src/storage/dal/mongo/local/mongo_test.go
- src/test/test.go
- src/tools/cmdb_ctl/app/config/config.go
- 将原来连接数写死的代码，改为读取配置的连接数，并设置默认为1500，最大为3000连接
close #4711
> 让mongodb连接池配置生效

- src/source_controller/coreservice/cache/topo_tree/path.go
> 修复用户传多次相同节点时执行多次反向排序导致查询的拓扑路径顺序错误的问题

- src/scene_server/host_server/service/host.go
- 删除主机实例时，即使此实例存在“以host为原模型的关联关系”，也能删除。
这会产生一条没有源的关联关系脏数据。
错误原因：condition内容错误，应修正condition内容"bk_host_id"为"bk_inst_id"。
close #4717
> fix: 修正以host为关联关系原模型时，删除实例操作没有检测到其存在关联关系的问题。

- src/ui/src/utils/tools.js
- src/ui/src/views/audit/index.vue
> ui: 限制操作审计最大查询数量为200

- src/apimachinery/coreservice/common/api.go
- src/apimachinery/coreservice/common/common.go
- src/apimachinery/coreservice/coreservice.go
- src/common/metadata/common.go
- src/common/metadata/core_service.go
- src/scene_server/proc_server/service/processinstance.go
- src/source_controller/coreservice/core/common/common.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/service/common.go
- src/source_controller/coreservice/service/service.go
- src/source_controller/coreservice/service/service_initfunc.go
- coreservice增加获取mongo任意表字段dintinct值的通用接口
- 优化ListProcessInstancesNameIDsInModule接口
close issue #4746
> coreservice增加获取mongo任意表字段dintinct值的通用接口

- src/common/metadata/object.go
- src/scene_server/auth_server/service/service.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/inst_business.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/inst_business.go
- search_inst_by_object 和 get_biz_internal_module 接口优化，去除查询模型的操作
- auth server 添加默认用户，修复core service 校验用户失败的问题
> 修复权限中心反向拉取时因为没有设置用户导致查询失败的问题

- src/scene_server/host_server/logics/dynamic_grouping.go
- src/scene_server/host_server/logics/hostsearch.go
- 修复主机搜索和动态分组主机搜索逻辑中未能正确判定数据是否不存在的bug
> fix: 修复主机搜索和动态分组主机搜索逻辑中未能正确判定数据是否不存在的bug. issue #4750

- src/scene_server/host_server/logics/hostsearch.go
- 修复SearchHost逻辑中未能正确判定数据是否不存在的bug；
> fix: 修复SearchHost逻辑中未能正确判定数据是否不存在的bug. issue #4750

- src/common/definitions.go
- src/scene_server/datacollection/collections/hostsnap/hostsnap.go
- src/scene_server/datacollection/collections/hostsnap/window.go
-   主机快照属性，如cpu,bk_cpu_mhz,bk_disk,bk_mem等数据的处理时间窗口，用于限制在指定周期的前多少分钟可以让请求通过，超过限定时间将不会处理请求。它的下一级有三个参数，atTime,checkIntervalHours，windowMinute
当不配置windowMinute，窗口不生效。当配置了windowMinute,至少配置atTime或者checkIntervalHours中的一个，否则不生效。当atTime和checkIntervalHours都配置时，取atTime这个配置的语义功能
如果窗口生效，启动的时候，会先跑完windowMinutes。然后再生效
atTime，设置一天中，几点开启时间窗口，如配置成14:40，表示14:40开启窗口，如果配置格式不正确，默认值为1:00
checkIntervalHours，规定每隔几个小时窗口开启，单位为小时，如配置成 3，表示每隔3个小时，开启时间窗口，如果配置格式不正确，默认值为 1
windowMinutes，代表开启时间窗口后，多长时间内请求可以通过，单位为分钟。如配置成 60，表示开启窗口时间60分钟内请求可以通过。注意：该时间不能大于窗口每次开启的间隔时间，取值范围不能小于等于0，如果配置不正确，默认值为15
> datacollection添加时间窗口功能

- src/apimachinery/coreservice/association/api.go
- src/apimachinery/coreservice/association/association.go
- src/auth/parser/topology.go
- src/common/metadata/association.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/service/association.go
- src/scene_server/topo_server/service/service_business_initfunc.go
- src/scene_server/topo_server/service/service_initfunc.go
- src/source_controller/coreservice/service/association.go
- src/source_controller/coreservice/service/service_initfunc.go
- 现有通过某实例查询相关关联关系，并批量删除这些关联关系的接口；
此接口如果命中条目过多，会对cmdb造成很大压力；
现修正为依照id删除。
close #4743
> fix: 修改原先的依照模型实例删除关联关系的接口，改为按照id批量删除关联关系

- src/common/auditlog/hostmodule.go
- src/scene_server/host_server/logics/host.go
- src/scene_server/host_server/logics/module.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/module.go
- src/scene_server/host_server/service/transfer.go
> 操作审计传入kit，防止header改变导致事务提交失败

- src/scene_server/cloud_server/common/util.go
- 修复因supplierID不同导致云资源同步不成功的问题
> 修复因supplierID不同导致云资源同步不成功的问题

- src/scene_server/host_server/service/host.go
- src/source_controller/coreservice/core/host/transfer/manager.go
- src/source_controller/coreservice/core/instances/instance_validate.go
- 主机更新创建时对bk_cloud_id做校验，必须为数值型
> 主机更新创建时对bk_cloud_id做校验，必须为数值型

- src/scene_server/host_server/service/findhost.go
- 修复查询主机列表接口因集群查询结果为空没提前返回导致查询结果不对的问题
> 修复查询主机列表接口因集群查询结果为空没提前返回导致查询结果不对的问题

- src/scene_server/host_server/service/findhost.go
- 修复查询主机列表接口因集群查询结果为空没提前返回导致查询结果不对的问题
> fix: 修复查询主机列表接口因集群查询结果为空没提前返回导致查询结果不对的问题

- src/scene_server/event_server/service/watch.go
> 事件监听接口在异常情况下强制sleep 500ms，防止调用方一直使用错误的参数拉取事件

- src/source_controller/coreservice/event/gc.go
> 事件监听保留最后一个事件，修复所有事件均超时后使用cursor监听失败的问题

- src/ac/parser/topolatest.go
- src/apimachinery/toposerver/association/apis.go
- src/apimachinery/toposerver/association/association.go
- src/common/metadata/association.go
- src/scene_server/topo_server/service/association.go
- src/scene_server/topo_server/service/service_business_initfunc.go
- src/scene_server/topo_server/service/service_initfunc.go
- src/test/topo_server/asst_test.go
- 新增依照关联关系实例id批量删除关联关系的接口(无事务,尽量执行,某条执行失败不影响下一条执行)，并为其增加了集成测试。
close #4595
> feature: 新增依照关联关系实例id批量删除关联关系的接口

- src/source_controller/coreservice/core/process/service_instance.go
- src/storage/stream/event/watch.go
- src/test/host_server/host_abnormal_test.go
- src/test/host_server/host_test.go
-修复转移主机到直接新建的模块下时，会新增两个重复服务实例的问题
> fix: 修复转移主机到直接新建的模块下时，会新增两个重复服务实例的问题

- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
- 将升级程序里的删除实例关系的updatgeflag字段改成分页删除，防止实例数据过多时DB io timeout
> optimize: 将升级程序里的删除实例关系的updatgeflag字段改成分页删除，防止实例数据过多时DB io timeout

- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
- src/storage/dal/interface.go
- src/storage/dal/mongo/local/mock_mongo.go
- src/storage/dal/mongo/local/mongo.go
- src/storage/dal/mongo/remote/collection.go
- 将升级程序里的删除实例关系的updatgeflag字段改成分页删除，防止实例数据过多时DB io timeout
> 将升级程序里的删除实例关系的updatgeflag字段改成分页删除，防止实例数据过多时DB io timeout

- src/common/metadata/attribute.go
- 对于操作实例属性产生的报错，之前会显示以propertyid进行拼接的报错信息，不太友好。目前改为使用propertyName进行拼接。
> fix: 对于操作实例属性产生的报错，目前可正确显示为propertyName。

- src/web_server/service/service.go
- 去掉gin自带的recovery中间件，不打印panic关键字
> 去掉gin自带的recovery中间件，不打印panic关键字

- src/web_server/logics/excel_util.go
- src/web_server/service/host.go
- src/web_server/service/util.go
- 修复excel导入数据里用户类型值为中英文时的正则校验失败
- 修复登陆版本获取错误的问题
> 修复excel导入数据里用户类型值为中英文时的正则校验失败和登陆版本获取错误的问题

- src/scene_server/proc_server/service/processinstance.go
- 将list_process_related_info接口的返回总数count改为条件下的总数，不受分页参数影响
> 将list_process_related_info接口的返回总数count改为条件下的总数，不受分页参数影响

- src/common/definitions.go
- src/web_server/logics/excel_util.go
- src/web_server/logics/host.go
- src/web_server/logics/util.go
- 修复在excel导入编辑少量主机字段时，没有忽略业务拓扑、业务名、云区域等字段值为'--'而导致报错的问题
- 修复因db查询超时导致导入1000台主机失败的问题
> excel导入主机问题修复

- src/scene_server/topo_server/service/fulltextsearch.go
- 修复ES全文检索MAC地址这种带有':'等特殊符号报错的问题
> 修复ES全文检索MAC地址这种带有':'等特殊符号报错的问题

- src/source_controller/cacheservice/event/watch/watch.go
> 去除watch功能升级兼容逻辑，使用不存在的cursor监听时直接报错

- src/common/definitions.go
- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/y3.9.202102011055/add_os_type_index.go
- src/scene_server/admin_server/upgrader/y3.9.202102011055/pkg.go
- src/scene_server/operation_server/logics/logics.go
- src/source_controller/coreservice/core/operation/inner_chart.go
- src/source_controller/coreservice/core/operation/operation.go
- 优化统计业务总数、主机总数的接口
- 优化根据模型字段分组计数的接口
- 修复统计各业务下主机数量不对的问题
close #issue 5047
数据库里有业务数1966，主机数569694，在6核16G的mac下测试
原耗时324秒；优化后耗时1秒
原耗时5秒；优化后耗时1秒
原耗时3秒；优化后耗时0.3秒
> 优化统计业务总数、主机总数和根据模型字段分组计数的接口

- src/ac/parser/topolatest.go
- src/apimachinery/toposerver/inst/api.go
- src/apimachinery/toposerver/inst/inst.go
- src/common/metadata/inst.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/service_business_initfunc.go
- src/test/topo_server/object_test.go
- 添加根据实例名模糊查询模型实例名称列表的接口
close issue #5050
> 添加根据实例名模糊查询模型实例名称列表的接口

- src/common/util/model.go
- 修复查询模型属性接口在查询属性相关的分组时使用了or条件，被后续推荐业务ID查询条件覆盖的问题
> 修复添加模型的业务ID查询条件直接覆盖or条件的问题

- src/ac/parser/topolatest.go
- src/apimachinery/apiserver/api.go
- src/apimachinery/apiserver/apiserver.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/service_business_initfunc.go
- src/web_server/logics/association.go
- src/web_server/logics/excel.go
- src/web_server/service/host.go
- 修复当主机有关联主线模型实例时，导出主机失败的问题
因主机关联关系实例的导出只需要实例唯一校验字段，所以在toposerver增加查询所有模型实例唯一校验字段的接口
该接口只会返回唯一校验字段，即使主机关联了用户没权限的业务，也能正常导出关联关系excel表里的业务唯一字段
> 修复当主机有关联主线模型实例时，导出主机失败的问题

- src/ac/parser/topolatest.go
- src/ac/parser/util.go
- src/apimachinery/coreservice/association/api.go
- src/apimachinery/coreservice/association/association.go
- src/apimachinery/toposerver/association/apis.go
- src/apimachinery/toposerver/association/association.go
- src/common/auditlog/association.go
- src/common/metadata/association.go
- src/scene_server/datacollection/logics/report.go
- src/scene_server/host_server/logics/object.go
- src/scene_server/host_server/service/host.go
- src/scene_server/topo_server/core/inst/association.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/import_association.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/service/association.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/service_business_initfunc.go
- src/source_controller/coreservice/core/association/instance.go
- src/source_controller/coreservice/core/association/instance_test.go
- src/source_controller/coreservice/core/cloud/synctask.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/service/association.go
- src/source_controller/coreservice/service/instances_dependence.go
- src/storage/driver/mongodb/table.go
- src/test/topo_server/asst_test.go
- src/web_server/logics/association.go
- 实例关联数据写入相应分表
**注意：因为需要知道模型ID才能知道实例关联所在的表，因此对所有相关接口增加了必填objID的参数校验，会导致部分原有接口不可用**
> 实例关联数据写入相应分表

- src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
- src/scene_server/host_server/service/cloudarea.go
> 3.2升级到3.9进程有空bind_ip时使用默认值127.0.0.1

- src/scene_server/auth_server/logics/fetch_instance_info.go
- src/scene_server/auth_server/logics/list_instance.go
- src/scene_server/auth_server/service/gen_method.go
仅支持了按ID查询模型实例的回调接口，如何对其它直接按名称查询的接口进行分页需要再看一下怎么实现
> 权限中心回调接口支持动态模型实例

- src/storage/stream/event/watch.go
- 修复cacheservice未全部监听完成时切主导致重试时取消context，引起的监听时报错导致panic退出的问题
> cacheservice事件监听忽略context cancelled错误

- src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
- 修复upgrader中一部分bind ip已转为正确格式时校验不通过的问题
> 修复upgrader中一部分bind ip已转为正确格式时校验不通过的问题

- src/ac/iam/client.go
- src/ac/iam/iam.go
- src/ac/iam/initial_common_actions.go
- src/ac/iam/types.go
- 新增支持权限中心常用分组：业务运维，主机资源管理员，开发者，模型关系维护人，审计员。
> 添加权限中心内置的常用操作

- scripts/init.py
- src/common/backbone/configcenter/viper.go
- src/common/metadata/dataid.go
- src/common/resource/esb/esb.go
- src/scene_server/admin_server/app/options/options.go
- src/scene_server/admin_server/app/server.go
- src/scene_server/admin_server/service/dataid.go
- src/scene_server/admin_server/service/migrate.go
- src/scene_server/admin_server/service/service.go
- src/scene_server/admin_server/upgrader/register.go
- src/scene_server/admin_server/upgrader/x18.10.10.01/pkg.go
- src/scene_server/admin_server/upgrader/x18.10.10.01/procsrv.go
- src/thirdparty/esbserver/gse/api.go
- src/thirdparty/esbserver/gse/esbserv.go
- 添加注册主机静态快照采集的dataid的接口，支持dataid的新增、更新、和删除功能
- adminserver的mongodb、redis和common配置从相应配置文件读取
> 添加注册主机静态快照采集的dataid的接口

- src/common/metadata/attribute.go
- src/common/paraparse/host.go
- src/common/util/struti.go
- src/common/util/struti_test.go
- src/scene_server/admin_server/upgrader/y3.9.202010281615/update_inst_time_val.go
- src/source_controller/coreservice/core/instances/instance_validate.go
- 时间类型字段兼容带时区的格式
_因为db中的时间类型字段返回时会被marshal为带时区的格式，所以需要兼容直接将返回值传回的情况_
> 时间类型字段兼容带时区的格式

- src/scene_server/topo_server/core/operation/inst.go
- 修复导入实例报错信息不正确问题：
问题原因为实例创建函数中获取报错信息字典的key值时，在报错信息key值数组中拿出的是索引而不是索引对应的值导致存在字典中检索不到对应的值从而出现空的报错信息
> bugfix 修复导入实例报错信息不正确问题 issue #5186

- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/service/association.go
- src/source_controller/coreservice/core/association/instance.go
> fix: DeleteAssociationInstBatch function adapt to new DB-model

- src/apimachinery/rest/request.go
- src/scene_server/topo_server/core/settemplate/settemplate.go
- src/scene_server/topo_server/core/settemplate/sync_status.go
- src/scene_server/topo_server/service/set_template.go
- xxxx
- xxxx
- 集群被删除后， 集群同步表数据还存在，依然展示在集群模板实例中展示
- 集群同步表中没有集群同步市局的时候，在集群模板实例中不显示的
close   #5238
> fix: 修服务集群模板实例展示问题

- src/common/watch/cursor.go
- src/common/watch/cursor_test.go
- src/source_controller/cacheservice/event/flow/flow.go
- src/source_controller/cacheservice/event/key.go
- src/tools/cmdb_ctl/cmd/watch.go
- 事件服务Cursor新增支持UniqueKey功能，保证cursor唯一
> demand: event flow support cursor with unique key function. and common instance use unique key with bk_inst_id

- src/common/metadata/audit.go
- src/scene_server/topo_server/service/auditlog.go
- 操作审计的“账号”字段增加条件查询选择 ——> <包含> 和 <不包含>
- 拓展了resource_name 增加条件查询选择
issue #5283
> feature：操作审计支持账号In与NotIn操作

- src/common/metadata/object.go
- src/web_server/logics/object.go
- src/web_server/service/object.go
- src/web_server/service/service.go
- 查询多个模型实例的数量
- 单次最多支持查询二十个模型
- 重复模型id会去重后再查询
issue #5322
> feature：查询多个模型的实例数量

- src/scene_server/topo_server/service/fulltextsearch.go
- 调整通用模型实例表的es索引名,以兼容实例表拆分前后的情况
> 调整通用模型实例表的es索引名

- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/service/inst.go
- src/source_controller/coreservice/core/instances/instance_crud.go
- src/storage/driver/mongodb/monogdb.go
- 调整唯一校验失败时的报错信息
- 修复查询关联的实例的接口在自关联的情况下返回错误的问题
> 修复查询关联的实例的接口在自关联的情况下返回错误的问题+调整唯一校验失败时的报错信息

- src/common/registerdiscover/zkregdiscv.go
> 修复zk服务节点丢失后不能重新注册的问题

- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/y3.9.202106301910/change_host_attr_editable.go
- src/scene_server/admin_server/upgrader/y3.9.202106301910/pkg.go
- src/test/host_server/host_test.go
> 将主机的自动发现信息属性分组下的属性设置为可编辑

- src/common/metadata/procserver.go
- src/thirdpartyclient/esbserver/user/api.go
- src/thirdpartyclient/esbserver/user/esbserv.go
- src/web_server/middleware/user/plugins/method/self/userinfo.go
- src/web_server/service/util.go
- cmdb导出实例数据，当导出的字段包含用户字段，且用户字段有值时，导出非常慢
- 提高cmdb导出实例数据速度
- 依赖的用户管理后台版本>1.5
close issue #5425
> 修改获取用户列表接口，提高cmdb实例数据导出

- src/ac/extensions/business.go
- src/scene_server/topo_server/service/inst_business.go
- 接入权限中心场景下，当前端输入不存在的业务id时报错
#5472
> fix: 接入权限中心场景下，当前端输入不存在的业务id时直接返回空，而不是返回错误

- resources/language/default/web.json
- resources/language/en/web.json
- src/web_server/logics/excel.go
- src/web_server/logics/util.go
- excel导出用户管理中不存在的用户时，导出中英文名时保留原用户名并提示用户不存在
close issue  https://github.com/Tencent/bk-cmdb/issues/5491
> optimize: excel导出用户管理中不存在的用户时，导出中英文名时保留原用户名并提示用户不存在

- resources/language/default/web.json
- resources/language/en/web.json
- src/web_server/logics/excel.go
- src/web_server/logics/util.go
- excel导出用户管理中不存在的用户时，导出中英文时保留原用户名并提示用户不存在
close issue https://github.com/Tencent/bk-cmdb/issues/5491
> optimize: excel导出用户管理中不存在的用户时，导出中英文时保留原用户名并提示用户不存在

- src/common/metadata/webserver.go
- src/web_server/middleware/user/plugins/method/self/userinfo.go
- src/web_server/middleware/user/public.go
- 前端获取用户，后端依旧使用原来的get_all_users用户管理接口来获取，虽然慢，但是不会超时
请提供以下信息:
> 使用get_all_users接口获取全量用户

- src/source_controller/coreservice/core/process/service_instance.go
- 获取实例数据时，前端没有传递排序字段时，默认使用实例ID进行排序
> 默认使用服务实例ID排序

- src/ui/src/views/index/children/host-search.vue
> fix: 首页主机高级搜索跳转到资源主机全部列表页

- src/apimachinery/coreservice/system/api.go
- src/apimachinery/coreservice/system/system.go
- apimachinery/coreservice/system包名错误
> fix: apimachinery package name typo

- src/source_controller/coreservice/core/association/instance.go
> 修复新建实例自关联的关联关系时对该实例获取两次锁导致失败的问题

- vendor/github.com/rentiansheng/xlsx/datavalidation.go
- 下载批量导入模板时，枚举值过多，无法显示枚举值。修改限制枚举值的长度。
> 修改下载模板枚举值长度限制

- src/common/metadata/association.go
- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- src/scene_server/topo_server/service/association.go
- src/scene_server/topo_server/service/inst_business.go
- 修复使用主机/服务实例数量统计接口引起的topo创建问题。
> 修复使用主机/服务实例数量统计接口引起的topo创建问题

- src/source_controller/coreservice/core/auditlog/audit.go
- 大量ip链接起来的长度大于1024的场景下只取前256长度，防止由于mongo index长度限制写入失败
> fix:大量ip链接起来的长度大于1024的场景下只取前256长度，防止由于mongo index长度限制写入失败

- src/common/definitions.go
- src/common/util/time.go
- src/scene_server/admin_server/service/database.go
- src/scene_server/admin_server/service/service.go
- adminserver 新增清理审计日志接口，用户输入"2021-08-19"指定清理日期之后，会将此日期之前的日志清理掉。#5603
- 示例如下:
`curl -d '{"day":"2021-08-19"}' -X POST -H 'Content-Type:application/json' -H 'BK_USER:migrate' -H 'HTTP_BLUEKING_SUPPLIER_ID:0' http://127.0.01:60002/migrate/v3/delete/auditlog`
注意:
1、此操作属于高危操作，在清理日志之前需要确定清理的可行性，如果需要必须事先备份好审计日志，防止误操作之后日志丢失。
2、删除操作属于cpu和磁盘io密集型操作，为了防止此操作造成cpu或者磁盘io过高，实现上做了处理，根据测试如果删除100万数据，需要的时间大概10分钟。
3、建议此操作在业务低峰期进行操作。并且日志量过大，分时间段进行操作。您想删除半年之前数据，可以分别指定删除3年前数据、2年前数据、1年前数据、半年前数据。
> 新增清理审计日志接口

- src/common/metadata/process.go
- src/scene_server/proc_server/logics/processinstance.go
- src/web_server/service/util.go
- 导出实例数据时，实例数据中包含用户数据，如果用户数量大，一次性获取所有用户数据出现502错误。如果用户量数据大的话，按照分页的方式去获取所有的用户数据，这样能保证正确的获取所查询的所有用户数据。
> 导出实例数据时，分页获取用户数据

- src/web_server/service/util.go
- 导出实例数据时，实例数据中包含用户数据，如果用户数量大，一次性获取所有用户数据出现502错误。如果用户量数据大的话，按照分页的方式去获取所有的用户数据，这样能保证正确的获取所查询的所有用户数据。
> 实例数据导出时、用户量大、获取用户数据失败

- src/common/metadata/dynamic_grouping.go
- 处理动态分组，字段类型为组织时，attrType为organization， value值当成numeric进行校验
> 将组织字段类型调整为numeric type

- src/source_controller/cacheservice/event/identifier/handler.go
> 主机身份事件监听在watch token里添加id和cursor信息，防止用户用过期的最后一个cursor请求时报错

- src/ac/iam/iam.go
- src/scene_server/admin_server/upgrader/y3.10.202109131607/migrate_iam_sysinstances.go
> fix: skip migrate iam instances when first installation

- src/ui/src/utils/tools.js
- src/ui/src/views/dynamic-group/preview/preview.vue
> fix: 修复动态分组预览初始页码错误导致无法正确获取数据的问题

- src/web_server/logics/excel.go
- src/web_server/logics/excel_util.go
- src/web_server/logics/host.go
- src/web_server/logics/inst.go
- 添加判断防止导入关联关系时获取对应单元格数据数组越界
issue #5747
> bugfix 添加判断防止导入关联关系时获取对应单元格数据数组越界

- src/scene_server/admin_server/upgrader/y3.10.202109181134/migrate_svc_inst_id_to_proc.go
- src/tools/cmdb_ctl/cmd/migrate_check.go
- 3.10迁移校验小工具添加校验和清理无进程关系的进程的功能，使用方式：
1. 校验全部，包括唯一索引和进程：./tool_ctl migrate-check --check-all=true
2. 单独校验唯一索引：./tool_ctl migrate-check unique
3. 单独校验进程：./tool_ctl migrate-check process
4. 清除无进程关系的进程：./tool_ctl migrate-check process --clear-proc=true
> 3.10迁移校验小工具添加校验和清理无进程关系的进程的功能

- src/common/metadata/configadmin.go
> 初始化的snapshot_biz_name必须是蓝鲸

- src/web_server/logics/inst.go
- 导入excel数量超限返回正确的报错
close #5833
> bugfix 导入excel数量超限返回正确的报错

- src/scene_server/topo_server/core/operation/inst.go
> 修复判断主线父节点忽略内置集群模块时对default进行强制类型转换导致panic的问题

- src/scene_server/admin_server/service/dataid.go
- src/scene_server/admin_server/service/service.go
- src/thirdparty/esbserver/gse/api.go
- src/thirdparty/esbserver/gse/esbserv.go
3.1版本之后的gse不支持之前的用脚本注册dataid的方式，所以cc添加一段兼容逻辑在没有旧版本的dataid的情况下调用gse接口进行注册
注册旧版本dataID的接口的调用方式：curl -X POST -H 'Content-Type:application/json' -H 'BK_USER:migrate' -H 'HTTP_BLUEKING_SUPPLIER_ID:0' http://环境上的adminserver的ip:port地址/migrate/v3/migrate/old/dataid
**注意：
1. 本次调整了新老dataid判断是否已注册的方式，使用gse的错误码14001进行判断，该错误码在gse的ee1.7.18、 ce3.6.18中支持，合入该PR后的cc向此版本以下的gse注册会失败报错**
2. 要求用户在全新部署cmdbv3.9+时，需要调用该接口注册basereport的data id，否则无法正常采集主机的静态快照数据。
> 新增支持更新basereport老版本data id的到gse的接口

- src/scene_server/host_server/logics/host.go
- 查询主机对应模块的模板id过滤模板id为0的模块
close #5959 #5905
> feature 查询主机对应模块的模板id过滤模板id为0的模块

- src/ac/iam/iam.go
- src/common/index/instance.go
- src/scene_server/admin_server/app/server.go
- src/scene_server/admin_server/iam/synciam.go
- src/scene_server/topo_server/logics/model/attribute.go
- src/scene_server/topo_server/logics/model/classification.go
- src/scene_server/topo_server/logics/operation/import_association.go
- src/source_controller/cacheservice/event/watch/watch.go
- src/storage/dal/mongo/local/transaction.go
- src/web_server/logics/excel_util.go
- 创建模型时自动添加的bk_inst_name的唯一索引添加partial filter，防止和定时同步时生成的index冲突
- 创建模型分组和属性接口的返回实际创建的数据
- 模型实例权限同步等待db初始化完成后再开始
- 提交事务时若之前没有事务（无db操作的情况下）则跳过提交操作，防止AutoRunTxn里的函数直接返回nil的时候报错txn number不存在
- 修复excel导入反向实例关联和带/的组织名失败的问题
- 修复watch在正好超时的瞬间产生了一个新事件的情况下丢事件的问题
> 3.10测试问题修复

- src/web_server/logics/excel.go
> bugfix 修复导入时获取excel内容逻辑

- src/scene_server/proc_server/service/serviceinstance.go
- src/scene_server/topo_server/logics/settemplate/sync_status.go
- 解决当删除服务实例，但模块内的服务实例数不为零场景的同步问题 close #5977.
> 解决当删除服务实例，但模块内的服务实例数不为零场景的同步问题

- src/scene_server/auth_server/sdk/auth/count.go
- 修复用户拥有无限制业务权限，创建业务后查询资源池业务报错问题
close #5984
> bugfix 添加初始化指针操作防止调用出现panic

- src/ac/iam/types.go
- src/scene_server/topo_server/logics/model/mainline_association.go
- 修复无法跳转到权限中心申请业务集删除权限的问题 
close #6016
- 修复创建主线模型时自动为下层节点创建该层级的父节点时审计记录到通用模型实例的问题
> 修复无法跳转到权限中心申请业务集删除权限的问题

- src/web_server/logics/department.go
- skip-login和opensource登录方式，是否调用esb接口的判断方式改为根据登录方式判断，防止上述两种登录方式情况下，配了esb的配置，调用出现问题
> 调整opensource和skip-login登录方式是否调用esb接口的判断方式

- scripts/Makefile
- 去掉go build时的-i参数，官方已显示 The -i flag is deprecated. Compiled packages are cached automatically.
> 去掉go build时的-i参数

- src/common/index/collections/platbase.go
- 修复云区域名称由唯一校验产生的新版本的唯一索引会和旧版本的冲突的问题
> 云区域名称的唯一索引调整为新版本的形式

- src/scene_server/topo_server/logics/model/attribute.go
- src/scene_server/topo_server/service/object_attribute.go
> bugfix 修复删除模型属性时该模型属性为唯一校验报错未返回问题

- src/web_server/logics/association.go
- src/web_server/logics/excel.go
- 修复业务下导出主机为源模型时查询模型关联关系带上业务id导致查询结果为空的问题
- 修复导出模型的关联中包含自关联时报错
close #6044
> bugfix 修复导出主机关联关系时报错问题

- src/common/metadata/process.go
- src/common/metadata/process_bind_info.go
- src/scene_server/proc_server/service/processinstance.go
> 服务实例的端口和协议信息校验需要和进程模板中的校验规则保持一致

- src/scene_server/topo_server/logics/inst/association.go
- search_instance_associations只支持查询源模型关联，不支持查询目标模型关联
issues https://github.com/Tencent/bk-cmdb/issues/6112
> 修复search_instance_associations不支持双向查询关联关系

- src/ui/src/components/host-topo-path/host-topo-path.vue
- src/ui/src/components/ui/auth/auth-mask.vue
- src/ui/src/views/set-template/index.vue
- 去除主机列表中hover显示的跳转业务拓扑tips避免极端情况下遮挡跳转icon
- 添加license和删除注释代码
> 去除主机列表中hover显示的跳转业务拓扑tips避免极端情况下遮挡跳转icon

- src/common/definitions.go
- src/common/metadata/hostserver.go
> 限制绑定/解绑主机agentID接口的参数列表数量为200

- src/common/metadata/host.go
- src/scene_server/host_server/service/hostapplyrule.go
- 修复主备负责人在进行主机自动应用时，当修改目的负责人只有一个，并且属于原来一组负责人之一时，主机自动应用失效。
例如原主机的主负责人是 ： A,B，需要通过主机自动应用改成A ，那么会触发原bug
> 修复主备负责人在进行主机自动应用时，当修改目的负责人只有一个，并且属于原来一组负责人之一时，主机自动应用失效

- src/scene_server/event_server/sync/hostidentifier/hostIdentifier.go
- 设置hostid文件同步到机器时旧文件的备份名，防止根据时间更改旧文件名，导致文件越来越多
> 设置hostid文件同步到机器时旧文件的备份名

- src/web_server/service/util.go
- 修复excel导出时用户名太多导致超过esb限制的问题
- 修复excel导出时map并发读写panic的问题
> 调整获取esb用户列表的请求用户名长度

- src/scene_server/topo_server/service/fulltextsearch.go
- 修复es中将mongo的int字段存为string类型，从es中查询结果，无法将string转为int
> 修复es中存储的string无法转换为int

- src/scene_server/host_server/service/transfer.go
- 主机转移模块，如果目标模块需要创建服务实例，由于proc进程创建服务实例新增了不超过100的限制，所以主机模块转移需要同步做兼容处理。
> 修复主机转移模块场景下，如果涉及到新增服务实例，不能超过100的限制

- src/ui/config/index.js
> fix: v3.8.x关闭构建流程中的eslint检查解决过时依赖包兼容问题

- docs/support-file/helm/values.yaml
> 修改monstache默认镜像版本为v2.0.0

- src/ui/src/views/dynamic-group/form/form-property-list.vue
> fix: 动态分组的模块与集群名称模糊搜索支持直接输入字符

- src/scene_server/topo_server/logics/settemplate/sync_status.go
> 修复当没有配置集群模版属性时，查询不到对应模版的实例

- src/common/util/conv.go
- src/scene_server/admin_server/upgrader/y3.10.202109131607/util.go
> 修复权限迁移使用了GetInt64ByInterface解析string导致报错的问题

- src/web_server/service/util.go
- xxxx
- xxxx
- 获取用户数据时，get方式URL长度有限制，当用户数据过多时，拼接的用户长度就会超过URL的长度限制，所以每次请求用户数据时，将拼接的用户名称长度限制在500字节长度
> 修改获取用户数据时，拼接用户名长度限制在500字节

- src/scene_server/datacollection/collections/hostsnap/hostsnap.go
> 修复当主机快照字段采集不到时记录审计的问题

- src/common/util/chinese.go
- src/scene_server/topo_server/service/association.go
- src/scene_server/topo_server/service/inst_module.go
default>0的排前面（空闲机池），default=0的按名称排序，顺序为数字、字母和汉字首字母忽略大小写
> 调整业务拓扑默认排序方式

- src/ac/parser/settemplate.go
- src/web_server/logics/excel.go
- src/web_server/logics/excel_util.go
- src/web_server/logics/host.go
- src/web_server/logics/inst.go
> 修复excel导入数据更新时，主机关联数据无法更新，对字段bk_inst_id和bk_host_id无法校验

- src/source_controller/cacheservice/event/identifier/converter.go
- 修复当有脏数据主机id不是int64类型时，主机关系事件panic的问题
> 修复当有脏数据主机id不是int64类型时，主机关系事件panic的问题

- src/storage/stream/event/watch.go
- 修复当watch产生error原因是context cancelled时，进程退出的问题
> 修复当watch产生error原因是context cancelled时，进程退出的问题

- src/source_controller/coreservice/core/model/classification.go
- src/source_controller/coreservice/core/model/classification_crud.go
- src/source_controller/coreservice/core/model/classification_private.go
- 修复创建模型时，supplierAccount不为0，模型在内置模型分组下创建失败问题
> 修复创建模型时，supplierAccount不为0，模型在内置模型分组下创建失败问题

- src/web_server/logics/excel_util.go
- src/web_server/logics/util.go
- xxxx
- xxxx
- 修复组织类型字段为空时，无法导出实例数据
- 修复导入模型字段时，fields为空，无法做字段是否存在的校验
> 修复组织类型字段为空时，无法导出实例数据

- src/scene_server/host_server/logics/host.go
- 修复当没有自定义层级时，调用查询主机及其对应topo接口报错问题
> 修复当没有自定义层级时，调用查询主机及其对应topo接口报错问题

- src/scene_server/topo_server/logics/inst/association.go
- src/source_controller/coreservice/core/hostapplyrule/plan.go
- src/source_controller/coreservice/core/process/service_instance.go
- 关联关系中显示只有ipv6地址的主机
- 服务实例名字支持只有ipv6地址的主机
- 主机自动应用预览场景支持显示ipv6地址
> 适配主机只有单独ipv6地址的场景

- src/scene_server/auth_server/logics/util.go
> 优化权限中心的主机列表ipv4和ipv6字段用竖线分割

- src/scene_server/topo_server/service/fulltextsearch.go
> 放框全文检索的查询字符串长度

- src/source_controller/coreservice/core/instances/instance_crud.go
- xxxx
- xxxx
- 更新实例时，唯一校验失败，错误提示不明显，没有将真正的错误展示给用户，导致用户觉得很奇怪
将真实的错误返回，用户看到错误即可看出错误原因了
> 更新实例时，唯一校验失败提示不明确

- src/scene_server/topo_server/logics/inst/association.go
- src/scene_server/topo_server/logics/logics.go
- src/scene_server/topo_server/logics/operation/import_association.go
- xxxx
- xxxx
- excel导入关联关系数据时，对1:1,1:n进行校验
> excel导入关联关系时，对关联关系映射进行校验

- src/web_server/service/util.go
- 导出带用户数据的实例数据时，出现用户不存在现象
因为处理yo用户请求参数时，将临界用户丢弃了
除了cmdb的问题，用户管理接口也有问题，在并发测试场景下，可以看出没有传递zhongtao008的时候，在第四次请求里确返回了结果
> 导出带用户数据时，处理临界用户丢失问题

- src/common/metadata/attribute.go
- src/source_controller/coreservice/core/instances/instance_validate.go
- src/source_controller/coreservice/core/instances/validator_util.go
- 在创建实例时，枚举多选，枚举引用为空时，无法保存实例数据
> 创建实例时枚举多选，枚举引用可以为空

- src/source_controller/coreservice/core/process/service_template.go
- 修复进程模版相关接口鉴权时，查不到服务模版导致的鉴权问题，涉及到调用AuthorizeByServiceTemplateID方法查不到服务模版导致跳过鉴权的逻辑
> 修复进程模版相关接口鉴权时，查不到服务模版导致的鉴权问题

- src/common/metadata/dynamic_grouping.go
- src/scene_server/topo_server/logics/inst/set.go
- 创建动态分组时，枚举多选，枚举引用字段无法创建查询条件
issues #6654
> 枚举多选，枚举引用无法创建动态分组

- src/scene_server/datacollection/collections/hostsnap/hostsnap.go
- 调整主机磁盘容量的计算方式，将之前的每个分区容量转换为GB后取整再相加，调整为将所有分区容量相加后再转换为GB后取整
issues #6716
> 调整主机磁盘容量计算方式

- src/scene_server/datacollection/app/server.go
- 设置连接kafka允许的最小版本，此版本为Shopify/sarama包允许的使用消费者组的最小版本，https://github.com/Shopify/sarama/issues/1363
> 设置连接kafka允许的最小版本

- src/scene_server/topo_server/service/object_attribute.go
- 修复删除模型属性字段场景下错误的获取主机自动应用规则的问题
close #6752
> 修复删除模型属性字段场景下错误的获取主机自动应用规则的问题

- src/ui/src/views/dynamic-group/preview/preview.vue
> fix: 修复预览动态分组查询对象是集群时异常的问题

- src/scene_server/host_server/service/service_initfunc.go
- src/scene_server/proc_server/service/serviceinstance.go
- 修复当不传模块id时，查询不到业务下的服务实例的问题, 对应接口文档：https://github.com/TencentBlueKing/bk-cmdb/blob/v3.10.x/docs/apidoc/cc/zh_hans/list_service_instance.md
> 修复当不传模块id时，查询不到业务下的服务实例的问题

- src/scene_server/topo_server/logics/field_template/compare_unique.go
> fix: compare unique template failed when object unique belongs to other template

- src/source_controller/coreservice/service/model_quote/quoted_inst_validate.go
> 当表格数字类型字段没传时，默认值和模型实例保持一致

- src/scene_server/topo_server/service/field_template/field_template.go
- src/scene_server/topo_server/service/field_template/object_relation.go
- 字段模版先更新唯一校验再创建唯一校验，防止旧唯一校验和新加唯一校验规则冲突
> 字段模版先更新唯一校验再创建唯一校验

- src/scene_server/topo_server/logics/field_template/compare_attr.go
- 修复字段组合模版两个属性id和name一样时对比报错问题
> 修复字段组合模版两个属性id和name一样时对比报错问题

- src/common/metadata/process_bind_info.go
> 修复服务模板IP选项不可以置空的问题

- src/scene_server/topo_server/logics/model/attribute.go
- 表格字段添加默认值后，编辑修改勾选设置“当前列的值必填”不生效
close #7307
> 表格字段添加默认值后，编辑修改勾选设置“当前列的值必填”不生效

- src/common/metadata/instance_struct.go
- src/common/metadata/process.go
- src/scene_server/proc_server/logics/processinstance.go
- src/scene_server/proc_server/service/serviceinstance.go
- src/scene_server/task_server/taskconfig/taskconfig.go
服务模板同步目前是按照模块维度进行同步的，服务模板里进程较多且模块里主机较多的情况下会超时。
- 解决方案：
在原有的模块维度下按主机维度拆单，按主机数*进程数<=1000拆单，防止task-server回调超时（默认http请求超时时间25s，默认请求的context超时时间为2分钟，mongodb事务默认超时时间为60s）
- 影响：
原本一个模块的同步是在一个事务里的，现在拆单后是一批主机为一个事务。理论上在同步的场景下只要做到可重入就可以，所以拆单应该是可以接受的
> 修复服务模板同步超时的问题

- src/common/metadata/dynamic_grouping.go
- src/scene_server/host_server/service/dynamic_grouping.go
修复预览动态分组时提示：‘获取自定义查询详情失败, HTTP请求失败’的问题
> 修复预览动态分组时提示：‘获取自定义查询详情失败, HTTP请求失败’的问题

- src/ac/parser/topolatest.go
- src/apimachinery/apiserver/api.go
- src/apimachinery/apiserver/apiserver.go
- src/web_server/service/host.go
需要注意：之前导出主机时查询自定义层级报错no matched rules，这个报错会被忽略，导致如果有自定义层级的话是不会导出出来的，修复后会导出自定义层级
> 修复导出主机时报错no matched rules的问题

- docs/support-file/changelog/release.md
- docs/support-file/helm/Chart.yaml
- src/scene_server/admin_server/app/server.go
- 修复启动adminserver时，由于Service.Logics还没赋值导致panic的问题
> 修复启动adminserver时，由于Service.Logics还没赋值导致panic的问题

- src/common/paraparse/host.go
- src/scene_server/host_server/logics/hostsearch.go
- src/scene_server/host_server/service/host.go
-修复主机搜索时ipv6条件失效问题，对应issues：
https://github.com/TencentBlueKing/bk-cmdb/issues/7500
https://github.com/TencentBlueKing/bk-cmdb/issues/7502
> 修复主机搜索时ipv6条件失效问题

- resources/language/default/property.json
- resources/language/en/property.json
- src/source_controller/coreservice/service/translate.go
> 处理模型实例国际化的问题

- src/source_controller/coreservice/service/model.go
- src/web_server/service/excel/operator/model/operator.go
- 修复模型属性字段导出excel时枚举、枚举多选、表格字段的默认值没有导出 --- 定义为正常
- 修复模型属性字段excel导入时报错信息不规范
- 修复模型属性字段excel中日期/时间/用户/时区/列表这四个字段没做任何变动导入时报错问题
issue：https://github.com/TencentBlueKing/bk-cmdb/issues/6775
> 修复模型属性字段导出时默认值并未被导出、导入时报错信息不规范和日期/时间/用户/时区/列表这四个字段没做任何变动导入时报错问题

- src/ui/src/views/dynamic-group/form/form.vue
- 动态分组当没有添加条件，点击提交后，再次选择添加条件，对应的提示信息没有消失
> fix: bug修复

- src/ui/src/views/business-topology/host/host-list.vue
> fix: 容器主机列表搜索为空样式规范

- src/ui/package.json
> chore: bump bk-magic-vue to 2.5.8

- src/ui/src/views/business-set/router.config.js
- src/ui/src/views/business/router.config.js
- src/ui/src/views/project/router.config.js
- src/ui/src/views/resource/router.config.js
- 资源页面中，除了「管控区域、云账号、云资源发现」外，右侧面板面包屑都带上返回箭头，返回到“资源目录”页面
> fix: 资源页面中，右侧面板面包屑都带上返回箭头，返回到“资源目录”页面

- src/scene_server/proc_server/service/serviceinstance.go
> 修复根据集群模板id查不到模块时返回业务所有服务实例的问题

- src/source_controller/coreservice/core/instances/instance_validate.go
- 修复创建主线拓扑节点时，可以使用string类型的bk_parent_id的问题
> 修复创建主线拓扑节点时，可以使用string类型的bk_parent_id的问题

- src/scene_server/proc_server/service/serviceinstance.go
> 修复批量同步服务模板实例的属性时，只有一个成功的问题

- src/web_server/service/excel/operator/inst/importer/importer.go
- 修复导入动态寻址方式的主机时显示导入成功但主机不存在的问题
> 修复导入动态寻址方式的主机时显示导入成功但主机不存在的问题

- src/common/metadata/object.go
- src/scene_server/topo_server/logics/model/object.go
- src/source_controller/coreservice/core/model/model_crud.go
- 修复cmdb导入模型后，模型的顺序会被打乱问题；
- 修复在删除模型时，模型排序序号不连续问题；
> 修复cmdb导入模型后，模型的顺序会被打乱问题；修复在删除模型时，模型排序序号不连续问题；

- src/source_controller/coreservice/core/instances/instance.go
- src/source_controller/coreservice/core/instances/instance_validate.go
- 对应issue：https://github.com/TencentBlueKing/bk-cmdb/issues/7626
- 模型实例的创建时间和更新时间字段不可由用户指定，应当在新增或更新时由系统生成，如果在创建或更新时用户传递了相应字段则移除
> 修复接口涉及到创建时间与更新时间的字段参数不填写的，都会报未知的错误

- src/common/types/manager.go
3.10.x优化当未启用鉴权时，依然频繁扫描zk中的auth节点导致记录大量日志的问题
> 3.10.x优化当未启用鉴权时，依然频繁扫描zk中的auth节点导致记录大量日志的问题

- src/scene_server/topo_server/service/inst_set.go
> 批量创建集群设置最大限制数量为100

- src/common/types/manager.go
优化当未启用鉴权时，依然频繁扫描zk中的auth节点导致记录大量日志的问题
> 优化当未启用鉴权时，依然频繁扫描zk中的auth节点导致记录大量日志的问题

- src/ui/package.json
- src/ui/src/components/filters/store.js
- src/ui/src/components/model-manage/field-group/index.vue
- src/ui/src/components/ui/form/form.vue
- src/ui/src/components/ui/form/longchar.vue
- src/ui/src/components/ui/form/organization.vue
- src/ui/src/views/business-set/children/management-form.vue
- src/ui/src/views/business-topology/children/create-set.vue
- src/ui/src/views/index/children/host-search.vue
- textarea悬浮设置zIndex
- 组织下拉框增加flipOnUpdate属性
- cmdb-form组件增加对slot的内容进行校验是否修改过
- 修复首页-高级筛选下固资编号默认为''问题
- 新建集群, 粘贴名称时textarea设置rows
- 模型下内置分组不能编辑
> fix: 表单项内容超出后支持悬浮样式

- src/apimachinery/toposerver/fieldtemplate/api.go
- src/apimachinery/toposerver/fieldtemplate/field_template.go
- src/apimachinery/toposerver/object/api.go
- src/apimachinery/toposerver/object/attribute.go
- src/apimachinery/toposerver/toposerver.go
- src/common/metadata/attribute.go
- src/common/metadata/field_template.go
- src/common/metadata/taskserver.go
- src/common/metadata/webserver.go
- src/test/topo_server/field_template_test.go
- src/test/topo_server/model_quote_test.go
- src/test/topo_server/topo_server_suite_test.go
添加模型引用类型、字段组合模板功能测试用例:
1. 字段组合模版 https://github.com/TencentBlueKing/bk-cmdb/blob/v3.11.x/src/scene_server/topo_server/service/field_template/service.go
2. 表格类型 
实例相关：
https://github.com/TencentBlueKing/bk-cmdb/blob/v3.11.x/src/scene_server/topo_server/service/service_model_quote_initfunc.go
模型相关：
模型的表格字段crud以及其他场景的测试用例
> 添加模型引用类型、字段组合模板功能测试用例

- src/apimachinery/apiserver/apiserver.go
- src/apimachinery/procserver/process/api.go
- src/apimachinery/procserver/service/api.go
- src/apimachinery/toposerver/inst/api.go
- src/apimachinery/toposerver/settemplate/apis.go
- src/scene_server/auth_server/service/pull_resource.go
- src/scene_server/host_server/service/hostapplyrule.go
- src/scene_server/proc_server/service/service.go
- src/source_controller/coreservice/core/hostapplyrule/rule.go
- 修复权限中心查询实例时输入正则表达式中的部分特殊字符时报错问题
说明：后续不再使用正则匹配，而是简单的字符串模糊匹配，所有输入均转义为普通字符串
> 修复权限中心查询实例时输入正则表达式中的部分特殊字符时报错问题

- src/ui/src/views/business/index.vue
- src/ui/src/views/dynamic-group/index.vue
- src/ui/src/views/dynamic-group/preview/preview-result.vue
- src/ui/src/views/field-template/index.vue
- 动态分组预览滚动到底部线条不对齐
- 搜索存在的字段模板名称，前端提示搜索为空
- 资源-业务下当存在21个业务出现翻页后，归档下一页第21条业务后，页面显示没有业务权限
> fix: 动态分组预览滚动到底部线条不对齐

- src/ui/src/api/index.js
- src/ui/src/components/ui/form/user.vue
- src/ui/src/main.js
- src/ui/src/utils/login-helper.js
> fix: 组织与用户接口token失效时主动弹出登录窗口

- src/source_controller/cacheservice/cache/topology/logic.go
- get_biz_brief_cache_topo接口按名字排序
> get_biz_brief_cache_topo接口按名字排序

- src/scene_server/host_server/service/dynamic_grouping.go
- 修复execute_dynamic_group接口锁定条件为时间类型且可变条件没有的情况下panic的问题
> 修复execute_dynamic_group接口锁定条件为时间类型且可变条件没有的情况下panic的问题

- src/storage/stream/event/list_watch.go
- src/storage/stream/event/watch.go
- 修复一些watch相关问题
1. 当watch使用的token或起始时间太老导致oplog中对应数据已被删除时，mongodb可能会报错`(CappedPositionLost) Error in $cursor stage :: caused by :: CollectionScan died due to position in capped collection being deleted. Last seen record id: RecordId(xxx)`，此时cacheservice会报错退出。这种情况下应该将这个报错当作watch的FatalError来处理，从当前时间节点开始监听
2. watch遇到FatalError时会重置streamOptions里的token和起始时间，但是cc的watch opts的token和起始时间没有一起重置，然后重试时只会拉取db里最新的token而不会拉取起始时间，导致根据cc的watch opts重新生成streamOptions时会从进程启动时设置的起始时间开始监听
> 修复一些watch相关问题

- src/common/paraparse/host.go
- 修复search_host接口在设置了hostID条件和业务条件时拼接条件为特殊格式`{"field": "bk_host_id", "operator": "$eq", "value": {"$in": [1,2], "$eq": 1}}`时解析错误的问题
> 修复search_host接口问题

- src/ui/package.json
- src/ui/src/IframeEntry.vue
- src/ui/src/main.js
- src/ui/src/router/business-interceptor.js
- src/ui/src/router/index.js
- src/ui/src/views/index/index.vue
> feat: 支持iframe加载模式

- src/scene_server/event_server/sync/hostidentifier/common.go
> 下发hostid文件大小限制调整为100kb

- src/ui/src/components/filters/filter-form.vue
- src/ui/src/components/filters/general-model-filter-form.vue
- src/ui/src/components/search/array.vue
- src/ui/src/components/search/longchar.vue
- src/ui/src/components/search/map.vue
- src/ui/src/components/search/singlechar.vue
- src/ui/src/components/search/table.vue
- src/ui/src/views/dynamic-group/form/form-property-list.vue
> fix: 高级筛选 和 通用模型实例的高级筛选 悬浮框被遮挡

- src/common/metadata/page.go
- 校验分页参数的start和limit均不可以小于0
修复limit为负数时coreservice( https://github.com/TencentBlueKing/bk-cmdb/blob/v3.13.x/src/source_controller/coreservice/core/host/searcher/searcher.go#L219 )panic的问题
> 校验分页参数的start和limit均不可以为负数

- docs/db/README.md
- docs/db/built-in_model.md
- docs/db/business.md
- docs/db/cloud_resource.md
- docs/db/container_data_manage.md
- docs/db/field_template.md
- docs/db/host_apply_rule.md
- docs/db/instance.md
- docs/db/mainline_model.md
- docs/db/model.md
- docs/db/operational_analysis.md
- docs/db/other.md
- docs/db/plat.md
- docs/db/service_template.md
- docs/db/set_template.md
- docs/db/task.md
- docs/db/user_custom.md
- docs/db/watch.md
- readme.md
> 新增CMDB数据库表结构文档

- src/web_server/service/excel/core/asst_func.go
- 修复导出实例和主机时勾选导出关联模型实例但未成功导出的问题
> 修复导出实例和主机时勾选导出关联模型实例但未成功导出的问题

- src/scene_server/datacollection/collections/hostsnap/hostsnap.go
- 修复自动发现cpu架构字段失败的问题
bkmonitorbeat 支持的版本 v3.28.1542+;
basereport 支持的版本 10.12.85;
> 修复自动发现cpu架构字段失败的问题

- docs/support-file/helm/templates/servicemonitor.yaml
- 去掉servicemonitor.yaml中的namespaceSelector字段
> 去掉servicemonitor.yaml中的namespaceSelector字段

- src/thirdparty/apigw/cmdb/api.go
- 修复saas将请求proxy到apigw时遗漏URL参数的问题
> 修复saas将请求proxy到apigw时遗漏URL参数的问题

- src/apimachinery/toposerver/inst/api.go
- src/common/metadata/audit.go
- src/scene_server/proc_server/service/service.go
修复操作审计—>其他Tab，操作对象=模型分组、模型，动作有误问题
> 修复操作审计—>其他Tab，操作对象=模型分组、模型，动作有误问题

- src/scene_server/host_server/service/findhost.go
- 修复list_hosts_without_biz接口的排序功能失效问题
> 修复list_hosts_without_biz接口的排序功能失效问题

- src/scene_server/host_server/service/findhost.go
- 3.11修复list_hosts_without_biz接口的排序功能失效问题
> 3.11修复list_hosts_without_biz接口的排序功能失效问题

- src/ui/package.json
> fix: 锁定plotly.js版本解决build错误

- src/thirdparty/apigw/gse/api.go
- fix:修复当streamTo不存在时，apigw接口查询报错的问题
> fix:修复当streamTo不存在时，apigw接口查询报错的问题

- src/web_server/logics/host.go
- src/web_server/logics/inst.go
- 修复excel导入主机、实例时association子表不存在导致导入后点击下一步出现空白页面的问题
> 修复excel导入主机、实例时association子表不存在导致导入后点击下一步出现空白页面的问题

- src/ac/iam/initial_instance_selections.go
- src/ac/iam/initial_resources.go
- src/ac/iam/types.go
- src/common/metadata/inst.go
- src/common/metadata/instance_struct.go
- src/scene_server/auth_server/logics/list_instance.go
- src/scene_server/auth_server/logics/parser.go
- src/scene_server/auth_server/logics/util.go
- src/scene_server/auth_server/service/gen_method.go
- src/scene_server/proc_server/service/processinstance.go
> 添加业务拓扑的权限视图

- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/y3.9.202410101500/create_table_index.go
- src/scene_server/admin_server/upgrader/y3.9.202410101500/pkg.go
> 3.9修复主机与实例表唯一索引缺失问题

- src/common/metadata/dynamic_grouping.go
> 去除动态分组$in操作符的string类型校验

- src/source_controller/coreservice/service/translate.go
> fix: instance name did not change language during internationalization

- src/common/backbone/configcenter/viper.go
- src/common/definitions.go
- src/common/metadata/configadmin.go
- src/scene_server/admin_server/service/configadmin.go
- src/scene_server/admin_server/service/dataid.go
- src/scene_server/admin_server/upgrader/y3.14.202410100930/updateAdminConfigc.go
- src/scene_server/datacollection/app/server.go
- src/scene_server/datacollection/collections/hostsnap/hostsnap.go
- src/scene_server/datacollection/logics/logics.go
- src/scene_server/datacollection/service/service.go
- src/tools/cmdb_ctl/cmd/snapshot.go
- src/tools/cmdb_ctl/readme.md
> 去除主机采集通道名称中的业务ID

- src/storage/dal/mongo/local/txn_manager.go
- src/storage/dal/mongo/sharding/mongo.go
> 事务调整为按db ID区分

- src/ui/src/components/ui/selector/business-mix.vue
- src/ui/src/views/business-topology/children/topology-tree.vue
- src/ui/src/views/host-apply/children/search-select-mix.vue
-  业务选择器分页不显示对应的业务
-  业务拓扑点击刷新机器数量一直加载中
-  自动应用搜索值用name属性
> fix: 业务选择器分页不显示对应的业务

- docs/overview/source_compile.md
- docs/support-file/dockerfile/README.md
- docs/support-file/helm/README.md
- docs/support-file/helm/backend/README.md
- docs/support-file/helm/web/README.md
- docs/support-file/helm/web/templates/webserver/webserver-dpl.yaml
- docs/support-file/helm/web/values.yaml
- readme.md
- scripts/image.sh
> 优化helm部署cmdb文档

- src/ui/src/assets/scss/common.scss
- src/ui/src/components/filters/utils.js
- src/ui/src/components/model-manage/field-group/index.vue
- src/ui/src/views/model-manage/children/model-details/index.vue
- src/ui/src/views/model-manage/index.vue
- 自定义字段点击分组旁的三个点图标没有反应
- 收藏条件增加基本类型值判断
- 模型详情下选择修改分组，这里应该展示原有的所属分组
> fix: 收藏条件增加基本类型值判断
