TencentBlueKing/bk-cmdb

src/auth/parser/topolatest.go, src/scene_server/topo_server/core/operation/inst.go, src/scene_server/topo_server/service/inst.go
=> optimize: mainline model instance update operation with special logic.

.travis.yml, src/common/eventclient/eventclient.go, src/common/util/collection.go, src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go, src/scene_server/topo_server/core/operation/inst_business.go
=> 支持从IAM过滤无权限业务

src/common/eventclient/eventclient.go
=> 修复事件推送前对比数据panic问题

src/scene_server/topo_server/core/operation/association.go, src/scene_server/topo_server/core/operation/classification.go
- /api/v3/find/classificationobject接口查询速度
=> refactor: improve /api/v3/find/classificationobject performance

src/ui/src/magicbox/src/components/paging/paging.vue, src/ui/src/setup/validate.js, src/ui/src/views/business-synchronous/index.vue, src/ui/src/views/business-topology/children/service-instances.vue
=> update:ui: 回归优化

src/ui/src/components/hosts/transfer/index.vue, src/ui/src/components/ui/tree/tree-item.vue, src/ui/src/components/ui/tree/tree-node.js, src/ui/src/components/ui/tree/tree.vue, src/ui/src/directives/cursor.js, src/ui/src/views/host-details/router.config.js
=> UI: 修改新树组件对转移主机资源池权限判断

src/ui/src/api/middleware/business.js, src/ui/src/store/modules/api/object-biz.js
=> ui: 修改获取有权限业务列表的接口

src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
=> 修复升级到3.2.9+时未更新实例关联的问题

src/auth/authcenter/permit/permit.go
- skip set module get authorize
=> feature: skip set module get authorize

readme.md, readme_en.md
=> fix: 修复API文档链接失效问题

src/ui/src/components/audit-history/details.vue, src/ui/src/components/hosts/table/index.vue, src/ui/src/store/modules/api/host-update.js, src/ui/src/views/host-details/children/property.vue
=> fix:ui: 修复历史记录详情查看报错的问题

src/source_controller/coreservice/core/mainline/manager.go
=> 多个自定义层级情况下查询主机空问题 #2636

src/scene_server/topo_server/service/inst_business.go
=> 修复查询业务报参数非法问题

src/ui/src/components/modal/permission.vue, src/ui/src/store/modules/api/global-models.js, src/ui/src/views/status/403.vue, src/ui/src/views/status/require-business.vue
=> UI： 修复跳转权限中心页面地址不正确的问题

src/apiserver/core/compatiblev2/common/converter/converter.go
=> 修复查询主机panic问题

src/auth/extensions/instance.go
- 批量更新主机报注册到权限中心失败 
close #2638
=> 批量更新主机报注册到权限中心失败 #2638

src/source_controller/coreservice/core/instances/instance.go, src/source_controller/coreservice/core/instances/instance_validate.go
- 调整数据校验逻辑：提示非法Key错误变成主动删除非法key #2642
=> 调整数据校验逻辑：提示非法Key错误变成主动删除非法key #2642

src/scene_server/topo_server/core/operation/inst.go
=> 创建业务私有模型的实例失败 #2644

src/auth/authcenter/authcenter.go, src/auth/extensions/business.go, src/common/definitions.go, src/common/util/lib.go, src/scene_server/host_server/service/service.go, src/scene_server/proc_server/proc_service/service/service.go, src/scene_server/topo_server/service/service.go
- 注册IAM资源时使用当前登录的user #2648
- 业务注册到IAM过滤掉isdefault业务
=> 注册IAM资源时使用当前登录的user & 业务注册到IAM过滤掉isdefault业务

src/ui/src/store/modules/api/host-search.js, src/ui/src/views/host-details/children/status.vue
=> UI: 修复渲染主机实时状态失败的问题

src/scene_server/topo_server/core/operation/association_mainline_inst.go
- 业务自定义层级实例metadata信息丢失
close #2651
=> 业务自定义层级实例metadata信息丢失 #2651

readme.md
=> add blueking community links.

readme.md
=> optimize: blueking community bk-ci.

resources/language/default/import_instance.json, resources/language/en/import_instance.json, src/common/eventclient/eventclient.go, src/scene_server/admin_server/upgrader/x18.10.30.01/association.go, src/scene_server/topo_server/core/operation/import_association.go
- 修复实例数据关联关系导入，提示唯一健个数失败 #2667
=> 修复实例数据关联关系导入，提示唯一健个数失败

src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
=> fixes upgrade

src/scene_server/admin_server/upgrader/x18.10.30.01/association.go, src/scene_server/topo_server/core/operation/import_association.go
- 修复导入主机实例报错问题
- 修复模型互相关联时导致的升级缺陷
=> 修复导入主机实例报错问题

src/ui/src/views/model-manage/children/relation-detail/index.vue
=> ui: 禁止修改模型关联关系的关联类型

src/scene_server/admin_server/change_asst_id.js
=> add change_asst_id script

src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
=> change default association kind's DestinationToSourceNote to "被关联"

src/scene_server/host_server/logics/module.go, src/scene_server/host_server/service/host.go
- xxxx
- xxxx
-  多租户下主机分配业务的问题
-  多租户下主机删除主机错误的问题
=> 多租户下主机分配到业务，删除主机的问题

scripts/Makefile, scripts/prepare_cfg.py
- 用python重写makefile中的配置生成逻辑 
close #2688
=> 用python重写makefile中的配置生成逻辑 #2688

scripts/prepare_cfg.py
#2558 # 修复的问题：
- makefile 配置生成 bugfix 
close #2688
=> makefile 配置生成 bugfix 

src/scene_server/topo_server/core/operation/import_association.go
- 系统权限搜索按钮隐藏 && 操作审计业务不可输入搜索&& 操作审计模型和类型选中后不能清除选中
=> V3.2.x  fix: 系统权限搜索按钮隐藏 && 操作审计业务不可输入搜索 && 操作审计模型和类型选中后不能清除选中

src/storage/dal/mongo/remote/find.go, src/storage/dal/mongo/remote/wrapper_transaction.go, src/storage/mongodb/driver/collection.go
=> style:code format issue  #2614

scripts/prepare_cfg.py, src/apiserver/service/service.go, src/apiserver/service/version.go, src/common/metadata/process.go, src/common/selector/selector.go, src/scene_server/admin_server/upgrader/x19.05.16.01/update_process_property.go, src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go, src/scene_server/proc_server/logics/processinstance.go, src/scene_server/proc_server/service/serviceinstance.go, src/web_server/service/index.go
- 支持多个相同key的selector 
close #2688
=> 更进程实例数据结构：绑定IP由枚举类型改成IP串

scripts/prepare_cfg.py
=> 删除makefile调试信息

src/storage/dal/mongo/remote/collection.go, src/storage/mongodb/collection.go, src/storage/mongodb/driver/collection.go, src/storage/tmserver/core/command/aggregate.go
-  mongo driver 暴露Aggregate 方法
- xxxx
- 修复remote mongo 不支持Aggreate 方法
close #2714   
@vlon   
@breezelxp  @hoffermei   src/storage/mongodb/driver/collection.go  重点看下反射相关的代码
=> [v3.5.x] tmserver 支持 Aggregate 方法  issue  #2714

src/ui/src/views/eventpush/pop.vue, src/ui/src/views/model/details/field.vue
=> ui: 优化API配置

src/source_controller/objectcontroller/service/role_action.go
- privilege接口正常返回格式与默认值格式不一致
close #2743
=> privilege接口正常返回格式与默认值格式不一致 #2743

src/api_server/service/v3/uri.go
- 修复modulehost url api_server注册问题
=> 修复modulehost url api_server注册问题

src/apiserver/service/url.go, src/scene_server/event_server/distribution/reconclier.go
- 修复modulehost url api_server注册问题
=> 修复v3.4.x路由注册与eventserver数据清理

src/source_controller/objectcontroller/service/role_action.go
- 业务权限管理保存权限配置没有生效
close #2747
=> 业务权限管理保存权限配置没有生效 #2747

src/apiserver/service/url.go, src/common/eventclient/eventclient.go, src/source_controller/coreservice/core/host/host.go, src/source_controller/coreservice/core/host/transfer/manager.go, src/source_controller/coreservice/core/host/transfer/transfer.go, src/source_controller/coreservice/core/instances/event.go, src/source_controller/coreservice/core/instances/instance.go
- apiserver路由bugfix
close #2749
=> apiserver路由bugfix

src/common/util/flags.go, src/scene_server/admin_server/upgrader/register.go, src/scene_server/topo_server/core/operation/association_mainline_inst.go, src/scene_server/topo_server/core/operation/inst.go
- version flag optimize
- optimize delete mainline object operation.
=> optimize delete mainline object operation.

src/scene_server/topo_server/core/operation/association_mainline_inst.go, src/scene_server/topo_server/core/operation/inst.go
- optimize delete mainline object operation.
=> optimize: optimize delete mainline object operation.

src/source_controller/coreservice/core/instances/instance_crud.go
=> 解决字段查询没生效问题

resources/language/default/oplogdesc.json, resources/language/en/oplogdesc.json, src/scene_server/host_server/logics/log.go, src/scene_server/host_server/service/module.go, src/scene_server/topo_server/core/operation/association.go
-  转移主机操作审计内容新加业务名
- 新加主机优化错误日志返回
-  关联关系记录操作审计错误
close #2711 #2712
=> V3.4.x 主机相关优化

src/apimachinery/rest/request.go, src/scene_server/admin_server/app/server.go, src/scene_server/datacollection/app/server.go, src/scene_server/datacollection/datacollection/datacollection.go, src/scene_server/event_server/app/server.go, src/scene_server/topo_server/app/server.go, src/source_controller/coreservice/service/service.go, src/storage/dal/mongo/remote/mongo.go, src/storage/dal/mongo/remote/pool.go
- remote sdk 新加metric功能
- xxxx
- adminserver和tmserver启动有循环依赖 #2759
close #2763
close #2759
=> tmserver metric 和循环引用的问题

src/storage/mongodb/driver/collection.go
- xxxx
- xxxx
- tmserver aggregate 返回数据重复
close #2761
=> V3.5.x tmserver aggregate 返回数据重复

src/apimachinery/rest/request.go, src/auth/parser/framework.go, src/auth/parser/process.go, src/auth/parser/processinstance.go, src/auth/parser/processtemplate.go, src/auth/parser/servicetemplate.go
- 服务模板/进程权限接入 bugfix
close #2721
=> 服务模板/进程权限接入bugfix #2721

src/common/paraparse/app.go, src/scene_server/topo_server/service/inst_business.go
- 支持根据用户名搜索业务
- xxxx
- xxxx
close #2783
=> 支持根据用户名搜索业务

src/common/metrics/metrics.go, src/scene_server/datacollection/datacollection/datacollection.go, src/scene_server/datacollection/datacollection/porter.go, src/scene_server/host_server/app/server.go
- datacollection修改判断isMaster的方式
- metrics修改label process_instance为host
=> V3.5.x  datacollection修改判断isMaster的方式， metrics修改label

src/source_controller/auditcontroller/logics/audit.go
-  不记录没有修改数据的操作日志
- xxxx
- xxxx
close #2778
=> feature: filter  operate log duplicate info issue #2778

src/scene_server/synchronize_server/app/options/options.go, src/scene_server/synchronize_server/app/server.go, src/scene_server/synchronize_server/logics/background_synchronize.go, src/scene_server/synchronize_server/logics/inst.go
=> fix: sync WiteList 拼写错误改为WhiteList

src/common/paraparse/app.go, src/scene_server/topo_server/service/inst_business.go
- 支持根据用户搜索业务
- xxxx
- xxxx
close #2788
=> V3.4.x  支持根据用户搜索业务

src/scene_server/admin_server/authsynchronizer/producer.go
- 增强权限同步producer代码可读性
close #2809
=> 增强权限同步producer代码可读性

resources/language/en/enum.json
=> optimize multi-language issue

src/scene_server/host_server/service/favourite.go, src/source_controller/hostcontroller/service/favourite.go
- xxxx
- 优化收藏名字重复提示
- xxxx
close #2825
=> 优化收藏名字重复提示

resources/language/en/enum.json
=> 修改2nd Outer IP为1st Outer IP

src/ui/src/api/index.js, src/ui/src/components/modal/permission.vue, src/ui/src/setup/permission.js, src/ui/src/store/modules/api/auth.js
=> feature:ui: 无权限跳转

src/auth/parser/framework.go
=> fix grammer issue.

src/common/metadata/time.go, src/common/types/serverInfo.go, src/scene_server/host_server/logics/log.go, src/scene_server/synchronize_server/logics/background_synchronize.go, src/scene_server/synchronize_server/logics/model.go, src/source_controller/coreservice/core/instances/validator_util.go, src/source_controller/coreservice/core/mainline/manager.go, src/storage/rpc/types.go, src/storage/types/types.go, src/storage/types/types_test.go
- metadata.Time 支持string 反序列化 
- 使用bk_bson 序列化数据
- 数据同步修复没有同步模型分类 
- 记录操作日志的时候。查询业务没有返回业务ID
close #2834 #2833 #2835 #2837
=> V3.5.x mainline search

src/ui/src/assets/scss/common.scss, src/ui/src/components/ui/form/form-multiple.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/views/model-manage/index.vue
=> fix:ui: 修复表单校验错误提示文本超长未处理的问题

src/ui/src/api/middleware/admin-entrance.js, src/ui/src/components/modal/permission.vue, src/ui/src/dictionary/auth.js, src/ui/src/setup/permission.js, src/ui/src/store/modules/api/auth.js
=> UI：文案及url变更

src/ui/src/assets/scss/common.scss, src/ui/src/components/hosts/filter/_filter-field-operator.vue, src/ui/src/components/hosts/filter/_filter.vue, src/ui/src/components/ui/form/form-multiple.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/components/ui/form/search-input.vue, src/ui/src/components/ui/index.js, src/ui/src/views/model-manage/index.vue
=> UI: 主机字符类型字段支持批量模糊查询

src/common/definitions.go, src/common/paraparse/host.go, src/scene_server/host_server/logics/hostsearch.go
- 新增主机查询页面支持多字符字段模型查询功能
close #2841
=> 新增主机查询页面支持多字符字段模型查询功能

src/apiserver/service/auth.go, src/apiserver/service/service.go, src/auth/authcenter/adaptor.go, src/auth/authcenter/authcenter.go, src/auth/authcenter/client.go, src/auth/authcenter/id.go, src/auth/meta/meta.go, src/common/definitions.go, src/common/paraparse/host.go, src/scene_server/admin_server/synchronizer/handler/business.go, src/scene_server/admin_server/synchronizer/handler/core.go, src/scene_server/admin_server/synchronizer/handler/usergroup.go, src/scene_server/admin_server/synchronizer/producer.go, src/scene_server/host_server/logics/hostsearch.go, src/scene_server/host_server/service/module.go
- 新增前后端资源类型转换接口
- 新增主机多字段模型搜索功能，仅限字符字段。
=> demand: resource convert, multiple host search support

src/ui/package.json, src/ui/src/components/ui/form/form-multiple.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/setup/validate.js
=> fix:ui: 修复长短字符长度校验未按byte校验的问题

src/ui/src/views/resource/index.vue
=> fix:ui: 修改infobox 副标题vnode的使用方法

src/ui/package.json, src/ui/src/assets/scss/common.scss, src/ui/src/components/hosts/filter/_filter-field-operator.vue, src/ui/src/components/hosts/filter/_filter.vue, src/ui/src/components/model-manage/_create-model.vue, src/ui/src/components/ui/form/form-multiple.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/components/ui/form/search-input.vue, src/ui/src/components/ui/index.js, src/ui/src/setup/validate.js, src/ui/src/views/model-manage/index.vue
- 主机字符类型查询支持批量输入
- 修复表单校验错误提示文本超长未处理的问题
- 修复长短字符长度校验未按byte校验的问题
=> UI： 主机多模糊查询

src/source_controller/coreservice/core/host/identifier/identifier.go
- xxxx
- xxxx
-  主机身份panic的问题
close #2864
=> fix: host identifier, assignment to entry in nil map issue #2864

src/auth/parser/host.go, src/scene_server/host_server/service/host.go
- add search host instance property api in apiserver.
=> demand: add search host instance property api in apiserver.

src/tools/snapshot_check/Makefile, src/tools/snapshot_check/app/options/options.go, src/tools/snapshot_check/app/options/options_test.go, src/tools/snapshot_check/app/server.go, src/tools/snapshot_check/main.go, src/tools/snapshot_check/readme.md, src/tools/snapshot_check/service/check.go
=> feature: tool check snapshot issue #2844

src/common/metadata/association.go, src/scene_server/topo_server/core/operation/association_mainline_inst.go, src/scene_server/topo_server/core/operation/association_mainline_object.go
- 业务拓扑树web接口返回结果带上服务模板ID信息
close #2853
=> 业务拓扑树web接口返回结果带上服务模板ID信息 #2853

src/common/metadata/core_service.go, src/scene_server/host_server/service/module.go, src/scene_server/proc_server/service/servicecategory.go, src/scene_server/proc_server/service/servicetemplate.go
- optimize auth with service topology
=> optimize auth with service topology

src/ui/src/views/business-topology/children/topology-tree.vue
=> update:ui: 调整拓扑样式

src/apiserver/service/url.go, src/common/metadata/hostserver.go, src/common/metadata/page.go, src/scene_server/host_server/service/cloudarea.go, src/scene_server/host_server/service/phpapi.go, src/scene_server/host_server/service/service.go, src/source_controller/coreservice/core/model/attribute.go
- 新加云区域
- 删除云区域
- 查询云区域
- 查询属性的时候，自动新加模型id作为条件
- xxxx
- 
issue #2879  #2882
=> V3.5.x 云区域操作相关接口

src/auth/parser/servicecategory.go, src/scene_server/proc_server/service/service.go, src/scene_server/proc_server/service/servicecategory.go, src/ui/src/store/modules/api/service-classification.js
- 拆分服务分类接口，将Web接口需求从API接口中分离出来
=> 拆分服务分类接口 #2891

src/ui/src/views/host-details/children/service-instance-table.vue, src/ui/src/views/host-details/children/service-list.vue
=> update:ui: 修改权限表现

src/common/backbone/backbone.go
- 在启动的时候，zk链接不上，多次重试
- xxxx
- xxxx
close #2817
=> V3.4.x 在启动的时候，zk链接不上，多次重试

src/scene_server/host_server/logics/hostsearch.go, src/scene_server/host_server/service/phpapi.go
- 
- xxxx
- 主机查询，根据用户指定的字段返回数据
- 修复新加云区域错误，返回两个json的的问题
=> V3.2.x hostsearch 根据用户指定的字段返回数据

src/scene_server/host_server/logics/hostsearch.go, src/scene_server/host_server/logics/log.go, src/scene_server/host_server/logics/phpapi.go, src/scene_server/host_server/service/phpapi.go, src/source_controller/coreservice/core/host/modulehost/transfer.go
- xxxx
- xxxx
- 查询主机，限定返回字段的条件无效
- 转移主机， 转移成功，提示audit_server没有初始化
- 转移主机，在附加模式下。 主机可以同时属于普通模块和默认模块
=> V3.4.x host bug

src/apiserver/service/service.go, src/auth/authcenter/id.go, src/auth/authcenter/permit/permit.go, src/common/metadata/metadata.go, src/scene_server/proc_server/service/serviceinstance.go, src/source_controller/coreservice/core/process/service_template.go, src/thirdpartyclient/elasticsearch/esclient.go, src/web_server/logics/host.go, src/web_server/service/host.go
- 主机分配到业务全局鉴权没生效问题处理
- 新增限制：在同一个业务内，服务模板名称不能重复
- 进程模板删除后，同步模块时没有提示同步删除进程实例信息
- 全文索引高亮新增ID字段
=> 3.5体验问题优化/修复 #2867

src/storage/tmserver/core/command/find.go, src/tools/snapshot_check/Makefile
- xxxx
- tmserver在返回数据的时候。 自动过滤mongodb 的_id 字段。
- 修改检查快照的工具，编译出来的的名字
-
=> V3.5.x  优化

src/common/querybuilder/README.md, src/common/querybuilder/parser.go, src/common/querybuilder/parser_test.go, src/common/querybuilder/types.go, src/common/querybuilder/types_test.go, src/common/querybuilder/validate.go, src/common/selector/selector_test.go
=> 实现一套统一查询语言 

src/common/registerdiscover/zkregdiscv.go
- xxxx
- 服务注册依赖事件，不再使用定时的方式
- xxxx
issue #2654
=> 服务注册依赖事件，不再使用定时的方式

src/storage/dal/mongo/remote/collection.go, src/storage/mongodb/collection.go, src/storage/mongodb/driver/collection.go, src/storage/tmserver/core/command/aggregate.go, src/storage/tmserver/core/command/count.go, src/storage/tmserver/core/command/delete.go, src/storage/tmserver/core/command/find.go, src/storage/tmserver/core/command/insert.go, src/storage/tmserver/core/command/update.go, src/storage/types/message_type.go
- cc mongodb driver 更新操作支持自定义操作操作符
-  mongodb remote sdk 更新操作支持自定义操作符
- 优化tmserver日志
- xxxx
clse #2902
=> V3.5.x feature sync 支持多样化的更新操作

src/apimachinery/apiserver/api.go, src/apimachinery/apiserver/apiserver.go, src/auth/parser/serviceinstance.go, src/common/metadata/common.go, src/web_server/service/host.go, src/web_server/service/service.go
- 新增webserver接口：根据主机ID查询相关可监听IP列表 
close #2910
=> 新增webserver接口：根据主机ID查询相关可监听IP列表

src/ui/src/components/hosts/transfer/index.vue, src/ui/src/components/modal/permission.vue, src/ui/src/views/model-topology/index.old.vue
=> optimize:ui: 体验优化

src/storage/dal/mongo/remote/collection.go, src/storage/mongodb/collection.go, src/storage/mongodb/driver/collection.go, src/storage/tmserver/core/command/aggregate.go, src/storage/tmserver/core/command/count.go, src/storage/tmserver/core/command/delete.go, src/storage/tmserver/core/command/find.go, src/storage/tmserver/core/command/insert.go, src/storage/tmserver/core/command/update.go, src/storage/types/message_type.go
- cc mongodb driver 更新操作支持自定义操作操作符
-  mongodb remote sdk 更新操作支持自定义操作符
- 优化tmserver日志
- xxxx
=> Feature sync  数据更新操作及日志相关

docs/overview/installation.md, src/scene_server/admin_server/authsynchronizer/producer.go, src/scene_server/admin_server/authsynchronizer/worker.go, src/web_server/middleware/login.go
- remove sync auth in adminserver
=> remove sync auth in adminserver

src/ui/src/components/hosts/transfer/index.vue, src/ui/src/components/modal/permission.vue, src/ui/src/views/model-topology/index.old.vue, src/web_server/middleware/auth/auth_util.go, src/web_server/service/service.go, src/web_server/service/user.go
- 新增：用户查询接口，用于转化用户名 
close #2936
=> 新增：用户查询接口，用于转化用户名

src/scene_server/admin_server/configures/conf.go
-  支持自定义组件的配置文件写入到配置中心
- xxxx
- xxxx
issue #2933
=> feature:write conf fie to config center issue #2933

src/test/event_server/event_server_suite_test.go, src/test/host_server/host_server_suite_test.go, src/test/proc_server/proc_server_suite_test.go, src/test/reporter/html_reporter.go, src/test/reporter/template.go, src/test/test.go, src/test/topo_server/business_test.go, src/test/topo_server/inst_test.go, src/test/topo_server/object_test.go, src/test/topo_server/topo_server_suite_test.go
=> add: html_reporter to generate html test report

src/auth/parser/topology.go
- optimize add new api filter in auth parser.
=> optimize add new api filter in auth parser.

src/scene_server/proc_server/service/serviceinstance.go
=> bugfix: 模块变化对比返回的实例信息全部一样

src/scene_server/topo_server/app/server.go, src/source_controller/coreservice/core/model/attribute.go, src/source_controller/coreservice/core/model/attribute_private.go
- topo支持在mongodb和tmserver之间切换使用
- xxxx
-  新建模型没有预定义字段。（新建自定义层级失败， 创建模型没有默认字段， 新建模型属性，其他模型已经存在新建无效）
issue #2951  #2950
=> V3.5.x topo direct mgo addr create

src/storage/dal/interface.go, src/storage/dal/mongo/local/mock_mongo.go, src/storage/dal/mongo/local/mongo.go, src/storage/dal/mongo/remote/collection.go
- add upsert operation for mongo.
=> demand: add upsert operation for mongo.

src/storage/tmserver/core/command/find.go
- tmserver 支持sort中key前缀的+，-服务作为排序依据
- xxxx
- xxxx
close #2967
=> feature: support -,+ user sort conditon issue #2967

src/scene_server/host_server/service/host.go
- xxxx
- xxxx
-批量修改主机，提示信息错误
issue #2995
=> 批量修改主机，提示信息错误

src/test/proc_server/no_service_template_test.go, src/test/proc_server/service_template_test.go
=> 更新procserver测试用例

src/ui/src/components/hosts/table/index.vue
=> fix:ui: 修复编辑主机按钮未去掉鉴权的问题

src/apimachinery/discovery/discovery.go, src/common/types/serverInfo.go, src/scene_server/admin_server/configures/conf.go
- 非标准组件的节点支持IsMaster
- xxxx
- xxxx
close #2999
=> 非标准组件的节点支持IsMaster

src/scene_server/admin_server/authsynchronizer/meta/types.go, src/scene_server/admin_server/authsynchronizer/producer.go, src/scene_server/admin_server/authsynchronizer/worker.go, src/scene_server/admin_server/service/authcenter.go, src/scene_server/topo_server/service/association.go
- 审计信息不再注册到权限中心
- bk_mainline关联类型不再展示并注册到权限中心
=> optimize: 审计注册与bk_mainline注册优化

scripts/init.py, src/apimachinery/discovery/discovery.go, src/apiserver/service/healthz.go, src/apiserver/service/service.go, src/apiserver/service/version.go, src/common/definitions.go, src/common/types/serverInfo.go, src/scene_server/admin_server/configures/conf.go
- xxxx
- xxxx
- 解决apiserver /healthz 和/version冲突的问题
issue #3003
=>  解决apiserver /healthz 和/version冲突的问题

src/ui/src/views/business-topology/children/service-node-info.vue, src/ui/src/views/business-topology/children/topology-tree.vue
=> feature:ui: 禁止修改蓝鲸拓扑

src/apimachinery/coreservice/model/api.go, src/apimachinery/coreservice/model/model.go, src/scene_server/topo_server/service/object.go, src/scene_server/topo_server/service/service_initfunc.go, src/source_controller/coreservice/service/model.go, src/source_controller/coreservice/service/service_initfunc.go
=> 新增: 模型实例数统计接口 #3028

src/scene_server/topo_server/core/operation/association.go, src/scene_server/topo_server/core/operation/classification.go
- xxxx
- 减少FindClassificationWithObjects的for循环层数
- xxxx
=> V3.2.x 减少FindClassificationWithObjects的for循环层数

src/scene_server/topo_server/service/association.go
- xxxx
- xxxx
- xxxx
close #3031
=> 查询模型关联关系panic 问题

src/auth/parser/topology.go
优化的功能:
- apiserver鉴权处理：跳过模型实例数统计接口鉴权 
close #3028
=> apiserver鉴权处理：跳过模型实例数统计接口鉴权 #3028

src/apimachinery/objcontroller/inst/api.go, src/apimachinery/objcontroller/inst/inst.go, src/common/metadata/object_controller.go, src/scene_server/topo_server/core/operation/inst.go, src/source_controller/objectcontroller/service/inst_action.go, src/source_controller/objectcontroller/service/service.go, src/source_controller/validator/type.go, src/source_controller/validator/util.go, src/source_controller/validator/valid_basic.go, src/source_controller/validator/valid_unique.go
=> create_inst 接口性能优化

src/ui/src/components/hosts/table/index.vue, src/ui/src/views/general-model/index.vue, src/ui/src/views/model-topology/index.old.vue
- 去除批量编辑的鉴权
-模型拓扑关系连线兼容后端返回数据异常的情况
=> UI: 批量编辑鉴权优化，拓扑关系异常处理

src/auth/parser/servicecategory.go, src/scene_server/admin_server/authsynchronizer/handler/servicetemplate.go, src/scene_server/admin_server/authsynchronizer/meta/types.go, src/scene_server/admin_server/authsynchronizer/producer.go, src/scene_server/admin_server/authsynchronizer/worker.go, src/scene_server/proc_server/service/servicecategory.go, src/scene_server/topo_server/service/object.go
=> 服务模板鉴权策略调整 

src/auth/extensions/instance.go, src/scene_server/admin_server/authsynchronizer/handler/instance.go, src/scene_server/admin_server/authsynchronizer/producer.go, src/scene_server/admin_server/authsynchronizer/worker.go
=> instance权限同步区分mainline资源类型

src/auth/extensions/instance.go, src/scene_server/admin_server/authsynchronizer/handler/instance.go
- instance权限同步区分mainline资源类型bugfix
=> instance权限同步区分mainline资源类型bugfix

src/common/definitions.go, src/web_server/common/httpheader.go, src/web_server/middleware/login.go, src/web_server/middleware/user/public.go, src/web_server/service/host.go, src/web_server/service/index.go, src/web_server/service/inst.go, src/web_server/service/netdevice.go, src/web_server/service/netproperty.go, src/web_server/service/object.go
- 当cookie中设置了语言。 用户语言使用cookie中的值
- xxxx
- xxxx
close #3049
=> feature: user language use cookie issue #3049

src/ui/src/components/service/instance-table.vue
=> fix:ui: 修改模板模块服务实例进程表单可填项的判断

src/auth/authcenter/perm_biz.go, src/common/metadata/process.go, src/scene_server/admin_server/authsynchronizer/producer.go
- 下掉权限中心相关的业务模型资源
- bk_func_id调整为字符校验。
=> optimize: 权限中心资源调整与服务模板校验调整

src/scene_server/topo_server/core/operation/inst.go
- create_inst批量接口的操作审计全部是新增操作，包括更新的操作审计
=> 【v3.5.x】fix: create_inst批量接口的操作审计全是新增

src/scene_server/datacollection/app/server.go, src/scene_server/datacollection/datacollection/datacollection.go, src/scene_server/datacollection/service/service.go
- 修复datacollection的healthz接口的空指针异常
=> 修改datacollection的db和redis初始化位置 issue #3051

vendor/github.com/mitchellh/mapstructure/CHANGELOG.md, vendor/github.com/mitchellh/mapstructure/LICENSE, vendor/github.com/mitchellh/mapstructure/README.md, vendor/github.com/mitchellh/mapstructure/decode_hooks.go, vendor/github.com/mitchellh/mapstructure/error.go, vendor/github.com/mitchellh/mapstructure/go.mod, vendor/github.com/mitchellh/mapstructure/mapstructure.go, vendor/vendor.json
- add package mapstructure
close #3052
=> add package mapstructure

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x19.08.30.01/pkg.go, src/scene_server/admin_server/upgrader/x19.08.30.01/update_ip_regex.go
=> 优化IP正则 #2964

src/scene_server/topo_server/core/operation/inst.go
- 刚刚的create_inst接口的commit漏了一种更新的情况
=> fix: previous commit missing one update condition

src/scene_server/topo_server/core/operation/inst.go, src/scene_server/topo_server/core/operation/types.go
- find/instassttopo/object/{object_id}/inst/{inst_id} 接口返回关联关系ID
- xxxx
- xxxx
close #2953
=> [v3.2.x] find/instassttopo/object/{object_id}/inst/{inst_id} 接口返回关联关系ID

src/auth/extensions/instance.go, src/auth/extensions/plat.go, src/auth/extensions/types.go, src/scene_server/admin_server/authsynchronizer/handler/instance.go, src/scene_server/admin_server/authsynchronizer/handler/plat.go, src/scene_server/admin_server/authsynchronizer/meta/types.go, src/scene_server/admin_server/authsynchronizer/producer.go, src/scene_server/admin_server/authsynchronizer/worker.go
=> 权限同步问题处理 #3080

src/common/definitions.go, src/common/metadata/group.go, src/common/metadata/object_controller.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x19.09.03.01/model_attr_group_collapse_flag.go, src/scene_server/admin_server/upgrader/x19.09.03.01/pkg.go, src/scene_server/admin_server/upgrader/x19.09.03.01/update_set_description_property.go
=> feature: model attribute group support collapse flag

src/api_server/logics/v2/common/converter/converter.go
- fix nil map issue in apiserver
=> fix nil map issue in apiserver

src/auth/extensions/types.go, src/scene_server/admin_server/authsynchronizer/handler/instance.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x19.08.26.02/fix_service_instance_max_id.go, src/scene_server/admin_server/upgrader/x19.08.26.02/pkg.go, src/scene_server/topo_server/core/inst/inst.go, src/source_controller/coreservice/core/process/service_instance.go
- 服务实例主键冲突问题 
- 权限中心同步问题修复
close #3089
=> 服务实例主键冲突 & 权限中心同步问题修复

src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
- 
- xxxx
- 修复当网络，中间件下的模型被删除后，升级失败 
issue #3084
=> 修复当网络，中间件下的模型被删除后，升级失败 

src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
- xxxx
- xxxx
- 修复当网络，中间件下的模型被删除后，升级失败
close #3084
=> 修复当网络，中间件下的模型被删除后，升级失败

src/auth/extensions/host.go, src/auth/extensions/types.go, src/common/metadata/metadata.go, src/scene_server/datacollection/app/options/options.go, src/scene_server/datacollection/app/server.go, src/scene_server/datacollection/datacollection/datacollection.go, src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go, src/scene_server/datacollection/datacollection/middleware/discover.go, src/scene_server/datacollection/datacollection/middleware/handler.go, src/scene_server/datacollection/datacollection/netcollect/netdevice.go, src/scene_server/topo_server/core/operation/association_mainline_inst.go
- datacollection模块资源添加时注册到权限中心
close #3092
=> datacollection模块资源添加时注册到权限中心

src/auth/authcenter/perm_biz.go, src/auth/authcenter/perm_initial.go, src/scene_server/host_server/logics/agent.go, src/scene_server/topo_server/service/fulltextsearch.go, src/scene_server/topo_server/service/object_attribute.go, src/source_controller/coreservice/core/model/attribute_curd.go, src/thirdpartyclient/elasticsearch/esclient.go
- 运维新增进程服务相关的权限。
- 全文检索不可查询资源池业务
- 禁用业务下的审计权限
- 主机快照部分数据为空时，做了兼容处理。
- 更新模型属性必填字段失败的问题。
=> optimize: full text search, snapshot, auth related optimization.

src/ui/package.json, src/ui/src/setup/permission.js
=> UI： 修改权限转换协议

src/source_controller/coreservice/core/model/attribute_curd.go
=> refactor: rename

resources/language/default/property_group.json, resources/language/en/property_group.json, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x19.09.03.03/pkg.go, src/scene_server/admin_server/upgrader/x19.09.03.03/set_module_set_template_field_uneditable.go
=> 调整进程属性分组 #3105

src/apiserver/service/auth.go
- change auth convert protocol.
=> optimize: change auth convert protocol.

src/ui/src/components/layout/dynamic-router-view.vue, src/ui/src/mixins/auth.js, src/ui/src/store/modules/api/object-biz.js, src/ui/src/views/status/require-business.vue
=> UI: 修复业务下convert auth 参数错误的问题

src/ui/src/components/modal/permission.vue, src/ui/src/setup/permission.js, src/ui/src/store/modules/api/auth.js, src/ui/src/views/audit/router.config.js, src/ui/src/views/business-model/router.config.js, src/ui/src/views/business-topology/router.config.js, src/ui/src/views/business/router.config.js, src/ui/src/views/cloud-confirm/router.config.js, src/ui/src/views/cloud-discover/router.config.js, src/ui/src/views/custom-fields/router.config.js, src/ui/src/views/custom-query/router.config.js, src/ui/src/views/eventpush/router.config.js, src/ui/src/views/general-model/router.config.js, src/ui/src/views/host-details/router.config.js, src/ui/src/views/hosts/router.config.js, src/ui/src/views/model-association/router.config.js, src/ui/src/views/model-manage/router.config.js, src/ui/src/views/model-topology/router.config.js, src/ui/src/views/resource/router.config.js, src/ui/src/views/service-category/router.config.js, src/ui/src/views/service-instance/router.config.js, src/ui/src/views/service-template/router.config.js
=> fix:ui: 修复部分一级导航权限模式设置不正确的问题

src/ui/package.json, src/ui/src/router/index.js
=> Feature ui

src/apiserver/service/auth.go, src/apiserver/service/filter.go, src/auth/authcenter/perm_biz.go
=> roll back auth resources

resources/language/default/property.json, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x19.09.03.04/pkg.go, src/scene_server/admin_server/upgrader/x19.09.03.04/set_module_set_template_field_uneditable.go
=> 文案优化：集群名字->集群名

src/scene_server/admin_server/app/server.go, src/scene_server/admin_server/authsynchronizer/producer.go, src/scene_server/admin_server/authsynchronizer/synchronizer.go, src/scene_server/admin_server/imports.go
- 权限同步实现成主从方式
- 同步时间间隔调整成 30 minute
=> 权限同步实现成主从方式 #3116

src/ui/src/setup/permission.js, src/ui/src/store/modules/api/auth.js
=> UI: 调整convert auth 参数

src/ui/src/router/index.js, src/ui/src/store/modules/api/auth.js
=> fix:ui: 修复业务模式下convert auth传参错误的问题

src/auth/authcenter/authcenter.go, src/auth/meta/meta.go, src/scene_server/admin_server/authsynchronizer/handler/core.go
=> 权限注册支持分页 #3129

src/scene_server/host_server/logics/agent.go, src/scene_server/host_server/logics/agent_test.go
=> fix: solve bug in ParseHostSnap issue #3120

src/auth/extensions/base.go, src/scene_server/datacollection/datacollection.go, src/scene_server/datacollection/datacollection/manager.go, src/scene_server/datacollection/datacollection/middleware/handler.go, src/scene_server/datacollection/datacollection/middleware/util.go, src/scene_server/datacollection/readme.md
- data-collection模块导入实例时记录审计日志
close #3142
=> data-collection模块导入实例时记录审计日志 

src/auth/parser/topology.go, src/common/metadata/object.go, src/scene_server/topo_server/core/operation/association_mainline_inst.go, src/scene_server/topo_server/service/inst_business.go, src/scene_server/topo_server/service/service_initfunc.go
- 统计每个内置模块主机数 #3132 
- 统计每个拓扑模块主机数 #2662
=> 统计业务拓扑节点/内置模块主机数

src/ui/src/setup/validate.js, src/ui/src/views/business-topology/children/edit-label.vue
=> ui: 调整服务实例标签key正则

src/common/selector/label.go
- 调整服务实例的标签key校验规则
close #3151
=> 调整服务实例的标签key校验规则 

src/scene_server/admin_server/upgrader/x18.10.30.01/association.go, src/scene_server/admin_server/upgrader/x18.10.30.01/pkg.go, src/scene_server/admin_server/upgrader/x18.12.12.05/pkg.go, src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go, src/scene_server/admin_server/upgrader/x18.12.13.01/pkg.go, src/scene_server/admin_server/upgrader/x18.12.13.02/pkg.go, src/scene_server/admin_server/upgrader/x18.12.13.02/upgrader.go
- 卡到x18.10.30.01
- 卡到x18.12.12.05
- 修改x18.12.13.01, x18.12.13.02 版本注册错误
- xxxx
issue #3144
=> V3.5.x adminserver 18.12.12.05 bug

src/web_server/logics/excel_util.go
=> 读取execel，去除空格 #3180

src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
- 修复v3.2中进程升级到v3.5中的服务实例过程中，多创建服务模板的问题。
=> fix: fix upgrade process in v3.2 to v3.5 service instance problem.

src/ui/package.json, src/ui/src/views/business-topology/children/topology-tree.vue
=> update:ui: 拓扑树交互调整

resources/language/default/import_instance.json, resources/language/en/import_instance.json, src/common/mapstr/mapstr.go, src/scene_server/host_server/logics/import.go, src/test/host_server/host_abnormal_test.go
=> fix:增加主机导入时的云区域数值校验 issue #3169

src/ui/src/views/business-topology/children/service-instance-table.vue, src/ui/src/views/host-details/children/property.vue, src/ui/src/views/host-details/children/status.vue
- 对处理数据的代码做兼容
- 主机实时状态界面接口没加载完不显示界面
- 接口主机id修改为string类型
=> update:ui: 3.5回归

src/auth/authcenter/adaptor.go, src/auth/extensions/audit.go, src/auth/extensions/base.go, src/auth/extensions/business.go, src/auth/extensions/host.go, src/auth/extensions/module.go, src/auth/extensions/process.go, src/auth/extensions/servicecategory.go, src/auth/extensions/servicetemplate.go, src/scene_server/host_server/service/host.go
- 调整获取资源池业务的方式，加缓存，提高性能。
- 调整了批量修改主机时鉴权的无权限提示。
=> optimize: 优化批量修改主机时鉴权提示

src/apimachinery/toposerver/inst/api.go, src/apimachinery/toposerver/inst/app.go, src/auth/authcenter/adaptor.go, src/auth/extensions/audit.go, src/auth/extensions/business.go, src/auth/extensions/host.go, src/auth/extensions/model.go, src/auth/extensions/module.go, src/auth/extensions/set.go, src/auth/meta/resource.go, src/common/http/rest/rest.go, src/common/metadata/inst.go, src/common/metadata/toposerver.go, src/common/util/lib.go, src/scene_server/topo_server/service/inst_business.go, src/scene_server/topo_server/service/service_initfunc.go
=> 优化无权限时业务名获取逻辑

src/ui/src/views/business-topology/children/edit-label.vue, src/ui/src/views/business-topology/children/service-instance-empty.vue, src/ui/src/views/business-topology/children/service-instance-table.vue, src/ui/src/views/business-topology/children/service-instances.vue, src/ui/src/views/business-topology/children/service-node-info.vue, src/ui/src/views/host-details/children/service-list.vue, src/ui/src/views/service-template/children/operational.vue
- 服务拓扑标签搜索功能调整
- 服务模板编辑返回对应跳转界面
- 样式优化
=> feature-ui 回归调整

src/ui/package.json, src/ui/src/dictionary/menu.js, src/ui/src/views/business-model/index.vue, src/ui/src/views/business-model/router.config.js, src/ui/src/views/index.js, src/ui/src/views/model-manage/children/index.vue, src/ui/src/views/model-topology/router.config.js
=> UI： 界面入口调整

src/auth/authcenter/adaptor.go, src/auth/authcenter/perm_initial.go, src/auth/authcenter/permit/permit.go
- 业务运维默认新增全局业务的查询权限。
- 查询业务拓扑功能不再鉴权
=> 业务运维与查询业务拓扑权限调整

src/scene_server/topo_server/core/operation/inst_module.go
- 模块创建接口兼容无服务分类参数 
close #3204
=> 模块创建接口兼容无服务分类参数 

docs/overview/installation.md, scripts/init.py, scripts/template.sh.start
=> optimize init.py 

src/ui/src/App.vue, src/ui/src/components/layout/dynamic-navigation.vue, src/ui/src/components/layout/dynamic-router-view.vue, src/ui/src/components/layout/main-inject.vue, src/ui/src/components/ui/selector/business.vue, src/ui/src/dictionary/menu.js, src/ui/src/store/modules/global.js, src/ui/src/views/audit/router.config.js, src/ui/src/views/hosts/router.config.js, src/ui/src/views/model-topology/index.old.vue, src/ui/src/views/resource-manage/index.vue, src/ui/static/svg/cc-host.svg
- 资源目录隐藏禁用模型
- 导航高亮问题
- 切换业务改为刷新页面
=> UI： 导航相关问题修复

src/ui/src/App.vue, src/ui/src/views/audit/router.config.js
=> update:ui: merge and resolve conflict

src/auth/authcenter/adaptor.go, src/auth/authcenter/id.go, src/auth/extensions/base.go, src/auth/extensions/host.go, src/auth/parser/host.go, src/scene_server/topo_server/core/operation/inst_module.go
- 修复业务主机上交资源池鉴权问题
- 新增动态分组执行鉴权功能
=> optimize: fix move host to resource pool issue, add custom query auth 

src/apimachinery/rest/request.go, src/common/backbone/register.go, src/common/metadata/common.go
=> code optimize

src/common/metadata/object.go, src/common/universalsql/mongo/condition_private.go, src/common/universalsql/mongo/condition_test.go, src/scene_server/topo_server/core/operation/association.go, src/scene_server/topo_server/service/inst.go, src/scene_server/topo_server/service/service_initfunc.go
- 前端UI 获取关联关系API
- xxxx
-  universalsql and or 解析数据错误
=> Feature ui association list web

src/test/topo_server/object_test.go
=> fix: topo server test suite

src/ui/src/filters/formatter.js, src/ui/src/views/custom-query/define.vue, src/ui/src/views/custom-query/index.vue
=> update:ui: 优化代码兼容性

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x19.09.03.08/pkg.go, src/scene_server/admin_server/upgrader/x19.09.03.08/update_process_property.go, src/source_controller/coreservice/core/process/service_instance.go, src/source_controller/coreservice/service/model.go
=> 35bugfix&optimize

src/common/mapstr/convert.go, src/common/metadata/metadata.go, src/scene_server/proc_server/service/serviceinstance.go, src/scene_server/topo_server/service/association.go
- fix service instance panic issue
=> fix service instance panic issue

src/scene_server/topo_server/core/operation/inst.go
- xxxx
- xxxx
- 有特殊字符的，实例查询不出来
issue #2338
@makerwei
=>  search inst. 有特殊字符的，实例查询不出来

src/storage/tmserver/core/core.go, src/storage/tmserver/core/session/manager.go, src/storage/tmserver/service/service.go
- 超时事务判断， 避免重复处理， 交给master处理
- xxxx
- 事务异常，reconcilePersistence 给eventCh 事务状态异常
=> feature: optimized exception handling issue #2614

src/apiserver/service/url.go, src/auth/authcenter/perm_biz.go, src/auth/extensions/model.go, src/auth/parser/topolatest.go, src/auth/parser/topology.go, src/auth/parser/util.go, src/scene_server/admin_server/authsynchronizer/handler/model.go, src/scene_server/topo_server/core/operation/association.go, src/scene_server/topo_server/service/inst.go, src/scene_server/topo_server/service/inst_business.go, src/scene_server/topo_server/service/service_initfunc.go
- 全局模型也注册到业务下，用于业务私有字段/实例的鉴权 
close #3234
=> 鉴权优化：业务/集群/模块/主机新增业务私有自定义属性应申请业务下的权限

src/ui/src/views/host-details/children/association-create.vue, src/ui/src/views/host-details/children/association-list-table.vue, src/ui/src/views/host-details/children/association-list.vue
=> update:ui: 删除metadata参数

src/Makefile, src/common/backbone/http.go, src/common/backbone/notice.go
- log zk没删全
- 退出信号循环处理
- 编译企业版包未包含小工具
=> fix: cmdb_ctl related problem and makefile

src/scene_server/topo_server/core/operation/association.go
- xxxx
- xxxx
- 修复关联关系操作，审计日志header 记录name 和id 记录反了的错误
=>  修复关联关系操作，审计日志header错误

src/common/paraparse/app.go
- fix search host multilike search issue.
=> optimize: fix search host multilike search issue.

src/auth/authcenter/adaptor.go, src/auth/authcenter/id.go, src/auth/authcenter/perm_biz.go, src/auth/authcenter/perm_initial.go, src/auth/authcenter/permit/permit.go, src/auth/extensions/servicecategory.go, src/auth/extensions/settemplate.go, src/auth/meta/resource.go, src/auth/parser/framework.go, src/auth/parser/settemplate.go, src/auth/parser/topolatest.go, src/common/metadata/inst.go, src/common/metadata/set_template.go, src/common/metadata/set_template_request.go, src/scene_server/admin_server/authsynchronizer/handler/settemplate.go, src/scene_server/admin_server/authsynchronizer/meta/types.go, src/scene_server/admin_server/authsynchronizer/producer.go, src/scene_server/admin_server/authsynchronizer/worker.go, src/scene_server/topo_server/core/operation/inst_module.go, src/scene_server/topo_server/core/operation/inst_set.go, src/scene_server/topo_server/core/settemplate/settemplate.go, src/scene_server/topo_server/service/inst_set.go, src/scene_server/topo_server/service/set_template.go, src/source_controller/coreservice/core/settemplate/set_template.go, src/test/topo_server/inst_test.go
=> 3.6功能开发及优化调整

src/apimachinery/clientset_coreservice_model_test.go, src/apimachinery/coreservice/model/api.go, src/apimachinery/coreservice/model/model.go, src/auth/extensions/model.go, src/scene_server/topo_server/core/operation/association_mainline_object.go, src/scene_server/topo_server/core/operation/object.go, src/scene_server/topo_server/service/association.go, src/scene_server/topo_server/service/object.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/model/attribute_private.go, src/source_controller/coreservice/core/model/classification.go, src/source_controller/coreservice/core/model/classification_crud.go, src/source_controller/coreservice/core/model/classification_private.go, src/source_controller/coreservice/core/model/model.go, src/source_controller/coreservice/core/model/model_attribute_group.go, src/source_controller/coreservice/core/model/model_attribute_group_crud.go, src/source_controller/coreservice/core/model/model_attribute_group_private.go, src/source_controller/coreservice/core/model/model_crud.go, src/source_controller/coreservice/core/model/model_private.go, src/source_controller/coreservice/core/model/unique_crud.go, src/source_controller/coreservice/service/model.go, src/source_controller/coreservice/service/service_initfunc.go
- 移除 DeleteModelClassificationCascade #3291
- code refactor: rename
=> 移除 DeleteModelClassificationCascade

src/ui/src/views/eventpush/index.vue
=> fix: eventpush 字段错误，导致数据显示不出来

src/ui/src/components/audit-history/audit-history.vue, src/ui/src/components/relation/index.vue, src/ui/src/views/index/children/full-text-search.vue, src/ui/src/views/index/children/search-input.vue, src/ui/src/views/model-manage/index.vue
=> UI: 全文检索展示问题 / 样式调整

src/storage/dal/mongo/remote/mongo_test.go, src/storage/dal/mongo/remote/pool.go, src/storage/dal/mongo/remote/transaction_test.go, src/storage/rpc/server.go
=> fix: 修复tmserver的bug和更新相应的事务测试用例 issue #3286

src/source_controller/objectcontroller/service/common.go
- xxxx
- xxxx
- 修复内置业务、模块、集群国际化缺失的问题
=> 内置业务、模块、集群国际化

resources/language/default/property_group.json, resources/language/en/enum.json, resources/language/en/property_group.json, src/common/paraparse/app.go
=> v3.2.x: 主机多匹配及国际化翻译相关优化

src/apimachinery/coreservice/host/api.go, src/apimachinery/coreservice/label/api.go, src/apimachinery/coreservice/process/api.go, src/common/errors/defaultError.go, src/common/errors/errorIf.go, src/common/errors/error_test.go, src/common/errors/factory.go, src/common/metadata/result.go, src/common/metadata/result_test.go, src/scene_server/proc_server/logics/processinstance.go
- 规范会优化 cc errors 函数
- metdata.Response 提供转换为Error防范
- xxxx
- xxxx
issue #3309
=> response 返回值生成Error

src/auth/authcenter/adaptor.go, src/auth/authcenter/authcenter.go, src/auth/authcenter/client.go, src/auth/authcenter/permit/permit.go, src/auth/parser/topolatest.go
- 根据实例获取实例关联实例的数据
- xxxx
- xxxx
=> feature: instance association object instance info issue #3282

src/auth/authcenter/adaptor.go, src/auth/authcenter/id.go, src/auth/authcenter/perm_sys.go, src/auth/authcenter/permit/permit.go, src/auth/meta/resource.go, src/auth/parser/framework.go, src/auth/parser/operationstatistics.go, src/auth/parser/process.go
- 在权限中心，新加运营统计资源
- 对运营统计操作API新加授权
- xxxx
- xxxx
=> feature:auth add operation statistics resource, verify api issue #3299

src/tools/cmdb_ctl/app/app.go, src/tools/cmdb_ctl/cmd/echo.go, src/tools/cmdb_ctl/cmd/zk.go, src/tools/cmdb_ctl/readme.md
=> cmdb_ctl tool添加zk操作和回显服务器小工具

src/ui/src/views/business/index.vue
=> optimize:ui: 调整业务列表ID列宽

src/ui/src/api/middleware/index.js, src/ui/src/store/modules/api/auth.js
=> feature:ui: 下线权限转换拦截

resources/language/en/property.json, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x19.10.22.01/pkg.go, src/scene_server/admin_server/upgrader/x19.10.22.01/update_cpu_unit.go
=> fix: 修改cpu频率的英文字段名和单位 issue #3321

resources/language/default/import_instance.json, resources/language/en/import_instance.json, src/scene_server/host_server/logics/import.go, src/scene_server/host_server/service/host.go
=> code refactor: rename

src/ui/src/views/host-details/children/history.vue
=> fix: 主机详情变更记录排序传参错误

src/ui/package.json
=> update:ui: 更新magicbox版本

src/ui/src/views/business-topology/children/service-node-info.vue
=> update:ui: 模块节点信息展示调整

src/auth/parser/host.go, src/common/metadata/hostserver.go
=> fix: fix get biz host list api bug.

src/scene_server/task_server/app/server.go, src/scene_server/task_server/service/queue.go, src/test/topo_server/set_template_test.go
- optimize intelgation test for set template
- exit task server when receive signal term
=> optimize intelgation test for set template

src/scene_server/operation_server/app/options/options.go, src/scene_server/operation_server/logics/logics.go
=> fix: 运营统计，定时器没触发bug

src/common/metadata/inst.go, src/common/metadata/object.go, src/scene_server/topo_server/core/operation/inst_business.go
=> 业务内置模块拓扑树节点返回default字段

src/common/paraparse/app.go, src/common/paraparse/host.go, src/common/paraparse/paraparse_test.go, src/scene_server/host_server/service/userapi.go, src/scene_server/proc_server/proc_service/service/process.go, src/scene_server/topo_server/core/operation/inst.go
- xxxx
- xxxx
- UI 页面模糊查询不受特殊字符影响 
close  #3364
=> fix:UI 页面模糊查询不受特殊字符影响 close #3364

src/common/paraparse/app.go, src/common/paraparse/paraparse_test.go, src/scene_server/topo_server/core/operation/inst.go
- xxxx
- xxxx
- UI 页面模糊查询不受特殊字符影响
close #3368
=> fix:UI 页面模糊查询不受特殊字符影响 close #3368

src/scene_server/topo_server/service/unique.go
=> 允许给主机添加自定义唯一约束

src/scene_server/topo_server/core/operation/association.go
=> fix: 判断主线模型时未包括业务

src/ui/src/views/model-association/_detail.vue, src/ui/src/views/model-association/index.vue, src/ui/src/views/model-manage/children/verification.vue
=> UI: 添加sideslider关闭提示

src/auth/parser/topology.go, src/common/metadata/inst.go, src/scene_server/topo_server/service/inst_business.go, src/scene_server/topo_server/service/service_initfunc.go
- 新增：完整业务列表接口 #3387
close #3387
=> 新增：完整业务列表接口

src/apimachinery/coreservice/settemplate/api.go, src/apimachinery/coreservice/settemplate/settemplate.go, src/common/metadata/set_template_request.go, src/scene_server/topo_server/core/operation/inst_set.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/settemplate/sync_status.go, src/source_controller/coreservice/service/service_set_template_initfunc.go, src/source_controller/coreservice/service/set_template.go
=> 删除集群时同步清理集群同步状态

src/ui/src/views/service-template/children/operational.vue, src/ui/src/views/service-template/children/process.vue
=> update:ui: 新建/编辑进程模板权限调整

src/auth/extensions/instance.go, src/source_controller/coreservice/core/mainline/instance.go, src/source_controller/coreservice/core/mainline/manager.go
- xxxx
- xxxx
- 修复非正常的topo节点中可能会出现导致panic的问题。
=> fix get topo panic bug when a topo is not correct.

src/scene_server/admin_server/authsynchronizer/handler/core.go, src/scene_server/admin_server/authsynchronizer/handler/module.go, src/scene_server/admin_server/authsynchronizer/handler/plat.go, src/scene_server/admin_server/authsynchronizer/handler/set.go
=> fix: fix sync model instance auth bug.

src/common/metadata/process.go, src/scene_server/topo_server/core/operation/inst.go, src/scene_server/topo_server/service/association.go, src/scene_server/topo_server/service/inst.go, src/scene_server/topo_server/service/service_business_initfunc.go, src/scene_server/topo_server/service/service_initfunc.go
-  通过通用实例接口只能编辑主机，不能创建和删除主机
- 创建自定义层级模型接口重命名 CreateMainLineObject -> CreateMainLineModel
- 删除自定义层级时没有级联删除集群和模块bugfix
=> 删除自定义层级时没有级联删除集群和模块bugfix

src/auth/parser/topolatest.go, src/auth/parser/topology.go
- fix update object property group iam issue.
=> fix: update object property group iam issue.

src/auth/parser/topology.go
- rollback model attribute group auth logic.
=> optimize: rollback model attribute group auth logic.

src/ui/src/components/relation/_update.vue, src/ui/src/views/business-topology/children/service-instance-empty.vue, src/ui/src/views/custom-query/preview.vue, src/ui/src/views/host-details/children/association-create.vue, src/ui/src/views/model-manage/index.vue, src/ui/src/views/model-topology/index.old.vue, src/ui/src/views/resource/index.vue, src/ui/src/views/service-template/children/operational.vue, src/ui/src/views/service-template/children/process-form.vue
- 样式优化
- 进程模板传参调整
- 优化服务实例为空的显示
- 修复动态分组预览交互异常
- 修复实例新建关联table表头字段不显示
=> update:ui: 3.5回归优化

src/apimachinery/hostserver/apis.go, src/apimachinery/hostserver/hostserver.go, src/auth/parser/host.go, src/common/metadata/hostserver.go, src/scene_server/host_server/service/findhost.go, src/scene_server/host_server/service/service.go, src/source_controller/coreservice/core/host/transfer/transfer.go, src/test/host_server/host_test.go
- hosts/app/{bk_biz_id}/list_hosts_topo接口
- xxxx
- xxxx
=> 添加查询主机和拓扑信息的接口

src/apimachinery/hostserver/apis.go, src/apimachinery/hostserver/hostserver.go, src/auth/parser/host.go, src/common/metadata/hostserver.go, src/scene_server/host_server/logics/log.go, src/scene_server/host_server/service/host.go, src/scene_server/host_server/service/service.go, src/source_controller/coreservice/core/instances/instance_validate.go, src/test/host_server/host_abnormal_test.go, src/test/host_server/host_test.go
=> add: hosts/property/batch api

src/auth/parser/host.go, src/common/metadata/hostserver.go, src/scene_server/host_server/logics/findhost.go
- /api/v3/findmany/modulehost 权限URL错误
=> fix: /api/v3/findmany/modulehost 权限URL错误

src/auth/parser/topolatest.go, src/auth/parser/topology.go, src/scene_server/topo_server/core/operation/import_association.go
=> fix: 导入实例关联，报解析授权信息失败

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/views/general-model/index.vue
=> 批量编辑成功关闭侧滑 / 字段删除界面显示异常

src/ui/src/components/ui/auth/auth.vue, src/ui/src/views/index/children/host-search.vue, src/ui/src/views/index/children/search-input.vue
=> 主页搜索框样式优化 / 鉴权组件调整

src/auth/extensions/instance.go, src/scene_server/topo_server/core/operation/import_association.go
=> fix: 导入实例关联时鉴权错误

src/tools/cmdb_ctl/app/config/config.go, src/tools/cmdb_ctl/cmd/log.go, src/tools/cmdb_ctl/cmd/snapshot.go, src/tools/cmdb_ctl/cmd/topo.go, src/tools/cmdb_ctl/cmd/zk.go, src/tools/cmdb_ctl/readme.md
=> add: topo check tool

src/common/paraparse/host.go, src/scene_server/host_server/logics/hostsearch.go
=> demand: 支持内外网IP的多IP搜索功能。

src/scene_server/topo_server/core/model/object.go, src/scene_server/topo_server/core/operation/inst_business.go, src/scene_server/topo_server/core/operation/object.go, src/scene_server/topo_server/service/inst_business.go
- 移除查询模型属性时多余的查询模型分组操作
- 移除查询业务时多余的查询模型的操作
close #3352
=> 移除查询模型属性时多余的查询模型分组操作

src/tools/cmdb_ctl/cmd/echo.go
- revise cmdb tool echo server
=> optimize: revise cmdb tool echo server

src/source_controller/coreservice/core/instances/instance.go, src/source_controller/coreservice/core/instances/instance_validate.go, src/source_controller/coreservice/core/instances/validator_unique.go, src/source_controller/coreservice/core/instances/validator_util.go
=> coreservice validator 性能优化

src/tools/cmdb_ctl/cmd/auth.go, src/tools/cmdb_ctl/cmd/util.go
- optimize: revise cmdb tool auth command
=> optimize: revise cmdb tool auth command

src/ui/src/components/ui/form/enum.vue, src/ui/src/components/ui/table-empty/table-empty.vue, src/ui/src/views/operation/chart-detail.vue, src/ui/src/views/operation/index.vue
=> update:ui: 表格无权限优化 / 运营统计交互调整

src/scene_server/event_server/identifier/identifier.go, src/tools/cmdb_ctl/cmd/auth.go
- add preData in host identifier event.
=> optimize: add preData in host identifier event.

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x19.10.22.03/pkg.go, src/scene_server/admin_server/upgrader/x19.10.22.03/remove_mainline_property_required.go
- 移除主线模型自定义字段必填属性的upgrader
close #3439
=> 添加移除主线模型自定义字段必填属性的upgrader

src/auth/parser/topology.go
=> fix：更新实例旧接口权限资源解析错误

src/tools/cmdb_ctl/cmd/auth.go, src/tools/cmdb_ctl/readme.md
=> auth 小工具添加输入json文件的功能

src/source_controller/coreservice/core/association/model.go, src/source_controller/coreservice/core/association/model_private.go
=> fix：模型之间可以创建不同关联类型的多个关联 

src/common/querybuilder/types.go
=> fix: querybuilder 嵌套深度

src/common/util/conv.go, src/source_controller/coreservice/core/instances/validator_attr.go
=> fix: validator 判断数字允许字符串

src/web_server/logics/excel.go, src/web_server/logics/excel_util.go, src/web_server/logics/netdevice.go, src/web_server/logics/netproperty.go
=> fix: excel导入导出，把必填字段放最前面

src/apimachinery/toposerver/settemplate/apis.go, src/apimachinery/toposerver/settemplate/settemplate.go, src/auth/parser/topology.go, src/common/metadata/page.go, src/common/metadata/set_template_request.go, src/scene_server/topo_server/service/inst_module.go, src/scene_server/topo_server/service/service_initfunc.go, src/scene_server/topo_server/service/set_template.go, src/test/topo_server/set_template_test.go
- 集群模板与集群实例对比接口：新增返回模块主机数信息 #3024
=> 集群模板与集群实例对比接口：新增返回模块主机数信息 #3024

src/common/metadata/inst.go, src/scene_server/event_server/identifier/hostcache.go, src/scene_server/event_server/identifier/identifier.go, src/scene_server/event_server/service/subscription.go, src/source_controller/coreservice/core/host/identifier/identifier.go
- eventserver中使用通用的HostIdentifier结构
- eventserver主机身份相关的错误处理
- 主机身份api查询模块名未赋值
- eventserver中主机身份无进程信息
- 部分事件无之前主机身份信息
close #3477
=> 主机身份bugfix

src/test/event_server/event_server_suite_test.go, src/test/host_server/host_abnormal_test.go, src/test/host_server/host_server_suite_test.go, src/test/host_server/host_test.go, src/test/host_server/user_test.go, src/test/proc_server/no_service_template_test.go, src/test/proc_server/proc_server_suite_test.go, src/test/proc_server/service_template_test.go, src/test/test.go, src/test/topo_server/business_test.go, src/test/topo_server/inst_test.go, src/test/topo_server/object_test.go, src/test/topo_server/topo_server_suite_test.go, src/test/util/fail.go
- 集成测试失败时提示信息添加http返回
close #3503
=> 集成测试失败时提示信息添加http返回

scripts/init.py
- 初始化脚本里增加对eventserver的授权认证使用控制
=> 初始化脚本里增加对eventserver的授权认证使用控制

src/ui/package.json, src/ui/src/App.vue, src/ui/src/api/index.js, src/ui/src/router/index.js, src/ui/static/login_success.html
=> feature:ui: 小窗登陆

src/apimachinery/apiserver/api.go, src/apimachinery/apiserver/apiserver.go, src/apimachinery/toposerver/inst/api.go, src/apimachinery/toposerver/inst/app.go, src/common/metadata/toposerver.go, src/common/paraparse/app.go, src/common/universalsql/mongo/condition_private.go, src/common/universalsql/mongo/element.go, src/scene_server/topo_server/core/operation/inst_business.go, src/scene_server/topo_server/service/inst_business.go, src/web_server/middleware/user/owner.go
1. 调整查询归档业务接口
2. 查询业务列表接口SearchBusiness优化，删除native参数，变更查询结构。
3. 查询业务列表接口去掉了,如果字段为string，则进行正则搜索的逻辑，该逻辑不对，可能会导致用户查询错业务。
- 修复了universalsql中对regex操作符的支持问题，支持options附加操作。
=> optimize: 查询业务相关接口优化

src/scene_server/event_server/distribution/callback.go, src/scene_server/event_server/distribution/distribution.go, src/scene_server/event_server/distribution/handle_event.go, src/scene_server/event_server/identifier/identifier.go, src/source_controller/coreservice/core/process/base.go, src/source_controller/coreservice/core/process/process_instance_relation.go, src/source_controller/coreservice/service/service.go
=> 添加进程关系变化的主机身份事件推送

src/test/topo_server/object_test.go
=> fix: test util package conflict

src/ui/src/views/custom-query/preview.vue
=> fix:ui: 修复动态分组预览表格limit定位偏移的问题

src/scene_server/admin_server/imports.go
- import upgrade y3.6.201911261109
=> fix: import upgrade y3.6.201911261109

src/scene_server/admin_server/upgrader/y3.6.201911261109/init_chart.go, src/scene_server/admin_server/upgrader/y3.6.201911261109/pkg.go, src/scene_server/admin_server/upgrader/y3.6.201911261109/upgrader.go
-fix: operationserver migrate pkg name
=> fix: operationserver migrate pkg name

src/auth/parser/operationstatistics.go
- update/operation/chart/position auth parser missing
close #3522
=> fix: update/operation/chart/position auth parser missing

src/ui/src/store/modules/api/object-biz.js, src/ui/src/views/business-topology/host/host-selector.vue
=> update:ui: 切换查询业务列表的接口

src/source_controller/coreservice/core/model/attribute_curd.go, src/source_controller/coreservice/core/model/attribute_private.go
- 自定义字段唯一性校验未包含业务信息
close #3528
=> fix: biz attribute unique check missing biz info

src/scene_server/host_server/app/server.go
=> fix: 关闭云同步入口

src/storage/dal/mongo/config.go
=> fix typo: conifgmap => configmap

src/ui/src/store/modules/api/object-biz.js
=> UI: 调整查询业务链接

src/scene_server/host_server/logics/app.go, src/scene_server/host_server/logics/host.go, src/scene_server/topo_server/core/model/attribute.go
- 主机克隆无法克隆在默认模块的主机
- 创建模型属性重复的property id返回成功
close #3539
=> 集成测试bugfix

src/ui/src/components/ui/user/user-queue.js, src/ui/src/components/ui/user/user.vue, src/ui/src/directives/user.js, src/ui/src/views/business-synchronous/index.vue
=>  实例数量优化 / 文件路径调整

src/ui/src/views/business-synchronous/index.vue
=> update:ui: 实例数量优化

src/ui/src/components/model-manage/field-group/field-detail/enum.vue, src/ui/src/components/model-manage/field-group/field-detail/list.vue, src/ui/src/components/ui/form/longchar.vue, src/ui/src/components/ui/form/search-input.vue, src/ui/src/views/general-model/index.vue, src/ui/src/views/host-details/children/info.vue, src/ui/src/views/host-details/children/property.vue, src/ui/src/views/host-operation/index.vue
- 主机详情拓扑路径优化
- 添加字段样式优化
- longchar组件改用多行文本框
- 调整属性自动应用展示顺序
- 模型实例添加id表头
=> update:ui: 体验优化

src/ui/src/store/modules/api/host-apply.js, src/ui/src/views/host-apply/children/search-select-mix.vue, src/ui/src/views/host-apply/children/topology-tree.vue
=> feature:ui: 属性应用拓扑筛选完善

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/store/modules/view/host-details.js
=> fix: 属性字段排序

src/common/metadata/inst.go, src/scene_server/event_server/identifier/hostcache.go, src/scene_server/event_server/identifier/identifier.go, src/scene_server/topo_server/core/operation/identifier.go, src/source_controller/coreservice/core/host/identifier/identifier.go
=> 主机身份接口添加自定义层级

src/auth/authcenter/adaptor.go, src/auth/authcenter/authcenter.go, src/auth/authcenter/id.go, src/auth/extensions/plat.go, src/scene_server/admin_server/authsynchronizer/handler/core.go, src/scene_server/admin_server/authsynchronizer/handler/instance.go, src/scene_server/admin_server/authsynchronizer/handler/plat.go, src/scene_server/admin_server/authsynchronizer/producer.go, src/scene_server/host_server/service/cloudarea.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/mainline/class.go, src/source_controller/coreservice/core/mainline/instance.go, src/source_controller/coreservice/core/mainline/manager.go, src/source_controller/coreservice/core/mainline/model.go, src/source_controller/coreservice/service/mainline.go
- 云区域作为通用实例注册到权限中心数据结构调整 #3505
=> 云区域作为通用实例注册到权限中心数据结构调整

src/common/definitions.go, src/common/metadata/hostserver.go, src/scene_server/event_server/identifier/hostcache.go, src/scene_server/host_server/service/findhost.go, src/scene_server/proc_server/service/servicetemplate.go, src/test/host_server/host_test.go
=> list_biz_hosts接口添加set的过滤条件

scripts/init.py, src/scene_server/proc_server/app/options/options.go, src/scene_server/proc_server/app/server.go, src/scene_server/proc_server/logics/logics.go, src/scene_server/proc_server/service/service.go, src/source_controller/coreservice/service/health.go, src/source_controller/coreservice/service/host.go, src/source_controller/coreservice/service/service.go, src/storage/tmserver/app/options/options.go, src/storage/tmserver/app/server.go, src/web_server/app/server.go
=> remove redundant Redis option and client

src/auth/parser/topology.go
=> fix: 修复模型属性更新、删除接口权限解析无layer信息 issue #3493

src/web_server/service/host.go
=> listen_ip_options调用list_hosts_without_app时添加page.limit查询条件

src/ui/src/views/business-synchronous/index.vue
=> fix:ui: 实例数显示问题

src/ui/package.json, src/ui/src/dictionary/auth.js, src/ui/src/dictionary/menu-symbol.js, src/ui/src/views/host-apply/children/conflict-resolve.vue, src/ui/src/views/host-apply/children/multi-module-config.vue, src/ui/src/views/host-apply/children/property-config-table.vue, src/ui/src/views/host-apply/children/property-confirm-table.vue, src/ui/src/views/host-apply/children/sidebar.vue, src/ui/src/views/host-apply/children/single-module-config.vue, src/ui/src/views/host-apply/children/topology-tree.vue, src/ui/src/views/host-apply/conflict-list.vue, src/ui/src/views/host-apply/failed-list.vue, src/ui/src/views/host-apply/index.vue, src/ui/src/views/host-apply/property-confirm.vue, src/ui/src/views/host-apply/router.config.js
=> 主机属性自动应用加权限和体验问题修复

src/ui/src/components/ui/selector/business.vue
=> update:ui: 样式优化

src/ui/src/store/modules/api/object-main-line-module.js, src/ui/src/views/host-apply/children/conflict-resolve.vue, src/ui/src/views/host-apply/children/multi-module-config.vue, src/ui/src/views/host-apply/children/property-confirm-table.vue, src/ui/src/views/host-apply/children/sidebar.vue, src/ui/src/views/host-apply/children/topology-tree.vue, src/ui/src/views/host-apply/edit.vue, src/ui/src/views/host-apply/property-confirm.vue
=> 空闲机可以设置自动应用和体验问题修复

src/ui/src/views/host-details/children/info.vue
=> fix: 修复资源池bizId获取问题

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.7.201912121117/add_host_outer_ip_unique.go, src/scene_server/admin_server/upgrader/y3.7.201912121117/pkg.go
=> 添加外网ip唯一校验

src/auth/extensions/audit.go, src/scene_server/topo_server/service/auditlog.go
- 有全局操作审计权限时无法按业务筛选
close #3592
=> 添加有业务查询条件的操作审计的全局鉴权

src/scene_server/admin_server/upgrader/y3.7.201912121117/add_host_outer_ip_unique.go
=> 添加外网ip唯一校验的upgrader查找属性时添加owner id查询条件

src/ui/src/views/service-template/children/operational.vue, src/ui/src/views/service-template/children/process-form.vue
=> update:ui: 进程模板调整

src/ui/src/views/service-template/children/operational.vue
=> update:ui: 取消返回查看模式

src/scene_server/datacollection/datacollection/datacollection.go, src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
=> fix： 主机自动发现，添加操作日志

src/ui/src/components/host-apply/property-confirm-table.vue, src/ui/src/components/layout/dynamic-breadcrumbs.vue, src/ui/src/components/layout/dynamic-router-view.vue, src/ui/src/views/host-apply/children/multi-module-config.vue, src/ui/src/views/host-apply/children/single-module-config.vue, src/ui/src/views/host-apply/conflict-list.vue, src/ui/src/views/host-apply/edit.vue, src/ui/src/views/host-apply/failed-list.vue, src/ui/src/views/host-apply/index.vue, src/ui/src/views/host-apply/property-confirm.vue, src/ui/src/views/host-apply/router.config.js
=> optimize:ui: 属性自动应用添加面包屑回退功能

src/auth/authcenter/permit/permit.go
=> 云区域查询暂时跳过鉴权

src/ui/src/store/modules/api/user-custom.js, src/ui/src/store/modules/global.js, src/ui/src/views/business-topology/children/topology-tree.vue
=> update: 蓝鲸业务编辑判断

src/ui/src/views/operation/chart-detail.vue
- 饼图横轴数量设置隐藏，主机数量变化趋势图隐藏横轴数量设置
=> fix: 饼图横轴数量设置隐藏，主机数量变化趋势图隐藏横轴数量设置

src/ui/package.json, src/ui/src/components/ui/dialog/dialog.vue, src/ui/src/magicbox/index.js, src/ui/src/views/business-topology/host/host-selector-topology.vue, src/ui/src/views/business-topology/host/host-selector.vue, src/ui/src/views/host-operation/index.vue
=> feature:ui: 添加主机转移/移除确认界面可二次编辑功能

src/ui/src/views/business-topology/children/topology-tree.vue
=> update:ui: 蓝鲸业务可编辑

src/ui/src/views/host-apply/children/property-config-table.vue, src/ui/src/views/host-apply/children/single-module-config.vue, src/ui/src/views/host-apply/children/topology-tree.vue, src/ui/src/views/host-apply/index.vue
=> 修复主机属性为bool类型默认值错误问题

src/ui/package.json, src/ui/src/views/business-topology/host/host-selector-topology.vue, src/ui/src/views/host-apply/children/search-select-mix.vue, src/ui/src/views/host-apply/index.vue
- 修复属性自动应用搜索结果为空是展示不正确的问题 #3658
=> fix:ui: 修复属性自动应用搜索结果为空是展示不正确的问题

src/auth/extensions/host.go
=> fix: 修复主机操作时的鉴权报错问题 issue #3664

src/source_controller/coreservice/core/operation/chart_operation.go
=> fix: 修复运营统计中创建主机统计图表异常问题 issue #3661

resources/language/default/object.json, src/auth/authcenter/perm_sys.go
=> optimize: 调整权限中心的事件订阅和云区域名称 issue #3671

src/apimachinery/rest/request.go, src/web_server/common/httpheader.go, src/web_server/middleware/login.go, src/web_server/service/user.go
- 在http 调用的时候，不是用gzip 压缩
- xxxx
- xxxx
close #3641
=> feature: delete http header, not support http giz encoding   issue #3641

src/auth/parser/settemplate.go, src/common/metadata/set_template_request.go, src/scene_server/topo_server/service/service_settemplate_initfunc.go, src/scene_server/topo_server/service/set_template.go
=> 批量检查集群同步状态接口 #3623

src/ui/src/components/ui/form/search-input.vue, src/ui/src/views/business-topology/children/service-instances.vue, src/ui/src/views/host-details/children/property.vue, src/ui/src/views/host-operation/index.vue
- 修复默认选中节点不会拉取服务实例
- 主机操作显示属性应用
close ##3669
=> update:ui: 优化体验

src/ui/package.json, src/ui/src/magicbox/magicbox.scss, src/ui/src/store/modules/api/set-template.js, src/ui/src/views/business-topology/host/host-selector-topology.vue, src/ui/src/views/host-apply/children/search-select-mix.vue, src/ui/src/views/host-apply/index.vue, src/ui/src/views/set-template/index.vue
=> UI: 集群模板同步小红点

src/common/metadata/metadata.go, src/source_controller/coreservice/core/model/attribute_private.go
=> 完善业务私有字段与公有字段key互斥检查条件

src/scene_server/proc_server/app/server.go, src/scene_server/proc_server/service/service.go, src/scene_server/proc_server/service/serviceinstance.go
- 清理proc_server中的事务逻辑代码(实现方案不完成，后期事务实现统一添加)
=> refactor: 清理proc_server中的事务逻辑代码

src/apimachinery/coreservice/model/api.go, src/scene_server/topo_server/service/service_initfunc.go
- fix: UpdateObjectAttributeIndex url 修改
=> fix: UpdateObjectAttributeIndex url 修改

src/scene_server/admin_server/command/import.go, src/scene_server/admin_server/command/types.go
- 安装的时候，导入蓝鲸拓扑允许进程名，功能名不同
- 新加进程uuid，实现扩展功能的。
- xxxx
- xxxx
=> 安装的cmdb的时候，放开蓝鲸业务对进程信息的校验 

src/ui/src/views/business-topology/host/host-selector.vue, src/ui/src/views/business-topology/host/module-selector.vue
=> UI: 修复模块选择器/主机选择器生成模式下显示异常的问题

src/ui/src/views/hosts/index.vue
=> fix:ui: 修复业务主机业务选择器UI层级不正确的问题

src/apimachinery/util/client.go
- http client tranpsort 支持使用系统配置的代理
- xxxx
- xxxx
close  #3712
=> feature: add http transport support proxy issue #3712

scripts/init.py, src/scene_server/topo_server/app/options/options.go, src/scene_server/topo_server/app/server.go, src/thirdpartyclient/elasticsearch/esclient.go
- 全文检索连接es支持配置https与auth认证
close #3709
=> 全文检索连接es支持配置https与auth认证

src/scene_server/topo_server/core/operation/attribute.go
=> 查询模型属性接口性能优化

src/common/metadata/attribute.go, src/common/metadata/process_request.go, src/scene_server/proc_server/service/processinstance.go, src/scene_server/proc_server/service/serviceinstance.go, src/scene_server/topo_server/service/object_attribute.go, src/source_controller/coreservice/core/hostapplyrule/plan.go
- 批量服务实例删除支持预览发生主机转移时的属性自动应用信息预览 #3686
=> 批量服务实例删除支持预览发生主机转移时的属性自动应用信息预览 #3686

src/ui/src/views/set-template/template.vue
=> feature:ui: 查看集群模板tab添加同步提示

src/common/util/ownerutil.go, src/common/util/ownerutil_test.go, src/source_controller/coreservice/core/host/searcher/searcher.go, src/source_controller/coreservice/service/host.go
- SetQueryOwner使用确定的类型，减少interface类型判断和转换的开销
=> SetQueryOwner 优化

src/scene_server/host_server/service/findhost.go, src/scene_server/host_server/service/service.go
- 新增资源池主机查询接口 #3724
close #3724
=> 新增资源池主机查询接口

src/source_controller/coreservice/core/model/attribute_curd.go, src/web_server/logics/fields.go
- fix: 模型属性排序，index获取bug修复
- #3737
=> fix: 模型属性排序，index获取bug修复

src/ui/src/components/service/instance-table.vue, src/ui/src/views/business-synchronous/router.config.js, src/ui/src/views/business-topology/children/service-instances.vue, src/ui/src/views/business-topology/host/module-selector.vue, src/ui/src/views/host-details/children/property.vue, src/ui/src/views/host-operation/children/host-attrs-auto-apply.vue, src/ui/src/views/set-sync/router.config.js, src/ui/src/views/set-sync/sync-index.vue
=> update:ui: 内部体验优化

src/common/metadata/object_controller.go, src/scene_server/topo_server/core/operation/classification.go
- xxxx
- 优化  /api/v3/find/classificationobject 接口
- xxxx
=> 优化  /api/v3/find/classificationobject 接口

src/web_server/logics/fields.go
- 第一步：对必填字段按照字段分组排序，并选出非必填
- 第二步：对非必填字段排序
- #3737
=> 导出excel模型字段排序

src/scene_server/topo_server/core/operation/attribute.go
=> fix: 修复查询不存在的模型属性报错的问题 issue #3763

src/web_server/logics/excel_util.go
- xxxx
- xxxx
-  修复导出主机没有业务信息的问题
=> fix: export host not topolgy info issue #3753

resources/language/default/service_category.json, resources/language/en/service_category.json, src/source_controller/coreservice/service/service_category.go, src/source_controller/coreservice/service/translate.go
=> 内置服务分类添加翻译

src/source_controller/coreservice/core/instances/instance_validate.go
- fix: 更新主机报"根据主机ID获取业务ID失败"
#3765
=> fix: 更新主机报"根据主机ID获取业务ID失败"

src/scene_server/topo_server/core/operation/import_association.go
=> fix: excel导入实例与主机关联失败，报错主机不存在

src/ui/src/components/hosts/table/index.vue, src/ui/src/store/modules/view/business-host.js, src/ui/src/views/business-topology/children/service-node-info.vue, src/ui/src/views/business-topology/children/topology-tree.vue
- 蓝鲸业务下编辑/删除
- 修复全文检索跳转资源池切换scope状态没刷新列表
=> 蓝鲸业务下编辑/删除

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x20.01.13.01/pkg.go, src/scene_server/admin_server/upgrader/x20.01.13.01/update_none_property_group.go
- 查询模型属性bk_property_group为none时报错
=> 模型属性bk_property_group为none的改为default

src/common/registerdiscover/zkregdiscv.go
- 1s未收到服务变更事件时从zk读server数据并做对比
- zk服务发现冗余代码清理
=> 1s未收到服务变更事件时从zk读server数据并做对比

src/ui/src/views/operation/chart-detail.vue, src/ui/src/views/operation/index.vue
=> fix:ui: 修复运营统计图表创建/编辑时发起错误请求的问题

src/storage/dal/mongo/local/mongo.go
- 优化mgo client refresh session逻辑。
=> code optimize with mongo about tcp connections

src/ui/src/store/modules/view/host-details.js, src/ui/src/views/host-details/children/service-instance-table.vue, src/ui/src/views/host-details/children/service-list.vue, src/ui/src/views/host-details/index.vue, src/ui/src/views/index/children/full-text-search.vue
=> fix:ui: 修复首页搜索跳转主机详情404的问题

src/auth/parser/topology.go, src/scene_server/topo_server/service/inst_business.go, src/scene_server/topo_server/service/service_initfunc.go, src/web_server/middleware/user/owner.go, src/web_server/middleware/user/public.go, src/web_server/service/user.go
-  切换开发商，没有权限的操作的时候，返回对应信息
-  运行用户在没有权限的情况下进入到cc页面
- xxxx
close  #3778
=> 3.5.x init owner

scripts/init_db.sh, src/apimachinery/discovery/discovery.go, src/apimachinery/discovery/server.go, src/common/types/serverInfo.go
- 服务在zk注册时增加uuid字段，用来区分master, issue #3780
=> fix: 服务在zk注册时增加uuid字段，用来区分master, issue #3780

src/apimachinery/rest/request.go, src/common/definitions.go, src/common/metadata/attribute.go, src/common/metadata/procserver.go, src/common/metadata/webserver.go, src/source_controller/coreservice/core/instances/validator_util.go, src/source_controller/coreservice/core/model/attribute_curd.go, src/source_controller/coreservice/core/model/unique_crud.go, src/thirdpartyclient/esbserver/user/api.go, src/thirdpartyclient/esbserver/user/esbserv.go, src/web_server/logics/fields.go, src/web_server/middleware/user/plugins/method/blueking/userinfo.go, src/web_server/middleware/user/plugins/method/skip_login/userinfo.go, src/web_server/middleware/user/public.go, src/web_server/middleware/user/user.go, src/web_server/service/service.go, src/web_server/service/user.go
- 模型属性增加组织部门字段类型，提供查询部门列表和部门人员信息的接口
issue # #3644
=> 模型属性增加组织部门字段类型，提供查询部门列表和部门人员信息的接口

src/common/metadata/log.go
=> 修复操作审计数据库字段错误问题

src/common/metadata/audit.go
- 新增优化后的操作审计数据结构设计
close #3787
=> add new audit log struct definination.

src/apimachinery/rest/request.go, src/common/definitions.go, src/common/http/rest/contexts.go, src/scene_server/topo_server/core/operation/attribute.go, src/scene_server/topo_server/core/operation/inst_business.go, src/scene_server/topo_server/service/inst_business.go, src/scene_server/topo_server/service/service.go, src/scene_server/topo_server/service/service_initfunc.go, src/source_controller/coreservice/core/instances/instance.go, src/source_controller/coreservice/core/instances/instance_crud.go, src/source_controller/coreservice/service/host.go, src/source_controller/coreservice/service/instances.go, src/source_controller/coreservice/service/model.go, src/source_controller/coreservice/service/operation.go, src/source_controller/coreservice/service/service.go, src/source_controller/coreservice/service/service_category.go
=> optimize find business api performance.

src/apimachinery/util/client.go, src/common/metrics/metrics.go, src/scene_server/topo_server/service/service.go, src/source_controller/coreservice/service/service.go
- xxxx
- optimize http rest api performance.
- xxxx
=> optimize http rest api performance.

src/scene_server/event_server/distribution/start.go, src/storage/dal/mongo/local/mongo.go
- fix event server migrate instance id bug
=> fix event server migrate instance id bug

readme.md, readme_en.md, src/source_controller/coreservice/core/instances/instance.go
=> 修复查询模型实例接口中超级开发商不生效问题

src/scene_server/host_server/logics/app.go, src/source_controller/coreservice/core/mainline/class.go
- xxxx
- xxxx
- 修复查询条件，在多开发商场景下可能出现的问题。
=> optimize owner id query condition

src/scene_server/topo_server/service/service.go, src/source_controller/coreservice/service/service.go
- fix response code 406 issue.
=> fix response code 406 issue.

src/source_controller/coreservice/core/mainline/manager.go, src/web_server/logics/host.go
- xxxx
- xxxx
- 调整coreservice中ownerid的使用方式
=> 调整coreservice中ownerid的使用方式

src/ui/src/views/host-details/children/property.vue, src/ui/src/views/model-association/_detail.vue, src/ui/src/views/model-association/index.vue
- 优化关联类型筛选UI
- 修复主机详情标题提示语显示异常的问题
- 修复关联类型表单文本溢出显示异常的问题
=> UI: 3.7 bug修复

src/source_controller/coreservice/service/association.go, src/source_controller/coreservice/service/model.go, src/source_controller/coreservice/service/translate.go
=> 仅内置模型等进行国际化

src/ui/src/views/host-operation/index.vue
=> UI: 主机转移的变更确认badge优化

src/ui/src/views/business-topology/router.config.js
=> update:ui: 删除服务拓扑中无用的鉴权

src/ui/src/views/business-topology/router.config.js
=> update:ui: 删除业务拓扑中无用的鉴权

src/source_controller/coreservice/core/model/attribute_curd.go
=> 修复添加业务字段时与全局字段名相同时可添加成功的问题

src/common/definitions.go
- change FieldTypeLongCharRegexp, add '=' char support.
=> change FieldTypeLongCharRegexp, add '=' char support.

src/source_controller/coreservice/core/mainline/instance.go, src/source_controller/coreservice/core/mainline/mainline.go, src/source_controller/coreservice/core/mainline/manager.go, src/source_controller/coreservice/core/model/mock_test.go, src/source_controller/coreservice/multilingual/buildin_instance.go, src/source_controller/coreservice/service/host.go, src/source_controller/coreservice/service/instances.go, src/source_controller/coreservice/service/service.go, src/source_controller/coreservice/service/translate.go
- xxxx
- xxxx
- fix host apply multilingual issue and optimize the code.
=> fix host apply multilingual issue and optimize the code.

src/ui/src/views/host-details/children/info.vue
=> ui: 主机详情云区域信息展示优化

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go, src/scene_server/admin_server/upgrader/x20.02.17.01/fix_proctemp_procname.go, src/scene_server/admin_server/upgrader/x20.02.17.01/pkg.go
- 
- xxxx
- 修复进程模板进程名和进程功能名为空的问题
close #3821
=> fix: process template name and function name empty bug  issue #3821

scripts/init.py, src/scene_server/admin_server/app/options/options.go, src/scene_server/admin_server/app/server.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/service/migrate.go, src/scene_server/admin_server/service/service.go, src/scene_server/admin_server/upgrader/register.go, src/scene_server/admin_server/upgrader/y3.8.202002101113/migrate_event_id.go, src/scene_server/admin_server/upgrader/y3.8.202002101113/pkg.go, src/scene_server/event_server/distribution/start.go
- event server 事件id使用upgrader迁移
=> event server 事件id使用upgrader迁移

src/apimachinery/clientset.go, src/apimachinery/cloudserver/api.go, src/apimachinery/cloudserver/cloudserver.go, src/apimachinery/coreservice/cloud/api.go, src/apimachinery/coreservice/cloud/cloud.go, src/apimachinery/coreservice/coreservice.go, src/apimachinery/discovery/discovery.go, src/apimachinery/discovery/discovery_mock.go, src/apimachinery/healthz/healthz.go, src/apiserver/service/filter.go, src/apiserver/service/url.go, src/common/definitions.go, src/common/metadata/cloud.go, src/common/metadata/core_service.go, src/common/types/serverInfo.go, src/source_controller/coreservice/core/cloud/account.go, src/source_controller/coreservice/core/cloud/cloud.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/service/cloudaccount.go, src/source_controller/coreservice/service/service.go, src/source_controller/coreservice/service/service_initfunc.go
增加cloud server的coreservice层框架代码和apiclient接口
=> 增加cloud server的coreservice层框架代码和apiclient接口

src/source_controller/coreservice/service/service.go
=> 修复国际化空指针异常导致测试用例失败的问题

resources/language/default/property.json, resources/language/en/property.json
=> V3.6.x:  添加主机当前状态字段英文翻译

src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
=> 修复datacollection更新主机信息失败的问题

src/scene_server/task_server/Makefile
=> fix task_server TARGET_PORT

src/ac/auth.go, src/ac/iam/client.go, src/ac/iam/iam.go, src/ac/iam/initial_actions.go, src/ac/iam/initial_resources.go, src/ac/iam/types.go, src/apimachinery/rest/request.go
=> add access control pkg.

src/apimachinery/rest/request.go, src/common/json/json.go, src/common/mapstr/convert.go, src/common/mapstr/mapstr.go, src/common/mapstr/to_value.go, src/common/util/conv.go, src/scene_server/admin_server/authsynchronizer/handler/host.go, src/scene_server/topo_server/service/inst_business.go, src/test/host_server/host_abnormal_test.go, src/test/host_server/host_test.go, src/test/host_server/user_test.go, src/test/proc_server/no_service_template_test.go, src/test/proc_server/proc_server_suite_test.go, src/test/proc_server/service_template_test.go, src/test/topo_server/business_test.go, src/test/topo_server/inst_test.go, src/test/topo_server/object_test.go
=> 通用json反序列化去除科学记数法

src/scene_server/datacollection/datacollection/discover.go, src/scene_server/datacollection/datacollection/hostsnap.go
=> 修复3.2 datacollection空指针异常和连接未关闭的问题

src/apimachinery/coreservice/process/api.go, src/apimachinery/coreservice/process/process.go, src/apimachinery/procserver/process/api.go, src/apimachinery/procserver/process/instance.go, src/auth/parser/processinstance.go, src/common/metadata/core_service.go, src/common/metadata/process.go, src/scene_server/proc_server/service/processinstance.go, src/scene_server/proc_server/service/service.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/process/process_instance_relation.go, src/source_controller/coreservice/service/process_instance_relation.go, src/source_controller/coreservice/service/service_process_initfunc.go, src/test/proc_server/no_service_template_test.go
=> 添加查询业务下的主机和进程信息接口及测试用例

src/common/http/rest/contexts.go
=> fix: RespAutoError data 从""修改为nil

src/scene_server/datacollection/datacollection/porter.go
=> 修复datacollection连接未关闭的问题

src/apimachinery/apiserver/api.go, src/apimachinery/apiserver/apiserver.go, src/auth/parser/host.go, src/scene_server/host_server/service/host.go, src/scene_server/host_server/service/service.go, src/web_server/logics/host.go, src/web_server/service/host.go, src/web_server/service/service.go
=> v3.8.x：新加excel导入更新主机功能

src/ui/src/views/host-details/router.config.js
=> update:ui: 配置返回按钮

src/ui/src/views/host-operation/index.vue
=> update:ui: tab样式调整

src/apimachinery/hostserver/apis.go, src/apimachinery/hostserver/hostserver.go, src/auth/parser/host.go, src/common/metadata/hostserver.go, src/scene_server/host_server/logics/import.go, src/scene_server/host_server/logics/module.go, src/scene_server/host_server/service/host.go, src/scene_server/host_server/service/service.go, src/test/host_server/host_test.go
=> 新增添加主机到资源池接口

src/ui/src/views/host-details/children/info.vue
=> UI: 主机详情云区域样式优化

src/ui/src/views/host-details/children/association-list-table.vue
=> UI: 主机关联列表页面不显示无关联实例表格

src/apimachinery/apiserver/api.go
=> fix：excel导入更新主机，http method

src/scene_server/host_server/service/host.go, src/scene_server/topo_server/service/inst.go, src/scene_server/topo_server/service/inst_module.go, src/scene_server/topo_server/service/inst_set.go, src/scene_server/topo_server/service/unique.go
- 删除实例失败时权限中心注册的实例被解注册
close #3864
=> 修复删除实例失败时权限中心注册的实例被解注册的问题

src/common/util/valid.go, src/source_controller/coreservice/core/instances/validator_util.go, src/source_controller/coreservice/core/model/attribute_curd.go
=> 模型属性枚举类型添加id和name是否为字符串的校验

src/scene_server/admin_server/upgrader/y3.7.202002231026/add_bk_port_enable_property.go, src/scene_server/topo_server/service/inst.go, src/scene_server/topo_server/service/inst_business.go
=> 修复3.8合入低版本后测试用例不过的问题

src/scene_server/admin_server/upgrader/y3.7.202002231026/add_bk_port_enable_property.go
- bson decode time 错误的问题
- xxxx
- xxxx
=> fix: metadata bson decode error

src/scene_server/admin_server/upgrader/y3.7.202002231026/add_bk_port_enable_property.go, src/scene_server/topo_server/service/inst.go, src/scene_server/topo_server/service/inst_business.go, src/test/host_server/host_test.go
=>  修复3.9合入低版本后测试用例不过的问题

src/ui/src/components/model-manage/field-group/field-detail/enum.vue, src/ui/src/views/model-manage/children/field-detail/enum.vue
=> fix:ui: 修复枚举类型字段枚举列表缺失type的问题

src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
=> 修复自动发现主机日志bug

src/storage/dal/mongo/local/mongo.go
- xxxx
-  优化dal mgo类库使用session的方法
- xxxx
close #3884
=> 优化dal mgo类库使用session的方法

src/common/definitions.go, src/common/util/valid.go
=> 枚举新增长度和个数限制

src/apiserver/service/url.go, src/auth/authcenter/adaptor.go, src/auth/authcenter/id.go, src/auth/authcenter/perm_sys.go, src/auth/meta/resource.go, src/auth/parser/chain.go, src/auth/parser/cloud.go
=> feature: 增加云账户的API鉴权 issue #3846

src/scene_server/topo_server/core/operation/association_mainline_inst.go
=> fix search biz topo bug

src/auth/parser/topology.go, src/common/util/valid.go
=> 列表新增长度和个数限制

vendor/stathat.com/c/consistent/LICENSE, vendor/stathat.com/c/consistent/README.md, vendor/stathat.com/c/consistent/consistent.go, vendor/stathat.com/c/consistent/consistent_test.go, vendor/stathat.com/c/consistent/example_test.go
=> vendor目录里增加一致性哈希库 issue #3896

src/scene_server/admin_server/upgrader/y3.7.202002231026/add_bk_port_enable_property.go, src/scene_server/admin_server/upgrader/y3.9.202002131522/add_cloud_sync_tables.go
=> 修复migrate失败的bug

src/storage/reflector/reflector.go, src/storage/reflector/types.go, src/storage/stream/event/watch.go, src/storage/stream/types/types.go
- add reflector package and add function in stream.
close #3888
=> add reflector package and add function in stream.

src/ui/src/components/service/instance-table.vue, src/ui/src/views/business-topology/children/service-instance-table.vue, src/ui/src/views/host-details/children/service-instance-table.vue, src/ui/src/views/service-instance/children/clone-to-source.vue, src/ui/src/views/service-template/children/process.vue, src/ui/src/views/set-template/children/service-template-info.vue
=> ui: 进程表格信息添加协议字段

src/ui/src/components/audit-history/details.vue
=> ui: 审计详情变更信息溢出显示优化

src/apiserver/service/http.go, src/common/definitions.go
=> apiserver请求日志增加app code

src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
=> v3.5.x：修复主机自动发现，日志bug

src/common/querybuilder/validate.go
- add json.Number validate in host query builder.
=> fix: add json.Number validate in host query builder.

src/source_controller/coreservice/core/operation/inner_chart.go
=> fix：暂时关闭运营统计实例变更统计

src/source_controller/coreservice/core/auditlog/audit.go, src/source_controller/coreservice/core/auditlog/audit_test.go
-  审计日志对比支持忽略字段 
- xxxx
- xxxx
close #3869
=> feature: audit compare support ignore fields issue #3869

src/auth/extensions/types.go, src/scene_server/admin_server/authsynchronizer/handler/core.go
=> 修复权限同步时json序列化错误和判断带父层级资源位置错误的问题

src/source_controller/coreservice/core/auditlog/audit.go
- audit compare support ignore fields 
- xxxx
- xxxx
close #3869
=> feature: audit compare support ignore fields 

src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
=> datacollection map并发读写问题修复

resources/language/default/import_instance.json, resources/language/en/import_instance.json, src/scene_server/host_server/service/host.go, src/web_server/logics/excel.go
=> fix: excel导入更新主机添加错误提示

src/storage/stream/event/list_watch.go, src/storage/stream/event/watch.go
=> stream watch code optimize

src/storage/stream/event/watch.go
- stream watch code optimize issue #3887
=> stream watch code optimize issue #3887

src/scene_server/topo_server/service/set_template.go, src/source_controller/coreservice/core/settemplate/set_template.go
=> UI查询集群模板接口返回全量数据

src/source_controller/coreservice/core/process/service_instance.go
- 修复list_service_instance_detail无进程信息的问题
close #3931
=> 修复list_service_instance_detail无进程信息的问题

src/scene_server/host_server/logics/findhost.go
=> 修复find_host_by_module接口中的page参数无效的问题

src/source_controller/coreservice/core/host/searcher/searcher.go
- list_biz_hosts接口默认按host id排序
close  #3932
=> list_biz_hosts接口默认按host id排序

src/common/metadata/process.go, src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go, src/source_controller/coreservice/core/process/service_instance.go
=> 删除服务实例中的内网IP字段

src/common/metadata/attribute.go
=> 修改补全枚举类型的解析

src/ui/src/views/business-topology/children/create-module.vue, src/ui/src/views/service-template/children/operational.vue
=> optimize:ui: 服务分类默认给用户选中default

src/ui/src/views/general-model/index.vue, src/web_server/middleware/auth/auth_util.go
- xxxx
- xxxx
- 有权限普通用户修改实例显示无权限。
- 用户成功修改后，没有跳转页面。
=> V3.2.x 修改有权限普通用户无法批量修改实例的问题

src/auth/extensions/instance.go, src/common/definitions.go, src/common/metadata/core_service.go
- 修复权限同步时主线实例被注册为模型实例的问题
close #3949
=> 修复权限同步时主线实例被注册为模型实例的问题

src/ui/src/components/ui/details/details.vue, src/ui/src/views/business-topology/children/service-node-info.vue, src/ui/src/views/business-topology/router.config.js, src/ui/src/views/host-operation/index.vue
- 修复拓扑节点信息过多导致按钮组看不见的问题 #3960 
- 修复转移主机无权限时页面视图显示不正确的问题 #3961
=> UI：3.7.x BUG修复

src/scene_server/topo_server/core/operation/import_association.go
=> fix: 修复excel导入实例与多主机关联失败bug

src/common/zkclient/zkclient.go
=> 修复zk二次关闭的问题

src/common/auditlog/util.go, src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go, src/scene_server/datacollection/datacollection/middleware/handler.go, src/scene_server/host_server/logics/import.go, src/scene_server/host_server/logics/log.go, src/scene_server/host_server/service/transfer.go, src/scene_server/topo_server/core/operation/association.go, src/scene_server/topo_server/core/operation/supplementary_audit.go
- 操作审计添加业务内主机在模块set间的转移
close  #3977
=> 操作审计添加业务内主机在模块set间的转移

src/storage/dal/mongo/local/bson_decode_test.go, src/storage/dal/mongo/local/bson_register_struct_decode.go
- xxxx
- xxxx
-修复bson unmarshal 结构的匿名字段解析错误的问题
=> fix: bson unmarshal struct anonymous field error issue #3987

src/auth/extensions/audit.go, src/common/metadata/audit.go, src/scene_server/datacollection/datacollection/middleware/handler.go, src/scene_server/topo_server/core/operation/association_mainline_inst.go, src/scene_server/topo_server/core/operation/association_mainline_object.go, src/scene_server/topo_server/core/operation/supplementary_audit.go, src/scene_server/topo_server/service/auditlog.go
- 主线模型实例的操作审计与模型实例区别开
- 添加创建主线模型实例的操作审计
close #3984
=> 主线模型实例的操作审计与模型实例区别开

src/source_controller/coreservice/core/process/service_template.go, src/test/proc_server/service_template_test.go
=> 服务模板名称支持修改

scripts/init.py, src/apiserver/app/server.go, src/common/backbone/backbone.go, src/common/backbone/configcenter/cc.go, src/common/backbone/configcenter/parse.go, src/common/types/serverInfo.go, src/scene_server/admin_server/app/server.go, src/scene_server/admin_server/configures/conf.go, src/scene_server/datacollection/app/options/options.go, src/scene_server/datacollection/app/server.go, src/scene_server/event_server/app/server.go, src/scene_server/host_server/app/server.go, src/scene_server/operation_server/app/options/options.go, src/scene_server/operation_server/app/server.go, src/scene_server/operation_server/service/service.go, src/scene_server/proc_server/app/server.go, src/scene_server/proc_server/service/service.go, src/scene_server/synchronize_server/app/server.go, src/scene_server/task_server/app/server.go, src/scene_server/topo_server/app/server.go, src/source_controller/coreservice/app/server.go, src/storage/dal/mongo/config.go, src/storage/dal/redis/redis.go, src/web_server/app/server.go
=> 调整配置文件后进程获取配置的方式 #3990

src/apiserver/app/server.go, src/common/backbone/backbone.go, src/common/backbone/configcenter/cc.go, src/common/backbone/configcenter/parse.go, src/scene_server/admin_server/app/server.go, src/scene_server/datacollection/app/server.go, src/scene_server/event_server/app/server.go, src/scene_server/host_server/app/server.go, src/scene_server/operation_server/service/service.go, src/scene_server/proc_server/service/service.go, src/scene_server/synchronize_server/app/server.go, src/scene_server/task_server/app/server.go, src/scene_server/topo_server/app/server.go, src/source_controller/coreservice/app/server.go, src/web_server/app/server.go, src/web_server/middleware/user/plugins/method/blueking/userinfo.go
- 调整配置发现的相关逻辑，新增extra config配置管理能力，用于管理非标准进程配置相关的配置信息。
=> optimize: refactor config discovery.

src/apiserver/service/url.go, src/source_controller/coreservice/service/service_initfunc.go
- apiserver路由错误
- coreservice url错误
=> 运营统计bugfix

src/web_server/logics/object.go
- xxxx
- xxxx
- 列表字段导入时option未解析
=> 修复列表字段导入失败的问题

src/scene_server/proc_server/logics/processinstance.go, src/test/proc_server/service_template_test.go
=> 修复服务模板修改进程模板的进程启用端口不触发同步的问题

src/common/metadata/attribute.go
- 无法修改主机的当前状态字段
- 无法新建带列表类型字段的模型实例
=> 修复列表属性校验出错的问题

src/scene_server/topo_server/service/inst_module.go
=> 修复page的空指针异常

src/scene_server/proc_server/service/serviceinstance.go
=> 修复服务模板修改的服务分类在同步时未同步到模块的问题

src/ui/src/views/model-topology/index.new.vue
=> fix:ui: 修复模型关系分组名称溢出的问题

src/scene_server/topo_server/service/inst_module.go
=> 根据服务模板查询模块接口在无分页参数时返回全部数据

src/auth/parser/topolatest.go, src/common/metadata/attribute.go, src/scene_server/topo_server/core/operation/attribute.go, src/scene_server/topo_server/service/object_attribute.go, src/scene_server/topo_server/service/service_business_initfunc.go
- 查询模型属性接口输入输出适配bk_biz_id，和metadata互相转换
=> 查询模型属性接口输入输出支持bk_biz_id

src/ui/src/views/business-synchronous/children/details.vue, src/ui/src/views/business-synchronous/index.vue, src/ui/src/views/business-synchronous/router.config.js, src/ui/src/views/business-topology/children/service-instances.vue, src/ui/src/views/service-template/children/template-instance.vue
- 服务模板实例批量同步功能
- 修复服务模板实例表格溢出无滚动的问题
=> UI: 服务模板功能更新

src/scene_server/topo_server/service/inst_module.go
- 根据服务模板ID查模块接口支持按模块列表查
- xxxx
- xxxx
=> demand: 根据服务模板ID查模块接口支持按模块列表查

src/ui/src/views/business-synchronous/index.vue, src/ui/src/views/business-topology/children/create-module.vue, src/ui/src/views/business-topology/children/create-node.vue, src/ui/src/views/service-template/children/operational.vue, src/ui/src/views/service-template/children/template-instance.vue
- 修复服务模板实例同步显示异常的问题
- 修复创建服务模板时名称显示异常的问题
- 修复创建拓扑节点时服务分类切换错误的问题
=> UI:  服务模板、拓扑节点BUG修复

src/common/eventclient/eventclient.go
=> 补充推送事件时遗漏的解锁操作

src/ui/src/components/import/import.vue, src/ui/src/views/audit/index.vue, src/ui/src/views/business-topology/host/host-list-options.vue, src/ui/src/views/host-details/children/association-list.vue, src/ui/src/views/host-details/children/association.vue
- 修复主机关联在无实例时不显示空数据效果的问题 close #4027 
- 修复导入excel更新主机api地址错误的问题 close #4028
=> UI: 3.8 bug修复

src/source_controller/coreservice/core/host/identifier/identifier.go
- fix search host identifer with null array issue
=> fix search host identifer with null array issue

src/storage/dal/mongo/local/mongo.go
- 连接mongodb的时候， 执行ping，保证base session 中masterSocket 可用
- xxxx
- xxxx
=> refactor: add mongodb ping , product session mastersocket  issue #3884

src/common/eventclient/eventclient.go
=> event client bugfix

scripts/init.py, src/storage/dal/mongo/config.go, src/storage/dal/mongo/local/mongo.go, src/storage/dal/mongo/local/transaction.go, src/storage/stream/stream.go
- xxxx
- xxxx
- xxxx
close #4033
=> mongodb支持配置副本集名称

src/ui/src/components/model-manage/field-group/field-view.vue, src/ui/src/components/relation/_details.vue, src/ui/src/components/ui/form/form-multiple.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/components/ui/form/longchar.vue, src/ui/src/components/ui/form/search-input.vue, src/ui/src/views/business-synchronous/children/details.vue, src/ui/src/views/business-synchronous/index.vue, src/ui/src/views/business-topology/children/service-node-info.vue, src/ui/src/views/set-template/children/template-config.vue, src/ui/src/views/set-template/index.vue
- 服务模板同步，服务分类变更左侧不提示数量 close #4043 
- 修复统一表单元素未限制最大宽度的问题 close #4044 
- 修复模型字段详情备注字段读取错误的问题 close #4045 
- 修复服务模板同步内容去重及字段格式化错误的问题 close #4046
=> UI： 3.7 缺陷修复

src/ui/src/components/ui/auth/auth-queue.js
- 修复鉴权组件校验结果不严谨的问题 close #4041
=> UI: 修复鉴权组件校验结果不严谨的问题

src/auth/parser/topolatest.go, src/auth/parser/util.go
- 修复业务主机操作实例关联时提示无全局主机编辑权限的问题
close #4038
=> 修复业务主机操作实例关联时提示无全局主机编辑权限的问题

src/storage/dal/mongo/local/mongo_test.go, src/storage/dal/transaction_test.go, src/test/load/db_load_test.go, src/test/test.go, src/tools/cmdb_ctl/app/config/config.go, src/tools/cmdb_ctl/cmd/topo.go
=> 补上测试用例遗漏的rsName参数

src/scene_server/host_server/service/transfer.go
=> 主机转移等待全部转移完成后再返回，修复转移审计为空的问题

src/web_server/service/department.go
=> 修正获取组织接口的返回数据

vendor/github.com/holmeswang/contrib/sessions/redis.go
- session缓存大小设置为1M
close #4060
=> session缓存大小设置为1M

src/common/definitions.go, src/common/metadata/inst.go, src/common/metadata/process.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.7.202004141131/add_bk_port_enable_property.go, src/scene_server/admin_server/upgrader/y3.7.202004141131/pkg.go, src/source_controller/coreservice/core/process/process_template.go
=> bk_port_enable 改成 bk_enable_port

src/scene_server/host_server/service/host.go, src/scene_server/topo_server/service/inst_module.go
- 根据服务模板ID查模块接口支持按模块列表查
- 调整从权限中心解注册的方式，先解注册再删除。
=> optimize：服务模板与解注册主机信息调整

src/common/definitions.go, src/common/metadata/audit.go, src/scene_server/topo_server/service/auditlog.go, src/source_controller/coreservice/core/operation/inner_chart.go
=> 审计详情去掉basic_detail层

docs/apidoc/v3.1/host_relation.md, docs/apidoc/v3.2/host_relation.md, src/auth/authcenter/adaptor.go, src/auth/authcenter/authcenter.go, src/auth/parser/host.go, src/common/metadata/hostserver.go, src/scene_server/host_server/logics/host.go
=> 跨业务转移主机接口鉴权调整

src/common/definitions.go, src/test/topo_server/business_test.go, src/test/topo_server/inst_test.go, src/test/topo_server/object_test.go, src/ui/src/setup/validate.js
=> define: 更改短字符和长字符的类型要求，变更为"除空白符外所有类型"

src/scene_server/topo_server/core/model/attribute.go, src/scene_server/topo_server/service/object.go, src/source_controller/coreservice/core/model/attribute_curd.go
- 导入模型提示：修改不允许修改的属性的描述，但excel表中并未做修改的问题
=> 忽略不允许修改的属性

src/ui/src/assets/json/operation_audit.json, src/ui/src/components/audit-history/details.vue, src/ui/src/components/hosts/filter/_filter-field-operator.vue, src/ui/src/components/hosts/table/index.vue, src/ui/src/components/model-manage/_create-model.vue, src/ui/src/components/model-manage/field-group/field-detail/enum.vue, src/ui/src/components/model-manage/field-group/field-detail/index.vue, src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/components/property-selector/index.vue, src/ui/src/components/ui/form/form-multiple.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/components/ui/selector/business.vue, src/ui/src/filters/formatter.js, src/ui/src/mixins/form.js, src/ui/src/setup/validate.js, src/ui/src/store/modules/api/host-search.js, src/ui/src/store/modules/api/object-biz.js, src/ui/src/utils/tools.js, src/ui/src/views/audit/index.vue, src/ui/src/views/business-topology/children/service-node-info.vue, src/ui/src/views/business/index.vue, src/ui/src/views/general-model/index.vue, src/web_server/service/department.go
- 增加自定义拓扑节点审计动作表
- 主机集群/模块名称支持模糊查询
- 实例筛选属性排序增加唯一校验判断
- 新建实例必填字段增加唯一校验判断
- 调整模型字段创建校验规则
- 修复缺少自定义拓扑节点审计动作字典的问题
- 修复升级日志json数据重复显示的问题
- 修复升级日志json数据重复显示的问题
- 修复拓扑节点信息重复显示模板信息的问题
=> UI: 审计日志显示问题修复

src/ui/src/components/model-manage/field-group/field-detail/index.vue
=> fix:ui: 内置字段更新不提交名称字段

src/ui/src/views/business-topology/router.config.js, src/ui/src/views/host-details/children/info.vue, src/ui/src/views/host-operation/index.vue
=> fix:ui: 修复主机详情删除主机所属模块可以重新选择主机的问题

src/ui/src/setup/validate.js, src/ui/src/utils/tools.js, src/ui/src/views/service-category/index.vue, src/ui/src/views/set-template/children/template-intance.vue
- 统一数字字段正则校验
- 修复集群模板实例拓扑路径显示顺序错误的问题
- 修复服务一级分类名称超长修改入口被隐藏的问题
=> UI: bugfix

src/ui/src/components/audit-history/details.vue, src/ui/src/views/audit/index.vue, src/ui/src/views/host-apply/children/sidebar.vue, src/ui/src/views/host-apply/children/topology-tree.vue
- 调整审计日志数据读取路径
- 属性自动应用拓扑树批量编辑筛选交互优化
=> UI: 审计日志数据读取调整/属性自动应用交互优化

src/auth/extensions/instance.go, src/scene_server/admin_server/authsynchronizer/handler/core.go, src/scene_server/admin_server/authsynchronizer/handler/plat.go
- infoJSON日志使用%s
- 修复权限同步判断主线实例条件错误【不确定权限同步出错是不是这个原因】
=> 修复权限同步判断主线实例条件错误，infoJSON日志使用%s

scripts/init.py, src/apimachinery/coreservice/transaction/client.go, src/common/auditlog/util.go, src/common/blog/blog.go, src/common/blog/glog/glog.go, src/common/http/rest/contexts.go, src/source_controller/coreservice/core/instances/instance.go
- xxxx
- xxxx
- 日志的格式化问题
- map为nil时赋值导致的panic
=> 修复日志的格式化问题和map为nil时赋值导致的panic

src/auth/parser/topolatest.go, src/scene_server/topo_server/service/service_business_initfunc.go
- search_object_topo请求方法调整为post
=> search_object_topo请求方法调整为post

src/common/metadata/audit.go
=> 修复操作审计bson序列化时多一层的问题

src/auth/parser/host.go
- 添加list_resource_pool_hosts接口的权限解析
=> 添加list_resource_pool_hosts接口的权限解析

src/scene_server/host_server/service/transfer.go
=> 修复转移主机错误时返回转移成功的问题

src/scene_server/host_server/service/host.go, src/scene_server/topo_server/service/inst.go, src/scene_server/topo_server/service/inst_module.go, src/scene_server/topo_server/service/inst_set.go
- 修复删除实例时权限解注册不正确的问题
> 备注：高版本解注册2次是版本合并都合进去了，解决冲突时保留这个吧
close #4100
=> 修复删除实例时权限解注册不正确的问题

src/Makefile, src/scene_server/datacollection/datacollection/hostsnap.go
=> 修复同步的主机外网Mac地址与采集数据不一致的问题

src/scene_server/event_server/distribution/callback.go, src/scene_server/event_server/distribution/distribution.go, src/scene_server/event_server/distribution/handle_event.go, src/scene_server/event_server/distribution/reconclier.go, src/scene_server/event_server/service/subscription.go
优化的功能:
- 优化事件的回调方法
- 将多个redis命令用管道进行处理
- 修复对已发送的用户订阅事件进行过期删除的逻辑
- 对已取消订阅用户的回调记录进行删除
close issue #4103
=> 优化事件回调方法和修复已发送事件的过期删除

src/apiserver/service/http.go, src/auth/extensions/base.go, src/scene_server/host_server/logics/app.go, src/scene_server/host_server/logics/module.go
- code optimize with multiple supplier account support in biz resource pool, resource set and module
=> optimize: code optimize with multiple supplier account support

scripts/init.py, src/auth/extensions/business.go, src/auth/extensions/classification.go, src/auth/extensions/dynamicgroup.go, src/auth/extensions/host.go, src/auth/extensions/instance.go, src/auth/extensions/model.go, src/auth/extensions/module.go, src/auth/extensions/plat.go, src/auth/extensions/process.go, src/auth/extensions/servicetemplate.go, src/auth/extensions/set.go, src/scene_server/admin_server/authsynchronizer/handler/instance.go, src/scene_server/admin_server/authsynchronizer/handler/model.go
=> 权限中心同步时拉取coreservice改为分页拉取

src/ui/src/components/ui/other/property-value.vue, src/ui/src/store/modules/view/service-process.js, src/ui/src/views/service-template/children/operational.vue, src/ui/src/views/service-template/children/process-form.vue, src/ui/src/views/service-template/children/process.vue
=> fix: v3.8.x缺陷问题修复

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.8.202004241035/fix_set_template_version_time_empty.go, src/scene_server/admin_server/upgrader/y3.8.202004241035/pkg.go
- 修复set_template_version属性时间值为空的问题
=> 修复set_template_version属性时间值为空的问题

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/components/ui/other/property-value.vue, src/ui/src/views/business/index.vue, src/ui/src/views/general-model/index.vue, src/ui/src/views/host-apply/children/property-config-table.vue
- 修复模型字段分组名称长度保存未限制的问题
- 修复模型字段值得显示会出现undefined的问题
=> UI: 修复部分文本显示不正确的问题

src/scene_server/topo_server/service/inst.go
=> 去掉重复删除实例的代码

src/apimachinery/coreservice/host/api.go, src/apimachinery/coreservice/host/host.go, src/common/metadata/result.go, src/common/util/array.go, src/scene_server/host_server/logics/hostsearch.go, src/scene_server/host_server/service/findhost.go
- xxxx
- optimize: code optimize with host search related api. 
- 解决coreservice在去重时，导致内存过高的问题
close #4122
=> optimize: code optimize with host search related api.

src/common/metadata/attribute.go
- 调整属性自动应用的过滤规则，不存在的字段，不能进行属性自动应用。
=> optimize: 调整属性自动应用的过滤规则，不存在的字段，不能进行属性自动应用。

src/api_server/service/v3/uri.go
=> 增加查询模型实例关系的api路由

src/ui/src/assets/json/operation_audit.json, src/ui/src/components/model-instance/audit-history.vue, src/ui/src/components/ui/selector/selector.vue, src/ui/src/dictionary/audit.js, src/ui/src/views/audit/index.vue, src/ui/src/views/business-synchronous/index.vue, src/ui/src/views/business-topology/children/create-module.vue, src/ui/src/views/business-topology/children/create-set.vue, src/ui/src/views/business-topology/children/topology-tree.vue, src/ui/src/views/history/index.vue, src/ui/src/views/service-template/children/operational.vue, src/ui/src/views/service-template/template.vue
- 创建拓扑节点交互添加loading效果
- 业务拓扑搜索显示命中节点的子孙节点
- 修复操作审计显示异常的问题
- 修复服务模板同步判断服务分类变更逻辑错误的问题
=> UI: 审计/服务模板bugfix

src/ui/src/components/hosts/filter/index.vue, src/ui/src/components/ui/details/details.vue, src/ui/src/components/ui/form/enum.vue, src/ui/src/components/ui/form/list.vue, src/ui/src/components/ui/form/organization.vue, src/ui/src/components/ui/form/timezone.vue, src/ui/src/components/ui/selector/cloud.vue, src/ui/src/views/business-topology/children/service-instance-table.vue, src/ui/src/views/business-topology/children/service-instances.vue, src/ui/src/views/business/index.vue, src/ui/src/views/custom-query/define.vue, src/ui/src/views/custom-query/preview.vue, src/ui/src/views/host-details/children/service-list.vue, src/ui/src/views/set-template/children/service-template-selector.vue
- 列表枚举等字段组件在创建动态分组时支持多选
- 服务实例标签筛选显示名称优化
- 修复业务拓扑添加条件时遮盖层问题
- 主机筛选与关闭按钮样式优化
- 详情中的属性值溢出时使用tooltips提示
- 添加服务模板中的模板名称tooltips优化
- 主机详情中服务列表无服务实例样式优化
- 修复业务归档操作disabled态点击会跳转详情问题
- 解决组织组件显示宽度
- 动态分组弹窗中页码下拉遮挡问题
=> V3.8.x体验问题修复

src/storage/reflector/reflector.go, src/storage/stream/event/list.go, src/storage/stream/event/list_watch.go, src/storage/stream/stream.go, src/storage/stream/types/types.go
-  relector 与 stream框架新增支持list与liser操作。
=> demand： reflector 与 stream框架新增支持list与liser操作。

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.8.202004291536/add_index.go, src/scene_server/admin_server/upgrader/y3.8.202004291536/pkg.go
- cc_ServiceTemplate、cc_ProcessTemplate、cc_ServiceInstance表添加索引
=> cc_ServiceTemplate、cc_ProcessTemplate、cc_ServiceInstance表添加索引

src/apimachinery/coreservice/coreservice.go, src/apimachinery/coreservice/count/api.go, src/apimachinery/coreservice/count/count.go, src/scene_server/proc_server/service/servicetemplate.go, src/source_controller/coreservice/service/count.go, src/source_controller/coreservice/service/service_initfunc.go, src/storage/dal/mongo/local/mongo.go
- ListServiceTemplatesWithDetails接口性能优化
close  #4132
=> ListServiceTemplatesWithDetails接口性能优化

src/ui/src/views/business/index.vue, src/ui/src/views/general-model/index.vue
=> ui: 修复创建通用模型实例/业务时传递了自定id的问题

src/scene_server/topo_server/service/object.go
=> 修复excel导入模型属性无效的问题

src/scene_server/proc_server/service/serviceinstance.go
=> 服务模板同步过程中，difference接口中去掉服务模板名和绑定的模块名不一致的校验

src/scene_server/admin_server/upgrader/y3.8.202004291536/add_index.go, src/storage/dal/mongo/local/mongo.go
- cc_ServiceTemplate、cc_ProcessTemplate、cc_ServiceInstance表联合索引拆开
=> cc_ServiceTemplate、cc_ProcessTemplate、cc_ServiceInstance表联合索引拆开

src/common/rdapi/rdfunc.go, src/web_server/middleware/requestid.go
=> fix:duplicate rid issue #4146

scripts/init.py, src/web_server/middleware/login.go, src/web_server/middleware/user/plugins/method/open_source/userinfo.go, src/web_server/middleware/user/plugins/register/open_source.go, src/web_server/service/login.go, src/web_server/service/object.go, src/web_server/service/service.go
=> 开源版本增加一个简易的登录功能

src/apimachinery/coreservice/cache/api.go, src/apimachinery/coreservice/cache/cache.go, src/apimachinery/coreservice/host/api.go, src/apimachinery/coreservice/host/host.go, src/apimachinery/rest/request.go, src/common/definitions.go, src/common/http/rest/contexts.go, src/common/metadata/cache.go, src/common/metadata/result.go, src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go, src/scene_server/host_server/logics/host.go, src/scene_server/host_server/logics/import.go, src/scene_server/host_server/logics/log.go, src/scene_server/host_server/service/host.go, src/source_controller/coreservice/cache/business/client.go, src/source_controller/coreservice/cache/business/client_logic.go, src/source_controller/coreservice/cache/business/custom_level.go, src/source_controller/coreservice/cache/business/module_set.go, src/source_controller/coreservice/cache/cache.go, src/source_controller/coreservice/cache/host/cache.go, src/source_controller/coreservice/cache/host/client.go, src/source_controller/coreservice/cache/host/client_logic.go, src/source_controller/coreservice/cache/host/host.go, src/source_controller/coreservice/cache/host/key.go, src/source_controller/coreservice/cache/tools/lock.go, src/source_controller/coreservice/service/cache.go, src/source_controller/coreservice/service/service.go, src/source_controller/coreservice/service/service_initfunc.go
-  coreservice新增主机缓存管理能力
- datacollection中主机快照逻辑优化，去除原有的直接在内存缓存主机数据，调整为从coreservice中读取主机缓存数据进行管理。
close #4144
=> demand：datacollection中主机快照逻辑优化，新增coreservice主机缓存管理能力

src/common/backbone/configcenter/cc.go
- xxxx
- xxxx
- 修复从zookeeper 获取服务配置文件panic的问题
claose #4165
=> 修复从zookeeper 获取服务配置文件panic的问题

src/common/metadata/process.go, src/scene_server/proc_server/logics/processinstance.go, src/scene_server/proc_server/service/processinstance.go, src/scene_server/proc_server/service/serviceinstance.go
=> 服务模板同步接口性能优化

src/source_controller/coreservice/core/hostapplyrule/rule.go
=> 主机属性自动应用批量操作添加校验

src/apimachinery/healthz/healthz.go, src/apiserver/service/healthz.go, src/scene_server/admin_server/service/service.go, src/scene_server/host_server/service/service.go, src/scene_server/proc_server/service/service.go, src/source_controller/coreservice/service/health.go
=> healthz依赖组件更新

src/source_controller/coreservice/core/model/attribute_curd.go
=> 删除主机属性时同步删除主机自动应用

src/ui/src/App.vue, src/ui/src/assets/scss/common.scss, src/ui/src/components/layout/dynamic-navigation.vue, src/ui/src/components/layout/dynamic-router-view.vue, src/ui/src/components/ui/selector/business.vue, src/ui/src/dictionary/menu-symbol.js, src/ui/src/router/business-interceptor.js, src/ui/src/router/index.js, src/ui/src/router/query.js, src/ui/src/setup/preload.js, src/ui/src/store/modules/api/object-biz.js, src/ui/src/views/business-topology/children/topology-tree.vue, src/ui/src/views/business-topology/host/host-list.vue, src/ui/src/views/business-topology/index.vue, src/ui/src/views/index/index.vue, src/ui/src/views/index/router.config.js, src/ui/src/views/set-template/children/template-tree.vue
=> ui: 优化跳转至业务拓扑界面的性能

src/source_controller/coreservice/core/model/attribute_curd.go
=> 修复业务自定义字段判重条件错误的问题

src/scene_server/admin_server/service/flag.go, src/storage/driver/mongodb/monogdb.go, src/storage/driver/redis/redis.go
- xxxx
- 修改打印日志的内容
- 修复当配置文件频繁变化的时候，redis 打开连接过多的问题
=> V3.8.x redis driver

src/scene_server/admin_server/upgrader/y3.8.202004291536/add_index.go, src/scene_server/admin_server/upgrader/y3.8.202004291536/pkg.go
=> cc_ProcessInstanceRelation 添加索引

src/ui/src/views/host-operation/index.vue
=> optimize:ui: 优化确认转移主机的loading显示效果

src/scene_server/topo_server/service/association.go, src/scene_server/topo_server/service/inst_business.go
=> 调整主线模型的事务处理

src/ui/src/components/hosts/filter/index.vue, src/ui/src/utils/host.js
=> fix: 完善主机ip搜索

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/views/business-topology/children/create-node.vue
- 补充自定义层级的实例名称校验和模型字段分组名称长度限制调整
=> 补充自定义层级的实例名称校验和模型字段分组名称长度限制调整

src/ui/package.json
=> fix:ui: 修复login组件引起在safari假死的问题

src/ui/src/components/hosts/filter/index.vue, src/ui/src/components/hosts/table/index.vue, src/ui/src/components/layout/dynamic-navigation.vue, src/ui/src/router/query.js, src/ui/src/views/business-topology/children/topology-tree.vue, src/ui/src/views/business-topology/host/host-list.vue, src/ui/src/views/business-topology/index.vue, src/ui/src/views/general-model/index.vue, src/ui/src/views/index/children/footer.config.js, src/ui/src/views/index/children/footer.vue, src/ui/src/views/index/index.vue
- 首页页脚配置
- 修复切换业务时查询条件未重置的问题
- 修复进入子路由后父路由的QueryWatch失效的问题
=> UI: 业务菜单下的页面问题修复

src/auth/extensions/business.go, src/auth/extensions/classification.go, src/auth/extensions/dynamicgroup.go, src/auth/extensions/host.go, src/auth/extensions/instance.go, src/auth/extensions/model.go, src/auth/extensions/module.go, src/auth/extensions/plat.go, src/auth/extensions/process.go, src/auth/extensions/servicetemplate.go, src/auth/extensions/set.go
=> 修复分页判断条件错误的问题

src/ui/config/index.js, src/ui/index.html, src/ui/src/views/index/children/host-search.vue, src/ui/src/views/index/index.vue
- 添加bkDesktop配置
- 首页IP搜索添加按钮loading效果
=> UI： 添加desktop配置项

src/source_controller/coreservice/event/flow.go
=> golang.org/x/net/context替换成context

scripts/init.py, src/web_server/service/service.go
- 将gin的运行模式从debug改为release，修改adminserver的数据库连接数配置
=> 将gin的运行模式从debug改为release，修改adminserver的数据库连接数配置

src/ui/src/views/host-details/children/association-list-table.vue, src/ui/src/views/host-details/children/association.vue, src/ui/src/views/host-details/children/property.vue, src/ui/src/views/host-details/children/service-instance-table.vue, src/ui/src/views/host-details/children/service-list.vue, src/ui/src/views/host-details/mixin-auth.js
=> ui: 主机详情鉴权精细化

scripts/init.py, src/web_server/app/options/options.go, src/web_server/app/server.go, src/web_server/service/index.go
=> webserver添加蓝鲸桌面配置

src/common/metadata/audit.go, src/scene_server/topo_server/core/operation/object_attr_audit.go, src/scene_server/topo_server/core/operation/object_attrgroup_audit.go
=> 修复模型操作审计反序列化失败的问题

src/scene_server/topo_server/service/inst.go
=> 修复toposerver空指针异常的问题

src/common/metrics/metrics.go
=> 修复非utf-8的URL导致metrics panic的问题

src/common/zkclient/zkclient.go
=> 修复zk并发二次关闭的问题

src/scene_server/operation_server/service/service.go, src/scene_server/topo_server/service/service.go, src/source_controller/coreservice/service/service.go
- 修复url有可变参数时，metrics会采集多个url的问题
=> 修复url有可变参数时，metrics会采集多个url的问题

src/auth/authcenter/adaptor.go, src/common/http/rest/contexts.go, src/source_controller/coreservice/cache/host/host.go, src/source_controller/coreservice/core/mainline/class.go, src/source_controller/coreservice/core/mainline/instance.go, src/source_controller/coreservice/event/flow.go, src/source_controller/coreservice/event/gc.go, src/source_controller/coreservice/event/key.go, src/source_controller/coreservice/service/mainline.go
- xxxx
- coreservice 事件流优化，新加对主机事件的合法校验。
- xxxx
=> coreservice flow事件流优化

src/source_controller/coreservice/cache/host/host.go, src/source_controller/coreservice/cache/host/key.go, src/source_controller/coreservice/event/flow.go
- optimize：主机缓存逻辑中，去掉去oid key 的操作与管理
=> optimize：主机缓存逻辑中，去掉去oid key 的操作与管理

src/ui/src/components/ui/form/form.vue
=> 补充业务拓扑节点信息编辑中的集群和模块名称校验

src/scene_server/host_server/logics/hostsearch.go, src/source_controller/coreservice/service/host.go
=> optimize: 优化主机查询接口的查询性能。

src/api_server/service/v3/uri.go
- 对于ESB接口调用失败的情况，增加增删实例关联关系的接口路由
=> 增加增删实例关联关系的接口路由

src/tools/cmdb_ctl/cmd/snapshot.go
=> 主机快照小工具中datacollection的redis配置从redis.conf中读取

src/auth/parser/topolatest.go
=> /find/objecttopology 的parser使用post方法

src/ui/src/components/hosts/table/index.vue, src/ui/src/components/model-instance/mixin-auth.js, src/ui/src/components/model-instance/property.vue, src/ui/src/components/model-instance/relation/create.vue, src/ui/src/components/model-instance/relation/index.vue, src/ui/src/components/model-instance/relation/list-table.vue, src/ui/src/components/model-instance/relation/list.vue, src/ui/src/setup/permission.js, src/ui/src/utils/host.js, src/ui/src/views/audit/index.vue, src/ui/src/views/business-topology/host/host-list.vue, src/ui/src/views/business/details.vue, src/ui/src/views/custom-query/preview.vue, src/ui/src/views/eventpush/index.vue, src/ui/src/views/general-model/details.vue, src/ui/src/views/host-details/mixin-auth.js
- 精细化实例鉴权
- 事件订阅的operation字段改为statistics
- 修复业务修改鉴权错误
- 修复操作审计筛选项多选宽度超出问题
=> V3.8.x优化与体验问题修复

src/common/http/rest/contexts.go, src/common/rdapi/rdfunc.go, src/web_server/middleware/requestid.go
- xxxx
- 统一返回请求id功能
- 收敛请求id的生成位置
-
=> fix:not return rid in http header  issue #4146

src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go, src/scene_server/datacollection/datacollection/porter.go, src/source_controller/coreservice/cache/host/client.go
- fix data collection snapshot issue with multiple ipv4 and ipv6
=> optimize: fix data collection snapshot issue with multiple ipv4 and ipv6

src/apiserver/service/service.go, src/common/rdapi/rdfunc.go, src/scene_server/synchronize_server/service/service.go
=> apiserver入口处增加请求信息日志

src/common/metadata/eventserver.go
=> 事件订阅的operation字段改为statistics，和3.5版本保持一致

src/apimachinery/eventserver/api.go, src/apimachinery/eventserver/eventserver.go, src/auth/authcenter/adaptor.go, src/auth/authcenter/id.go, src/auth/parser/event.go, src/common/types/serverInfo.go, src/common/watch/watch.go, src/scene_server/event_server/service/lua.go, src/scene_server/event_server/service/watch.go, src/source_controller/coreservice/cache/business/custom_level.go, src/source_controller/coreservice/cache/business/key.go, src/source_controller/coreservice/event/flow.go, src/source_controller/coreservice/event/gc.go, src/source_controller/coreservice/event/lua.go, src/tools/cmdb_ctl/cmd/watch.go, src/tools/cmdb_ctl/cmd/zk.go
- xxxx
- 调整事件监听的返回协议，优化处理效率。
- 新增tool工具支持watch资源变化，支持filter过滤。
- xxxx
=> optimize: optimize event watch logics.

src/common/blog/blog.go, src/storage/dal/mongo/local/mongo.go, src/storage/dal/mongo/local/mongo_test.go, src/storage/dal/redis/redis.go, src/storage/dal/types/types.go
-  mongodb driver 新加DropDocsColumn方法，用来根据条件删除document 的column
-  新加warnJSON 用写入warn 日志
- 
- 修复配置文件中配置redis 最大连接个无效德问题。
=> V3.8.x driver

src/scene_server/topo_server/core/operation/association.go, src/scene_server/topo_server/core/operation/association_mainline_inst.go, src/scene_server/topo_server/core/operation/inst.go, src/scene_server/topo_server/core/operation/object.go, src/scene_server/topo_server/service/association.go
=> topoinst接口性能优化

src/scene_server/host_server/logics/hostsearch.go
=> 修复主机查询时指定bk_host_id查询条件后无数据的问题

src/scene_server/topo_server/core/operation/identifier.go
=> 修复查询主机身份接口返回数据嵌套的问题，添加主机不存在的判断

src/auth/meta/meta.go, src/common/auditlog/util.go
- 调整资源监听的鉴权方式
- 修复datacollection记审计时可能会引发的panic问题
=> optimize: resource watch iam revised and fix audit log err check issue.

src/common/backbone/backbone.go
- backbone增加uuid字段的检查设置，防止有些第三方插件没有设置该字段而出错的问题
=> backbone增加uuid字段的检查设置，防止有些第三方插件没有设置该字段而出错的问题

src/source_controller/coreservice/cache/tools/lock.go
=> fix: fix cache refresh concurrent read map.

src/common/zkclient/zkclient.go
=> 修复zk connect失败导致空指针异常的问题

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.8.202005201015/add_host_attr.go, src/scene_server/admin_server/upgrader/y3.8.202005201015/pkg.go
- 主机属性增加docker版本字段
close #4235
=> 主机属性增加docker版本字段

src/ui/src/views/host-details/children/service-instance-table.vue, src/ui/src/views/host-details/children/service-list.vue
=> fix:ui: 修复主机详情服务列表未注入权限数据的问题

src/common/backbone/backbone.go, src/framework/main.go, src/test/test.go
=> 调整zk的session timeout到40秒

src/common/metrics/metrics.go
=> metrics采集添加appcode、用户和用户ip的采集label

src/storage/driver/mongodb/monogdb.go, src/storage/driver/redis/redis.go
- redis driver 提供healthz 接口给metric 使用  
- mongodb driver 提供healthz 接口给metric 使用
- xxxx
- xxxx
close #4254
=> V3.8.x driver healthz

src/scene_server/proc_server/service/serviceinstance.go
modify syncServiceInstanceByTemplate param option
=> modify syncServiceInstanceByTemplate param option

src/ui/src/store/modules/api/service-instance.js, src/ui/src/views/service-instance/create.vue
=> UI: 新增主机到模块添加确认自动应用属性tab页

src/auth/parser/serviceinstance.go, src/common/metadata/process.go, src/scene_server/host_server/service/transfer.go, src/scene_server/proc_server/service/service.go, src/scene_server/proc_server/service/serviceinstance.go
- 添加新增服务实例时的主机自动应用等信息的预览接口
- 添加服务实例接口增加主机自动应用冲突处理
- 修复主机转移时解决主机自动应用冲突无效的问题
=>  添加服务实例接口增加主机自动应用冲突处理

src/apiserver/app/server.go, src/apiserver/service/filter.go, src/apiserver/service/limiter.go, src/apiserver/service/service.go, src/common/definitions.go, src/common/errInfo.go, src/common/metadata/apilimiter.go, src/common/rdapi/rdfunc.go, src/common/types/serverInfo.go, src/common/util/struti.go, src/tools/cmdb_ctl/cmd/limiter.go, src/tools/cmdb_ctl/readme.md
- apiserver新增服务降级能力，能对api进行限流
- 提供操作api限流策略的命令行工具
close #4243
=> apiserver新增服务降级能力

src/apimachinery/toposerver/inst/api.go, src/apimachinery/toposerver/inst/module.go, src/apimachinery/toposerver/inst/set.go, src/auth/parser/topology.go, src/common/metadata/common.go, src/common/metadata/page.go, src/scene_server/topo_server/service/inst_module.go, src/scene_server/topo_server/service/inst_set.go, src/scene_server/topo_server/service/service_initfunc.go, src/test/topo_server/object_test.go
- 增加批量查询某业务下的集群详情接口
- 增加批量查询某业务下的模块详情接口
close issue #4229
=> 增加批量查询某业务下集群和模块的接口

src/scene_server/host_server/service/transfer.go
=> 修复转移主机时进程删除失败的问题

src/scene_server/datacollection/datacollection/hostsnap/filter.go
- optimize: 主机快照失效时间新增随机策略，避免短时间大量数据操作。
=> optimize: 主机快照失效时间新增随机策略，避免短时间大量数据操作。

src/auth/parser/host.go, src/common/metadata/hostserver.go, src/scene_server/host_server/service/module.go
=> 补充查询主机业务关系信息接口的权限解析

src/common/condition/condition.go, src/common/condition/field.go, src/scene_server/host_server/logics/host.go, src/scene_server/host_server/logics/import.go, src/scene_server/host_server/logics/log.go, src/scene_server/host_server/service/host.go, src/scene_server/topo_server/core/model/object.go
- 审计日志只记录模型的公共属性，不记录业务下的私有属性
close #4267
=> 审计日志只记录模型的公共属性，不记录业务下的私有属性

src/common/definitions.go, src/common/metadata/common.go, src/scene_server/topo_server/service/auditlog.go
=> 增加审计日志page limit的校验

src/common/definitions.go, src/common/errors/errorIf.go, src/common/metadata/common.go, src/scene_server/topo_server/service/auditlog.go
=> 增加审计日志分页limit参数的校验

src/scene_server/host_server/service/findhost.go
=> 查询资源池主机时，如果查到多个资源池，使用自己开发商下的

src/apiserver/service/http.go, src/scene_server/host_server/service/findhost.go
- xxxx
-  apiserver proxy 输出的日志新加rid
- 删除获取业务主机的无效代码
- xxxx
close #4272
close #4277
=>  hostserver optimize

src/apimachinery/coreservice/cache/cache.go, src/common/http/rest/contexts.go, src/common/metadata/cache.go, src/source_controller/coreservice/cache/host/client.go, src/source_controller/coreservice/cache/host/host.go, src/source_controller/coreservice/service/cache.go, src/source_controller/coreservice/service/service_initfunc.go
-  coreservice新增批量查询主机缓存数据接口。 
- rest context新增对json array string响应的支持
=> demand: coreservice新增批量查询主机缓存数据接口

src/apimachinery/coreservice/cache/api.go
- add cache api ListHostWithHostID
=> add cache api ListHostWithHostID

src/scene_server/host_server/logics/hostsearch.go
=> 避免一次性获取过多的数据

vendor/stathat.com/c/consistent/LICENSE, vendor/stathat.com/c/consistent/README.md, vendor/stathat.com/c/consistent/consistent.go, vendor/stathat.com/c/consistent/consistent_test.go, vendor/stathat.com/c/consistent/example_test.go
=> vendor目录里增加一致性哈希库

src/common/metadata/core_service.go, src/scene_server/host_server/logics/host.go, src/scene_server/host_server/logics/hostsearch.go, src/source_controller/coreservice/core/host/transfer/manager.go
=> 控制主机关系返回的字段

src/auth/authcenter/adaptor.go, src/auth/authcenter/perm_sys.go, src/auth/meta/meta.go, src/common/watch/cursor.go, src/common/watch/watch.go, src/source_controller/coreservice/cache/business/module_set.go, src/source_controller/coreservice/event/event.go, src/source_controller/coreservice/event/key.go, src/source_controller/coreservice/event/types.go, src/storage/dal/mongo/local/mongo.go
=> 新增业务、集群、模块watch事件通知

src/scene_server/proc_server/service/processtemplate.go, src/source_controller/coreservice/service/transaction.go
=> 修复创建没有附带进程的服务模板失败问题

src/ui/src/views/business-topology/children/service-node-info.vue, src/ui/src/views/model-manage/index.vue
- 模型管理搜索忽略大小写
- 修复拓扑节点信息编辑信息溢出导致操作选项不可见的问题
=> UI: 模型管理搜索优化/拓扑节点编辑UI溢出BUG修复

src/common/auditlog/util.go, src/common/metadata/host.go, src/scene_server/admin_server/upgrader/y3.8.202005251144/change_host_ip_user_to_array.go, src/source_controller/coreservice/cache/host/host.go, src/source_controller/coreservice/core/instances/validator_unique.go, src/source_controller/coreservice/event/flow.go, src/storage/dal/mongo/local/mongo.go, src/test/host_server/host_test.go
- bson.String的类型判断兼容去掉。
- parseBsonString，返回[]byte，减少数据拷贝
- specialFields定义成pkg变量。
- getHostDetailsFromMongodbIP, IP支持精确匹配。
- host watch中拿到的事件，也要把ip等改成字符串逗号。
- dal层，新增校验，如果用户传了fields,且包含了4个敏感字段，则进行强制的类型判断，否则不用。
=> code review调整

scripts/init.py
=> 修复init,py配置rs_name失败的问题

src/ui/src/components/hosts/filter/_filter-field-operator.vue, src/ui/src/views/custom-query/define.vue
- 添加一种主机字段查询操作符应用于动态分组和优化查询条件值显示逻辑
=> V3.8.x动态分组缺陷问题修复

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/views/business/router.config.js
- 模型分组名称显示长度优化
- 业务与资源目录菜单激活状态显示优化
=> V3.8.x体验问题优化

src/apimachinery/coreservice/host/api.go, src/apimachinery/coreservice/host/host.go, src/common/metadata/core_service.go, src/common/metadata/hostcontroller.go, src/scene_server/host_server/logics/hostsearch.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/host/transfer.go, src/source_controller/coreservice/core/host/transfer/manager.go, src/source_controller/coreservice/service/host.go, src/source_controller/coreservice/service/service_initfunc.go, src/storage/dal/mongo/local/mongo.go, src/storage/dal/mongo/local/mongo_test.go, src/storage/dal/types/types.go
-  mongodb dal 新加distinct 操作
-  coreservice 新加根据拓扑条件使用distinct来获取满足条件的主机 
-  优化hostserver 查询主机获取限定条件下主机id
- xxxx
=> V3.8.x hostserver optimize

src/test/host_server/host_abnormal_test.go, src/test/host_server/host_apply_test.go, src/test/host_server/host_test.go, src/test/host_server/user_test.go, src/test/proc_server/no_service_template_test.go, src/test/proc_server/proc_server_suite_test.go
=> 测试用例使用127网段

src/auth/extensions/host.go, src/auth/parser/util.go, src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go, src/scene_server/host_server/logics/app.go, src/scene_server/host_server/logics/host.go, src/scene_server/host_server/logics/log.go, src/scene_server/host_server/logics/module.go, src/scene_server/host_server/service/findhost.go, src/scene_server/host_server/service/host.go, src/scene_server/host_server/service/hostapplyrule.go, src/scene_server/host_server/service/transfer.go, src/scene_server/proc_server/service/processinstance.go, src/scene_server/proc_server/service/serviceinstance.go, src/scene_server/topo_server/core/operation/association_mainline_inst.go, src/scene_server/topo_server/core/operation/inst.go, src/scene_server/topo_server/core/operation/inst_business.go, src/scene_server/topo_server/core/operation/inst_module.go, src/scene_server/topo_server/service/inst_business.go, src/scene_server/topo_server/service/set_template.go
=> 查询主机关系时限制返回字段

src/ui/src/views/custom-query/define.vue, src/ui/src/views/host-apply/children/multi-module-config.vue, src/ui/src/views/host-apply/children/single-module-config.vue, src/ui/src/views/host-apply/children/topology-tree.vue, src/ui/src/views/host-apply/edit.vue, src/ui/src/views/host-apply/index.vue
- 主机自动应用模块页面loading态优化
- 动态分组下拉框无法使用问题
=> V3.8.x缺陷与体验问题修复

src/ac/iam/adaptor.go, src/ac/iam/client.go, src/ac/iam/iam.go, src/ac/iam/initial_actions.go, src/ac/iam/initial_instance_selections.go, src/ac/iam/initial_resources.go, src/ac/iam/types.go, src/common/metadata/operation.go, src/scene_server/admin_server/app/server.go, src/scene_server/auth_server/app/options/options.go, src/scene_server/auth_server/app/server.go, src/scene_server/auth_server/logics/fetch_instance_info.go, src/scene_server/auth_server/logics/list_attr.go, src/scene_server/auth_server/logics/list_attr_value.go, src/scene_server/auth_server/logics/list_instance.go, src/scene_server/auth_server/logics/util.go, src/scene_server/auth_server/service/business_resource.go, src/scene_server/auth_server/service/instance_resource.go, src/scene_server/auth_server/service/no_instance_resource.go, src/scene_server/auth_server/service/system_resource.go, src/scene_server/auth_server/types/parser.go, src/scene_server/cloud_server/app/options/options.go, src/scene_server/cloud_server/app/server.go, src/test/test.go
- authserver 配置获取方式调整
- adminserver iam配置使用common里的权限配置
- 注册iam权限资源bugfix
- 拉取权限资源接口bugfix
=> WIP 新版权限中心相关调整

src/source_controller/coreservice/event/gc.go
=> 修复watch里gc回收head与tail直接全部的节点导致tail指向不存在节点的问题

src/scene_server/host_server/service/findhost.go, src/source_controller/coreservice/core/host/searcher/searcher.go
=> fix set cond not used issue

src/source_controller/coreservice/core/host/transfer/manager.go, src/source_controller/coreservice/core/host/transfer/transfer.go
=> 取消转移主机的服务实例存在性校验

src/scene_server/host_server/app/server.go, src/test/host_server/host_abnormal_test.go, src/test/host_server/host_test.go, src/test/host_server/user_test.go, src/test/proc_server/proc_server_suite_test.go, src/web_server/app/server.go, vendor/github.com/holmeswang/redistore/redistore.go
=> redis配置解析错误修复

src/scene_server/host_server/logics/host.go
=> 根据IP和云区域查询主机时IP数组使用精准匹配

src/ui/src/views/business/index.vue, src/ui/src/views/general-model/index.vue
=> 模型实例侧滑详情标题溢出显示优化

src/auth/parser/host.go, src/common/metadata/hostlock.go, src/scene_server/host_server/logics/hostlock.go, src/scene_server/host_server/service/hostlock.go, src/source_controller/coreservice/core/host/lock.go
=> 主机锁接口入参调整为主机ID数组

src/ui/src/filters/formatter.js, src/ui/src/views/index/children/full-text-search.vue, src/ui/src/views/index/children/search-input.vue
- 全文检索适配主机IP等数据调整为数组及高亮搜索词显示优化
=> 全文检索适配主机IP等数据调整为数组及高亮搜索词显示优化

src/source_controller/coreservice/service/hostuser.go
=> 修复用户名中带.的用户的展示属性写入mongodb时会被解析为多层的问题
