- bk-cmdb.sql
在bk-cmdb.sql文件中加上新建数据库和选择数据库，感觉会更好一些。
> add create databse cmdb and use cmdb sql

- src/scene_server/host_server/host_service/logics/modulehostconfig.go
- src/scene_server/topo_server/topo_service/actions/inst/inst.go
- src/scene_server/validator/valid_basic.go
修复实例导入 时处理缺省字段不合理的问题
close #82
> 修复实例导入失败的问题

- src/common/paraparse/app.go
解决查询条件中带有特殊字符导致查询不到数据的问题
close #83
> fixbug:修复输入特殊字符查询失败的bug

- src/scene_server/topo_server/topo_service/logics/object/object.go
- src/ui/src/components/common/selector/association.vue
> fixbug:禁止删除内置模型

- src/scene_server/admin_server/migrate_service/actions/migrate.go
- src/scene_server/admin_server/migrate_service/data/objAttDescData.go
- src/scene_server/admin_server/migrate_service/logics/upgrade.go
- src/scene_server/admin_server/migrate_service/models/obj_att_desc_data.go
> fixes_require_fields #96

- src/scene_server/host_server/host_service/logics/host_log.go
- src/scene_server/proc_server/proc_service/actions/detail.go
- src/scene_server/proc_server/proc_service/actions/process.go
- src/scene_server/topo_server/topo_service/actions/inst/inst.go
> Feature historydatas

- src/scene_server/host_server/host_service/logics/object.go
> 修复普通对象查询主机

- src/scene_server/admin_server/migrate_service/ccapi.go
- src/scene_server/admin_server/migrate_service/config/conf.go
> admin-server don't listen port before related resource was ready

- src/scene_server/topo_server/topo_service/actions/object/topo_action.go
- src/scene_server/topo_server/topo_service/logics/object/object_attribute.go
> fixbug:修复问题

- src/scene_server/admin_server/migrate_service/data/objAttDescData.go
add property bk_parent_id to set row #143
> add property bk_parent_id to set row #143

- src/scene_server/topo_server/topo_service/actions/inst/auditlog.go
> 操作日志 操作类型支持delete参数，获取删除数据的操作日志

- scripts/init.py
modified:   init.py
check cmdb url start with "http://"
> Changes to be committed:

- src/scene_server/admin_server/migrate_service/data/objAttDescData.go
- src/scene_server/proc_server/proc_service/actions/process.go
- src/scene_server/validator/valid_basic.go
修复进程名重名bug, 优化validator逻辑 close #209
> 修复进程名重名bug

- src/api_server/ccapi/actions/v2/application/app.go
- src/api_server/ccapi/logics/v2/topo.go
修复v2版本getappsetmoduletreebyappid 在多层级下返回拓扑数据缺少层级的问题
> v2 api getopobyid fixed multilevel data error issue #210

- docs/apidoc/object_common_inst.md
- src/api_server/ccapi/actions/v3/topo/inst.go
- src/scene_server/api/inst_select.go
- src/scene_server/topo_server/topo_service/actions/inst/inst.go
- src/scene_server/topo_server/topo_service/actions/inst/inst_asst.go
- src/scene_server/topo_server/topo_service/ccapi.go
- src/source_controller/api/metadata/object.go
> 实现普通模型实例关联查找

- src/ui/src/components/filter/screening.vue
- src/ui/src/pages/topology/topology.vue
> bugfix:修复主机查询参数重复的问题

- src/scene_server/topo_server/topo_service/actions/object/topo_action.go
> feature:创建主线模型默认实例的时候，实例名只用模型名

- src/scene_server/validator/valid_basic.go
> 修复进程属性无法修改bug

- src/scene_server/host_server/host_service/instapi/inst.go
- src/scene_server/topo_server/topo_service/actions/inst/inst.go
修复关联数据查询 返回nil 的bug close #246
> fixbug:修复 #246

- src/api_server/ccapi/actions/v3/host/host.go
> 修复api_server请求url

- src/ui/src/components/object/attribute.vue
- src/ui/src/pages/organization/object.vue
- src/ui/src/pages/process/process.vue
bugfix:修复int类型被保存为字符串的问题
bugfix:修复通用模型实例切换页面未清空已选的问题
update:进程管理不显示业务ID
> Bugfix ce v4

- src/common/paraparse/app.go
- src/scene_server/topo_server/topo_service/actions/inst/inst_asst.go
> 修复输入条件特殊字符转义的bug

- src/ui/src/components/common/hostAssociation/children/filter.vue
- src/ui/src/components/object/attribute.vue
- src/ui/src/pages/topology/children/attribute.vue
minor: 修复内网IP未国际化的问题
bugfix：修复option为null时校验问题
>  bugfix：修复option为null时校验问题

- src/api_server/ccapi/actions/v3/topo/inst.go
- src/scene_server/api/inst_select.go
- src/scene_server/topo_server/topo_service/actions/inst/helper.go
- src/scene_server/topo_server/topo_service/actions/inst/inst.go
- src/scene_server/topo_server/topo_service/actions/inst/inst_asst.go
- src/scene_server/topo_server/topo_service/actions/inst/inst_search.go
> 支持子网区域实例查询 

- src/common/confcenter/conf.go
- src/scene_server/event_server/event_service/ccapi.go
- src/scene_server/event_server/event_service/config/conf.go
- src/scene_server/proc_server/proc_service/ccapi.go
- src/scene_server/proc_server/proc_service/config/conf.go
- src/source_controller/auditcontroller/audit/ccapi.go
- src/source_controller/auditcontroller/audit/config/conf.go
- src/source_controller/objectcontroller/objectdata/config/conf.go
- src/source_controller/proccontroller/procdata/ccapi.go
- src/source_controller/proccontroller/procdata/config/conf.go
- src/web_server/application/config/conf.go
> update language discover

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/source_controller/api/client/client.go
- src/source_controller/hostcontroller/hostdata/actions/instdata/userapi_action.go
> Fixed proc protocol

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/common/definitions.go
- src/scene_server/datacollection/datacollection/logics/hostsnap.go
- src/scene_server/topo_server/topo_service/actions/inst/app.go
1. 修复系统类型枚举映射错误
2. 操作审计操作类型不正确
> Globalization

- src/ui/package.json
- src/ui/src/components/deleteHistory/deleteHistory.vue
- src/ui/src/magicbox/bk-magic/components/date/src/date.vue
bugifx:修复归档历史中枚举类型id与label未做转换的问题
update:修复时间选择器修改时间不派发事件的问题
update:固定vee-validate版本为2.0.6
> Bugfix tencent master

- docs/apidoc/object_common_inst.md
- src/api_server/ccapi/actions/v2/application/app.go
- src/api_server/ccapi/actions/v2/application/set.go
- src/api_server/ccapi/actions/v2/host/host.go
- src/api_server/ccapi/actions/v2/plat/plat.go
- src/api_server/ccapi/logics/v2/fileds.go
- src/common/definitions.go
- src/scene_server/admin_server/migrate_service/data/objAttDescData.go
- src/scene_server/admin_server/migrate_service/logics/default_app_migrate.go
- src/scene_server/admin_server/migrate_service/logics/upgrade.go
- src/scene_server/host_server/host_service/actions/openapi/host.go
- src/scene_server/host_server/host_service/instapi/inst.go
- src/scene_server/host_server/host_service/logics/common.go
- src/scene_server/host_server/host_service/logics/host_add.go
- src/scene_server/proc_server/proc_service/actions/detail.go
- src/scene_server/topo_server/topo_service/actions/inst/inst.go
- src/scene_server/topo_server/topo_service/actions/inst/module.go
- src/scene_server/topo_server/topo_service/actions/inst/set.go
- src/scene_server/topo_server/topo_service/logics/object/object.go
- src/scene_server/topo_server/topo_service/logics/object/object_attribute.go
- src/scene_server/validator/valid_basic.go
- src/scene_server/validator/validator.go
- src/source_controller/objectcontroller/objectdata/actions/metadata/objectatt_action.go
- src/web_server/application/logics/excel.go
- src/web_server/application/logics/fields.go
修改拼写错误， 将filed改为field，只修改了函数名， 变量没有改
>  Misspell  change filed to field

- src/api_server/ccapi/actions/v2/application/app.go
- src/api_server/ccapi/actions/v2/application/set.go
- src/api_server/ccapi/actions/v2/host/host.go
- src/api_server/ccapi/logics/v2/topo.go
- src/common/util/lib.go
- src/scene_server/topo_server/topo_service/actions/inst/app.go
- src/scene_server/topo_server/topo_service/actions/object/object.go
- src/source_controller/hostcontroller/hostdata/actions/instdata/history_action.go
- src/source_controller/hostcontroller/hostdata/actions/instdata/userapi_action.go
- src/web_server/application/controllers/host.go
- src/web_server/application/controllers/inst.go
- src/web_server/application/controllers/object.go
- src/web_server/application/logics/excel.go
- src/web_server/application/logics/fields.go
- src/web_server/application/logics/host.go
- src/web_server/application/logics/httpheader.go
- src/web_server/application/logics/inst.go
- src/web_server/application/logics/object.go
1. 更新自定义API，提示数据重复
2. 字段类型，导入枚举类型的字段，枚举的选项无法导入
3. 删除业务新接口报错
3. 创建模块新接口报错
4. 修改主机自定义老接口属性报错
> Fixed i18n bug

- src/common/auditoplog/operationlog.go
- src/scene_server/host_server/host_service/logics/host_log.go
> use new optype 100 indicate that the host module change

- docs/apidoc/host_search.md
- resources/language/en/topo.json
- src/api_server/ccapi/actions/v3/host/host.go
- src/api_server/ccapi/actions/v3/topo/inst.go
- src/common/definitions.go
- src/scene_server/api/inst_select.go
- src/scene_server/host_server/host_service/actions/search/host.go
- src/scene_server/host_server/host_service/actions/userapi/userapi.go
- src/scene_server/host_server/host_service/instapi/inst.go
- src/scene_server/host_server/host_service/logics/host.go
- src/scene_server/topo_server/topo_service/actions/inst/inst.go
- src/scene_server/topo_server/topo_service/actions/inst/type.go
- src/web_server/application/controllers/host.go
- src/web_server/application/logics/excel.go
- src/web_server/application/logics/fields.go
- src/web_server/application/logics/host.go
- src/web_server/application/logics/inst.go
- src/web_server/application/logics/util.go
1. 关联字段导出
2. 新家主机，实例查询返回关联的详情接口
> Excel asst outport

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/common/definitions.go
- src/common/util/valid.go
- src/scene_server/topo_server/topo_service/actions/object/object.go
- src/scene_server/topo_server/topo_service/logics/object/object_attribute.go
- src/web_server/application/controllers/object.go
- src/web_server/application/logics/excel.go
- src/web_server/application/logics/object.go
1. v2 app info return developer and operator, (获取key不存可以忽略)
2. output  property handle nil 
3. import enum type option is require
4. import enum type option is require
4. 字段是主键，将设置为必填字段
> Fixed bug 20180505

- src/scene_server/proc_server/proc_service/actions/openapi/process.go
> v2 api getprocessbyapplicationid  bug    issue 377

- src/scene_server/topo_server/topo_service/actions/inst/inst.go
> 通用实例操作接口支持云区域更新与删除

- docs/apidoc/operation_audit.md
- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/common/util/valid.go
- src/scene_server/topo_server/topo_service/actions/inst/auditlog.go
- src/scene_server/topo_server/topo_service/actions/object/object.go
- src/web_server/application/logics/object.go
1. v2 根据用户获取业务， 兼容处理
2. 导入字段int类型校验错误
> Fixed bug 20180510

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/scene_server/topo_server/topo_service/actions/object/object.go
> import property

- src/ui/src/components/common/hostAssociation/children/filter.vue
- src/ui/src/components/common/hostAssociation/host.vue
- src/ui/src/pages/model/children/field.vue
- src/ui/src/pages/model/children/other.vue
bugfix: 变更关联，操作系统类型搜索无结果
bugfix: 新增模型数字类型属性时 最小值可以比最大值大
bugfix: 编辑属性字段 取消后再次查看还是修改后的数据
feature: 主线模型禁止删除
> bugifx: 1、解决模型属性新增时关联类型可以为空的问题 2、新增枚举类型时删除是否必填选项

- src/scene_server/host_server/host_service/logics/host_add.go
- src/scene_server/validator/valid_basic.go
1. addhost新加校验主机信息逻辑
2. bool类型字段，非必填值可以为nil
> add host checkout host info , valid bool allow nil

- src/ui/src/components/table/table-body.vue
- src/ui/src/components/table/table.vue
- src/ui/src/pages/index/index.vue
- src/ui/src/store/modules/navigation.js
update:首页添加主机管理  
update:表格组件添加行悬浮背景配置
> Dev tencent master

- src/api_server/ccapi/actions/v2/application/app.go
- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/api_server/ccapi/logics/v2/common/converter/converter_test.go
- src/api_server/ccapi/logics/v2/common/defs/defs.go
- src/api_server/ccapi/logics/v2/topo.go
close #430 
问题：
修复字段转换为字符串，panic问题
修复根据用户名获取模糊匹配有问题
新功能：
获取主机可以使用模块类型，获取主机
> Fixed 20180518

- src/framework/api/api.go
- src/framework/common/gorun.go
- src/framework/core/input/input.go
- src/framework/core/input/input_private.go
- src/framework/core/input/private_func.go
> update:修复recover 中调用 fatal 引发进程退出的问题

- src/scene_server/topo_server/topo_service/actions/inst/inst.go
- src/scene_server/topo_server/topo_service/actions/inst/inst_topo.go
- src/scene_server/validator/valid_basic.go
1.  close #407 
2. 修复查询拓扑时对于内置类型处理错误导致查不到数据的问题
> Fixbug 407

- docs/apidoc/host_search.md
- src/scene_server/host_server/host_service/logics/apphost.go
- src/ui/src/pages/hosts/children/status.vue
> Fixed 20180519

- src/scene_server/topo_server/topo_service/actions/inst/inst_topo.go
拓扑关联上下级拓扑查询，增加plat 模型搜索
close #502
> add:增加plat 拓扑查询

- src/common/util/valid.go
- src/scene_server/topo_server/topo_service/actions/object/object.go
1. close #492 
2. 模型导入的错误提示国际化处理
> Fixbug 492

- src/api_server/ccapi/actions/v3/topo/topo.go
- src/scene_server/topo_server/topo_service/actions/object/topo_action.go
> Feature 515 业务拓扑查询增加层级参数

- .travis.yml
- pre-commit.sh
- readme.md
- readme_en.md
- scripts/travis_ci.sh
> add Travis ci config

- src/scene_server/topo_server/topo_service/actions/inst/inst_topo.go
> 屏蔽脏数据对读取拓扑实例的影响

- src/common/paraparse/app.go
- src/scene_server/host_server/host_service/logics/module.go
- src/scene_server/host_server/host_service/logics/set.go
> 修复主机查询中集群、模块条件为字符串的问题

- src/scene_server/host_server/host_service/logics/host_add.go
close #556
1. 优化主机导入代码结构
2. 优化查询导入主机数据，查询方法
> optimization add host code  issue #556

- src/api_server/ccapi/logics/v2/common/converter/converter.go
1. 由于hostserver机构变更，动态分组不展示数据问题
> customergroup return no data   close #573

- src/common/util/getobjIdByobj.go
- src/scene_server/topo_server/topo_service/actions/inst/inst_asst.go
> fixes【cc3.0】关联搜索没有结果

- src/scene_server/topo_server/topo_service/actions/inst/app.go
- src/scene_server/validator/valid_unique.go
> 修复  data status 状态查询

- src/common/basetype/type.go
provide a easy to decode data without using interface.
> add a basic type for cmdb which acts like a buildin type in golang.

- src/scene_server/host_server/host_service/actions/phpapi/host.go
- src/scene_server/host_server/host_service/logics/phpapi/host.go
close #595 
修复克隆主机，未克隆主机模块关系bug， 
cc3.0中兼容api克隆主机接口，只克隆主机属性及模块关系，不克隆主机关联关系   @techfindd
> clone host support issue #595

- src/api_server/ccapi/logics/v2/common/converter/converter.go
-  v2 getAppByUserRole 当用户角色没有数据的时候，返回用户角色对应的数据为空数组
> v2 fixed getappbyuserrole return data struct, issue #603

- resources/language/default/common.json
- resources/language/en/common.json
- src/scene_server/topo_server/topo_service/actions/object/object.go
- src/web_server/application/controllers/object.go
- src/web_server/application/logics/object.go
- 导入模型属性的时候增加分组导入
- 无
- 无
close #562
> Feature 562

- src/scene_server/topo_server/topo_service/actions/inst/inst.go
- 导入实例的时候 提取实例id 后将实例id 删掉
- 无
- 无
> Feature 607

- resources/language/en/host_server.json
- src/scene_server/host_server/host_service/actions/hosts/relation.go
- src/scene_server/host_server/host_service/logics/common.go
- src/scene_server/host_server/host_service/logics/modulehostconfig.go
- xxxx
-  优化主机转移到资源池错误提示
- xxxx
close #615
> optimize host transfer resource pool error prompt

- src/common/metadata/object_controller.go
> 修改通用实例搜索返回的数据结构

- src/framework/api/wrapper_business.go
- src/framework/api/wrapper_module.go
- src/framework/api/wrapper_set.go
- src/framework/core/output/module/inst/inst.go
- src/framework/core/output/module/inst/inst_business.go
- src/framework/core/output/module/inst/inst_module.go
- src/framework/core/output/module/inst/inst_set.go
- src/framework/plugins/example/business_inputer.go
- src/framework/plugins/example/host_inputer.go
- src/framework/plugins/example/model_inputer.go
> 增加获取业务、模块、集群 ID 的方法

- src/framework/api/wrapper_business.go
- src/framework/api/wrapper_module.go
- src/framework/api/wrapper_plat.go
- src/framework/api/wrapper_set.go
> 修改数据返回值，将返回值类型由 int 改为int64 并增加获取实例对应Model 的方法

- src/scene_server/topo_server/topo_service/actions/inst/app.go
> 限制有主机的业务归档

- src/scene_server/host_server/util/gseconfig.go
- src/scene_server/host_server/util/gseconfig_test.go
- src/scene_server/host_server/util/util.go
- xxxx
- update hostserver with new util pkg
- xxxx
> update hostserver with new util pkg

- src/common/RegisterDiscover/zkregdiscv.go
- src/common/backbone/configcenter/cc.go
- src/common/backbone/configcenter/parse.go
- src/scene_server/host_server/app/options/options.go
- src/scene_server/host_server/app/server.go
- src/scene_server/host_server/host.go
- src/source_controller/hostcontroller/host.go
- xxxx
- update host server and backbone about automate configuration.
- xxxx
> update host server and backbone about automate configuration.

- src/scene_server/host_server/logics/app.go
- src/scene_server/host_server/logics/host.go
- src/scene_server/host_server/logics/module.go
- xxxx
- 优化host_server 中GetAppMapByCond及GetModuleMapByCond返回值返回
- 优化主机查询的问题
- xxxx
> Apimachinery fixed bug

- resources/language/default/web.json
- resources/language/en/web.json
- src/web_server/application/logics/excel.go
- src/web_server/application/logics/excel_util.go
-  excel 头部被删除提示
-  excel 智能识别数字类型
- xxxx
close #628 
close #532
> Excel template error tips

- src/scene_server/event_server/event_service/distribution/handle_event.go
- src/scene_server/event_server/event_service/identifier/hostcache.go
- src/scene_server/event_server/event_service/identifier/hostcache_test.go
- src/scene_server/event_server/event_service/identifier/identifier.go
> 主机身份供应商ID位置变更

- src/ui/src/components/common/hostAssociation/host.vue
- src/ui/src/components/object/attribute.vue
- src/ui/src/components/timezone/timezone.vue
- src/ui/src/magicbox/bk-magic/components/button/src/button.vue
- src/ui/src/pages/model/children/field.vue
- src/ui/src/pages/model/model.vue
- 时区默认为上海
- 变更关联参数未清空问题
- 模型属性无法导出
- 批量修改时，没有勾选必填选项，不输入无法修改保存
- 删除模型分类后一直loading
> Bugifx 3.0.8 beta

- src/scene_server/admin_server/fixes_att_id.js
- src/scene_server/admin_server/migrate_service/models/obj_att_desc_data.go
> 修复模型字段ID为0的错误

- src/source_controller/proccontroller/procdata/actions/module.go
- optimization code for api function of module
> optimization code for api function of module

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/scene_server/host_server/host_service/logics/phpapi/host.go
- v2 api getapphostlist 接口返回模块类型
- xxxx
- xxxx
close #680
>  getapphostlist return moduletype    issue #680

- src/common/backbone/backbone.go
- src/common/backbone/configcenter/cc.go
- src/common/backbone/configcenter/parse.go
- src/common/errors/error.go
- src/common/language/language.go
- src/scene_server/topo_server/app/options/options.go
- src/scene_server/topo_server/app/server.go
- src/scene_server/topo_server/service/association.go
- src/scene_server/topo_server/service/auditlog.go
- src/scene_server/topo_server/service/compatiblev2.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/inst_business.go
- src/scene_server/topo_server/service/inst_module.go
- src/scene_server/topo_server/service/inst_set.go
- src/scene_server/topo_server/service/object.go
- src/scene_server/topo_server/service/object_attribute.go
- src/scene_server/topo_server/service/object_classification.go
- src/scene_server/topo_server/service/object_group.go
- src/scene_server/topo_server/service/privilege.go
- src/scene_server/topo_server/service/privilege_group.go
- src/scene_server/topo_server/service/privilege_role.go
- src/scene_server/topo_server/service/service.go
- src/scene_server/topo_server/service/service_initfunc.go
> 修改backbone 的死锁的bug， 修改topo server 启动流程

- docs/overview/framework.md
- src/framework/api/type.go
- src/framework/api/wrapper_host.go
- src/framework/core/output/module/inst/inst_host.go
- 开放主机划分模块时候  设置追加和替换的参数
- 无
- 无
> 开放主机划分模块时候  设置追加和替换的参数

- src/scene_server/datacollection/datacollection/logics/hostsnap.go
- 修复datacollection channel 长时间没消息panic
> fixes nil pointer

- src/scene_server/admin_server/command/command.go
- src/scene_server/admin_server/command/getter.go
- src/scene_server/admin_server/command/import.go
- src/scene_server/admin_server/command/types.go
- src/scene_server/admin_server/migrate_service/actions/clear.go
- src/scene_server/admin_server/migrate_service/upgrader/register.go
- src/scene_server/admin_server/readme.md
> Bluekingbiz upgrade

- docs/apidoc/object_batch.md
- docs/apidoc/object_model_classify.md
> minor: api文档错误修正

- src/web_server/application/middleware/auth/public.go
- src/web_server/application/service/service.go
- 只有管理员具备模型配置权限
- cookie  中携带有权限的业务ID
> only admin have model privilege

- resources/language/default/web.json
- resources/language/en/web.json
- src/web_server/application/controllers/inst.go
- src/web_server/application/controllers/object.go
- src/web_server/application/logics/excel.go
- src/web_server/application/logics/excel_util.go
- src/web_server/application/logics/host.go
- src/web_server/application/logics/inst.go
> fixed import object property bug

- src/scene_server/admin_server/migrate_service/upgrader/v3.0.8/objAttDescData.go
> 统一初始化数字字段结构

- src/scene_server/topo_server/topo_service/actions/object/object.go
- 无
- 无
- 修复导入模型分组的时候处理空字符串的bug
> 修改导入模型分组对分组名的校验

- src/source_controller/common/eventdata/eventutil.go
- src/source_controller/hostcontroller/logics/logics.go
- src/source_controller/hostcontroller/service/host.go
- update code from event
- xxxx
- xxxx
> update code from event.

- src/scene_server/admin_server/migrate_service/upgrader/v3.0.9-beta.1/fixes_supplier_account.go
- src/scene_server/admin_server/migrate_service/upgrader/v3.0.9-beta.1/pkg.go
- src/storage/storage.go
> add default supplier account fields

- src/api_server/app/server.go
- src/api_server/ccapi/ccapi.go
- src/api_server/service/service.go
- src/common/backbone/backbone.go
- src/common/rdapi/rdfunc.go
- src/scene_server/event_server/app/server.go
- src/scene_server/event_server/service/service.go
- src/scene_server/host_server/app/server.go
- src/scene_server/host_server/host_service/ccapi.go
- src/scene_server/host_server/service/service.go
- src/scene_server/proc_server/proc_service/ccapi.go
- src/scene_server/topo_server/app/server.go
- src/scene_server/topo_server/service/service.go
- src/source_controller/hostcontroller/app/server.go
- src/source_controller/hostcontroller/service/service.go
- xxxx
- xxxx
- 修复http  action filter panic 问题
- 修复hostcontroller 服务注册错误问题
> fixed action filter panic question

- src/common/http/httpclient/client.go
- src/framework/api/output_host.go
- src/framework/api/output_model.go
- src/framework/core/output/module/client/clientset.go
- src/framework/core/output/module/client/v3/client.go
- src/framework/core/output/module/client/v3/model.go
- src/framework/core/output/module/inst/inst.go
- src/framework/core/output/module/inst/inst_business.go
- src/framework/core/output/module/inst/inst_host.go
- src/framework/core/output/module/inst/inst_host_transfer.go
- src/framework/core/output/module/inst/inst_module.go
- src/framework/core/output/module/inst/inst_set.go
- src/framework/core/output/module/inst/iterator_host.go
- src/framework/core/output/module/inst/iterator_inst.go
- src/framework/core/output/module/inst/iterator_inst_business.go
- src/framework/core/output/module/inst/iterator_inst_module.go
- src/framework/core/output/module/inst/iterator_inst_set.go
- src/framework/core/output/module/inst/operation.go
- src/framework/core/output/module/model/attribute.go
- src/framework/core/output/module/model/classification.go
- src/framework/core/output/module/model/factory.go
- src/framework/core/output/module/model/group.go
- src/framework/core/output/module/model/iterator_attribute.go
- src/framework/core/output/module/model/iterator_classification.go
- src/framework/core/output/module/model/iterator_group.go
- src/framework/core/output/module/model/iterator_model.go
- src/framework/core/output/module/model/model.go
- src/framework/core/output/module/model/type.go
- src/framework/core/output/output_model.go
- src/framework/core/output/type.go
> 支持多开发商 透传 owner id

- src/ui/src/pages/hosts/hosts.vue
- src/ui/src/pages/resource/resource.vue
> 修复已分配主机判断条件不准确的问题

- resources/configures/datacollection.conf
- scripts/init.py
- src/scene_server/datacollection/datacollection/ccapi.go
> add discover configuration

- src/scene_server/event_server/event_service/actions/subscription/subscription.go
> update subscription action

- src/common/definitions.go
- src/common/rdapi/rdfunc.go
- src/common/util/lib.go
- 产生配置平的request id
- xxxx
- xxxx
> generate http request id

- src/common/eventclient/eventclient.go
- src/common/metadata/hostcontroller.go
- src/common/util/conv.go
- src/scene_server/host_server/logics/agent.go
- src/scene_server/host_server/logics/app.go
- src/scene_server/host_server/logics/host.go
- src/scene_server/host_server/logics/import.go
- src/scene_server/host_server/logics/import_asst.go
- src/scene_server/host_server/logics/instance.go
- src/scene_server/host_server/logics/log.go
- src/scene_server/host_server/logics/module.go
- src/scene_server/host_server/logics/util.go
- src/scene_server/host_server/service/favourite.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/module.go
- src/scene_server/host_server/service/service.go
- src/scene_server/host_server/service/userapi.go
- src/scene_server/host_server/service/usercustom.go
- src/scene_server/validator/valid_unique.go
- src/source_controller/hostcontroller/app/server.go
- src/source_controller/hostcontroller/logics/logics.go
- src/source_controller/hostcontroller/service/host.go
- src/source_controller/hostcontroller/service/service.go
- xxxx
- 新加主机  
- 主机查询  
- 主机详情  
- 转移主机到业务 
- 业务内转移    
- 转移到空闲机 
- 转移到故障机 
- 上交到资源池 
- 主机删除 
- xxxx
> hostserver 主机与模块相关panic及逻辑错误处理

- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/service.go
- xxxx
- 调整hostserver api 顺序
- 批量修改主机panic 问题
> Apimachinery host

- src/scene_server/host_server/service/phpapi.go
- src/scene_server/validator/valid_unique.go
- src/source_controller/hostcontroller/service/favourite.go
> Apimachinery host controller

- src/scene_server/validator/valid_basic.go
> fixed enum valid error

- src/apimachinery/objcontroller/meta/api.go
- src/apimachinery/objcontroller/meta/graphic.go
- src/apimachinery/objcontroller/meta/group.go
- src/apimachinery/objcontroller/privilege/privilege.go
- src/apimachinery/rest/request.go
- src/common/metadata/graphic.go
- src/common/metadata/struct_tags.go
- src/scene_server/topo_server/core/core.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/audit.go
- src/scene_server/topo_server/core/operation/graphics.go
- src/scene_server/topo_server/core/operation/group.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/inst_business.go
- src/scene_server/topo_server/core/operation/inst_module.go
- src/scene_server/topo_server/core/operation/inst_set.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/core/privilege/group.go
- src/scene_server/topo_server/service/auditlog.go
- src/scene_server/topo_server/service/graphics.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/inst_business.go
- src/scene_server/topo_server/service/inst_set.go
- src/scene_server/topo_server/service/object_group.go
- src/scene_server/topo_server/service/privilege_role.go
- src/scene_server/topo_server/service/service.go
- src/scene_server/topo_server/service/service_initfunc.go
- src/scene_server/topo_server/service/types.go
- xxxx
- xxxx
- 完成业务状态测试，graphic 逻辑补充 与测试，权限接口测试
> Dev refine topo

- src/scene_server/proc_server/proc_service/service/proc2module.go
- src/scene_server/proc_server/proc_service/service/procinstance.go
- src/source_controller/proccontroller/app/server.go
- src/source_controller/proccontroller/service/configure.go
- src/source_controller/proccontroller/service/module.go
- src/source_controller/proccontroller/service/procinstance.go
- src/source_controller/proccontroller/service/service.go
- xxxx
- 
- proccontroller接入api machinery 问题修复
> Apimachinery procctl

- src/apimachinery/rest/request.go
- src/scene_server/proc_server/app/options/options.go
- src/scene_server/proc_server/app/server.go
- src/scene_server/proc_server/proc_service/service/openapi.go
- src/scene_server/proc_server/proc_service/service/proc2module.go
- src/scene_server/proc_server/proc_service/service/procdetail.go
- src/scene_server/proc_server/proc_service/service/process.go
- src/scene_server/proc_server/proc_service/service/procinstance.go
- src/scene_server/proc_server/proc_service/service/proconf.go
- src/scene_server/proc_server/proc_service/service/service.go
- src/scene_server/proc_server/process.go
- src/source_controller/proccontroller/app/server.go
- src/source_controller/proccontroller/service/configure.go
- src/source_controller/proccontroller/service/module.go
- src/source_controller/proccontroller/service/procinstance.go
- src/source_controller/proccontroller/service/service.go
- xxxx
- procserver 接入apimachinery 进程curl修改
- xxxx
> Apimachinery proc

- src/scene_server/host_server/service/module.go
- src/scene_server/host_server/util/util.go
- src/scene_server/proc_server/proc_service/service/procinstance.go
- xxxx
- 跨业务转移主机接入api machinery
- xxxx
> Apimachinery multiple host

- src/api_server/service/v3/service.go
- xxxx
- update api server with proxy error.
- xxxx
> update api server with proxy error.

- src/common/metadata/querycondition_test.go
- src/scene_server/host_server/logics/import.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/module.go
- xxxx
- 新加日志记录
- 修复新加主机没有日志及关系问题
> Apimachinery add logic

- src/scene_server/datacollection/app/server.go
- src/scene_server/datacollection/datacollection.go
- src/scene_server/datacollection/datacollection/datacollection.go
- src/scene_server/datacollection/datacollection/hostsnap.go
- src/source_controller/objectcontroller/objectdata/actions/instdata/object_action.go
- datacollection apimachinary 改造
> datacollection apimachinary 改造

- src/common/definitions.go
- src/scene_server/admin_server/command/getter.go
- src/scene_server/admin_server/command/import.go
- src/scene_server/datacollection/datacollection/const.go
- src/scene_server/datacollection/datacollection/hostsnap.go
- src/source_controller/common/eventdata/eventutil.go
- src/source_controller/hostcontroller/logics/object.go
- src/source_controller/hostcontroller/service/host.go
- src/source_controller/objectcontroller/objectdata/actions/openapi/set.go
- src/source_controller/proccontroller/app/server.go
- src/source_controller/proccontroller/service/configure.go
- src/source_controller/proccontroller/service/module.go
- src/source_controller/proccontroller/service/service.go
> Apimachinery dong

- src/apimachinery/clientset.go
- src/apimachinery/healthz/healthz.go
- src/apimachinery/rest/request.go
- src/common/backbone/backbone.go
- src/scene_server/host_server/service/service.go
- add healthz in apimachinery, and add healthz in host server.
- xxxx
- xxxx
> add healthz in apimachinery, and add healthz in host server.

- src/common/types/serverInfo.go
- src/scene_server/admin_server/service/service.go
- src/scene_server/datacollection/service/service.go
- src/scene_server/event_server/service/service.go
- 添加healthz接口到datacollection,adminserver,eventserver
> add healthz interface

- src/source_controller/objectcontroller/objectdata/actions/identifier/identifier.go
> support search hostidentifier by bk_cloud_id

- src/scene_server/topo_server/core/operation/inst_module.go
- src/scene_server/topo_server/core/operation/inst_set.go
- src/scene_server/topo_server/service/service.go
- xxxx
- xxxx
- 去掉自动设置create_time 的操作
> 取消设置 create_time 字段

- src/api_server/ccapi/logics/v2/fileds.go
- src/api_server/ccapi/logics/v2/topo.go
- src/api_server/service/set.go
- src/apimachinery/toposerver/object/action.go
- src/apimachinery/toposerver/object/api.go
- src/common/metadata/toposerver.go
- src/scene_server/topo_server/service/service.go
- 
- v2 createset api 不支持多级拓扑新加集群
- xxxx
> Apimachinery newfunc apiserver

- src/api_server/service/set.go
- src/common/metadata/hostserver.go
- src/scene_server/host_server/logics/import.go
- src/scene_server/host_server/logics/phpapi_host.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/module.go
- src/scene_server/host_server/service/service.go
- api machinery 新加同步主机的功能
- xxxx
- xxxx
> add host sync api  in host server

- src/ui/src/components/relevance/topo.vue
- src/ui/src/pages/model/children/field.vue
>  bugfix: 接口地址调整

- src/api_server/app/server.go
- src/api_server/service/v3/service.go
- src/common/definitions.go
- src/common/rdapi/rdfunc.go
- src/scene_server/host_server/service/service.go
- src/scene_server/proc_server/proc_service/service/service.go
- src/source_controller/auditcontroller/service/service.go
- src/source_controller/proccontroller/service/service.go
- 新加healthz 健康检查接口
- 删除全局filter 对于服务的状态检查
- xxxx
> Apimachinery apiserver metric

- src/api_server/service/v3/service.go
- src/scene_server/host_server/service/service.go
- src/scene_server/host_server/service/usercustom.go
- src/source_controller/auditcontroller/service/search.go
- src/web_server/application/logics/excel.go
- src/web_server/application/logics/fields.go
- xxxx
- xxxx
- 修复导出模版没有头部
- 修复审核日志无内容
> Apimachinery fixed 0723.17

- src/scene_server/host_server/service/service.go
> change url path

- scripts/Makefile
- scripts/template.sh.restart
- scripts/template.sh.start
- src/api_server/service/v3/service.go
- src/api_server/service/v3/uri.go
- src/common/backbone/configcenter/cc.go
- src/common/rdapi/rdfunc.go
- src/common/util/lib.go
> fix event api 404 error

- src/common/mapping.go
- src/common/metadata/common.go
- src/scene_server/topo_server/core/operation/audit.go
- src/source_controller/objectcontroller/service/common.go
- src/source_controller/objectcontroller/service/identifier.go
- src/source_controller/objectcontroller/service/inst_action.go
- src/source_controller/objectcontroller/service/object_action.go
- src/source_controller/objectcontroller/service/objectasst_action.go
- src/source_controller/objectcontroller/service/objectatt_action.go
- src/source_controller/objectcontroller/service/objectatt_group_action.go
- src/source_controller/objectcontroller/service/objectcls_action.go
- src/source_controller/objectcontroller/service/set.go
- xxxx
- 去掉对本地common 的依赖
- xxxx
> 去除controller 对source 下面common

- src/scene_server/topo_server/service/service.go
> 去掉对老APIResonse的引用

- src/scene_server/topo_server/core/model/attribute.go
- src/scene_server/topo_server/service/inst.go
- src/source_controller/objectcontroller/service/common.go
- xxxx
- xxxx
- 修改关联查询返回的数据 结构
> 修改查询关联拓扑的返回数据结构

- src/scene_server/topo_server/core/inst/inst.go
- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- src/scene_server/topo_server/core/operation/association_mainline_object.go
- src/scene_server/topo_server/core/operation/supplementary_validator.go
- src/scene_server/topo_server/service/service.go
- xxxx
- xxxx
- 增加主线模型删除后对应实例重名校验
> 增加主线模型删除后对应实例重名校验

- src/scene_server/topo_server/core/core.go
- src/scene_server/topo_server/core/operation/attribute.go
- src/scene_server/topo_server/service/object_attribute.go
- xxxx
- xxxx
- 修改读取模型属性时丢失关联字段的bug
> 修改读取模型属性时丢失关联字段的bug

- src/scene_server/host_server/logics/phpapi.go
- src/scene_server/host_server/service/phpapi.go
- src/scene_server/host_server/service/service.go
- 新加 getHostListByAppidAndField api
- xxxx
- xxxx
>  add getHostListByAppidAndField api

- src/scene_server/host_server/service/service.go
>  change getHostListByAppidAndField api http mothod

- src/scene_server/host_server/logics/import.go
- src/scene_server/host_server/logics/import_asst.go
- src/scene_server/host_server/logics/phpapi_host.go
- src/scene_server/host_server/service/host.go
> Apimachinery logic 20180726

- src/common/mapstr/mapstr.go
- src/common/metadata/association.go
- src/scene_server/topo_server/core/inst/association.go
- src/scene_server/topo_server/core/inst/inst.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/attribute.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/types.go
- xxxx
- xxxx
- 关联实例拓扑查询时候兼容老的通过字段存储的方式
> 关联实例拓扑查询时候兼容老的通过字段存储的方式

- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- src/scene_server/topo_server/core/operation/association_mainline_object.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/core/operation/supplementary_validator.go
- src/scene_server/topo_server/service/inst.go
- xxxx
- xxxx
- 修复创建主线及通过模型查询实例的bug
> 修复创建主线及通过模型查询实例的bug

- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/inst_business.go
- src/scene_server/topo_server/core/operation/supplementary_validator.go
- src/scene_server/topo_server/service/inst_business.go
- src/scene_server/validator/valid_unique.go
- xxxx
- xxxx
- 创建业务增加 supplier id 字段，屏蔽更新业务状态无效的body 数据
> 创建业务增加 supplier id 字段，屏蔽更新业务状态无效的body 数据

- src/common/metadata/privilege.go
- src/scene_server/topo_server/core/privilege/privilege.go
- src/source_controller/objectcontroller/service/privilege_action.go
> 修改权限返回的结构的bug

- src/apimachinery/rest/request.go
- src/scene_server/host_server/service/userapi.go
- src/scene_server/host_server/service/usercustom.go
- src/source_controller/hostcontroller/service/user.go
- xxxx
- http 返回不是json，在日志中记录
- 修复userapi 更新失败bug
> 修复userapi 更新失败bug

- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/inst.go
- xxxx
- xxxx
- 修改判断关联关系错误的bug
> 修改归档业务判断关联关系错误的bug

- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/service/inst_business.go
- 修复查询模型拓扑时返回的箭头方向不正确的问题
- 修改业务查询接口处理查询条件转义的bug
> 【fixbug】吸附物查询模型拓扑结构与业务查询条件处理的bug

- src/txnframe/server/lock/redislock/lib.go
- src/txnframe/server/lock/redislock/lock.go
- src/txnframe/server/lock/redislock/lock_test.go
- src/txnframe/server/lock/redislock/util.go
- 锁的补偿机制
- 锁的补偿机制部分测试代码
- xxxx
- xxxx
> Compensation

- src/txnframe/dal/dal.go
- src/txnframe/dal/mongodb/collection.go
- src/txnframe/dal/type.go
> commit dal

- src/common/metadata/hostcontroller.go
- src/source_controller/hostcontroller/service/user.go
- src/storage/mgoclient/mgo.go
- xxxx
- xxxx
- 修复自定义api 数据缺少字段
> 修复自定义api 数据缺少字段。

- src/common/util/lib.go
- src/common/util/struti.go
- src/scene_server/host_server/service/service.go
- xxxx
- 修改删除主机接口地址
- 修复按照时间查询，由于时区转换错误引起的问题
close #866
> 修复按照时间查询，由于时区转换错误引起的问题

- src/scene_server/validator/util.go
> bool type variable default  false

- src/scene_server/host_server/logics/phpapi_host.go
- xxxx
- xxxx
- 修复v2没有关联关系的bug
> fixed handle assocate fields

- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/supplementary_audit.go
- src/scene_server/topo_server/service/inst_business.go
- xxxx
- xxxx
- 导入实例增加设置实例关系表的逻辑
- 修改操作审计日志数据记录错误的bug
> 【fixbug】修改导入实例与操作审计日志的bug

- src/txnframe/server/mongobyc/bson.go
- src/txnframe/server/mongobyc/client.go
- src/txnframe/server/mongobyc/collection.go
- src/txnframe/server/mongobyc/collection_test.go
- src/txnframe/server/mongobyc/config.go
- src/txnframe/server/mongobyc/convert.go
- src/txnframe/server/mongobyc/cpkgconfig.go
- src/txnframe/server/mongobyc/findopt/opts.go
- src/txnframe/server/mongobyc/insertopt/opts.go
- src/txnframe/server/mongobyc/mongo.c
- src/txnframe/server/mongobyc/mongo.h
- src/txnframe/server/mongobyc/results.go
- src/txnframe/server/mongobyc/transaction.go
>  finish CRUD methods

- src/txnframe/mongobyc/client.go
- src/txnframe/mongobyc/collection.go
- src/txnframe/mongobyc/collection_test.go
- src/txnframe/mongobyc/convert.go
- src/txnframe/mongobyc/findopt/opts.go
- src/txnframe/mongobyc/mongo.c
- src/txnframe/mongobyc/mongo.h
- src/txnframe/mongobyc/results.go
- src/txnframe/mongobyc/type.go
> 修改查询接口 增加option 参数

- src/txnframe/mongobyc/client.go
- src/txnframe/mongobyc/client_pool.go
- src/txnframe/mongobyc/client_pool_test.go
- src/txnframe/mongobyc/collection.go
- src/txnframe/mongobyc/collection_test.go
- src/txnframe/mongobyc/database.go
- src/txnframe/mongobyc/database_test.go
- src/txnframe/mongobyc/deleteopt/opts.go
- src/txnframe/mongobyc/replaceopt/opts.go
- src/txnframe/mongobyc/results.go
- src/txnframe/mongobyc/updateopt/opts.go
> 修改mongobyc 接口

- src/txnframe/mongobyc/client.go
- src/txnframe/mongobyc/client_pool_test.go
- src/txnframe/mongobyc/collection.go
- src/txnframe/mongobyc/collection_test.go
- src/txnframe/mongobyc/results.go
- src/txnframe/mongobyc/transaction_test.go
- 增加delete 和update 的返回值 修改Session 操作的方法
> 增加delete 和update 的返回值 修改Session 操作的方法

- src/txnframe/mongobyc/collection.go
- src/txnframe/mongobyc/collection_test.go
- src/txnframe/mongobyc/convert.go
> 修改查询字段的设置 及数据转换的bug

- src/txnframe/mongobyc/collection_test.go
- src/txnframe/mongobyc/convert.go
>  增加对Nil map 的判断

- src/common/util/lib.go
- src/storage/dal/filter.go
- src/storage/dal/mongo/local_mongo.go
- src/storage/dal/mongo/rpc_mongo.go
- src/storage/dal/rdb.go
- src/storage/mongobyc/convert.go
- src/storage/rpc/client.go
- src/storage/rpc/server.go
- src/storage/rpc/types.go
- src/storage/server/manager/txn_manager.go
- mv types.Filter to dal.Filter
>  mv types.Filter to dal.Filter

- src/common/definitions.go
- src/scene_server/topo_server/core/operation/classification.go
- 修改短字符长度上线为 256 ，长字符上线为2000
- 删除分类主动探测分类下是否包含模型
> Fixbug topo 08

- src/common/definitions.go
- src/scene_server/topo_server/core/operation/classification.go
> 从Master 同步代码

- src/common/definitions.go
- src/storage/dal/mongo/local_mongo.go
- src/storage/dal/mongo/rpc_mongo.go
- src/storage/dal/mongo/rpc_mongo_test.go
- src/storage/dal/rdb.go
- src/storage/rpc/readme.md
- src/storage/rpc/server.go
- src/storage/rpc/types.go
- src/storage/server/app/options/options.go
- src/storage/server/app/server.go
- src/storage/server/manager/txn_manager.go
- src/storage/server/service/txn.go
- src/storage/types/types.go
> 根据code review 修改代码TM

- src/source_controller/auditcontroller/app/server.go
- src/source_controller/hostcontroller/app/server.go
- src/source_controller/objectcontroller/app/server.go
- src/source_controller/proccontroller/service/service.go
> 修复数据库用户配置映射错误

- src/storage/dal/redis/redis.go
> 添加redis client

- src/storage/dal/mongo/mgo_mongo.go
- src/storage/dal/mongo/mgo_mongo_test.go
- src/storage/dal/mongo/rpc_mongo.go
- src/storage/dal/rdb.go
- src/storage/rpc/client.go
- src/storage/rpc/server.go
- src/storage/rpc/stream_test.go
- src/storage/rpc/types.go
- src/storage/rpc/wire.go
- add IsDuplicatedError && IsNotFoundError interface
>  add IsDuplicatedError && IsNotFoundError interface

- src/scene_server/proc_server/proc_service/service/process.go
> fixed process audit log type error

- src/scene_server/host_server/host_service/actions/userapi/userapi.go
- src/source_controller/api/userapi/userapi_create.go
- xxxx
- xxxx
- 解决userapi 供应商为空的问题
> 解决userapi 没有透传http header 的问题

- src/ui/src/components/header/header-v3.vue
> update: 修复最近浏览更新不正确的问题

- src/ui/src/pages/customQuery/children/define.vue
> Bugfix：自定义查询关联类型不能正常显示

- src/api_server/ccapi/logics/v2/common/converter/converter.go
> change app language key

- src/scene_server/proc_server/proc_service/service/proc2module.go
- src/scene_server/proc_server/proc_service/service/process.go
- src/scene_server/validator/valid_basic.go
- 进程绑定和解绑无日志
- 查询进程无分页参数查询错误
- 校验模块对数字最大值最小值校验错误
> resolve review problems

- src/storage/rpc/client.go
- src/storage/rpc/client_test.go
- src/storage/rpc/server.go
- src/storage/rpc/stream_test.go
- src/storage/rpc/types.go
- src/storage/rpc/wire.go
- src/storage/server/service/rdb_executor.go
- src/storage/server/service/txn.go
> rpc 支持steaming

- src/source_controller/objectcontroller/service/objectcls_action.go
- src/source_controller/objectcontroller/service/process.go
> 修复包引用错误的bug

- src/scene_server/topo_server/core/inst/association.go
- src/scene_server/topo_server/core/operation/inst.go
> 修复删除实例监测主机异常的bug

- src/scene_server/topo_server/core/operation/inst_module.go
- src/scene_server/topo_server/core/operation/inst_set.go
> 修复模块和集群default 字段被覆盖的问题

- src/common/metadata/hostcontroller.go
- src/scene_server/host_server/host.go
- src/source_controller/auditcontroller/app/options/options.go
- src/source_controller/auditcontroller/app/server.go
- src/source_controller/auditcontroller/logics/audit.go
- src/source_controller/auditcontroller/logics/logics.go
- src/source_controller/auditcontroller/service/host.go
- src/source_controller/auditcontroller/service/object.go
- src/source_controller/auditcontroller/service/search.go
- src/source_controller/auditcontroller/service/service.go
- src/source_controller/auditcontroller/service/topology.go
- src/source_controller/hostcontroller/app/options/options.go
- src/source_controller/hostcontroller/app/server.go
- src/source_controller/hostcontroller/logics/logics.go
- src/source_controller/hostcontroller/logics/object.go
- src/source_controller/hostcontroller/service/favourite.go
- src/source_controller/hostcontroller/service/history.go
- src/source_controller/hostcontroller/service/host.go
- src/source_controller/hostcontroller/service/service.go
- src/source_controller/hostcontroller/service/user.go
- xxxx
- 修改使用底层的mongodb 
- xxxx
> audit, host 替换storage

- scripts/upgrade.sh
- src/common/blog/blog.go
- src/common/metadata/inst.go
- src/common/metadata/procserver.go
- src/scene_server/event_server/identifier/hostcache.go
- src/scene_server/event_server/identifier/identifier.go
- src/source_controller/objectcontroller/service/identifier.go
- vendor/github.com/golang/glog/glog.go
> 主机身份添加进程信息

- src/scene_server/topo_server/core/operation/identifier.go
- src/scene_server/topo_server/service/identifier.go
> 解决主机身份分页问题

- src/scene_server/datacollection/app/server.go
> 修复mastername配置缺失问题

- scripts/init.py
- src/common/definitions.go
- src/common/eventclient/eventclient.go
- src/common/metadata/eventserver.go
- src/common/util/lib.go
- src/storage/dal/mongo/mgo_mongo.go
- src/storage/dal/mongo/mgo_mongo_test.go
- src/storage/dal/mongo/rpc_mongo.go
- src/storage/dal/mongo/rpc_mongo_test.go
- src/storage/dal/rdb.go
- src/storage/dal/redis/redis.go
> 解决sort为空串时panic问题

- src/scene_server/proc_server/proc_service/service/process.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/inst_business.go
- src/scene_server/topo_server/service/inst_module.go
- src/scene_server/topo_server/service/inst_set.go
> 修改searchparams 初始化的bug

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/api_server/ccapi/logics/v2/topo.go
- src/api_server/service/application.go
- src/api_server/service/search.go
- 修复v2 业务查询、拓扑查询
- 修复v2 更新业务属性
> 修复v2 api系列问题

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/api_server/service/userapi.go
- xxxx
-  动态分组没有数据的时候，返回空数组而不是null
- 使用version=1参数获取动态分组结果，提示404的
- GetHostAppByCompanyId 接口主机属于多模块，无数据返回
> Fixed userapi

- src/apimachinery/rest/request.go
- xxxx
- http 状态允许使用非200的值
- xxxx
> allow http status not 200

- src/scene_server/admin_server/command/import.go
- src/scene_server/admin_server/upgrader/register.go
- src/scene_server/admin_server/upgrader/util.go
- src/storage/dal/filter.go
> 解决admin初始化问题

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/apimachinery/objcontroller/openapi/api.go
- src/apimachinery/objcontroller/openapi/openapi.go
- src/common/metadata/procserver.go
- src/scene_server/proc_server/proc_service/service/openapi.go
- xxxx
- xxxx
- 修复v2版本进程返回格式错误的问题
> 修复v2版本进程返回格式错误的问题

- resources/language/default/web.json
- resources/language/en/web.json
- src/web_server/application/controllers/host.go
- src/web_server/application/controllers/inst.go
- src/web_server/application/controllers/object.go
- src/web_server/application/logics/excel.go
- src/web_server/application/logics/excel_util.go
- src/web_server/application/logics/host.go
- src/web_server/application/logics/inst.go
- xxxx
- 导入数据支持数字到字符串的自动转换
- xxxx
> 导入数据支持数字到字符串的自动转换

- src/common/metadata/hostserver.go
- src/scene_server/host_server/service/host.go
> change addhostfromagent params

- src/scene_server/topo_server/service/identifier.go
> 修复identify接口返回多了一层数据的问题

- src/scene_server/proc_server/proc_service/service/procdetail.go
> 修复proc_server 编译问题

- src/ui/src/api/axios.js
- src/ui/src/store/modules/common.js
> feature: api base url protocol detect

- src/common/mapstr/mapstr.go
- src/scene_server/topo_server/core/inst/inst.go
- src/scene_server/topo_server/core/operation/inst.go
> 解决编译通不过的问题

- src/ui/src/api/axios.js
- src/ui/src/store/modules/common.js
> update: API prefix使用页面地址

- src/ui/src/store/modules/common.js
> bugfix: 修复人员列表API地址错误的问题

- src/source_controller/hostcontroller/logics/object.go
- xxxx
- xxxx
- 修复调用hostcontroller painc 问题
> fixed panic query host

- src/source_controller/auditcontroller/app/server.go
- src/source_controller/hostcontroller/app/server.go
- src/source_controller/hostcontroller/logics/object.go
- src/source_controller/hostcontroller/service/service.go
- src/source_controller/hostcontroller/service/user.go
> fixed db instance

- src/common/condition/condition.go
- src/scene_server/proc_server/proc_service/service/process.go
- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/inst_business.go
- src/scene_server/topo_server/core/operation/inst_module.go
- src/scene_server/topo_server/core/operation/inst_set.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/inst_business.go
- src/scene_server/topo_server/service/inst_module.go
- src/scene_server/topo_server/service/inst_set.go
- 修改SearchParam 的未初始化的bug
- 修改由于合并代码包引起的包引用错误
- 查询业务，分页查询不生效 
- 业务下拥有 主机的时候，删除主线模型时会提示“有主机不允许删除”
> Fixbug 修复一系列的bug

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- xxxx
- xxxx
-  host/getapphostlist  接口 将NULL 转化为空字符串
close #982
> apiserver  host/getapphostlist  接口 将NULL 转化为空字符串

- src/scene_server/host_server/service/userapi.go
- xxxx
- xxxx
- 动态分组返回其他业务的数据
close #990
> 动态分组返回其他业务的数据

- src/scene_server/host_server/host_service/actions/hosts/relation.go
- xxxx
- xxxx
- 修复多主机转移到空闲机或者故障机未删除原有模块的问题
> batch move host to default module, not delete old module

- src/scene_server/topo_server/core/inst/inst.go
- src/scene_server/topo_server/core/model/object.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/core/operation/supplementary_audit.go
- src/scene_server/topo_server/service/object_attribute.go
> fixbug close #998 模型属性字段管理会导出内建字段，需要屏蔽

- src/source_controller/objectcontroller/service/group_action_test.go
- src/source_controller/objectcontroller/service/mock.go
> add restful service test method

- src/framework/core/output/module/client/v3/inst_business.go
- src/framework/core/output/module/client/v3/inst_business_test.go
- src/framework/core/output/module/inst/inst_plat_factory.go
> fixbug 修改framework 的接口

- scripts/gotest.sh
- src/source_controller/objectcontroller/service/group_action_test.go
> add go test script

- src/scene_server/host_server/logics/instance.go
- xxxx
- xxxx
- 删除主机关联字段值后，主机查询失败
> 删除主机关联字段值后，主机查询失败

- src/ui/src/components/slider/sideslider.vue
- src/ui/src/magicbox/bk-magic/components/date-range/src/date-picker.vue
- 修复侧滑UI标题溢出的问题
- 修复magicbox日期范围组组件'今天'计算不正确的问题
> Bugfix 0.0.56

- src/ui/src/pages/auditing/auditing.vue
- src/ui/src/pages/model/children/baseInfo.vue
- src/ui/src/pages/model/children/other.vue
> minor：修改错误提示

- src/scene_server/topo_server/core/model/attribute.go
- src/scene_server/topo_server/core/model/object.go
- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- src/scene_server/topo_server/core/operation/association_mainline_object.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/service/object.go
- 主线模型增加一定的异常处理能力，不至于导致所有业务拓扑异常。
> fixbug close #1019 对一些导致拓扑结构异常的情况做处理，尽量保障数据能恢复

- src/ui/src/components/filter/filter.vue
> feature: 隐藏主机查询历史功能

- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/x08.09.07.01/create_table_netcollect.go
- src/scene_server/admin_server/upgrader/x08.09.07.01/pkg.go
- upgrader 新增 x08.09.07.01 版本
- xxxx
- xxxx
> new upgrader version x08.09.07.01

- src/api_server/service/host.go
- xxxx
- xxxx
- v2 /host/updatehostmodule 转移主机到多个模块的失败 
close  #1024
> v2 /host/updatehostmodule 转移主机到多个模块的失败 

- src/scene_server/host_server/logics/host.go
- src/scene_server/host_server/logics/object.go
- src/scene_server/proc_server/proc_service/service/process.go
- src/web_server/application/middleware/auth/public.go
- src/web_server/application/middleware/types/types.go
- 主机查询返回重复的业务、集群、模块信息
- 主机查询中查到空闲机的信息
- 修复查询关联权限
> fix host query return dup data

- src/common/blog/blog_test.go
- src/common/condition/condition_test.go
- src/common/errors/defaultError_test.go
- src/common/errors/error_test.go
- src/common/eventclient/eventclient_test.go
- src/common/metadata/inst_test.go
- src/common/util/array_test.go
- src/common/util/conv_test.go
- src/common/util/lib_test.go
- src/common/util/ownerutil_test.go
- src/common/util/parseinterface_test.go
- src/common/util/valid_test.go
common通用库增加单元测试用例。
使用gotest.sh统计common覆盖率53.8%， 整体28.1%
> add testcase for common

- src/scene_server/topo_server/core/operation/attribute.go
- src/scene_server/topo_server/core/operation/object.go
- 禁止导入bk_childid or bk_parent_id
> 禁止导入bk_childid or bk_parent_id

- src/scene_server/host_server/logics/object.go
> commit host query with no default module

- src/scene_server/host_server/service/host.go
- xxxx
- 修复http 返回不是json的问题
- xxxx
> 修复http 返回不是json的问题

- src/scene_server/admin_server/upgrader/x08.09.13.01/pkg.go
- src/scene_server/admin_server/upgrader/x08.09.13.01/upgrader.go
- src/storage/mgoclient/mgo.go
- src/storage/redisclient/redis.go
- src/storage/storage.go
> cc_OperationLog 添加索引

- src/scene_server/admin_server/upgrader/x08.09.13.01/upgrader.go
> 解决索引添加失败问题

- src/scene_server/admin_server/upgrader/x08.09.13.01/pkg.go
- src/scene_server/admin_server/upgrader/x08.09.13.01/upgrader.go
- xxxx
- xxxx
- 删除cc_UserGroupPrivilege表重复数据
> 删除cc_UserGroupPrivilege表重复数据

- src/scene_server/host_server/service/userapi.go
- xxxx
- xxxx
- 修复动态分组不存在时，panic 问题
close #1056
> 修复动态分组不存在时，panic 问题

- src/api_server/service/host.go
- src/common/metadata/hostserver.go
- src/common/metadata/phpapi.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/phpapi.go
- xxxx
- xxxx
- 修复克隆主机参数提示错误问题
> 修复克隆主机参数提示错误问题

- src/common/tablenames.go
- src/scene_server/admin_server/upgrader/x08.09.17.01/create_table_netcollect.go
- src/scene_server/admin_server/upgrader/x08.09.17.01/pkg.go
- 增加 upgrader 版本号 x08.09.17.01
- xxxx
- xxxx
> add upgrader version x08.09.17.01

- src/scene_server/event_server/service/subscription.go
>  事件订阅的创建接口支持upsert

- src/scene_server/admin_server/upgrader/x08.09.18.01/pkg.go
- src/scene_server/admin_server/upgrader/x08.09.18.01/upgrader.go
- src/scene_server/host_server/logics/host.go
- xxxx
- xxxx
- 修复v2版本API新加主机，没有新加关联关系的bug
> 修复v2版本API新加主机，没有新加关联关系的bug

- src/scene_server/admin_server/upgrader/x08.09.13.01/upgrader.go
- src/source_controller/objectcontroller/app/server.go
- src/storage/dal/mongo/mgo_mongo.go
- src/storage/dal/mongo/mock_mongo.go
- src/storage/dal/mongo/mongo.go
- src/storage/dal/mongo/rpc_mongo.go
- src/storage/dal/rdb.go
> 实现Indexes接口

- src/ui/src/pages/customQuery/children/define.vue
- src/ui/src/pages/eventpush/children/pop.vue
>  bugfix: 事件推送错误提示显示不一致

- src/scene_server/topo_server/core/operation/association.go
> 修改校验关联关系是否存在条件错误的问题

- src/common/metadata/datacollection.go
- src/scene_server/datacollection/logics/device.go
- src/scene_server/datacollection/service/device.go
- 增加 根据条件搜索设备 的功能
- xxxx
- xxxx
> add search net device

- src/ui/src/components/relevance/topo.vue
> update: update topo supplier account

- src/scene_server/topo_server/core/operation/association.go
- src/ui/src/components/relevance/topo.vue
> merge from master

- src/common/metadata/datacollection.go
- src/scene_server/datacollection/logics/device.go
- src/scene_server/datacollection/service/device.go
> add function of  delete device

- src/common/metadata/webserver.go
- src/web_server/application/controllers/login.go
- src/web_server/application/controllers/user.go
- src/web_server/application/middleware/login.go
>  optinization user logout  issue #1102

- src/ui/src/api/axios.js
- src/ui/src/components/header/header-v3.vue
- src/ui/src/main.js
> update: change API login stauts check

- src/scene_server/admin_server/upgrader/x08.09.19.01/upgrader.go
- xxxx
- 调整java 大小写 #1132
- xxxx
close #1132
> 调整java 大小写 #1132

- src/common/definitions.go
- src/common/metadata/webserver.go
- src/web_server/application/controllers/login.go
- src/web_server/application/middleware/user/plugins/method/self/userinfo.go
- src/web_server/application/middleware/user/public.go
- xxxx
- 支持用户在HTTP，HTTPS状态下推出
- xxxx
> 优化用户注销 issue #1102

- src/common/definitions.go
- src/scene_server/datacollection/datacollection/hostsnap.go
- 主机自动发现docker版本
- xxxx
- xxxx
> 主机自动发现docker版本  issue #1143

- src/thirdpartyclient/esbserver/esb.go
- src/thirdpartyclient/esbserver/esbutil/common.go
- src/thirdpartyclient/esbserver/esbutil/esbdiscovery.go
- src/thirdpartyclient/esbserver/gse/api.go
- src/thirdpartyclient/esbserver/gse/esbserv.go
- 新加调用esb sdk 类库
- xxxx
- xxxx
> 新加调用esb sdk 类库

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- src/api_server/ccapi/logics/v2/search.go
- src/api_server/ccapi/logics/v2/topo.go
- src/api_server/service/application.go
- src/api_server/service/host.go
- src/api_server/service/search.go
- src/api_server/service/searchext.go
- src/api_server/service/service.go
- 【v2兼容接口】支持根据供应商获取主机信息接口
- 【v2兼容接口】支持根据供应商获取业务信息接口
- 【v2兼容接口】支持获取主机硬件数据接口
- xxxx
- xxxx
> 【v2兼容接口】新加根据供应商获取主机，业务信息接口

- src/common/definitions.go
- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/x18.09.30.01/pkg.go
- src/scene_server/admin_server/upgrader/x18.09.30.01/upgrader.go
> 解决重复的直连区域问题

- src/common/metadata/datacollection.go
- src/common/metadata/netdevice.go
- src/scene_server/datacollection/logics/device.go
- src/scene_server/datacollection/logics/property.go
- src/scene_server/datacollection/service/device.go
- src/scene_server/datacollection/service/property.go
- src/scene_server/datacollection/service/service.go
- 更改网络设备和设备属性的删除方式，把“单个元素的删除”更改为“可删除多个元素”；
- xxxx
- xxxx
> Delete multiple net devices and propertys

- src/scene_server/datacollection/logics/property.go
- src/web_server/application/controllers/netproperty.go
- xxxx
- xxxx
- 增加关键字之间的分隔符
- 增加导入属性的重构reponse body
> Fix net property

- src/scene_server/datacollection/logics/device.go
- src/scene_server/datacollection/logics/property.go
- xxxx
- xxxx
- 修复获取 device 缺少 obj_name 字段
> add obj name show device #1077

- src/common/metadata/netdevice.go
- src/scene_server/datacollection/logics/common.go
- src/scene_server/datacollection/logics/device.go
- src/scene_server/datacollection/logics/property.go
- src/web_server/application/controllers/netproperty.go
- xxxx
- xxxx
- 修复网络设备属性重复数据更新的问题
- 修复网络设备展示的字段
- 修复导入设备属性解析返回 body 两次
- 调整 ptheader 到函数参数的第一位
> 修复设备管理和属性管理的问题

- src/api_server/service/v3/service.go
- src/common/rdapi/rdfunc.go
- src/scene_server/host_server/logics/phpapi.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/phpapi.go
- src/scene_server/host_server/service/userapi.go
- src/source_controller/auditcontroller/service/host.go
- src/source_controller/auditcontroller/service/object.go
- src/source_controller/auditcontroller/service/search.go
- src/source_controller/auditcontroller/service/topology.go
- src/source_controller/hostcontroller/service/hostlock.go
- src/source_controller/hostcontroller/service/user.go
- src/web_server/application/controllers/host.go
- src/web_server/application/controllers/inst.go
- src/web_server/application/controllers/object.go
> 修复http 状态码

- src/ui/README.md
> update: update ui readme.md

- src/common/metadata/association.go
- src/scene_server/topo_server/core/operation/inst.go
- 实例拓扑查询结果增加关联名 与关联字段
close  #1176
> 实例拓扑查询结果增加关联名 与关联字段

- src/scene_server/topo_server/core/operation/inst_business.go
- src/web_server/application/middleware/login.go
- src/web_server/application/middleware/user/owner.go
- src/web_server/application/middleware/user/public.go
> 解决多开发商登录没有复制默认关联关系问题

- src/apimachinery/util/client.go
- src/scene_server/host_server/logics/host.go
- src/storage/mgoclient/mgo.go
- xxxx
- 修改http client 超时时间
- 设置mongodb 查询 超时时间
- 主机查询panic问题
> 修改http client 及mongodb 查询 超时时间

- src/source_controller/proccontroller/service/module.go
- 修改proccontroller 入参未设置引用的bug
> 修改proccontroller 入参未设置引用的bug

- scripts/upgrade.sh
- src/scene_server/admin_server/upgrader/x18.09.30.01/upgrader.go
- upgrade.sh 用 readlink 替代 realpath，以增强兼容性
> upgrade.sh 用 readlink 替代 realpath，以增强兼容性

- src/ui/package.json
- src/ui/src/assets/scss/common.scss
- src/ui/src/components/hosts/filter/_filter.vue
- src/ui/src/components/hosts/filter/index.vue
- src/ui/src/components/layout/header.vue
- src/ui/src/components/ui/tree/_tree-node.vue
- src/ui/src/magicbox/src/bk-magic-ui/src/member-selector.scss
- src/ui/src/magicbox/src/bk-magic-ui/src/tag-input.scss
- src/ui/src/magicbox/src/components/date-range/date-range.vue
- src/ui/src/magicbox/src/components/dialog/dialog.vue
- src/ui/src/magicbox/src/components/member-selector/index.js
- src/ui/src/magicbox/src/components/member-selector/member-selector.vue
- src/ui/src/magicbox/src/components/selector/selector.vue
- src/ui/src/magicbox/src/components/sideslider/sideslider.vue
- src/ui/src/magicbox/src/components/tag-input/render.js
- src/ui/src/magicbox/src/components/tag-input/tag-input.vue
- src/ui/src/magicbox/src/index.js
- src/ui/src/magicbox/src/util.js
- src/ui/src/utils/tools.js
- src/ui/src/views/custom-query/preview.vue
- src/ui/src/views/topology/index.vue
> update: merge master ui

- src/apimachinery/objcontroller/association/api.go
- src/apimachinery/objcontroller/association/association.go
- src/common/metadata/association.go
- src/common/tablenames.go
- src/source_controller/objectcontroller/service/association_action.go
- src/source_controller/objectcontroller/service/objectasst_action.go
- 关联类型的增删改查API定义
- 模型关联的增删改查API定义
- 实例关联的增删查API定义
> #1149 关联类型、模型关联、实例关联的接口定义

- src/api_server/ccapi/logics/v2/common/converter/converter.go
- xxxx
- xxxx
- 修复v2版本操作系统类型错误bug
> 修复v2版本操作系统类型错误bug

- src/source_controller/hostcontroller/service/favourite.go
- src/source_controller/hostcontroller/service/user.go
- xxxx
- xxxx
- 修复数据在数据库不存在报错的问题
@breezelxp 
close  #1229
> 处理数据在数据库不存在的情况

- src/ui/src/components/hosts/status/status.vue
- xxxx
- xxxx
- 主机“实时状态”图表不显示
close #1234
> bugfix: 主机“实时状态”图表不显示

- src/scene_server/topo_server/service/compatiblev2.go
> 解决v2接口根据set_id查询模块失败问题

- src/ui/src/components/relation/_topology.vue
- xxxx
- 实例关联关系拓扑图增加关联描述
- xxxx
> feature: 实例关联关系拓扑图增加关联描述

- src/ui/src/assets/json/event-push-example.json
- src/ui/src/views/eventpush/pop.vue
> bugfix: 测试推送没有post数据

- src/apimachinery/rest/request.go
- src/apimachinery/toposerver/association/apis.go
- src/apimachinery/toposerver/association/association.go
- src/scene_server/topo_server/service/service_initfunc.go
- 新加apimachinery http 调用日志
- 新加apimachinery 新加toposerver 关于关联关系操作接口
- xxxx
- 修复关联关系toposerver http 调用方式错误问题
@breezelxp  @wusendong
> 关联关系toposerver http 调用方式修改

- src/ui/src/views/network-config/collect.vue
- src/ui/src/views/network-config/device.vue
- src/ui/src/views/network-config/property.vue
- src/ui/src/views/network-discovery/confirm.vue
- src/ui/src/views/network-discovery/details.vue
> minor: 网络发现接口参数调整

- src/common/metadata/association.go
- src/source_controller/objectcontroller/service/instasst_action.go
- src/source_controller/objectcontroller/service/objectasst_action.go
- 
- 模型关联关系和实例关联关系的查询结构体，从map改为struct，支持or类型查询
-
> 关联查询，对or查询条件的转换 #1149

- src/common/metadata/association.go
- src/source_controller/objectcontroller/service/instasst_action.go
> 关联关系处理，插入实例关联关系时写入模型id #1149

- src/scene_server/topo_server/core/model/association.go
- src/scene_server/topo_server/core/model/classification.go
- src/scene_server/topo_server/core/model/factory.go
- 增加默认设置SupplierAccount的逻辑 #1264
> 增加默认设置SupplierAccount的逻辑 #1264

- src/scene_server/admin_server/command/import.go
- src/scene_server/admin_server/command/types.go
- src/scene_server/event_server/identifier/identifier.go
- src/scene_server/topo_server/core/operation/inst_business.go
- 解决推送主机身份缺少进程信息问题
- 解决导入拓扑进程模块映射表缺少开发商字段问题
> 解决推送主机身份缺少进程信息问题

- src/scene_server/proc_server/proc_service/service/openapi.go
- xxxx
- xxxx
- 修复根据IP获取进程信息时， 业务下多个进程。只展示一个进程的问题
> 修复根据IP获取进程信息时， 业务下多个进程。只展示一个进程的问题

- src/ui/src/views/network-config/property.vue
> minor：接口字段调整

- src/ui/src/components/hosts/filter/_collection.vue
- src/ui/src/store/modules/api/host-favorites.js
- src/ui/src/store/modules/api/net-collect-property.js
- src/ui/src/views/model/details/base-info.vue
- src/ui/src/views/network-config/property.vue
> bugfix: 网络发现接口更正

- src/common/definitions.go
- src/common/mapping.go
- src/common/metadata/object.go
- src/common/metadata/object_test.go
- src/common/tablenames.go
- src/common/tablenames_test.go
- src/framework/core/output/module/types/type.go
- src/scene_server/event_server/distribution/handle_event.go
- src/scene_server/host_server/logics/host.go
- src/scene_server/host_server/logics/import.go
- src/scene_server/host_server/logics/import_asst.go
- src/scene_server/host_server/logics/instance.go
- src/scene_server/host_server/logics/object.go
- src/scene_server/proc_server/proc_service/service/procdetail.go
- src/scene_server/topo_server/core/operation/import_asst.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/supplementary_audit.go
- src/scene_server/validator/valid_unique.go
- src/source_controller/hostcontroller/logics/object.go
- src/source_controller/objectcontroller/service/common.go
- src/source_controller/objectcontroller/service/inst_action.go
- src/web_server/logics/excel.go
- src/web_server/logics/fields.go
- xxxx
- 修改 BKINnerObjIDObject 名字到 BKInnerObjIDObject
- xxxx
@breezelxp
> 修改 BKINnerObjIDObject 名字到 BKInnerObjIDObject

- src/common/metadata/struct_tags.go
- 修改SetValueToStructByTags 的实现，增加float 类型数据到 int 默认转换  close #1286
> 修改SetValueToStructByTags 的实现，增加float 类型数据到 int 默认转换 #1286

- src/common/definitions.go
- src/scene_server/topo_server/core/model/object.go
- xxxx
- delete is_pre check in the mainline topo operation.
- xxxx
> delete is_pre check in the mainline topo operation.

- scripts/Makefile
- src/scene_server/admin_server/upgrader/register.go
- src/scene_server/admin_server/upgrader/x18.10.10.01/pkg.go
- src/scene_server/topo_server/core/model/object.go
- src/scene_server/validator/valid_basic.go
- 解决testdog问题
- 解决upgrader在x18.10.10.01后不执行问题
> fix: instance validator

- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
- update association structure in upgrader
> fix: update association upgrader

- src/common/metadata/association.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/service/service_initfunc.go
- xxxx
- xxxx
- 修改关联关系的http verb.
- 为inst相关的结构体添加json omitempty和bson tag.
> topo 关联关系verb和字段调整。

- src/apimachinery/apiserver/api.go
- src/web_server/service/object.go
- xxxx
- xxxx
- 修复导入模型实例失败的问题
- 修复导入模型实例出错时，返回多个json结果问题
close  #1317
@breezelxp
>  web server import object error, http reply multip json 

- src/scene_server/topo_server/service/service_initfunc.go
- xxxx
- xxxx
- change topo association get verb
> change topo association get verb

- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
> 解决upgrader的default关联类型

- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
> fix: upgrader update association type descriptions

- src/common/metadata/association.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/graphics.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/service/association.go
- src/scene_server/topo_server/service/object_association.go
- src/scene_server/topo_server/service/service_initfunc.go
> 修改关联关系的BUG

- src/common/definitions.go
- src/scene_server/topo_server/service/inst_business.go
> support superadmin query

- src/web_server/logics/excel.go
- src/web_server/logics/inst.go
- src/web_server/service/service.go
- xxxx
- xxxx
- 修复导出实例跳转到login out接口问题
- 修复导出excel 数据为空问题
close  #1335
> fix: export instance bug issue #1335

- src/common/condition/condition.go
- src/common/condition/condition_test.go
- src/common/condition/field.go
- src/common/condition/or.go
- src/common/condition/or_test.go
- src/common/metadata/association.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/import_association.go
- src/scene_server/topo_server/service/service.go
- src/web_server/logics/excel.go
- src/web_server/logics/excel_util.go
- src/web_server/logics/fields.go
- src/web_server/logics/host.go
- src/web_server/logics/inst.go
- src/web_server/service/host.go
- src/web_server/service/inst.go
- toposerver 返回错误时，data 允许带数据
- condition 支持OR查询
- 优化导入关联关系关返回数据错误
- 优化关联关系导出
- xxxx
@breezelxp 
close #1338
> import association 

- scripts/Makefile
- src/common/condition/field.go
- src/common/condition/types.go
- src/common/definitions.go
- src/common/metadata/association.go
- src/scene_server/admin_server/command/getter.go
- src/scene_server/admin_server/command/import.go
- src/scene_server/admin_server/upgrader/register.go
- src/scene_server/topo_server/core/model/object.go
- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- src/scene_server/validator/valid_basic.go
- 解决拓扑查询慢问题
- 解决导入拓扑时没删掉不含default字段的模块问题
> cherry-pick from 3.1.1

- src/common/errInfo.go
- src/common/metadata/association.go
- src/source_controller/objectcontroller/service/instasst_action.go
- fix object controller instance association lost a field(bk_asst_id) in InstAsst.
>  bugfix: fix object controller instance association lost a field

- .travis.yml
> docs: change golang version

- src/scene_server/host_server/logics/hostsearch.go
- xxxx
- xxxx
- host search return all host
> fix: host search return all host  issue #1237

- docs/wiki/container-support.md
- xxxx
- optimize wiki doc about container-support.md
- xxxx
> optimize wiki doc about container support

- src/common/metadata/association.go
- src/scene_server/topo_server/core/operation/association_mainline_inst.go
> mainline topo optimize

- src/common/metadata/association.go
- add IsPre field in association kind.
> add IsPre field in association kind.

- src/common/definitions.go
- src/common/util/conv.go
- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
- src/scene_server/validator/valid_basic.go
> add ForeignKeyType

- src/common/mapstr/mapstr.go
- src/common/mapstr/mapstr_test.go
- 公共类mapstr支持本身类型转换。
- xxxx
- xxxx
@breezelxp 
close #1411
> feature:mapstr support self convert issue #1411

- src/common/mapstr/mapstr.go
- src/common/mapstr/mapstr_test.go
- src/scene_server/host_server/service/module.go
- xxxx
- 优化主机从业务模块转移资源池提示。
- xxxx
> refactor:[v3.3.x]host hand over the business module to resource pool tips 

- src/ui/src/views/permission/authority.vue
- src/ui/src/views/permission/business.vue
> checkbox样式调整

- src/web_server/logics/httpheader.go
- src/web_server/middleware/auth/auth_util.go
- 替换登录使用session 类库
- xxxx
- xxxx
close #1422
> 替换登录使用session 类库

- src/web_server/logics/httpheader.go
- src/web_server/middleware/auth/auth_util.go
> feature:webserver session use cluster  issue #1422

- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
- src/storage/dal/mongo/mgo_mongo.go
> update preset object association

- src/api_server/logics/v2/common/converter/converter.go
- src/scene_server/host_server/logics/hostsearch.go
- 
- xxxx
- 修复v2API无法适配hostsearch函数云区域字段的适配的问题
- 修复hostsearch函数排序字段无效的问题
> V3.3.x 修复hostsearch 排序字段失效及云区域适配问题

- src/api_server/logics/v2/common/converter/converter.go
- src/common/mapstr/mapstr.go
- src/common/mapstr/mapstr_test.go
- src/scene_server/host_server/logics/hostsearch.go
- 
- xxxx
- 修复v2API无法适配hostsearch函数云区域字段的适配的问题
- 修复hostsearch函数排序字段无效的问题
@breezelxp 
close #1428 #1427
> V3.2.x 问题修复

- src/scene_server/topo_server/core/operation/association_mainline_inst.go
> 解决业务拓扑被异常转移到其他业务问题 to 3.1.0 #1437

- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- xxxx
- xxxx
- 解决业务拓扑被异常转移到其他业务问题 #1437
> 解决业务拓扑被异常转移到其他业务问题--to 3.2.x

- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- xxxx
- xxxx
- 解决业务拓扑被异常转移到其他业务问题
fixes #1437
>  解决业务拓扑被异常转移到其他业务问题 to master #1437

- src/ui/src/assets/scss/model-manage.scss
- src/ui/src/views/model-manage/topo.vue
> minor: 样式调整

- src/api_server/logics/v2/common/converter/converter.go
- src/api_server/logics/v2/common/utils/utils.go
- src/api_server/service/v2/host.go
- src/api_server/service/v2/module.go
- src/api_server/service/v2/process.go
- src/api_server/service/v2/search.go
- src/apimachinery/hostserver/apis.go
- src/apimachinery/hostserver/hostserver.go
- src/apimachinery/procserver/openapi/api.go
- src/apimachinery/procserver/openapi/openapi.go
- src/apimachinery/toposerver/inst/api.go
- src/apimachinery/toposerver/inst/module.go
- src/apimachinery/toposerver/inst/set.go
- src/apimachinery/toposerver/openapi/api.go
- src/apimachinery/toposerver/openapi/openapi.go
- src/common/util/ownerutil.go
- src/scene_server/host_server/logics/phpapi_host.go
- src/scene_server/host_server/logics/plat.go
- src/scene_server/topo_server/core/compatiblev2/module.go
- src/scene_server/topo_server/core/operation/object.go
- src/source_controller/objectcontroller/service/inst_action.go
- 多供应商下，支持全局实例
- 优化apimachinery部分函数返回值
- 修复兼容API实例inst ID，返回科学计数法的错误
close #1454  #1453  #1451 
@breezelxp
> Apiserver apimchiney supplier

- src/scene_server/topo_server/core/operation/import_association.go
- src/web_server/middleware/login.go
- 导入实例，源-目标约束1:1的时候，如果已经存在关联关系，不可在进行关联操作
- xxxx
-  修复用户没有权限，返回两段JSON格式数据给前端的问题
close #1460  #1458 
@breezelxp
> Master cherry pick v3.2.x to master

- src/source_controller/objectcontroller/service/association_action.go
> fix: should query common association type

- resources/language/default/property.json
- resources/language/en/property.json
- src/common/definitions.go
- src/common/metadata/hostlock.go
- src/common/metadata/webserver.go
- src/common/util/lib.go
- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/x18.10.30.02/biz_supplier_id.go
- src/scene_server/admin_server/upgrader/x18.10.30.02/pkg.go
- src/scene_server/topo_server/core/operation/inst_business.go
- src/source_controller/hostcontroller/app/server.go
- src/source_controller/hostcontroller/logics/hostlock.go
- src/web_server/logics/httpheader.go
- src/web_server/middleware/login.go
- src/web_server/middleware/user/plugins/method/self/userinfo.go
- src/web_server/middleware/user/public.go
- src/web_server/service/user.go
- 主机锁支持多供应商
- 给业务模型新加供应商ID字段
- 登录session 缓存供应商ID数据
- xxxx
- xxxx
> V3.3.x 登录，业务新加supplier_id字段

- src/ui/src/views/index/children/recently.vue
> bugfix:修复删除最近浏览记录导致所有记录被清空的问题

- src/ui/src/setup/validate.js
> 长短字符支持输入@和#号

- docs/overview/source_compile.md
- xxxx
- xxxx
- xxxx
- 编译文档关于GOPATH路径问题
> doc: update gopath desc

- src/scene_server/host_server/logics/phpapi.go
- xxxx
- xxxx
- 修复主机克隆的时候，asset_id重复问题
> V3.2.x duplicate index 修复主机克隆的时候，asset_id重复

- src/api_server/logics/v2/common/converter/converter.go
- src/api_server/logics/v2/topo.go
- src/api_server/service/v2/application.go
- src/api_server/service/v2/host.go
- src/api_server/service/v2/module.go
- src/api_server/service/v2/plat.go
- src/api_server/service/v2/set.go
- src/web_server/logics/excel_util.go
- src/web_server/logics/host.go
- src/web_server/logics/inst.go
- src/web_server/service/host.go
- src/web_server/service/inst.go
- xxxx
- 
- 修复apiserver 数据转换的问题
- 修复导入数据，没有返回导入结果详情问题
> V3.2.x bug修复

- src/web_server/middleware/login.go
- xxxx
- xxxx
- 修复登录供应商ID使用错误的问题
> V3.2.x 修复登录供应商ID使用错误的问题

- src/source_controller/proccontroller/service/procinstance.go
> fefector:  blog level issue #1517

- src/common/metadata/result.go
- src/source_controller/coreservice/core/model/classification.go
- src/source_controller/coreservice/core/type.go
> 实现新建模型分类的接口 #1495

- src/common/condition/condition.go
- src/common/condition/page.go
- src/common/metadata/query.go
- src/common/metadata/query_test.go
- src/common/metadata/result.go
> feature: 重新定义查询条件 issue #1496

- src/common/metadata/core_service.go
- src/common/metadata/result.go
- src/common/metadata/update.go
- src/source_controller/coreservice/core/association/dependences.go
- src/source_controller/coreservice/core/association/instance.go
- src/source_controller/coreservice/core/association/kind.go
- src/source_controller/coreservice/core/association/model.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/instances/dependences.go
- src/source_controller/coreservice/core/instances/instance.go
- src/source_controller/coreservice/core/model/attribute.go
- src/source_controller/coreservice/core/model/classification.go
- src/source_controller/coreservice/core/model/classification_crud.go
- src/source_controller/coreservice/core/model/classification_private.go
- src/source_controller/coreservice/core/model/dependences.go
- src/source_controller/coreservice/core/model/model.go
- src/source_controller/coreservice/core/model/model_crud.go
- src/source_controller/coreservice/core/model/model_private.go
- src/source_controller/coreservice/core/type.go
- src/source_controller/coreservice/service/service.go
- src/source_controller/coreservice/service/service_initfunc.go
>  实现模型分类的管理接口 以及更新 删除操作返回数据类型调整 #1495

- src/common/metadata/query.go
- src/common/universalsql/mongo/condition.go
> 修改条件入参 #1503

- src/ui/src/views/network-config/collect.vue
- src/ui/src/views/network-discovery/confirm.vue
- src/ui/src/views/network-discovery/details.vue
> 网络发现bugfix

- src/ui/src/components/hosts/filter/_filter-field-operator.vue
- src/ui/src/components/hosts/table/index.vue
- src/ui/src/components/layout/nav.vue
- src/ui/src/components/relation/index.vue
- src/ui/src/components/ui/details/details.vue
- src/ui/src/components/ui/form/form-multiple.vue
- src/ui/src/components/ui/form/form.vue
- src/ui/src/router/index.js
- src/ui/src/store/modules/api/object-model-classify.js
- src/ui/src/store/modules/api/user-privilege.js
- src/ui/src/views/business-model/index.vue
- src/ui/src/views/business/index.vue
- src/ui/src/views/custom-query/define.vue
- src/ui/src/views/custom-query/index.vue
- src/ui/src/views/general-model/index.vue
- src/ui/src/views/index/children/classify.vue
- src/ui/src/views/model-association/index.vue
- src/ui/src/views/model-manage/children/_property-group.vue
- src/ui/src/views/model-manage/children/field.vue
- src/ui/src/views/model-manage/children/index.vue
- src/ui/src/views/model-manage/children/relation.vue
- src/ui/src/views/model-manage/children/verification.vue
- src/ui/src/views/model-manage/index.vue
- src/ui/src/views/model-topology/index.vue
- src/ui/src/views/permission/business.vue
- src/ui/src/views/process/index.vue
- src/ui/src/views/process/module.vue
- src/ui/src/views/resource/index.vue
- src/ui/src/views/topology/index.vue
> feature: 普通用户导航视图

- src/ui/src/components/layout/nav.vue
> bugfix: bad code 导航计算属性循环引用

- src/common/mapstr/mapstr.go
- src/common/universalsql/mongo/condition.go
- src/common/universalsql/mongo/condition_private.go
- src/common/universalsql/mongo/condition_test.go
- src/common/universalsql/type.go
- 完善universalsql 支持从复杂条件结构解析生成 universal 定义的条件对象 # 1499
> 完善universalsql 支持从复杂条件结构解析生成 universal 定义的条件对象 # 1499

- src/apimachinery/coreservice/association/api.go
- src/apimachinery/coreservice/association/association.go
- src/apimachinery/coreservice/coreservice.go
- src/apimachinery/coreservice/instance/api.go
- src/apimachinery/coreservice/instance/instance.go
- src/apimachinery/coreservice/model/api.go
- src/apimachinery/coreservice/model/model.go
- src/common/metadata/core_service.go
- src/common/metadata/create.go
- src/common/metadata/query.go
- src/common/metadata/result.go
- src/common/metadata/update.go
- apimachinery 封装
- 新加coreservice用到set,delete,create,update 的结构
- xxxx
> coreservice 常量定义和apimachinery封装

- src/web_server/middleware/auth/public.go
- src/web_server/middleware/types/types.go
- minor: add get privilege authority to get associatioin kind info.
> minor: add get privilege authority to get associatioin kind info.

- src/common/blog/blog.go
- src/common/definitions.go
- src/scene_server/topo_server/core/model/unique.go
- src/source_controller/objectcontroller/service/object_unique.go
- src/storage/dal/mongo/mgo_mongo.go
- src/storage/dal/mongo/mock_mongo.go
- src/storage/dal/mongo/rpc_mongo.go
- src/storage/dal/rdb.go
> fix: 修改分组唯一时要重算存量模型实例唯一性

- src/source_controller/objectcontroller/service/object_unique.go
> fix: check unique should include bk_obj_id

- src/scene_server/topo_server/service/service_initfunc.go
- src/web_server/middleware/auth/public.go
- src/web_server/middleware/types/types.go
> 新增普通用户的模型查询权限

- src/scene_server/topo_server/service/service_initfunc.go
> minor: delete mistake code

- src/common/metadata/query.go
- src/common/metadata/result.go
- src/source_controller/coreservice/core/model/attribute.go
- src/source_controller/coreservice/core/model/attribute_curd.go
- src/source_controller/coreservice/core/model/classification.go
- src/source_controller/coreservice/core/model/classification_crud.go
- src/source_controller/coreservice/core/model/classification_private.go
- src/source_controller/coreservice/core/model/dependences.go
- src/source_controller/coreservice/core/model/model.go
- src/source_controller/coreservice/core/model/model_crud.go
- src/source_controller/coreservice/service/service.go
- finish code about model management logic #1494
> finish code about model management logic #1494

- src/ui/src/pages/hosts/hosts.vue
- src/ui/src/pages/organization/object.vue
- 3.1.0修复使用主机收藏条件无效的问题
- 3.1.0修复通用模型无权限时对应按钮未禁用的问题
> 3.1.0 bugfix

- src/ui/src/common/json/timezone.json
- src/ui/src/common/scss/common.scss
- src/ui/src/components/filter/screening.vue
- src/ui/src/components/history/details.vue
- src/ui/src/pages/eventpush/eventpush.vue
- src/ui/src/pages/hosts/hosts.vue
- src/ui/src/pages/topology/topology.vue
- 下拉框禁用样式问题
- 清空筛选条件会勾上‘精确’复选框
- 新增模块时，进程信息的选项卡会无意义出现
- 批量修改主机属性侧滑未正确收起
- 操作审计详情展开收起按钮优化
> V3.1.0 bugfix

- src/ui/src/pages/hosts/hosts.vue
> bugfix-3.1.0:修复无业务权限时可以刷新查询主机信息的问题

- src/apimachinery/clientset.go
- src/apimachinery/clientset_coreservice_inst_test.go
- src/apimachinery/clientset_coreservice_model_test.go
- src/apimachinery/coreservice/association/api.go
- src/apimachinery/coreservice/association/association.go
- src/apimachinery/coreservice/coreservice.go
- src/apimachinery/coreservice/instance/api.go
- src/apimachinery/coreservice/instance/instance.go
- src/apimachinery/coreservice/model/api.go
- src/apimachinery/coreservice/model/model.go
- src/apimachinery/discovery/discovery.go
- src/apimachinery/discovery/discovery_mock.go
- src/common/metadata/create.go
- apimachinery mock封装
- apimachinery discovery 封装
- apimachinery 格式化
- xxxx
- xxxx
> coreservice apimachinery mock and test case.

- src/ui/src/views/eventpush/pop.vue
> bugfix: 事件推送推送测试参数错误

- src/source_controller/coreservice/core/association/dependences.go
- src/source_controller/coreservice/core/association/instance.go
- src/source_controller/coreservice/core/association/kind.go
- xxxx
- change count type int64=>uint64
> feature:change count type int64=>uint64

- src/common/metadata/object_controller.go
- src/scene_server/topo_server/app/server.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/service/object_association.go
- xxxx
- xxxx
- fix create association with invalid id problem.
> bugfix: fix create association with invalid id problem.

- src/common/metadata/graphic.go
- src/common/metadata/graphic_test.go
- src/scene_server/topo_server/core/operation/graphics.go
> fix： fix bug in issue #1565, topo graph missing fields lead to panic

- src/source_controller/objectcontroller/service/topographics.go
> fix: graphics missing fields lead to panic, issue #1565.

- src/scene_server/host_server/logics/phpapi.go
- src/scene_server/host_server/logics/phpapi_host.go
- src/scene_server/host_server/logics/phpapi_searchhost.go
- src/scene_server/host_server/service/phpapi.go
- xxxx
- xxxx
- 修复v2  getHostAppByCompanyId api由于类型转换造成painc的问题
@breezelxp
> fix: v2 getHostAppByCompanyId api  get host panic issue #1564

- scripts/init.py
- src/apimachinery/rest/request.go
- src/common/tablenames.go
- src/scene_server/admin_server/upgrader/x18.11.19.01/reconcil_unique.go
- src/scene_server/topo_server/app/server.go
- src/scene_server/topo_server/core/operation/association_mainline_object.go
- src/web_server/middleware/login.go
- xxxx
- xxxx
- 修复模块可以在不同业务下可重复问题
- 修复新建业务拓扑层级模型时没有默认字段问题
> bugfix: 修复模块可以在不同业务下可重复问题

- src/common/definitions.go
- src/common/eventclient/eventclient.go
- src/common/eventclient/eventclient_test.go
- src/common/tablenames.go
- src/scene_server/admin_server/upgrader/v3.0.8/createtable.go
- src/scene_server/event_server/distribution/start.go
- src/source_controller/hostcontroller/app/server.go
- src/source_controller/hostcontroller/logics/logics.go
- src/source_controller/hostcontroller/service/host.go
- src/source_controller/hostcontroller/service/service.go
- src/source_controller/objectcontroller/app/server.go
- src/source_controller/objectcontroller/service/inst_action.go
- src/source_controller/objectcontroller/service/instasst_action.go
- src/source_controller/objectcontroller/service/service.go
- src/source_controller/objectcontroller/service/set.go
- src/source_controller/proccontroller/app/server.go
- src/source_controller/proccontroller/service/module.go
- src/source_controller/proccontroller/service/operatetask.go
- src/source_controller/proccontroller/service/service.go
- src/source_controller/proccontroller/service/template.go
> 提高eventclient的Robustness

- src/common/metadata/graphic.go
- src/source_controller/objectcontroller/service/topographics.go
>  fix: topo graphics update and search with wrong data.

- src/common/metadata/classification.go
- src/source_controller/coreservice/core/association/model.go
- src/source_controller/coreservice/core/association/model_crud.go
- src/source_controller/coreservice/core/association/model_private.go
- src/source_controller/coreservice/core/model/attribute.go
- src/source_controller/coreservice/core/model/attribute_curd.go
- src/source_controller/coreservice/core/model/attribute_private.go
- src/source_controller/coreservice/core/model/classification.go
- src/source_controller/coreservice/core/model/classification_crud.go
- src/source_controller/coreservice/core/model/classification_private.go
- src/source_controller/coreservice/core/model/model.go
- src/source_controller/coreservice/core/model/model_crud.go
- src/source_controller/coreservice/core/model/model_private.go
- optimize the implementation of basic operation methods , 
- add logs for all model management logic
> :optimize the implementation of basic operation methods , add logs for all model management logic

- src/web_server/middleware/auth/public.go
- src/web_server/middleware/types/types.go
- xxxx
- optimize: add privilege for export object excel api.
- xxxx
> optimize: add privilege for export object excel api.

- src/web_server/middleware/auth/public.go
- src/web_server/middleware/types/types.go
- xxxx
- optimize: add privilege for search inst association api for common user
- xxxx
> optimize: add privilege for search inst association api for common user

- src/ui/src/components/relation/index.vue
- src/ui/src/views/index/children/classify-item.vue
- src/ui/src/views/model-manage/children/_property-group.vue
- src/ui/src/views/model-manage/children/index.vue
- src/ui/src/views/model-manage/index.vue
- src/ui/src/views/model-topology/index.vue
- 修复普通用户可以修改字段分组名称的问题
- 修复普通用户可以修改模型图标的问题
- 修改实例关联界面关联管理按钮状态判断的接口
- 修复普通用户可以初始化拓扑节点位置的问题
- 修复添加收藏数量判断不正确的问题
- 修复普通用户可以管理模型分组的问题
- 修复修改模型分组时可以编辑唯一标识的问题
> 3.2.x ui bug fix

- src/ui/src/views/general-model/index.vue
- src/ui/src/views/status/403.vue
- src/ui/src/views/status/404.vue
- src/ui/src/views/status/error.vue
- src/ui/src/views/status/require-business.vue
> fix:ui:修复部分页面未重置页面标题的问题

- src/web_server/middleware/auth/public.go
- src/web_server/middleware/types/types.go
- xxxx
- add privilege for common user with create inst association api.
- xxxx
> optimize: add privilege for common user with create inst association api.

- src/ui/src/components/ui/selector/selector.vue
> refactor:  selector支持带分组的筛选

- src/web_server/middleware/auth/public.go
- src/web_server/middleware/types/types.go
- xxxx
- optimize: add delete inst association api privilege for common user.
- xxxx
> optimize: add delete inst association api privilege for common user.

- src/scene_server/host_server/logics/import.go
> fix: 修复错误信息判断错误的问题

- src/common/universalsql/mongo/condition_private.go
- src/common/universalsql/mongo/condition_test.go
- src/common/universalsql/mongo/element.go
- src/source_controller/coreservice/core/association/model.go
- src/source_controller/coreservice/core/association/model_private.go
- src/source_controller/coreservice/core/association/model_test.go
- src/source_controller/coreservice/core/model/attribute.go
- src/source_controller/coreservice/core/model/mock_test.go
- src/source_controller/coreservice/service/model_dependencs.go
- Compatible with older versions of mongodb equal syntax issue
> Compatible with older versions of mongodb equal syntax issue 

- src/scene_server/datacollection/datacollection/handler.go
- src/scene_server/datacollection/datacollection/netdevice.go
- datacollection coreservice 改造
> datacollection coreservice 改造

- src/scene_server/admin_server/upgrader/x18.11.19.01/pkg.go
- src/scene_server/admin_server/upgrader/x18.11.19.01/reconcil_unique.go
- src/scene_server/validator/valid_basic.go
> 修复用户类型字段未校验问题

- resources/language/default/association.json
- resources/language/en/association.json
- src/source_controller/objectcontroller/service/association_action.go
- src/source_controller/objectcontroller/service/common.go
> feature: add translation for association kind

- src/common/metadata/metadata.go
- xxxx
- change label type and add new receivers
- xxxx
> optimize: change label type and add new receivers.

- src/scene_server/admin_server/app/server.go
- src/scene_server/admin_server/command/command.go
- src/scene_server/datacollection/datacollection/datacollection.go
- src/scene_server/event_server/app/server.go
- src/source_controller/auditcontroller/app/server.go
- src/source_controller/hostcontroller/app/server.go
- src/source_controller/objectcontroller/app/server.go
- src/source_controller/proccontroller/app/server.go
- src/storage/dal/mongo/mgo_mongo.go
> fix: solve dail mongodb forever problem

- src/source_controller/objectcontroller/service/identifier.go
> fix: find all result should use pointer

- src/scene_server/host_server/logics/app.go
- xxxx
- xxxx
- 修复多租户下，获取资源池业务问题
close #1656
> fix: multip-supplier method, assign to app issue #1656

- resources/language/default/enum.json
- resources/language/default/property.json
- resources/language/en/enum.json
- resources/language/en/property.json
- src/common/metadata/graphic.go
- src/scene_server/topo_server/core/model/classification.go
- src/scene_server/topo_server/core/model/factory.go
- src/scene_server/topo_server/core/model/types.go
- src/scene_server/topo_server/core/operation/classification.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/service/graphics.go
- src/scene_server/topo_server/service/service_initfunc.go
- xxxx
- xxx
- 修复多语言支持问题
- 修复topo graph位置信息异常问题
- 修复模型分类唯一校验问题。
> V3.2.1 regression

- src/common/rdapi/rdfunc.go
- src/common/util/lib.go
- src/scene_server/host_server/logics/hostlock.go
- src/scene_server/proc_server/app/server.go
- src/scene_server/proc_server/logics/appinstance.go
- src/scene_server/proc_server/logics/backgroup.go
- src/scene_server/proc_server/logics/gsehandle.go
- src/scene_server/proc_server/logics/host.go
- src/scene_server/proc_server/logics/instance.go
- src/scene_server/proc_server/logics/instanceconst.go
- src/scene_server/proc_server/logics/instanceutil.go
- src/scene_server/proc_server/logics/log.go
- src/scene_server/proc_server/logics/logics.go
- src/scene_server/proc_server/logics/matchprocinstance.go
- src/scene_server/proc_server/logics/process.go
- src/scene_server/proc_server/logics/task.go
- src/scene_server/proc_server/logics/template.go
- src/scene_server/proc_server/logics/topo.go
- src/scene_server/proc_server/logics/variables.go
- src/scene_server/proc_server/proc_service/service/init_func.go
- src/scene_server/proc_server/proc_service/service/openapi.go
- src/scene_server/proc_server/proc_service/service/proc2module.go
- src/scene_server/proc_server/proc_service/service/procdetail.go
- src/scene_server/proc_server/proc_service/service/process.go
- src/scene_server/proc_server/proc_service/service/procinstance.go
- src/scene_server/proc_server/proc_service/service/service.go
- src/scene_server/proc_server/proc_service/service/template.go
- src/scene_server/proc_server/proc_service/service/templatefile.go
- src/scene_server/proc_server/proc_service/service/templateversion.go
- xxxx
- procserver 日志记录使用request id
- xxxx
clsoe #1682
@breezelxp
> refactor: proc log use http request id issue #1682

- src/common/metadata/core_service.go
- src/common/metadata/result.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/model/attribute.go
- src/source_controller/coreservice/core/model/classification.go
- src/source_controller/coreservice/core/model/mock_test.go
- src/source_controller/coreservice/core/model/model.go
- src/source_controller/coreservice/core/model/model_attribute_group.go
- src/source_controller/coreservice/core/model/model_test.go
- src/source_controller/coreservice/service/model.go
- src/source_controller/coreservice/service/model_classification_test.go
- src/source_controller/coreservice/service/model_test.go
- src/source_controller/coreservice/service/service_test.go
- update coreservice testcase  #1685
> update coreservice testcase  #1685

- src/api_server/service/v2/addhost.go
- xxxx
- xxxx
- 修复v2 版本api enterIP新加主机，操作系统类型值只能为Linux问题
close #1693 
@holmeswang
> fix: enterIP add host info, ostype  field value error issue #1693

- src/common/mapstr/mapstr_test.go
- src/common/mapstr/struct_tags_private.go
- src/common/mapstr/to_value.go
- src/source_controller/coreservice/service/model_test.go
- xxxx
- xxxx
-: Support for conversion to multi-type maps for MapStr #1625
>  fix: Support for conversion to multi-type maps for MapStr #1625

- src/api_server/service/v2/service.go
- src/api_server/service/v3/service.go
- src/common/rdapi/rdfunc.go
- src/scene_server/admin_server/service/service.go
- src/scene_server/datacollection/service/service.go
- src/scene_server/event_server/service/service.go
- src/scene_server/host_server/service/service.go
- src/scene_server/proc_server/proc_service/service/service.go
- src/scene_server/topo_server/service/service.go
- src/source_controller/auditcontroller/service/service.go
- src/source_controller/hostcontroller/service/service.go
- src/source_controller/objectcontroller/service/service.go
- src/source_controller/proccontroller/service/service.go
- toposerver,coreservice 新加http 请求filter
- 优化filter代码格式和输出
- xxxx
close #1695
> feature:[v3.2.x] http filter 功能

- src/common/mapstr/mapstr_test.go
- src/source_controller/coreservice/core/model/model_attribute_group.go
- src/source_controller/coreservice/core/model/model_attribute_group_crud.go
- src/source_controller/coreservice/service/model.go
- src/source_controller/coreservice/service/model_attribute_group_test.go
- src/source_controller/coreservice/service/model_attribute_test.go
- fixed bug in grouping updates for model attributes
- add attribute group testcase
> test:add attribute group testcase, issue #1644

- src/scene_server/topo_server/core/model/attribute.go
- xxxx
- xxxx
- 修复查询属性接口panic的问题。
> fix: fix a panic in attribute query api.

- src/source_controller/coreservice/core/model/model_crud.go
- Model ID unassigned bug, issue #1494
> fix:Model ID unassigned bug, issue #1494

- scripts/start.sh
- scripts/stop.sh
- scripts/template.sh.stop
- src/apimachinery/coreservice/model/api.go
- src/apimachinery/rest/request.go
- src/scene_server/topo_server/core/model/attribute.go
- src/scene_server/topo_server/core/operation/group.go
- src/scene_server/topo_server/core/operation/object.go
- src/source_controller/coreservice/core/model/attribute.go
- src/source_controller/coreservice/core/model/attribute_curd.go
- src/source_controller/coreservice/core/model/model_crud.go
- vendor/github.com/golang/glog/glog.go
- xxxx
- xxxx
- 修复coreservice属性相关问题
> 修复coreservice属性相关问题

- src/source_controller/coreservice/core/association/model_crud.go
- fix:set model association id, issue #1710
> fix:set model association id, issue #1710

- src/scene_server/topo_server/core/operation/association.go
- src/source_controller/coreservice/core/model/unique.go
- src/source_controller/coreservice/service/instances_dependence.go
- xxxx
- xxxx
- fix query attribute unique
> refactor: fix query attribute unique

- src/common/metadata/association.go
- src/common/metadata/time.go
- src/source_controller/coreservice/core/association/model_private.go
- src/source_controller/coreservice/service/model_association_test.go
- test:add some testcase for model association, issue #1644
>  test:add some testcase for model association, issue #1644

- src/scene_server/host_server/util/util.go
- xxxx
- xxxx
- v3.3 修复主机导入，[restful] recover from panic situation: - assignment to entry in nil map 错误
@holmeswang 
close #1722
> fix: assignment to entry in nil map issue #1722

- src/scene_server/topo_server/core/model/attribute.go
- src/scene_server/topo_server/core/model/factory.go
- src/scene_server/topo_server/core/model/object.go
- xxxx
- xxxx
- fix import attribute
> refactor: fix import attribute

- src/scene_server/topo_server/core/operation/association.go
- src/source_controller/coreservice/core/association/instance.go
- src/source_controller/coreservice/core/association/kind_crud.go
- src/source_controller/coreservice/core/instances/instance_crud.go
- src/source_controller/coreservice/core/model/unique_crud.go
> refactor: init array first

- src/source_controller/coreservice/core/association/model.go
- src/source_controller/coreservice/core/model/attribute.go
- src/source_controller/coreservice/core/model/classification.go
- src/source_controller/coreservice/core/model/model.go
- src/source_controller/coreservice/core/model/model_attribute_group.go
- src/source_controller/coreservice/service/model_classification_test.go
- refactor: replace the update owner way in a condition in coreservice  , issue #1727
> refactor: replace the update owner way in a condition , issue #1727

- scripts/init.py
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/object.go
- xxxx
- xxxx
- fix create inst association
> fix create inst association

- src/common/universalsql/mongo/condition_test.go
- src/common/universalsql/mongo/element.go
…r  and  operator, issue #1738
- xxxx
- xxxx
- fix:if the value in mapstr is nil, then to convert nil to array object for $in  and $nin operator, issue #1738
> fix:if the value in mapstr is nil, then to convert nil to array object for $in  and $nin operator, issue #1738

- src/common/mapstr/deal_types.go
- src/common/mapstr/struct.go
- src/common/rdapi/rdfunc.go
> refactor: fix mapstr

- src/common/util/ownerutil.go
- src/common/util/ownerutil_test.go
- src/common/util/valid_test.go
- xxxx
- xxxx
- should return modified value 
close #1745
should cherry-pick to v3.3.x
> fix: should return modified value

- src/source_controller/coreservice/core/instances/instance_validate.go
- src/source_controller/coreservice/core/instances/validator.go
> refactor: ignore valid bk_data_status

- src/common/definitions.go
- src/common/rdapi/rdfunc.go
- request id 支持第三系统 request id
- xxxx
- xxxx
issue #1752 
@holmeswang code  review
> feature: request id 支持第三系统 request id

- src/scene_server/topo_server/core/operation/inst.go
- xxxx
- xxxx
- fix not delete association when delete instance
> refactor: fix not delete association when delete instance

- src/auth/parser/chain.go
- src/auth/parser/parser.go
- src/auth/type.go
> feature: add url parse chain filters. issue #1746

- src/scene_server/host_server/logics/phpapi.go
- xxxx
- xxxx
- 修复克隆主机。主机有已经被删除的字段，克隆失败问题
close #1753 
@lowenitt  review code
> fix: 克隆主机。主机有已经被删除的字段，克隆失败

- src/ui/src/components/hosts/transfer/index.vue
> fix:ui: 修复转移主机时模块过多UI溢出的问题

- src/auth/auth.go
- src/auth/authcenter/authcenter.go
- src/auth/authcenter/type.go
- src/auth/type.go
- add rest api with blueking auth center. issue #1771
close #1771
> feature:add rest api with blueking auth center. issue #1771

- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/x19.01.18.01/drop_index.go
- src/web_server/logics/inst.go
- src/web_server/middleware/auth/public.go
- src/web_server/middleware/types/types.go
- src/web_server/service/host.go
- src/web_server/service/inst.go
- src/web_server/service/object.go
> 修复webserver实例导出问题

- src/ui/src/views/model-manage/children/relation-detail/index.vue
> UI: 拓扑组成关系从新建关联下拉列表中移除

- src/ui/src/components/ui/form/objuser.vue
- 人员选择器在仅允许输入系统用户时默认选中第一个匹配的用户
> optimize:ui: 人员选择器在仅允许输入系统用户时默认选中第一个匹配的用户

- src/scene_server/topo_server/core/operation/association.go
> fixbug: limit the return and deletion of the mainline model association

- src/ui/src/components/ui/form/objuser.vue
> fix:ui: objuser component update scroller timing

- scripts/start.sh
- xxxx
- xxxx
- scripts/start.sh 注释错误
> Fix start.sh 注释

- scripts/generate.py
- scripts/init.py
- scripts/ip.py
- scripts/license.py
- 源码编译在Python3.x 环境下脚本运行失败
close: #1808
> fix:Python脚本在Python3.x环境下失败

- src/scene_server/proc_server/proc_service/service/proc2module.go
- xxxx
- xxxx
- 修复进程与模块绑定，删除模块后， 进程无法删除的问题。
@breezelxp 
close #1812
> fix:module bind proc, delete module, then delete proc error issue #1812

- src/auth/auth.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/core/operation/supplementary_auth.go
- src/scene_server/topo_server/core/types/types.go
- src/scene_server/topo_server/core/wrapper/auth.go
- src/scene_server/topo_server/service/service.go
- feature:add auth module for supplementary, issue #1774
> feature:add auth module for supplementary, issue #1774

- src/auth/auth.go
- src/auth/authcenter/authcenter.go
- src/auth/authcenter/type.go
- src/auth/parser/chain.go
- src/auth/parser/parser.go
- src/auth/parser/topolatest.go
- src/auth/parser/topology.go
- src/auth/resource.go
- src/auth/type.go
- 新增topo的api鉴权接口，包括老的接口和业务拓扑中新调整的所有接口。
- 对权限中心的鉴权和资源管理的接口进行了优化调整，简化鉴权逻辑。
> feature: add topology auth api filters and optimize authorize interface and data structure.

- src/scene_server/topo_server/core/model/object.go
- add error log when model occurs to have multiple children
> add error log when model occurs to have multiple children

- src/scene_server/host_server/service/host.go
- xxxx
- 优化参数缺少的提示信息
- 为函数新加注释
- 优化日志记录
- xxxx
close #1825 
@breezelxp  @lowenitt
> refactor: miss parameters tip, log message etc issue #1825

- src/scene_server/admin_server/command/command.go
- src/scene_server/admin_server/command/import.go
- src/scene_server/admin_server/command/types.go
- src/storage/dal/mongo/mgo_mongo.go
- fix: should recursively check child while delete a topo layer instance
should cherry-pick to v3.3.x
> fix: should recursively check child while delete a topo layer instance

- src/scene_server/topo_server/core/operation/object.go
- src/storage/dal/mongo/local/mongo.go
- src/storage/dal/mongo/remote/mongo.go
- xxxx
- xxxx
- fix: ignore import singleasst or multiasst attribute
> fix: ignore import singleasst or multiasst attribute

- src/source_controller/objectcontroller/service/association_action.go
> 修复查询关联类型接口分页查询错误

- src/scene_server/admin_server/readme.md
- src/scene_server/admin_server/service/clear.go
- src/scene_server/admin_server/service/flag.go
- src/scene_server/admin_server/service/migrate.go
- src/scene_server/admin_server/service/service.go
- src/scene_server/admin_server/upgrader/register.go
- 拼写错误
- markdown格式规范
- 重命名函数/变量
> refacor: rename and resolve misspell

- src/storage/dal/mongo/remote/mongo.go
> fix: fix lost time package error in storage dal.

- scripts/Makefile
- 编译branch/tag/pr时能提取正确的version/tag/branch信息
close #1847
> update makefile with supports for branch/tag/pr at building #1847

- scripts/Makefile
> bugfix: makefile extract branch/version/tag

- src/scene_server/admin_server/fixes_inst_association.js
- src/scene_server/admin_server/fixes_topo.js
- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
> fix wrong condition for upgrade inst association

- src/scene_server/event_server/service/subscription.go
> 解决replaceALL问题

- src/common/metadata/common.go
- src/source_controller/objectcontroller/service/inst_action.go
- src/web_server/logics/excel_commet_sheet.go
- xxxx
- xxxx
- xxxx
@breezelxp 
close #1855 close #1860  close #1861
> V3.2.x fix issue

- src/scene_server/event_server/distribution/transaction.go
- waitGroup should add before start the goroutine
close #1854
> fix: waitGroup should add before start the goroutine #1854

- src/source_controller/coreservice/core/model/model_attribute_group.go
> fix:error handle nil error

- src/scene_server/topo_server/core/compatiblev2/module.go
- src/scene_server/topo_server/core/compatiblev2/set.go
- src/scene_server/topo_server/core/model/group.go
- src/scene_server/topo_server/core/model/unique.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/inst_module.go
- src/scene_server/topo_server/core/operation/inst_set.go
- 修复toposerver和api server中可能由于err导致的painc问题。
> fix: fix err panics in toposerver . issue #1862

- src/api_server/logics/v2/fileds.go
- src/api_server/service/v2/process.go
- src/api_server/service/v2/searchext.go
- src/scene_server/host_server/logics/host.go
- src/scene_server/host_server/logics/plat.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/phpapi.go
- src/scene_server/proc_server/logics/gsehandle.go
- src/scene_server/proc_server/proc_service/service/openapi.go
- xxxx
- xxxx
- 修复变量不正确使用，引起panic问题
@breezelxp
> fix: fix nil pointer error at apiserver,hostserver,procserver 

- src/scene_server/admin_server/command/import.go
- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
- fixes nil pointer error at adminserver when dealing error
> fixes nil pointer error at adminserver when dealing error. #1862

- src/auth/authcenter/adaptor.go
- src/auth/authcenter/authcenter.go
- src/auth/authcenter/client.go
- src/auth/authcenter/type.go
- src/auth/meta/meta.go
- src/auth/meta/resource.go
- src/auth/parser/host.go
- src/auth/parser/topolatest.go
- cmdb和权限中心的资源映射关系，资源操作映射。
close #1816
> feature: adaptor cmdb and auth center's policy and resource actions.

- src/api_server/service/v3/uri.go
- src/common/metadata/hostserver.go
- src/common/metadata/metadata.go
- src/scene_server/host_server/logics/findhost.go
- src/scene_server/host_server/service/findhost.go
- src/scene_server/host_server/service/service.go
> 新增根据模块ID查询主机接口

- src/common/metadata/attribute.go
- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
- fixes miss change muti associate to single when upgrade to 3.2
> fixes miss change muti associate to single when upgrade to 3.2

- src/common/mapstr/mapstr.go
- src/common/types/serverInfo.go
- src/scene_server/synchronize_server/app/server.go
- src/scene_server/synchronize_server/logics/synchronize.go
- src/scene_server/synchronize_server/synchronize.go
- src/source_controller/coreservice/core/datasynchronize/association.go
> feature:support master-slave issue #1780

- src/ui/src/setup/preload.js
> 注释加载权限的接口，用于测试

- src/apiserver/service/service.go
- src/auth/authcenter/adaptor.go
- src/auth/authcenter/authcenter.go
- src/auth/authcenter/client.go
- src/auth/authcenter/id.go
- src/auth/authcenter/perm_initial.go
- src/auth/authcenter/perm_sys.go
- src/auth/authcenter/type.go
- src/auth/meta/resource.go
- src/auth/parser/chain.go
- src/auth/parser/event.go
- src/auth/parser/parser.go
- src/common/util/net.go
- src/common/util/net_test.go
- src/scene_server/event_server/app/server.go
- src/scene_server/event_server/distribution/start.go
- src/scene_server/event_server/service/service.go
> 添加事件订阅的权限校验

- src/scene_server/validator/valid_basic.go
- fixes ignore empty when enum is not require
> fixes ignore empty when enum is not require

- src/apiserver/service/service.go
- src/auth/authcenter/adaptor.go
- src/auth/authcenter/authcenter.go
- src/auth/authcenter/id.go
- src/scene_server/topo_server/core/auth/auth.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/classification.go
- src/scene_server/topo_server/core/operation/inst_business.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/service/object_classification.go
- src/web_server/app/server.go
- src/web_server/service/index.go
> optimize: test object classification, object, association type, 

- src/scene_server/host_server/logics/import.go
- src/scene_server/host_server/service/host.go
> 优化 add host 代码逻辑

- src/apiserver/app/server.go
- src/apiserver/service/service.go
- src/auth/authcenter/adaptor.go
- src/auth/authcenter/authcenter.go
- src/auth/authcenter/client.go
- src/auth/authcenter/id.go
- src/auth/authcenter/permit/permit.go
- src/auth/meta/resource.go
- src/auth/parser/chain.go
- src/auth/parser/event.go
- src/auth/parser/host.go
- src/auth/parser/parser.go
- src/auth/parser/process.go
- src/auth/parser/topolatest.go
- src/auth/parser/topology.go
- src/scene_server/event_server/app/options/options.go
- src/scene_server/event_server/app/server.go
- src/scene_server/event_server/service/service.go
- src/scene_server/event_server/service/subscription.go
- src/source_controller/objectcontroller/service/group_action.go
- src/source_controller/objectcontroller/service/objectcls_action.go
- src/storage/rpc/pool.go
> 支持动态注册“事件订阅”类型资源到IAM

- src/Makefile
> fixes enterprise package

- src/source_controller/coreservice/core/instances/instance_crud.go
- 新加，修改实例自动对create_time,last_time 字段赋值
- xxxx
- xxxx
close #1926 
@lowenitt
> V3.3.x 新加，修改实例自动对create_time,last_time 字段赋值

- src/scene_server/host_server/service/host.go
- xxxx
- xxxx
- 修改主机审计日志，变化前后一样 
close #1937
> 修改主机审计日志，变化前后一样

- src/apimachinery/toposerver/inst/inst.go
- src/scene_server/topo_server/core/model/classification.go
- src/source_controller/objectcontroller/service/privilege_action.go
- src/web_server/middleware/auth/auth_util.go
- src/web_server/middleware/auth/public.go
- src/web_server/middleware/login.go
- src/web_server/middleware/types/types.go
- 模型实例导入、导出、新建的权限校验问题。
close #1945
> fix: solve object instance auth problem. issue #1945

- src/web_server/middleware/auth/auth_util.go
> fix: delete object instance auth problem.

- src/scene_server/topo_server/core/model/object.go
- src/source_controller/objectcontroller/service/inst_action.go
- src/source_controller/objectcontroller/service/objectasst_action.go
> fix codecc warnings

- src/auth/authcenter/authcenter.go
- src/auth/authcenter/permit/permit.go
- src/auth/extensions/host.go
- src/common/metadata/hostserver.go
- src/scene_server/host_server/host.go
- src/scene_server/host_server/service/host.go
> bugfix for authorization

- src/source_controller/coreservice/service/service.go
- src/source_controller/coreservice/service/service_datasync_initfunc.go
- src/source_controller/coreservice/service/service_initfunc.go
- src/source_controller/coreservice/service/translate.go
- core service add action 单行过长
> refactor coreservice's add action to better line length

- src/auth/authcenter/authcenter.go
- src/auth/parser/chain.go
- src/auth/parser/event.go
- src/auth/parser/host.go
- src/auth/parser/netcollector.go
- src/auth/parser/process.go
- src/auth/parser/topolatest.go
- src/auth/parser/topology.go
> 优化paser执行效率

- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/service/inst.go
- 批量更新实例时，强制校验inst_id字段非空
- 批量创建实例时，input_type为空时返回失败（之前是成功）
> issue: #1964, issue: #1966

- src/scene_server/synchronize_server/app/server.go
- src/scene_server/synchronize_server/logics/background_synchronize.go
- src/scene_server/synchronize_server/logics/exception/file/exception.go
- src/scene_server/synchronize_server/logics/synchronize.go
- xxxx
- fix codecc warning 
- xxxx
> style:fix codecc warning issue #1961

- src/ui/src/components/layout/nav.vue
- src/ui/src/dictionary/auth.js
- src/ui/src/mixins/auth.js
- src/ui/src/router/index.js
- src/ui/src/setup/preload.js
- src/ui/src/store/modules/api/auth.js
- src/ui/src/views/business/index.vue
- src/ui/src/views/business/router.config.js
- src/ui/src/views/custom-query/router.config.js
- src/ui/src/views/eventpush/router.config.js
- src/ui/src/views/general-model/router.config.js
- src/ui/src/views/history/router.config.js
- src/ui/src/views/hosts/router.config.js
- src/ui/src/views/index/children/classify-item.vue
- src/ui/src/views/index/children/classify.vue
- src/ui/src/views/resource/router.config.js
> 特殊模型前端路由处理

- src/scene_server/admin_server/app/options/options.go
- src/scene_server/admin_server/app/server.go
- src/scene_server/admin_server/command/command.go
- src/scene_server/admin_server/command/export.go
- src/scene_server/admin_server/command/getter.go
- src/scene_server/admin_server/command/import.go
- src/scene_server/admin_server/command/types.go
- src/scene_server/admin_server/migrate.go
- src/scene_server/topo_server/core/operation/inst.go
> Codereview adminserver

- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/service/inst.go
> enhance parameter validate for batch instance create and update

- src/source_controller/hostcontroller/logics/logics.go
- xxxx
- xxxx
- 修复主机转移到空闲机/故障机模块。当主机属于多个模块的时候，主机的模块没有清除掉 
@hoffermei 
close #1978
> fix:host transfer default module ,can has other module issue #1978

- src/api_server/logics/v2/topo.go
- src/api_server/service/v2/userapi.go
- src/apimachinery/apiserver/api.go
- src/scene_server/host_server/service/host.go
- src/web_server/service/index.go
> 修复v3.2.x分支中codecc扫描结果

- src/source_controller/coreservice/app/server.go
- src/source_controller/coreservice/service/service.go
- xxxx
- coreservice获取到配置文件后再启动
- xxxx
close #1992 
@breezelxp
> feature: coreservice get config after, run service issue #1992

- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/inst.go
- fix not delete association when delete instance
cherry-pick from 3.1 #1994 3eaba29
close #2001
> fix not delete association when delete instance

- src/auth/authcenter/adaptor.go
- src/auth/extensions/base.go
- src/auth/extensions/business.go
- src/auth/extensions/host.go
- src/scene_server/host_server/logics/host.go
- src/scene_server/host_server/logics/logics.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/hostlock.go
- src/scene_server/host_server/service/module.go
- src/scene_server/host_server/service/phpapi.go
- src/scene_server/host_server/service/service.go
> modify  transfer host action id

- src/scene_server/proc_server/proc_service/service/openapi.go
- xxxx
- xxxx
- v2接口查询到不同业务下的同名称模块下的进程 #2003
> v2接口查询到不同业务下的同名称模块下的进程 #2003

- src/scene_server/proc_server/proc_service/service/openapi.go
- 修复v2接口查询到不同业务下的同名称模块下的进程问题 #2003
close #2003
> v2接口查询到不同业务下的同名称模块下的进程

- src/scene_server/synchronize_server/logics/synchronize.go
- 程序启动时，直接运行同步服务
- xxxx
- xxxx
> feature:run proc sync data issue #1780

- src/auth/authcenter/adaptor.go
- src/auth/authcenter/perm_biz.go
- src/auth/authcenter/perm_sys.go
> feature: add OperationLog

- src/auth/extensions/association.go
- src/auth/extensions/classification.go
- src/auth/extensions/instance.go
- src/scene_server/topo_server/core/operation/association.go
> register association type to iam bugfix

- src/apiserver/service/auth.go
- src/auth/authcenter/adaptor.go
- src/auth/authcenter/authcenter.go
- src/auth/extensions/classification.go
- src/auth/meta/meta.go
- src/common/metadata/webserver.go
- src/common/types/serverInfo.go
- src/scene_server/topo_server/core/operation/classification.go
- 资源注册无法注册，异常未处理。
- 登录接口返回数据不对
> fix: 资源注册与登录

- src/ui/src/dictionary/auth.js
- src/ui/src/router/index.js
- src/ui/src/setup/afterload.js
- src/ui/src/setup/preload.js
- src/ui/src/store/modules/api/auth.js
- src/ui/src/views/audit/router.config.js
- src/ui/src/views/custom-query/router.config.js
- src/ui/src/views/hosts/router.config.js
- src/ui/src/views/process/router.config.js
- src/ui/src/views/resource/router.config.js
- src/ui/src/views/topology/router.config.js
> ui: 无业务权限用户的伪鉴权

- src/apimachinery/rest/request.go
- src/source_controller/coreservice/core/association/instance.go
- src/source_controller/coreservice/core/association/kind_crud.go
- src/source_controller/coreservice/core/instances/instance.go
- src/source_controller/coreservice/service/instances.go
> 修复coreservice中数据缺少开发商的问题

- src/ui/src/setup/afterload.js
- src/ui/src/store/modules/global.js
> fix:ui: 修复后台模式判断错误的问题

- src/auth/extensions/attribute.go
- src/auth/extensions/attributegroup.go
- src/auth/extensions/base.go
- src/auth/extensions/business.go
- src/auth/extensions/modelunique.go
- src/auth/extensions/plat.go
- src/auth/extensions/types.go
- src/web_server/middleware/login.go
- register business to iam bug fix
- remove unecessary binary file
> 对接权限中心&移除多余二进制文件

- src/source_controller/coreservice/service/model.go
- src/source_controller/coreservice/service/translate.go
- src/source_controller/objectcontroller/service/common.go
- src/source_controller/objectcontroller/service/objectatt_action.go
> fixes translation #2024

- src/source_controller/objectcontroller/service/common.go
- src/source_controller/objectcontroller/service/objectatt_action.go
- fixes translate placeholder  #2024
> fixes translate placeholder branch v3.2

- src/auth/authcenter/client.go
- src/auth/extensions/attributegroup.go
- src/auth/extensions/business.go
- src/auth/extensions/instance.go
- src/auth/extensions/model.go
- src/auth/extensions/modelunique.go
- src/auth/extensions/types.go
- src/scene_server/topo_server/core/core.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/service/inst.go
- src/scene_server/topo_server/service/unique.go
- src/source_controller/coreservice/core/instances/instance.go
- src/source_controller/coreservice/core/instances/instance_crud.go
- src/source_controller/coreservice/core/instances/instance_validate.go
- src/web_server/middleware/login.go
> 权限中心调试 bugfix

- .gitignore
> feature: add gitignore file. issue #2032

- src/auth/extensions/types.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/service/association.go
- xxxx
- 主线拓扑的事务处理逻辑。
- 修复创建主线拓扑中的权限问题
> fix: fix create mainline object problem.

- src/ui/src/store/modules/menu.js
- src/ui/src/views/audit/router.config.js
- src/ui/src/views/business/index.vue
- src/ui/src/views/business/router.config.js
- src/ui/src/views/general-model/router.config.js
- src/ui/src/views/model-manage/children/field.vue
- src/ui/src/views/model-manage/children/verification.vue
- src/ui/src/views/resource/router.config.js
> ui: 模型管理页面操作鉴权

- .gitignore
> update gitignore file.

- src/auth/extensions/model.go
- src/scene_server/topo_server/core/operation/attribute.go
- src/scene_server/topo_server/core/operation/graphics.go
- src/scene_server/topo_server/core/operation/object.go
- 模型拓扑查看、更新权限相关
- 模型删除相关的属性权限相关
> 优化模型拓扑、视图、属性权限

- src/ui/src/router/index.js
- src/ui/src/store/modules/api/auth.js
- src/ui/src/views/general-model/router.config.js
- src/ui/src/views/model-manage/router.config.js
- 修复模型实例鉴权参数缺失parent_layers的问题
> fix:ui: 修复模型实例鉴权参数缺失parent_layers的问题

- src/apimachinery/coreservice/model/api.go
- src/apimachinery/coreservice/model/model.go
- src/common/metadata/core_service.go
- src/common/metadata/unique.go
- src/scene_server/topo_server/core/operation/unique.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/model/unique.go
- src/source_controller/coreservice/core/model/unique_crud.go
- src/source_controller/coreservice/service/model.go
- src/source_controller/objectcontroller/service/object_unique.go
- src/storage/dal/mongo/remote/mongo.go
- 修复 coreservice 创建模型唯一校验存在的问题 close #2041
> 修复 coreservice 创建模型唯一校验存在的问题

- src/ui/src/components/hosts/transfer/index.vue
- src/ui/src/components/ui/form/bool.vue
- src/ui/src/dictionary/auth.js
- src/ui/src/router/StatusError.js
- src/ui/src/router/index.js
- src/ui/src/store/modules/api/operation-audit.js
- src/ui/src/views/audit/router.config.js
- src/ui/src/views/business/index.vue
- src/ui/src/views/general-model/router.config.js
- src/ui/src/views/history/router.config.js
- src/ui/src/views/index/children/classify.vue
- src/ui/src/views/model-manage/children/index.vue
- src/ui/src/views/model-manage/router.config.js
- src/ui/src/views/process/module.vue
- src/ui/src/views/resource/index.vue
- src/ui/src/views/resource/router.config.js
- src/ui/src/views/topology/index.vue
> UI： 鉴权修复、路由跳转优化

- src/ui/src/components/hosts/transfer/index.vue
- src/ui/src/store/modules/api/object-biz.js
- src/ui/src/views/model-manage/index.vue
- 修复preload中metadata注入失败的问题
- 修复主机转移选择模块报错的问题
> ui: 修复preload中metadata注入失败的问题

- src/auth/extensions/association.go
- src/auth/extensions/attribute.go
- src/auth/extensions/attributegroup.go
- src/auth/extensions/audit.go
- src/auth/extensions/business.go
- src/auth/extensions/classification.go
- src/auth/extensions/dynamicgroup.go
- src/auth/extensions/host.go
- src/auth/extensions/model.go
- src/auth/extensions/modelunique.go
- src/auth/extensions/module.go
- src/auth/extensions/plat.go
- src/auth/extensions/process.go
- src/auth/extensions/set.go
> bugfix: check register empty resoruces

- src/auth/authcenter/adaptor.go
- src/auth/authcenter/perm_sys.go
- src/auth/extensions/business.go
- src/auth/parser/topolatest.go
- src/auth/parser/util.go
- src/common/definitions.go
- src/common/metadata/object.go
- 取消视图配置权限 #2066
- 解决新建的业务没有注册到权限中心 #2067
- 解决新建模型，唯一标识过长显示数据越界，但还是新建成功了 #2068
- 解决新建全局模型字段时报错 #2070
- 解决删除全局模型字段报错 #2071
- 解决点击查看实例的关联tab页，报解析授权信息失败 #2072
> v3.4.x  4/9 体验修复

- src/common/metadata/webserver.go
- src/scene_server/host_server/logics/hostsearch.go
- src/scene_server/host_server/logics/phpapi.go
- src/scene_server/host_server/logics/phpapi_searchhost.go
- src/scene_server/host_server/service/phpapi.go
- src/scene_server/proc_server/logics/gsehandle.go
- src/scene_server/proc_server/proc_service/service/openapi.go
- src/scene_server/proc_server/proc_service/service/process.go
- src/scene_server/proc_server/proc_service/service/template.go
- src/web_server/logics/excel.go
- src/web_server/middleware/user/plugins/method/self/userinfo.go
- xxxx
- 规范化代码，解决golint提示
- 日志是用request id
- xxxx
@breezelxp
> style:fix codecc warning issue #1949

- src/auth/extensions/model.go
- src/auth/extensions/modelunique.go
- src/scene_server/topo_server/service/auditlog.go
- src/scene_server/topo_server/service/unique.go
> 模型唯一约束权限控制调整 #2091

- src/ui/config/index.js
> UI：添加权限中心配置

- docs/overview/experience.md
> 去掉公有云版体验相关描述

- src/auth/authcenter/permit/permit.go
- src/auth/extensions/business.go
- src/source_controller/objectcontroller/service/topographics.go
- 模型拓扑位置更新去除业务信息。
- 资源池主机转移到空闲机，修改多个业务的校验策略。
> 模型拓扑与主机转移更新优化

- src/auth/authcenter/authcenter.go
- src/scene_server/host_server/app/server.go
- src/web_server/service/index.go
> 支持选择性启用权限中心相关功能

- src/ui/.gitignore
- src/ui/config/index.js
- src/ui/index.html
- src/ui/src/api/index.js
- src/ui/src/api/middleware/auth.js
- src/ui/src/api/middleware/business.js
- src/ui/src/api/middleware/index.js
- src/ui/src/api/middleware/util.js
- src/ui/src/dictionary/menu.js
- src/ui/src/router/index.js
- src/ui/src/setup/preload.js
- src/ui/src/store/index.js
- src/ui/src/store/modules/api/user-privilege.js
- src/ui/src/store/modules/menu.js
- src/ui/src/views/permission/authority.vue
- src/ui/src/views/permission/business.vue
- src/ui/src/views/permission/index.vue
- src/ui/src/views/permission/role-form.vue
- src/ui/src/views/permission/role.vue
- src/ui/src/views/permission/router.config.js
> UI: 添加cmdb内置权限控制

- src/ui/src/api/middleware/auth.js
- src/ui/src/api/middleware/business.js
- src/ui/src/api/middleware/util.js
- src/ui/src/setup/preload.js
- src/ui/src/views/audit/router.config.js
- src/ui/src/views/general-model/router.config.js
- src/ui/src/views/model-topology/children/create-relation.vue
- src/ui/src/views/permission/authority.vue
> ui: 资源池、操作审计、事件推送权限映射

- src/common/mapstr/struct.go
- src/web_server/app/options/options.go
- src/web_server/middleware/login.go
> 解决权限更新只更新一部分的问题

- src/apiserver/core/compatiblev2/logic/topo.go
- src/apiserver/core/compatiblev2/service/host.go
- src/apiserver/core/compatiblev2/service/search.go
- src/apiserver/core/compatiblev2/service/set.go
- src/common/metadata/core_service_synchronize.go
- src/scene_server/host_server/logics/hostsearch.go
- src/scene_server/host_server/logics/phpapi.go
- src/scene_server/host_server/logics/phpapi_searchhost.go
- src/scene_server/host_server/service/favourite.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/module.go
- src/scene_server/host_server/service/phpapi.go
- src/scene_server/host_server/service/userapi.go
- src/scene_server/proc_server/logics/instanceutil.go
- src/scene_server/proc_server/logics/process.go
- src/scene_server/proc_server/logics/topo.go
- src/scene_server/proc_server/proc_service/service/openapi.go
- src/scene_server/proc_server/proc_service/service/proc2template.go
- src/scene_server/proc_server/proc_service/service/process.go
- src/scene_server/proc_server/proc_service/service/template.go
- src/source_controller/coreservice/core/datasynchronize/association.go
- src/source_controller/coreservice/core/datasynchronize/instance.go
- src/source_controller/coreservice/core/datasynchronize/model.go
- src/web_server/logics/excel.go
- src/web_server/middleware/user/plugins/method/self/userinfo.go
- xxxx
-  codecc代码扫描优化
- xxxx
close  #2119
>  codecc代码扫描优化

- src/scene_server/host_server/logics/import.go
- xxxx
- xxxx
-  导入主机失败
close #2124
> V3.4.x hostimport 导入主机失败

- src/auth/authcenter/authcenter.go
- src/auth/authcenter/permit/permit.go
- src/auth/extensions/business.go
- src/auth/extensions/host.go
- src/auth/extensions/instance.go
- src/auth/extensions/model.go
- src/auth/parser/topolatest.go
- src/auth/parser/topology.go
- src/scene_server/admin_server/synchronizer/handler/host.go
- src/scene_server/admin_server/synchronizer/handler/instance.go
- src/scene_server/topo_server/core/operation/object.go
- src/web_server/app/server.go
- src/web_server/logics/fields.go
- src/web_server/logics/host.go
- src/web_server/service/host.go
- src/web_server/service/object.go
- 加入鉴权后主机数据导出大部分字段不见了
close #2118
> 主机导出数据缺失修复 issue #2118

- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/service/service.go
- src/scene_server/topo_server/service/service_business_initfunc.go
- src/scene_server/topo_server/service/service_initfunc.go
- src/web_server/service/host.go
> topo service route 代码漏提交日志优化

- src/scene_server/topo_server/core/privilege/privilege.go
- src/web_server/middleware/auth/auth_util.go
- src/web_server/middleware/auth/public.go
> 解决给模型授了所有权限，但是没法进行编辑、新建、删除 #2142

- src/common/paraparse/app.go
- src/common/paraparse/host.go
修复的问题：
- v3.4.x：search_host接口无法使用"^"符号正则搜索数据
issue:
#2133
> v3.4.x：search_host接口无法使用"^"符号正则搜索数据

- src/auth/authcenter/authcenter.go
- src/auth/authcenter/permit/permit.go
- src/auth/extensions/business.go
- src/auth/extensions/host.go
- src/auth/extensions/instance.go
- src/auth/extensions/model.go
- src/auth/parser/topolatest.go
- src/auth/parser/topology.go
- src/scene_server/admin_server/synchronizer/handler/host.go
- src/scene_server/admin_server/synchronizer/handler/instance.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/service/service.go
- src/scene_server/topo_server/service/service_business_initfunc.go
- src/scene_server/topo_server/service/service_initfunc.go
- src/web_server/app/server.go
- src/web_server/logics/fields.go
- src/web_server/logics/host.go
- src/web_server/service/host.go
- src/web_server/service/object.go
-  merge v3.4.x branch code 
- xxxx
- xxxx
> Feature v3.4.0 merge v3.4.x

- src/auth/auth.go
- src/auth/authcenter/authcenter.go
- src/auth/extensions/association.go
- src/auth/extensions/attribute.go
- src/auth/extensions/attributegroup.go
- src/auth/extensions/audit.go
- src/auth/extensions/base.go
- src/auth/extensions/business.go
- src/auth/extensions/classification.go
- src/auth/extensions/dynamicgroup.go
- src/auth/extensions/host.go
- src/auth/extensions/instance.go
- src/auth/extensions/model.go
- src/auth/extensions/modelunique.go
- src/auth/extensions/module.go
- src/auth/extensions/plat.go
- src/auth/extensions/process.go
- src/auth/extensions/set.go
- src/scene_server/admin_server/synchronizer/synchronizer.go
- src/scene_server/topo_server/core/operation/inst.go
- src/web_server/logics/inst.go
- 权限注册/鉴权入口时加enabled检测，确保关闭时没有多余请求
> 权限注册/鉴权入口时加enabled检测，确保关闭时没有多余请求 issue #2139

- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/x19.04.16.01/pkg.go
- src/scene_server/admin_server/upgrader/x19.04.16.01/removeDescriptionField.go
- src/scene_server/topo_server/service/service_business_initfunc.go
- 删除唯一项的方法改为post
- 删除description字段
> 删除唯一项的方法改为post

- src/ui/src/api/index.js
- src/ui/src/api/middleware/auth.js
- src/ui/src/components/ui/selector/business.vue
- src/ui/src/store/modules/api/object-unique.js
- src/ui/src/views/model-manage/children/verification.vue
- 修改唯一校验删除接口为post
- 主机资源下的主机无法编辑的问题
- 修复业务下拉组件错误的删除了请求头的问题
> UI: 业务资源主机编辑权限修正

- src/common/mapstr/struct.go
- src/common/metadata/classification.go
- src/source_controller/coreservice/core/instances/instance.go
- xxxx
- xxxx
- 修复mapstr map 转换到struct panic 问题
- 修复更新实例不存在，没有错误提示问题
close #2153 
close #2154 
@lowenitt
> Feature v3.4.0 mapstr panic,  更新实例不存在报错

- src/ui/src/utils/tools.js
> ui: 修复部分字段为空时显示不正确的问题

- src/scene_server/topo_server/core/operation/association.go
- src/web_server/logics/association.go
- src/web_server/logics/excel.go
- src/web_server/logics/fields.go
- src/web_server/logics/object.go
- src/web_server/middleware/login.go
- 解决不能建立单关联实例关系 #2151
- 支持通过组合唯一导出实例关联
> 解决不能建立单关联实例关系 #2151

- src/api_server/logics/v2/common/converter/converter.go
- 操作系统支持AIX 操作系统类型
- xxxx
- xxxx
> feature: support aix os type issue #2161

- src/scene_server/host_server/logics/hostsearch.go
- src/source_controller/coreservice/core/host/modulehost/transfer.go
- xxxx
- xxxx
- 修复转移主机，缺少集群id的bug
> fix: transfer host miss setID issue #2163

- src/scene_server/topo_server/service/graphics.go
- src/scene_server/topo_server/service/object_group.go
- src/scene_server/topo_server/service/privilege_role.go
- src/scene_server/topo_server/service/service.go
- src/scene_server/topo_server/service/service_initfunc.go
- src/scene_server/topo_server/service/types.go
- 处理topo server统一加parse metadata后部分接口异常问题
close #2172
> 处理topo server统一加parse metadata后部分接口异常问题 issue #2172

- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/util/util.go
- src/source_controller/coreservice/core/host/modulehost/transfer.go
- xxxx
- xxxx
- 关联关系对象为主机， 在实例详情页面的关联关系tab中，查看主机实例报错的问题
- 关联关系对象为主机， 在实例详情页面的关联关系tab中，查看主机实例数据返回无结果的问题
- 主机转移到多个模块时，关系表中setID异常的问题
@hoffermei
> Feature v3.4.0 关联关系主机实例展示和主机转移集群

- src/source_controller/coreservice/core/instances/instance_validate.go
- src/source_controller/coreservice/core/instances/validator_attr.go
- src/source_controller/coreservice/core/instances/validator_util.go
> 修复浮点型类型数据不校验值范围问题

- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/v3.0.8/objAttDescData.go
- src/scene_server/admin_server/upgrader/x19.04.16.02/pkg.go
- src/scene_server/admin_server/upgrader/x19.04.16.02/updateFranceName.go
- src/scene_server/topo_server/core/inst/inst.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/service/inst_module.go
- 解决 主机基础信息-所在国家-法国出现文字重复 #2167
- 解决 同名模块创建失败的提示不够友好 #2168
> 主机基础信息-所在国家-法国出现文字重复等

- src/ui/src/assets/scss/admin-view.scss
- src/ui/src/components/hosts/filter/_filter.vue
- src/ui/src/components/ui/form/date-range.vue
- src/ui/src/store/index.js
- src/ui/src/store/modules/api/host-batch.js
- src/ui/src/views/audit/index.vue
- src/ui/src/views/resource/index.vue
- 时间组件添加清空按钮
- 更新管理后台导航样式
- 修复收藏界面异常
- 主机导出调整
> 时间组件添加按钮/更新样式/修复主机导出和收藏界面

- src/scene_server/topo_server/core/types/types.go
- src/scene_server/topo_server/service/service.go
- toposerver 支持request id 
- xxxx
- xxxx
close #2210
> V3.4.x toposerver requestid

- src/ui/src/components/audit-history/audit-history.vue
- src/ui/src/components/ui/form/float.vue
- src/ui/src/components/ui/form/form.vue
- src/ui/src/components/ui/form/int.vue
- src/ui/src/components/ui/slider/slider.vue
- src/ui/src/setup/validate.js
- src/ui/src/store/modules/api/global-models.js
- src/ui/src/store/modules/api/user-custom.js
- src/ui/src/views/business/index.vue
- src/ui/src/views/custom-query/preview.vue
- src/ui/src/views/model-association/_detail.vue
- src/ui/src/views/model-association/index.vue
- src/ui/src/views/model-topology/children/create-relation.vue
- src/ui/src/views/model-topology/children/display-config.vue
- src/ui/src/views/model-topology/index.vue
- src/ui/src/views/permission/role-form.vue
- 模型拓扑调整
- 关联类型页搜索问题
- 修改关联类型正则
- 去除预览分组模块与集群排序
- 筛选可选关联类型
- 侧滑标题溢出处理
- 限制新建角色名长度
- 数字类型支持输入负数
- 变更记录搜索当前页码错误
- 业务搜索参数与分页调整
> 3.2.x 回归调整

- src/ui/src/api/index.js
- src/ui/src/components/hosts/table/index.vue
- src/ui/src/components/ui/slider/slider.vue
- src/ui/src/magicbox/src/bk-magic-ui/src/dialog.scss
- src/ui/src/mixins/form.js
- src/ui/src/store/modules/api/global-models.js
- src/ui/src/utils/tools.js
- src/ui/src/views/general-model/index.vue
- src/ui/src/views/model-manage/children/index.vue
- src/ui/src/views/model-topology/index.vue
- src/ui/src/views/process/index.vue
- src/ui/src/views/topology/index.vue
- 优化magicbox弹窗文字过长断行的问题
- 导出实例改为异步
- 修复侧滑标题超长溢出的问题
- 修复主机表格显示字段业务名未固定的问题
- 修复业务拓扑自定义层级节点主机查询不到的问题
- 修复修改模型名称头部标题未更新的问题
- 修复停用模型仍在拓扑图中出现的问题
- 修复批量编辑可以编辑唯一校验字段的问题
- 修复实例空属性值显示异常的问题
> 3.2.x 优化回归

- src/ui/src/components/audit-history/audit-history.vue
- src/ui/src/views/business/index.vue
- src/ui/src/views/model-association/index.vue
- 优化业务与关联类型搜索代码
- 修复业务变更记录搜索问题
> 调整业务与关联类型搜索代码 / 修复业务变更记录搜索问题

- src/ui/src/components/ui/form/float.vue
- src/ui/src/utils/tools.js
- src/ui/src/views/model-topology/index.old.vue
- 修复模型拓扑中自定义模型颜色显示不正确的问题
- 修复浮点数属性无法输入负数的问题
- 修复实例空字段显示异常的问题
> UI: 3.4.0 缺陷修复

- src/scene_server/host_server/logics/hostsearch.go
- src/scene_server/topo_server/core/operation/import_association.go
- src/scene_server/topo_server/service/object_association.go
- xxxx
- 新加参数解析失败日志
- 导入关联关系成功。不再提示用户
- 导出主机返回业务名
- xxxx
close #2206  
close #2213
> v3.2.x 导入相关优化

- src/source_controller/coreservice/core/instances/instance.go
- src/source_controller/coreservice/core/instances/instance_crud.go
- xxxx
- xxxx
- 修复多租户下无法返回全部数据的问题
close #2216
> fix: multip-tenant use superadmin not return all data issue #2216

- src/scene_server/host_server/logics/hostsearch.go
- src/scene_server/topo_server/core/operation/import_association.go
- src/scene_server/topo_server/service/object_association.go
- xxxx
- 新加参数解析失败日志
- 导入关联关系成功。不再提示用户
- 导出主机返回业务名
- xxxx
> v3.4.x 导入相关优化

- src/common/mapstr/mapstr.go
- src/common/metadata/netdevice.go
- src/common/metric/api.go
- src/common/metric/client.go
- src/common/metric/floatOrStr.go
- src/common/metric/go-metric.go
- src/common/metric/plugin/counter.go
- src/common/metric/plugin/integer.go
- src/common/metric/type.go
- src/common/util/lib.go
- src/scene_server/admin_server/command/command.go
- src/scene_server/datacollection/datacollection/porter.go
- src/scene_server/topo_server/core/model/object.go
- src/scene_server/topo_server/core/operation/association_mainline_inst.go
- src/scene_server/topo_server/service/privilege_role.go
- src/source_controller/coreservice/core/model/unique_crud.go
- src/web_server/service/index.go
> fixes warning

- src/source_controller/coreservice/core/host/modulehost/transfer.go
-  
- xxxx
- 主机转移到内置模块失败
close #2221
> V3.4.x fix hosttoinnermodule

- src/auth/parser/host.go
- src/scene_server/topo_server/core/operation/association.go
- src/scene_server/topo_server/core/operation/inst.go
- src/scene_server/topo_server/service/association.go
> 解析metadata bugfix

- src/common/universalsql/mongo/condition_private.go
- src/common/universalsql/mongo/condition_test.go
- xxxx
- xxxx
- 修复NewConditionFromMapStr不支持布尔，数据类型的参数。
close #2229
> fix: NewConditionFromMapStr support boolean, slice, struct close #2229

- src/ui/index.html
> feature:ui: 默认使用内置权限

- src/web_server/app/options/options.go
- src/web_server/app/server.go
- src/web_server/middleware/login.go
- src/web_server/service/index.go
>  update webserver config

- src/apimachinery/rest/request.go
- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/x18.12.12.06/pkg.go
- src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
- src/scene_server/topo_server/core/operation/association.go
- src/web_server/logics/fields.go
- src/web_server/service/inst.go
- src/web_server/service/service.go
- vendor/github.com/golang/glog/glog.go
- 解决 模型停用期间，实例仍可被其他有关系的模型实例关联 #2235
- 解决 无法导出系统预设模型实例，接口返回服务器内部错误500且没有其他内容 #2236
> Solve 3.2.7

- scripts/init.py
- init.py 代码规范
- 配置生成支持auth相关配置项
close #2244
> init.py代码规范及配置生成支持auth相关配置项

- src/web_server/app/options/options.go
- src/web_server/app/server.go
- src/web_server/service/index.go
-  rollback auth config for iam in webserver.
> optimize: rollback auth config for iam in webserver.

- src/apimachinery/apiserver/api.go
- src/apiserver/core/compatiblev2/service/userapi.go
> 修复codecc告警

- src/ui/src/views/resource/index.vue
- src/ui/src/views/status/require-business.vue
> fix:ui: 修复桌面版切换app失败的问题

- src/web_server/service/index.go
> 补充使用iam时本地鉴权跳过逻辑

- src/apimachinery/clientset_coreservice_inst_test.go
- src/apimachinery/clientset_coreservice_model_test.go
- src/apimachinery/discovery/server.go
- src/apimachinery/rest/request.go
- src/apiserver/core/compatiblev2/common/utils/utils.go
- src/apiserver/core/compatiblev2/logic/topo.go
- src/apiserver/core/compatiblev2/service/host.go
- src/apiserver/core/compatiblev2/service/set.go
- src/auth/parser/host.go
- src/auth/parser/parser.go
- src/common/backbone/configcenter/cc.go
- src/common/core/cc/api/api_resource.go
- src/common/metadata/classification.go
- src/scene_server/topo_server/service/service.go
- src/web_server/service/util.go
- rollback json package to encoding/json.
> optimize: rollback json package to encoding/json.

- scripts/Makefile
> update make file

- src/apimachinery/discovery/server.go
- src/common/types/serverInfo.go
- xxxx
- xxxx
- 使用IsMaster的时候。服务不存在panic的问题
close #2261
> fix:discovery not exist server panic issue #2261

- scripts/init.py
- 配置文件排版
- 配置生成脚本redis host中去掉端口号 
close #2283
> 配置生成脚本redis host中去掉端口号 #2283

- src/ui/src/components/hosts/table/index.vue
> fix:ui: 修复主机表格可能出现无表头字段的问题

- src/scene_server/host_server/logics/phpapi.go
- src/scene_server/host_server/service/host.go
- xxxx
- xxxx
- 修复克隆主机，提示主机未发现的问题
close #2287
> fix: clone host tips host not found issue #2287

- src/apimachinery/hostserver/apis.go
- src/auth/extensions/host.go
- src/scene_server/host_server/service/host.go
- src/scene_server/host_server/service/module.go
- src/scene_server/host_server/service/phpapi.go
- bugfix：id字段转换方案切换 
close #2284
> id字段转换换成GetInt64ByInterface

- src/ui/src/components/import/import.vue
- src/ui/src/views/model-manage/children/index.vue
> fix:ui: 修复导入文件对响应的处理配置不正确的问题

- src/scene_server/admin_server/upgrader/x19.04.16.02/updateFranceName.go
- src/source_controller/coreservice/core/instances/validator_attr.go
- src/source_controller/coreservice/core/instances/validator_util.go
- src/source_controller/coreservice/service/translate.go
- 修复官方bson库导致的解析enum失败问题 #2289
> 修复官方bson库导致的解析enum失败问题 #2289

- src/common/mapping.go
- src/common/metadata/core_service.go
- src/scene_server/admin_server/imports.go
- src/scene_server/admin_server/upgrader/x18.12.12.06/pkg.go
- src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
- src/scene_server/topo_server/core/operation/object.go
- src/source_controller/coreservice/service/model.go
- 补充内置模型 cherry-pick from 3.2
- 禁止删除内置模型
> 补充18.12.12.06

- src/web_server/service/inst.go
- fix export object instance nil map issue
> fix export object instance nil map issue

- scripts/generate.py
- scripts/ip.py
- scripts/license.py
> 重构：py文件代码规范 #2303

- src/ui/src/api/index.js
> UI: 修复导出文件无法打开的问题

- src/web_server/service/service.go
-  下载模型导入模版支持改为POST方法。支持业务模式
- xxxx
- xxxx
issue #2314
> V3.4.x 下载模型导入模版支持改为POST方法。支持业务模式

- src/ui/src/api/index.js
- src/ui/src/components/import/import.vue
> fix:ui: 下载模板get => post

- src/auth/authcenter/permit/permit.go
> optimize get business topology auth

- src/common/metadata/core_service.go
- src/source_controller/coreservice/core/mainline/class.go
- src/source_controller/coreservice/core/mainline/manager.go
> 业务拓扑查询主机接口优化

- src/auth/authcenter/id.go
> demand: add host instance auth.

- docs/overview/upgrade-from-ce.md
- readme.md
> 文档：用开源CMDB替换社区版

- src/common/metadata/process.go
> metadata data structure for process

- src/framework/core/config/configcenter.go
- src/framework/core/config/factory.go
- src/framework/core/discovery/rdiscover.go
- src/framework/main.go
> 修复framework编译不通过的问题

- src/apimachinery/coreservice/coreservice.go
- src/apimachinery/coreservice/process/api.go
- src/apimachinery/coreservice/process/process.go
- src/common/metadata/core_service.go
- src/common/metadata/process.go
- 绑定地址类型新增枚举类型表示
- 协议类型新增枚举类型表示
close #2352
> define enum type for socket bind type and protocol type

- src/storage/dal/db.go
- src/storage/dal/mongo/local/mock_mongo.go
- src/storage/dal/mongo/local/mongo.go
- src/storage/dal/mongo/remote/collection.go
-  dal 中mongodb 的update支持指定操作符
- xxxx
- xxxx
close #2357
> feature:  mongo update support operator  issue #1780 #2357 #2340

- src/auth/parser/topology.go
> add proc fresh auth.

- src/common/errInfo.go
- src/common/metadata/metadata.go
- src/common/metadata/process.go
- src/common/tablenames.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/process/process.go
- src/source_controller/coreservice/core/process/process_template.go
- src/source_controller/coreservice/core/process/service_category.go
- src/source_controller/coreservice/core/process/service_instance.go
- src/source_controller/coreservice/core/process/service_template.go
- src/source_controller/coreservice/service/process_template.go
- src/source_controller/coreservice/service/service.go
- src/source_controller/coreservice/service/service_category.go
- src/source_controller/coreservice/service/service_initfunc.go
- src/source_controller/coreservice/service/service_instance.go
- src/source_controller/coreservice/service/service_process_initfunc.go
- src/source_controller/coreservice/service/service_template.go
> 实现进程相关coreservice接口 #2361

- src/auth/parser/topology.go
- 调整apiserver上操作审计鉴权
close #2362
> 调整apiserver上操作审计鉴权 #2362

- src/ui/src/views/model-topology/index.old.vue
> optimize:ui: 业务模式下拓扑视图中不允许删除公有模型的位置

- readme.md
- optimize: add experience cmdb online support.
> optimize: add experience cmdb online support.

- src/apimachinery/synchronize/synchronizeserver/syncrhonize.go
- src/common/definitions.go
- src/common/util/lib.go
- src/framework/core/discovery/rdiscover.go
- src/scene_server/synchronize_server/app/options/options.go
- src/scene_server/synchronize_server/app/server.go
- src/scene_server/synchronize_server/logics/assocation.go
- src/scene_server/synchronize_server/logics/background_synchronize.go
- src/scene_server/synchronize_server/logics/inst.go
- src/scene_server/synchronize_server/logics/model.go
- src/scene_server/synchronize_server/logics/synchronize.go
- src/source_controller/coreservice/core/datasynchronize/data_clear.go
- src/source_controller/coreservice/core/datasynchronize/identifier.go
- src/source_controller/coreservice/core/datasynchronize/util.go
-  新加根据身份做多个cmdb之间数据同步功能
- 优化数据存储结构
- xxxx
> feature: synchronize data baseed on identifier issue #1780

- src/ui/src/views/audit/index.vue
> update:ui: 操作审计过滤条件选中清空问题

- src/auth/parser/topolatest.go
- src/auth/parser/topology.go
- src/scene_server/topo_server/core/operation/object.go
- src/web_server/service/inst.go
- fix update object name but not update to iam problem, but still has this problem for the inner object like bk_tomcat, which is caused by the multiple-language support and translate problem.
> fix: fix update object name but not update to iam problem

- src/scene_server/host_server/logics/object.go
- src/source_controller/coreservice/core/instances/instance.go
> 主机查询失败 #2328

- src/apimachinery/coreservice/process/api.go
- src/apimachinery/coreservice/process/process.go
- src/apiserver/service/url.go
- src/common/http/rest/contexts.go
- src/common/http/rest/rest.go
- src/scene_server/proc_server/app/server.go
- src/scene_server/proc_server/service/service.go
- add proce server api to apiserver router.
> optimize: add proce server api to apiserver router.

- src/common/mapstr/convert.go
- src/common/metadata/metadata.go
- src/common/metadata/process.go
- src/source_controller/coreservice/core/process/process.go
- src/source_controller/coreservice/core/process/process_instance_relation.go
- src/source_controller/coreservice/core/process/process_template.go
- src/source_controller/coreservice/core/process/service_category.go
- src/source_controller/coreservice/core/process/service_instance.go
- src/source_controller/coreservice/core/process/service_template.go
- coreservice中进程模块metadata采用结构体替换mapstr
> coreservice中进程模块metadata采用结构体替换mapstr #2439

- src/common/util/lib.go
- ExtractRequestIDFromContext 输入参数空指针异常
> bugfix 处理ExtractRequestIDFromContext空指针问题

- src/scene_server/topo_server/core/operation/object.go
- src/scene_server/topo_server/core/operation/types.go
- 修复自定义模型通过导入方式修改后，字段的页面操作（编辑，删除）灰掉问题 #2446
> 修复自定义模型通过导入方式修改后，字段的页面操作（编辑，删除）灰掉问题

- src/scene_server/host_server/logics/module.go
- src/scene_server/host_server/logics/phpapi_host.go
- src/source_controller/coreservice/core/instances/event.go
- src/source_controller/coreservice/core/instances/instance.go
- src/source_controller/coreservice/service/service.go
- 实例新加支持事件
-  实例修改支持事件
-  实例删除支持事件
- xxxx
- xxxx
close  #2432
> V3.4.x 实例删除，更新，新加新加事件处理

- src/apimachinery/healthz/healthz.go
- src/apimachinery/rest/request.go
- src/apiserver/service/healthz.go
- src/apiserver/service/service.go
- src/scene_server/admin_server/app/server.go
- src/scene_server/admin_server/service/service.go
- src/scene_server/datacollection/app/server.go
- src/scene_server/datacollection/service/service.go
- src/scene_server/event_server/app/server.go
- src/scene_server/event_server/service/service.go
- src/scene_server/host_server/app/server.go
- src/scene_server/host_server/service/service.go
- src/scene_server/proc_server/app/server.go
- src/scene_server/proc_server/proc_service/service/service.go
- src/scene_server/topo_server/app/server.go
- src/scene_server/topo_server/core/operation/health.go
- src/scene_server/topo_server/service/service.go
- src/source_controller/coreservice/app/server.go
- src/source_controller/coreservice/service/health.go
- src/source_controller/coreservice/service/service.go
- src/source_controller/coreservice/service/service_initfunc.go
- src/source_controller/hostcontroller/app/server.go
- src/source_controller/hostcontroller/service/service.go
- src/source_controller/objectcontroller/app/server.go
- src/source_controller/objectcontroller/service/service.go
- src/source_controller/proccontroller/app/server.go
- src/source_controller/proccontroller/service/service.go
- toposerver，coreservice 新加healthz 处理逻辑
- 在场景层新加coreservice的healthz接口调用
- 将healthz接口地址有/xx/xx/healthz变成/healthz接口
- 优化healthz接口apimachinery接口
- 修复healthz接口展示错误
issue #2368
> V3.4.x healthz  功能新加

- src/apimachinery/rest/client.go
- src/apimachinery/rest/request.go
- src/common/metadata/metadata.go
- src/scene_server/topo_server/core/operation/association.go
- fix url wrapper, metadata parse issue and association id update issue
> optimize: fix url wrapper, metadata parse issue and association id 

- src/apimachinery/coreservice/process/api.go
- src/common/metadata/core_service.go
- src/common/metadata/process.go
- src/scene_server/proc_server/app/server.go
- src/scene_server/proc_server/logics/processinstance.go
- src/scene_server/proc_server/service/serviceinstance.go
- src/scene_server/validator/valid_basic.go
- src/source_controller/coreservice/core/instances/instance_validate.go
- src/source_controller/coreservice/core/instances/validator_attr.go
- src/source_controller/coreservice/core/process/process.go
- src/source_controller/coreservice/core/process/service_instance.go
- src/source_controller/coreservice/core/process/service_template.go
- src/source_controller/coreservice/service/service_category.go
> 服务实例/进程相关接口调整

- src/scene_server/host_server/logics/hostsearch.go
> 主机查询支持按id查询 #2461

- src/apimachinery/coreservice/host/api.go
- src/apimachinery/coreservice/host/host.go
- src/common/metadata/inst.go
- src/common/metadata/process.go
- src/scene_server/event_server/identifier/identifier.go
- src/scene_server/topo_server/core/operation/identifier.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/host/identifier.go
- src/source_controller/coreservice/service/host.go
- src/source_controller/coreservice/service/service_initfunc.go
-  coreservice新加主机身份查询接口
-  优化toposerver主机身份接口
- xxxx
close #2421
> V3.5.x host identifier 相关调整

- src/ui/src/components/ui/form/float.vue
- src/ui/src/components/ui/form/int.vue
- src/ui/src/components/ui/form/longchar.vue
- src/ui/src/components/ui/form/objuser.vue
- src/ui/src/components/ui/form/singlechar.vue
- src/ui/src/views/host-details/children/association-create.vue
- src/ui/src/views/host-details/children/association-property-filter.vue
- src/ui/src/views/host-details/children/history.vue
- src/ui/src/views/host-details/children/info.vue
- src/ui/src/views/host-details/children/property.vue
- src/ui/src/views/host-details/index.vue
> UI: 主机详情优化

- src/ui/src/components/ui/form/bool.vue
- src/ui/src/router/index.js
- src/ui/src/store/modules/view/host-details.js
- src/ui/src/views/host-details/children/association-list-table.vue
- src/ui/src/views/host-details/children/association.vue
- src/ui/src/views/host-details/children/property.vue
- src/ui/src/views/host-details/index.vue
> UI: 主机详情关联表格全部展开

- src/auth/authcenter/adaptor.go
- src/auth/authcenter/permit/permit.go
- src/auth/meta/resource.go
- src/auth/parser/process.go
- src/auth/parser/topolatest.go
- src/common/definitions.go
- src/common/metadata/process.go
- src/scene_server/proc_server/service/processtemplate.go
- src/scene_server/proc_server/service/service.go
- 新增进程迭代相关接口在apiserver中的权限校验功能
- 删除了原有进程中下掉接口的鉴权能力。
> feature: add process related auth method in api server.

- src/web_server/service/host.go
- src/web_server/service/inst.go
- src/web_server/service/object.go
- xxxx
-  规范主机，实例，模型导入模版，导出数据excel文件名
- xxxx
关联pull request  #2481
close #2479
> refactor: change import and export excel file name  issue #2479

- src/apimachinery/coreservice/process/api.go
- src/apimachinery/coreservice/process/process.go
- src/common/definitions.go
- src/common/metadata/core_service.go
- src/common/metadata/process.go
- src/scene_server/proc_server/service/serviceinstance.go
- src/source_controller/coreservice/core/core.go
- src/source_controller/coreservice/core/process/process.go
- src/source_controller/coreservice/core/process/process_instance_relation.go
- src/source_controller/coreservice/core/process/process_template.go
- src/source_controller/coreservice/core/process/service_category.go
- src/source_controller/coreservice/core/process/service_instance.go
- src/source_controller/coreservice/core/process/service_template.go
- src/source_controller/coreservice/service/process_instance_relation.go
- src/source_controller/coreservice/service/process_template.go
- src/source_controller/coreservice/service/service_category.go
- src/source_controller/coreservice/service/service_instance.go
- src/source_controller/coreservice/service/service_template.go
- 单个删除接口改成支持批量删除，支持所有字段的删除过滤条件
close #2483
> coreservice 删除关联关系改成批量接口 #2483

- src/apimachinery/apiserver/api.go
- src/apimachinery/apiserver/apiserver.go
- src/web_server/logics/netdevice.go
- src/web_server/logics/netproperty.go
- src/web_server/service/netdevice.go
- src/web_server/service/netproperty.go
- src/web_server/service/service.go
>  修复web_server 中网络设备采集接口相关代码

- src/apimachinery/coreservice/process/api.go
- src/apimachinery/coreservice/process/process.go
- src/common/metadata/core_service.go
- src/common/metadata/process.go
- src/scene_server/proc_server/service/service.go
- src/scene_server/proc_server/service/servicetemplate.go
- src/source_controller/coreservice/service/service_process_initfunc.go
- src/source_controller/coreservice/service/service_template.go
- 新增服务模板详情接口，提供使用统计信息
close #2530
> 新增服务模板详情接口 #2530

- src/web_server/logics/host.go
- src/web_server/logics/inst.go
- issue: #2400 
由于本地git设置问题，这个PR是重新提交。之前的PR已作废。
> fix error nil dereferences and duplicate lines

- src/ui/src/setup/preload.js
- src/ui/src/views/model-manage/children/relation-detail/index.vue
> UI:修复编辑关联关系时唯一标识显示不正确的问题

- src/ui/src/setup/preload.js
- src/ui/src/views/model-manage/children/relation-detail/index.vue
> UI: 修复编辑关联关系时唯一标识显示不正确的问题

- src/common/metadata/core_service.go
- src/scene_server/proc_server/logics/processinstance.go
- src/scene_server/proc_server/service/serviceinstance.go
- src/source_controller/coreservice/core/process/service_instance.go
- 服务实例同步时，模板ID参数与实例ID缺少一致性校验
- 新增进程，对比出来了，同步没有生效
- 修改模板部分字段属性，对比没出来
- 新增进程，对比时显示出来的进程名称不对
- 同步模板接口报序列化json失败
> 服务实例与模板对比/同步 #2557

- src/apiserver/service/auth.go
- src/apiserver/service/service.go
- src/auth/auth.go
- src/auth/authcenter/authcenter.go
- src/auth/authcenter/client.go
> 添加判断管理员入口接口

- src/ui/src/api/index.js
- src/ui/src/components/modal/permission.vue
- src/ui/src/components/ui/selector/business.vue
- src/ui/src/directives/cursor.js
- src/ui/src/setup/permission.js
- src/ui/src/store/modules/api/auth.js
- src/ui/src/views/model-manage/index.vue
> feature:ui: 将990403状态的请求reject掉

- src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
- src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go
> 关联升级需要交换 源<->目标模型

- src/common/eventclient/eventclient.go
- src/scene_server/event_server/distribution/reconclier.go
- src/scene_server/event_server/identifier/identifier.go
> 解决evenserver中redis oom问题

- src/ui/src/components/service/instance-table.vue
- src/ui/src/views/business-topology/children/service-instance-table.vue
- src/ui/src/views/business-topology/children/service-instances.vue
- src/ui/src/views/service-template/children/process-form.vue
- src/ui/src/views/service-template/children/process.vue
> update:ui: 添加侧栏关闭提示

- src/ui/src/components/ui/tree/tree.vue
- src/ui/src/views/business-topology/children/service-node-info.vue
- src/ui/src/views/business-topology/children/topology-tree.vue
> fix:ui: 修复拓扑树新增节点插入位置错误的问题

- src/ui/src/assets/images/lock.svg
- src/ui/src/assets/scss/common.scss
> update:ui: 修改鼠标跟随图标

- resources/language/default/enum.json
- resources/language/en/enum.json
- src/common/language/language.go
> fix： 修复内置”防火墙”模型枚举字段多语言支持问题

- resources/language/default/enum.json
- resources/language/en/enum.json
- src/apiserver/service/auth.go
- src/common/language/language.go
- xxxx
- xxxx
- 修复内置模型的多语言支持问题
> optimize: 修复内置模型的多语言支持问题

- src/auth/authcenter/adaptor.go
- src/scene_server/topo_server/core/operation/inst.go
> 调整权限中心的资源命名

- src/scene_server/topo_server/core/operation/inst.go
> V3.2.x 修复创建云区域唯一校验不过的问题

- src/ui/src/api/middleware/admin-entrance.js
- src/ui/src/components/layout/header.vue
- src/ui/src/dictionary/auth.js
- src/ui/src/router/index.js
- src/ui/src/views/permission/router.config.js
> UI: 去除原有关于管理入口的鉴权

- src/ui/src/components/layout/header.vue
> update:ui: admin-tips添加hover色

- src/ui/src/components/ui/selector/business.vue
> UI: 业务选择器提示语优化
