TencentBlueKing/bk-cmdb

src/ui/src/views/general-model/index.vue

- 根据指标搜索实例时，如未在第一页，搜索结果会出问题。
close #4304

fix: 前端修改。修改搜索界面因未返回第一页搜索，导致搜索不到实例的问题。

---

src/apimachinery/discovery/server.go

- fix: discovery GetServer() concurrent rw slice panic issue.

fix: discovery GetServer() concurrent rw slice panic issue.

---

src/scene_server/auth_server/logics/fetch_instance_info.go

修复fetch_instance_info使用id查询无效的问题

---

src/scene_server/auth_server/sdk/operator/calculate.go
src/scene_server/auth_server/sdk/operator/kit.go
src/scene_server/auth_server/sdk/operator/operator.go
src/scene_server/auth_server/sdk/operator/policy.go
src/scene_server/auth_server/sdk/operator/policy_test.go

feature: add iam sdk.

---

src/scene_server/admin_server/command/import.go

修复导入蓝鲸业务拓扑配置失败的问题

---

src/common/metadata/update.go
src/scene_server/datacollection/collections/hostsnap/hostsnap.go
src/scene_server/datacollection/collections/middleware/handler.go
src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/test/host_server/host_abnormal_test.go
src/test/host_server/host_test.go

添加不允许更新不可编辑字段的校验

---

src/web_server/app/options/options.go
src/web_server/app/server.go
src/web_server/service/index.go

webserver提供读取用户管理的ESB接口地址配置

---

src/ui/src/views/custom-query/define.vue

修复动态分组保存multilike值不为数组的问题

---

src/apiserver/service/url.go
src/auth/parser/host.go
src/common/metadata/hostserver.go
src/scene_server/host_server/service/findhost.go
src/scene_server/host_server/service/service.go

- 添加根据模块ID查询主机和模块关系接口
close #4349

添加根据模块ID查询主机和模块关系接口

---

src/scene_server/host_server/app/options/options.go
src/scene_server/host_server/app/server.go
src/scene_server/host_server/service/cloudarea.go
src/scene_server/host_server/service/favourite.go
src/scene_server/host_server/service/host.go
src/scene_server/host_server/service/hostapplyrule.go
src/scene_server/host_server/service/hostlock.go
src/scene_server/host_server/service/module.go
src/scene_server/host_server/service/service.go
src/scene_server/host_server/service/special.go
src/scene_server/host_server/service/transfer.go
src/scene_server/host_server/service/userapi.go
src/scene_server/host_server/service/usercustom.go
src/test/host_server/host_abnormal_test.go

- hostserver的所有写接口支持事务
close issue #4161

hostserver的所有写接口支持事务

---

src/scene_server/auth_server/sdk/auth/auth.go
src/scene_server/auth_server/sdk/auth/authorize.go
src/scene_server/auth_server/sdk/client/client.go
src/scene_server/auth_server/sdk/client/policy.go
src/scene_server/auth_server/sdk/client/type.go
src/scene_server/auth_server/sdk/types/auth.go
src/scene_server/auth_server/sdk/types/client.go
src/scene_server/auth_server/sdk/types/const.go

- add iam client sdk and interface definition.

feature: add iam client sdk and interface definition.

---

src/scene_server/auth_server/sdk/auth/auth.go
src/scene_server/auth_server/sdk/auth/authorize.go
src/scene_server/auth_server/sdk/auth/calculate.go
src/scene_server/auth_server/sdk/auth/count.go
src/scene_server/auth_server/sdk/client/client.go
src/scene_server/auth_server/sdk/client/policy.go
src/scene_server/auth_server/sdk/client/type.go
src/scene_server/auth_server/sdk/operator/operator.go
src/scene_server/auth_server/sdk/operator/policy.go
src/scene_server/auth_server/sdk/types/auth.go
src/scene_server/auth_server/sdk/types/client.go
src/scene_server/auth_server/sdk/types/const.go

- finished auth sdk development, support authorize, authorize batch and list user's authorized resource instances function.

feature: finished auth sdk development.

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/v3.0.8/createtable.go
src/scene_server/admin_server/upgrader/y3.8.202006231730/create_table_del_archive.go
src/scene_server/admin_server/upgrader/y3.8.202006231730/pkg.go
src/scene_server/host_server/service/usercustom.go

- 修复配置自定义属性列表报错的问题
- 增加创建cc_DelArchive的升级程序，修复因事务中不能创建该表导致转移主机报错的问题

修复配置自定义属性列表报错的问题

---

src/common/metadata/set_template_request.go
src/scene_server/task_server/logics/task.go
src/scene_server/task_server/service/queue.go
src/scene_server/topo_server/core/settemplate/settemplate.go
src/scene_server/topo_server/service/internal_task.go

- 
- 优化任务组件header， 不存储不需要使用的header中内容到db
- 优化同步集群模板任务存储的数据， 使用公用的header， 而不是每个子任务都记录
- xxxx

feature: streamline asynchronous task header   issue #4377

---

src/common/metadata/hostserver.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/service/findhost.go

接口入参数量限制调整

---

src/web_server/logics/fields.go

优化的功能:
修改了导出实例的excel字段排序逻辑----唯一校验字段优先排序。
close #4109

V3.8.x 修改了导出实例的excel字段排序逻辑----唯一校验字段优先排序

---

src/auth/parser/host.go
src/auth/parser/topolatest.go
src/auth/parser/topology.go

- 暂时注释掉auth parser里在topolatest有替换接口的接口，验证无问题后再清理这些接口相关的代码
close #3920

下线auth parser里在topolatest有替换接口的接口

---

src/ui/src/components/ui/form/form-multiple.vue
src/ui/src/router/index.js
src/ui/src/views/audit/index.vue
src/ui/src/views/eventpush/pop.vue
src/ui/src/views/history/index.vue
src/ui/src/views/service-instance/children/clone-to-other.vue
src/ui/src/views/service-instance/children/clone-to-source.vue
src/ui/src/views/service-instance/clone.vue
src/ui/src/views/service-instance/create.vue

- 批量编辑表单的复选框触发区域修改为包含属性名称
- 克隆服务实例页面操作按钮吸底优化
- 添加主机的删除操作添加渐隐动画和loading优化
- 资源实例删除历史查询无结果问题修复
- 操作审计功能板块显示值逻辑优化
- 事件订阅测试推送操作请求取消优化

UI: 缺陷与体验问题修复

---

src/scene_server/event_server/app/server.go
src/scene_server/event_server/distribution/reconclier.go
src/scene_server/event_server/distribution/start.go

定时删除cc:v3:event:inst_queue中的多余数据，防止redis OOM

---

scripts/init.py
src/scene_server/cloud_server/app/options/options.go
src/scene_server/cloud_server/app/server.go
src/thirdpartyclient/secrets/api.go
src/thirdpartyclient/secrets/secrets.go

增加基于rest框架的密码服务客户端，用于获取密钥

---

src/scene_server/topo_server/core/operation/inst.go

- 修正excel导入实例时，报错内容乱序的问题。
close #4274

修正excel导入实例时，报错内容乱序的问题

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.8.202007011748/change_bk_mainlin_set_biz_asst.go
src/scene_server/admin_server/upgrader/y3.8.202007011748/pkg.go

- 将集合和业务在bk_mainline的关联方式下的关联设置为内置关系
- xxxx
- xxxx

feature:set biz and set association is pre issue #4398

---

src/scene_server/event_server/app/server.go
src/scene_server/event_server/distribution/reconclier.go
src/scene_server/event_server/distribution/start.go

优化redis事件队列处理机制，避免事件堆积

---

src/ac/iam/adaptor.go
src/ac/iam/initial_resources.go
src/ac/iam/types.go
src/apimachinery/authserver/authserver.go
src/scene_server/auth_server/logics/fetch_instance_info.go
src/scene_server/auth_server/logics/list_instance.go
src/scene_server/auth_server/logics/list_instance_by_policy.go
src/scene_server/auth_server/logics/parser.go
src/scene_server/auth_server/logics/util.go
src/scene_server/auth_server/service/service.go

- list_instance_by_policy 支持按照 _bk_iam_path_ 进行筛选
- fetch_instance_info 支持返回 _bk_iam_path_

_bk_iam_path_ 相关调整

---

src/common/metadata/toposerver.go
src/scene_server/topo_server/service/resource_directory.go

查询资源池目录接口支持排序和指定返回字段

---

src/scene_server/auth_server/logics/list_attr.go
src/scene_server/auth_server/logics/list_instance.go
src/source_controller/coreservice/core/auth/auth.go

- 修复部分条件中包含 $in 时未判断数组是否为空的问题
- 查询权限资源接口类型为主机时使用metadata.HostMapStr

WIP 权限相关bugfix

---

src/auth/authcenter/perm_sys.go
src/auth/parser/admin.go

去掉配置管理的查询鉴权

---

src/ui/src/views/admin/router.config.js

去掉配置管理视图进入权限

---

src/scene_server/auth_server/logics/parser.go
src/scene_server/auth_server/sdk/auth/authorize.go
src/scene_server/auth_server/sdk/operator/policy.go

修复用户无权限时权限中心返回策略为{}时解析失败的问题

---

src/ui/index.html
src/ui/src/components/ui/form/user.vue

- 人员选择器兼容用户管理/内置用户两种场景
- 允许部署为https时加载http内容

UI： 优化人员选择器使用场景

---

src/apimachinery/apiserver/api.go

- 修复主机信息excel导出失败的问题，更新apimachinery下的apiserver路由path

修复主机信息excel导出失败的问题，更新apimachinery下的apiserver路由path

---

src/source_controller/coreservice/service/set_template.go

- xxxx
- xxxx
-  修改集群模板最后同步时间展示错误的问题
close #3321

fix: time parse error. time zone question issue #4421

---

src/source_controller/coreservice/event/flow.go
src/source_controller/coreservice/event/types.go

optimize: host event support host struct change to array.

---

src/ui/src/views/service-template/children/operational.vue
src/ui/src/views/service-template/children/process.vue

fix:ui: 修复服务模板进程无法操作的问题

---

src/ac/parser/topolatest.go
src/apimachinery/coreservice/cache/api.go
src/apimachinery/coreservice/cache/cache.go
src/auth/parser/topolatest.go
src/scene_server/topo_server/service/cache.go
src/scene_server/topo_server/service/service_initfunc.go
src/source_controller/coreservice/cache/business/client.go
src/source_controller/coreservice/cache/business/client_logic.go
src/source_controller/coreservice/cache/topo_tree/path.go
src/source_controller/coreservice/cache/topo_tree/type.go
src/source_controller/coreservice/service/cache.go
src/source_controller/coreservice/service/service_initfunc.go

- 新增根据业务拓扑实例节点，查询该节点的父节点路径接口。主要用于鉴权服务。

feature: add api to find a topology node's parent path

---

src/source_controller/coreservice/cache/topo_tree/path.go
src/source_controller/coreservice/cache/topo_tree/type.go

demand: 根据业务拓扑节点查询拓扑路径，新增返回根节点名称。

---

src/ac/extensions/servicetemplate.go
src/ac/iam/adaptor.go
src/ac/iam/id.go
src/ac/iam/initial_actions.go
src/ac/parser/event.go
src/ac/parser/servicetemplate.go
src/ac/parser/topology.go
src/apimachinery/authserver/api.go
src/apimachinery/authserver/authserver.go
src/apiserver/service/auth.go
src/scene_server/auth_server/sdk/auth/auth.go
src/scene_server/auth_server/sdk/auth/authorize.go
src/scene_server/auth_server/sdk/auth/calculate.go
src/scene_server/auth_server/sdk/auth/count.go
src/scene_server/auth_server/sdk/operator/operator.go
src/scene_server/auth_server/service/auth.go
src/scene_server/auth_server/service/service.go
src/scene_server/event_server/service/subscription.go
src/scene_server/proc_server/service/servicetemplate.go

AuthVerify 接口鉴权使用特殊接口返回用户是否拥有动作的任意权限

---

src/scene_server/event_server/identifier/hostcache.go

- xxxx
- xxxx
- xxxx
issue : #4441

修复主机身份事件中process_name为空

---

src/common/watch/cursor.go
src/common/watch/cursor_test.go
src/common/watch/watch.go
src/scene_server/event_server/service/lua.go
src/scene_server/event_server/service/watch.go

- 优化事件监听逻辑，特别是在无事件时，返回无事件通知，避免抛出异常。
- 调整了事件游标的encode, decode逻辑，使产生的游标更容易识别。

demand: 优化事件监听逻辑，特别是在无事件时，返回无事件通知，避免抛出异常。

---

src/ui/src/components/service/instance-table.vue
src/ui/src/views/business-topology/children/topology-tree.vue

- 修复业务拓扑搜索后无法选择节点的问题
- 修复非服务模板创建的模块添加主机时无法编辑进程的问题

UI：业务拓扑下的功能bug修复

---

src/ac/extensions/instance.go
src/ac/extensions/resource_directory.go
src/ac/iam/adaptor.go
src/ac/iam/id.go
src/ac/iam/types.go
src/ac/parser/host.go
src/ac/parser/topolatest.go
src/apimachinery/apiserver/api.go
src/apiserver/service/auth.go
src/common/metadata/auth.go
src/scene_server/auth_server/logics/parser.go
src/scene_server/auth_server/logics/util.go
src/scene_server/event_server/service/subscription.go
src/scene_server/host_server/logics/import.go
src/scene_server/host_server/service/host.go
src/scene_server/topo_server/core/core.go
src/scene_server/topo_server/core/operation/inst.go
src/scene_server/topo_server/service/inst.go

V3.9.x iam

---

src/common/backbone/http.go

- 服务在收到退出指令的时候， 先不退出， 等5s后退出
- xxxx
- xxxx
close #4443

 服务在收到退出指令的时候， 先不退出， 等5s后退出

---

src/web_server/service/login.go

- xxxx
- xxxx
- 修复logout清楚session没有调用save保存的问题

[FIX]修复logout清楚session没有调用save保存的问题

---

src/scene_server/cloud_server/app/options/options.go
src/scene_server/cloud_server/app/server.go
src/scene_server/cloud_server/service/account.go
src/scene_server/cloud_server/service/service.go
src/scene_server/cloud_server/service/synctask.go
src/test/cloud_server/cloud_sync_task_test.go

- 云资源管理写DB操作接入分布式事务
close #4449

云资源管理写DB操作接入分布式事务

---

src/ui/src/views/model-manage/index.vue

优化模型管理操作按钮鉴权时机解决打开页面卡顿问题

---

src/scene_server/topo_server/service/inst_set.go

修复批量创建集群失败的问题

---

src/scene_server/host_server/service/cloudarea.go
src/scene_server/host_server/service/favourite.go
src/scene_server/host_server/service/findhost.go
src/scene_server/host_server/service/host.go
src/scene_server/host_server/service/hostapplyrule.go
src/scene_server/host_server/service/hostlock.go
src/scene_server/host_server/service/module.go
src/scene_server/host_server/service/service.go
src/scene_server/host_server/service/service_initfunc.go
src/scene_server/host_server/service/special.go
src/scene_server/host_server/service/transfer.go
src/scene_server/host_server/service/userapi.go
src/scene_server/host_server/service/usercustom.go

- 优化hostserver,使用kit方式接入服务
close #4367

对hostserver的服务的接入模式变更

---

src/common/paraparse/app.go
src/common/paraparse/host.go

查询主机接口兼容$in操作符后为nil数组的情况

---

src/common/version/version.go
src/scene_server/topo_server/core/operation/inst_module.go
src/scene_server/topo_server/core/operation/inst_set.go

增加集群和模块创建是否要使用模版的控制选项

---

src/ac/iam/adaptor.go
src/ac/iam/gen_id.go
src/ac/iam/initial_actions.go
src/ac/iam/initial_instance_selections.go
src/ac/iam/initial_resources.go
src/ac/iam/types.go
src/ac/meta/meta.go
src/ac/parser/host.go
src/ac/parser/util.go
src/apiserver/service/auth.go
src/scene_server/auth_server/logics/parser.go
src/scene_server/auth_server/logics/util.go
src/scene_server/auth_server/sdk/auth/calculate.go
src/scene_server/auth_server/service/auth.go
src/scene_server/auth_server/service/instance_resource.go
src/scene_server/auth_server/service/system_resource.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/service/host.go
src/scene_server/host_server/service/module.go

demand: add all api authorize with iam v3.

---

src/ui/src/utils/tools.js
src/ui/src/views/custom-query/define.vue
src/ui/src/views/custom-query/index.vue

UI: 修复动态分组操作符是$in/$nin值不为数组的问题

---

src/scene_server/event_server/distribution/distribution.go
src/scene_server/event_server/distribution/handle_event.go
src/scene_server/event_server/distribution/start.go
src/scene_server/event_server/types/const.go

- fix event distribution slow problem

fix event distribution slow problem

---

src/ui/src/views/custom-query/index.vue

UI: 优化动态分组查询条件取值逻辑

---

src/common/definitions.go
src/common/metadata/common.go
src/scene_server/host_server/logics/module.go
src/scene_server/topo_server/service/resource_directory.go

修复从自定义主机池目录转移到业务空闲机失败的问题

---

src/scene_server/cloud_server/logics/synctask.go
src/scene_server/cloud_server/service/synctask.go

修复拉取不到用户权限下对应云同步任务列表的问题

---

src/ui/src/dictionary/iam-auth.js
src/ui/src/setup/permission.js
src/ui/src/views/host-operation/index.vue

update:ui: 调整主机操作相关的权限设置

---

src/scene_server/cloud_server/app/options/options.go
src/scene_server/cloud_server/cloudsync/hostsyncor.go

- 云资源管理启动默认使用加密服务
- 后台云同步服务查询任务时不鉴权

云资源管理启动默认使用加密服务

---

src/storage/stream/event/watch.go

- 修复删表操作导致进程使用watch服务时CPU高的问题。

fix: fix stream watch problem which will cause a high cpu of process 

---

src/ac/parser/util.go

auth parser包中getOneModel函数返回做优化

---

src/scene_server/topo_server/app/server.go

修复同步集群模版时的异常报错

---

src/source_controller/coreservice/core/settemplate/sync_status.go

fix: fix coreservice panic issue

---

src/ui/src/views/set-template/children/template-config.vue

UI: 集群模板名称校验规则调整

---

src/storage/stream/event/watch.go
src/storage/stream/types/types.go

- 新增事件stream支持获取字段变更的详情，即可以看到那些字段发生了变更触发了事件。

feature: add update fields support in event stream

---

src/apimachinery/coreservice/transaction/client.go

- 事务方法内出现panic后进行回滚，防止未提交的相同数据在另一个事务中出现写冲突

事务方法内出现panic后进行回滚，防止未提交的相同数据在另一个事务中出现写冲突

---

src/ui/src/router/index.js
src/ui/src/setup/afterload.js

- 优化验证组件初始化时机以支持通过判断全局loading确定配置已加载

优化验证组件初始化时机

---

src/ui/src/router/index.js
src/ui/src/setup/validate.js
src/ui/src/store/modules/global.js

新增表单验证插件配置完成状态值

---

src/ui/src/components/model-manage/field-group/field-detail/index.vue
src/ui/src/views/host-details/landing.vue

UI: 主机查询跳转错误修复

---

src/ui/src/components/model-manage/_create-model.vue
src/ui/src/components/service/form/form.vue
src/ui/src/components/ui/auth/auth.vue

- 修复服务实例查看进程权限参数格式错误的问题
- 修复生成模式下新建模型可以选择无权限的分组的问题

UI: 鉴权BUG修复

---

src/ui/src/components/ui/form/organization.vue
src/ui/src/components/ui/other/property-value.vue

组织组件兼容不存在的数据及支持focus

---

resources/language/default/property.json
resources/language/en/property.json
src/common/definitions.go
src/common/metadata/attribute.go
src/common/metadata/inst.go
src/common/metadata/process.go
src/common/metadata/process_bind_info.go
src/scene_server/admin_server/command/import.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
src/scene_server/admin_server/upgrader/y3.8.202007211455/pkg.go
src/scene_server/admin_server/upgrader/y3.8.202007211455/proc_bind_change.go
src/scene_server/event_server/identifier/hostcache.go
src/scene_server/event_server/identifier/identifier.go
src/scene_server/proc_server/logics/processinstance.go
src/scene_server/proc_server/service/processinstance.go
src/scene_server/proc_server/service/processtemplate.go
src/source_controller/coreservice/core/host/identifier/identifier.go
src/source_controller/coreservice/core/process/process_template.go
src/source_controller/coreservice/core/process/service_instance.go
src/test/proc_server/no_service_template_test.go

V3.8.x table

---

src/scene_server/event_server/service/watch.go
src/source_controller/coreservice/event/flow.go
src/storage/stream/types/types.go

watch的事件详情支持具体字段变化信息

---

src/common/metadata/attribute.go
src/common/util/struti.go

增加用户类型模型属性的正则校验

---

src/web_server/service/service.go

- http.ErrAbortHandler 不打印panic日志 [相关issue](https://github.com/golang/go/issues/28239)

http.ErrAbortHandler 不打印panic日志

---

src/ui/src/dictionary/iam-auth.js

fix:ui: 修复动态分组对应权限中心视图配置错误的问题

---

src/ac/iam/adaptor.go
src/ac/iam/initial_action_groups.go
src/ac/iam/initial_actions.go
src/ac/iam/types.go
src/ac/meta/meta.go

添加set_template事件监听权限

---

src/auth/authcenter/adaptor.go
src/auth/authcenter/perm_sys.go
src/auth/meta/meta.go
src/common/watch/cursor.go
src/source_controller/coreservice/event/event.go
src/source_controller/coreservice/event/key.go
src/source_controller/coreservice/event/types.go
src/storage/dal/mongo/local/mongo.go
src/storage/stream/types/types.go

添加 set_template 事件监听功能

---

src/common/metadata/hostserver.go

list_host校验fields必填

---

src/auth/extensions/base.go
src/auth/extensions/host.go
src/auth/extensions/instance.go
src/auth/extensions/module.go
src/auth/extensions/process.go
src/auth/extensions/set.go

- 优化与权限中心进行资源同步的策略，延长同步周期，降低db压力。

optimize: optimize sync iam policy to avoid read mongodb frequently.

---

src/scene_server/admin_server/upgrader/y3.7.201911141719/init_host_property_apply.go
src/test/host_server/host_apply_test.go
src/test/host_server/host_test.go

修复upgrader里模块的host_apply_enabled字段生成ID时使用了object表的问题

---

src/tools/cmdb_ctl/cmd/limiter.go
src/tools/cmdb_ctl/readme.md

补充api限流工具使用说明

---

src/apimachinery/apiserver/api.go
src/apimachinery/apiserver/apiserver.go
src/web_server/logics/association.go
src/web_server/logics/inst.go

修复导出有实例关联的实例时报错解析授权信息失败的问题

---

src/ui/src/api/index.js
src/ui/src/components/model-instance/relation/create.vue
src/ui/src/components/model-instance/relation/list.vue
src/ui/src/components/ui/auth/auth-option.vue
src/ui/src/components/ui/index.js
src/ui/src/views/cloud-area/index.vue
src/ui/src/views/cloud-resource/children/task-region-selector.vue
src/ui/src/views/general-model/index.vue
src/ui/src/views/host-details/children/association-create.vue
src/ui/src/views/model-association/index.vue
src/ui/src/views/model-manage/children/relation-detail/index.vue

- 模型新增关联关系选择模型列表进行前置鉴权
- 去除实例批量删除操作前置鉴权
- 实例关联创建前置鉴权配置调整为双向鉴权
- 内置关联类型不允许申请权限删除
- 云区域地域请求异常兼容

UI: 前端前置鉴权优化

---

src/ui/src/store/modules/api/global-models.js
src/ui/src/views/model-manage/children/index.vue
src/ui/src/views/model-manage/children/relation-detail/index.vue
src/ui/src/views/model-manage/index.vue
src/ui/src/views/model-topology/index.new.vue
src/ui/src/views/operation/chart-detail.vue
src/ui/src/views/resource-manage/index.vue

- 不可操作的模型通过model.bk_ishidden判断

feature:ui: 不可操作的模型通过model.bk_ishidden判断

---

src/common/metadata/inst.go
src/scene_server/event_server/identifier/identifier.go

主机身份加回bk_supplier_id字段，兼容GSE

---

src/ui/src/views/host-details/index.vue

fix:ui: 修复主机详情查询属性参数错误的问题

---

src/scene_server/host_server/service/findhost.go
src/scene_server/host_server/service/hostapplyrule.go
src/scene_server/host_server/service/transfer.go
src/scene_server/topo_server/service/inst_module.go
src/scene_server/topo_server/service/set_template.go
src/source_controller/coreservice/service/host_apply_rule.go
src/source_controller/coreservice/service/service_template.go
src/source_controller/coreservice/service/set_template.go

修复部分接口参数先解析成map后解析为struct的问题，优化不必要的结构解析

---

src/ac/iam/adaptor.go
src/ac/iam/gen_id.go
src/ac/iam/initial_actions.go
src/ac/iam/initial_resource_creator_actions.go
src/ac/parser/host.go
src/ac/parser/topology.go
src/common/metadata/attribute.go
src/scene_server/host_server/service/userapi.go
src/scene_server/proc_server/service/service.go
src/scene_server/proc_server/service/servicetemplate.go
src/scene_server/topo_server/service/set_template.go

- 主机收藏跳过鉴权
- 添加业务拓扑等新建操作的关联权限
- 主机转移鉴权使用服务实例增删改权限
- 修复模型导出时获取模型信息接口鉴权解析要求业务ID不为0的问题
- 修复主机自动应用包含组织字段导致应用失败的问题

auth bugfix

---

src/common/metadata/process.go

feature: check whether it is legal  issue #4468

---

src/scene_server/admin_server/upgrader/x20.08.24.01/add_cpu_mem_disk_unit.go

style: 修改import顺序,修改文件名。

---

src/scene_server/admin_server/service/authcenter.go

权限中心初始化成功时返回一个成功response

---

src/apimachinery/coreservice/host/api.go
src/apimachinery/coreservice/host/host.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/service/host.go
src/source_controller/coreservice/core/core.go
src/source_controller/coreservice/core/host/transfer.go
src/source_controller/coreservice/core/host/transfer/manager.go
src/source_controller/coreservice/core/host/transfer/transfer.go
src/source_controller/coreservice/service/host.go
src/test/host_server/host_abnormal_test.go

删除主机改为批量操作

---

src/scene_server/event_server/service/watch.go
src/scene_server/event_server/watcher/watch.go

watch超时时返回bk_watched为false的仅包含cursor的事件

---

src/scene_server/admin_server/upgrader/y3.8.202007211455/proc_bind_change.go

- 进程，进程模板中的端口一行不再支持非连续的端口 
- xxxx
- xxxx

feature: port not support mutli-port   issue #4468

---

src/auth/parser/host.go
src/common/metadata/hostserver.go
src/scene_server/host_server/logics/set.go
src/scene_server/host_server/service/findhost.go
src/scene_server/host_server/service/module.go
src/scene_server/host_server/service/service.go

- 添加查询拓扑节点下的主机接口
- 查询主机关系接口去掉分页

添加查询拓扑节点下的主机接口

---

src/common/metadata/hostserver.go

This reverts commit 8c41136a7202d057479d10e344635858ce1e4518.

Revert "list_host校验fields必填"

---

src/scene_server/auth_server/logics/list_instance.go

修复权限回调接口查询主机时使用分页缓存查询传递了所有hostID导致返回全部数据的问题

---

src/scene_server/topo_server/service/inst_business.go

…eturn date of api-with_reduced. issue #4589
- xxxx
- xxxx
- xxxx

删除with_reduced接口返回数据中的business_dept_name和business_dept_id字段

---

src/common/metadata/host_apply_rule.go
src/scene_server/host_server/service/hostapplyrule.go
src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/core/instances/instance_crud.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/source_controller/coreservice/core/instances/validator_unique.go

主机自动应用性能优化

---

src/ac/iam/adaptor.go
src/ac/iam/gen_id.go
src/ac/iam/initial_action_groups.go
src/ac/iam/initial_actions.go
src/ac/iam/initial_resource_creator_actions.go
src/ac/iam/types.go
src/ac/parser/host.go
src/scene_server/host_server/service/userapi.go

调整查询动态分组鉴权方式

---

src/common/mapstruct/decode.go
src/scene_server/proc_server/service/processinstance.go
src/scene_server/topo_server/core/settemplate/settemplate.go
src/scene_server/topo_server/core/settemplate/sync_status.go
src/scene_server/topo_server/service/set_template.go

- 解决原有 common/mapstruct.Decode2Struct 的性能问题（Hook函数导致）

REFACTOR: Solve Decode2Struct performance issues #4569

---

src/common/json/json.go
src/source_controller/coreservice/core/host/host.go
src/source_controller/coreservice/core/host/searcher/searcher.go
src/source_controller/coreservice/service/service.go

- xxxx
- 优化拉取全量主机场景， 使用cache中的数据
- xxxx

refactor: list all host with cache issue #4605

---

src/ui/src/components/model-manage/field-group/field-detail/enum.vue

- cmdb模型属性的枚举字段删除异常。
close #4596

fix :修正cmdb模型设计，无法删除枚举项的问题。

---

src/thirdpartyclient/elasticsearch/esclient.go

- xxxx
- xxxx
- 修复 http 无法连接云ES问题

FIX: Solve the problem that http cannot connect to cloud ES

---

src/scene_server/admin_server/upgrader/y3.8.202007211455/proc_bind_change.go

- 进程绑定信息的子字段设置为必填
- xxxx
- xxxx

feature: bind info sub attribute  is require   issue #4468

---

src/scene_server/topo_server/service/auditlog.go

修复业务实例变更记录里包含非该业务实例相关记录的问题

---

src/ac/iam/initial_resource_creator_actions.go
src/scene_server/host_server/logics/import.go
src/scene_server/topo_server/service/inst.go

去除资源池主机、模型实例的新建关联权限

---

src/common/metadata/hostserver.go
src/scene_server/host_server/service/module.go

- 查询主机业务关系接口增加对入参bk_host_id的校验

查询主机业务关系接口增加对入参bk_host_id的校验

---

src/source_controller/coreservice/event/gc.go
src/source_controller/coreservice/event/lua.go

修复gc导致tail不指向head的问题

---

scripts/start.sh
src/apiserver/service/healthz.go
src/scene_server/cloud_server/app/server.go
src/scene_server/cloud_server/logics/logics.go
src/scene_server/cloud_server/service/health.go
src/scene_server/cloud_server/service/service.go
src/scene_server/synchronize_server/app/server.go
src/scene_server/synchronize_server/service/service.go

- 调整synchronizeserver和cloudserver的健康检查接口

调整synchronizeserver和cloudserver的健康检查接口

---

src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/core/process/service_instance.go

- xxxx
- change resource to driver method 
- xxxx

refactor: change resource to driver method issue #4570

---

src/scene_server/topo_server/core/operation/identifier.go
src/source_controller/coreservice/core/host/identifier/identifier.go
src/source_controller/coreservice/service/host.go

fix: 修复查询主机身份空指针问题

---

src/common/auditlog/host.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/service/host.go

Style: change code style for audit log related.

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.8.202009101702/pkg.go
src/scene_server/admin_server/upgrader/y3.8.202009101702/proc_bind_change.go

- xxxx
-  调整进程bind info migrate 版本
-

refactor: change migrate version issue #4468

---

src/ui/config/prod.env.js
src/ui/src/main.js

feature:ui: 编译时自动注入当前的commit id

---

src/scene_server/admin_server/command/import.go
src/scene_server/admin_server/upgrader/v3.0.8/addPlatData.go
src/scene_server/admin_server/upgrader/v3.0.8/upgradeBKBiz.go
src/scene_server/admin_server/upgrader/x18.11.19.01/reconcil_unique.go
src/scene_server/admin_server/upgrader/x18.12.12.01/reconcil_unique.go
src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
src/scene_server/admin_server/upgrader/y3.6.201911261109/init_chart.go
src/source_controller/coreservice/core/auditlog/audit.go
src/storage/dal/dal.go
src/storage/dal/mongo/local/mongo.go

添加批量获取新序列号的函数

---

src/source_controller/coreservice/core/model/attribute.go

修复拖动模型内置字段排序失败的问题

---

src/ui/src/components/ui/form/bool.vue
src/ui/src/components/ui/form/enum.vue
src/ui/src/components/ui/form/float.vue
src/ui/src/components/ui/form/int.vue
src/ui/src/magicbox/magicbox.scss
src/ui/src/utils/tools.js
src/ui/src/views/service-template/children/operational.vue
src/ui/src/views/service-template/children/process-form-property-table.vue
src/ui/src/views/service-template/children/process-form.vue

- 修复服务实例模板进程编辑失败的问题
- 修复拓扑输搜索后UI异常的问题

UI: 修复服务模板进程编辑失败的问题

---

src/common/definitions.go
src/common/util/lib.go
src/scene_server/admin_server/authsynchronizer/handler/instance.go
src/scene_server/admin_server/authsynchronizer/utils/types.go
src/storage/dal/mongo/local/mongo.go

optimize: adminserver 权限资源同步支持读写分离

---

src/scene_server/auth_server/service/service.go

增加authserver的supplierID设置

---

src/ui/src/views/audit/children/audit-business-options.vue
src/ui/src/views/audit/children/audit-host-options.vue
src/ui/src/views/audit/children/audit-other-options.vue
src/ui/src/views/audit/children/audit-resource-options.vue
src/ui/src/views/business-topology/host/host-list-options.vue
src/ui/src/views/business-topology/host/host-list.vue
src/ui/src/views/operation/chart-detail.vue
src/ui/src/views/service-category/index.vue

- 操作审计默认筛选项调整
- 修复收藏条件应用无效的问题
- 修复运营统计新增图标UI异常的问题
- 修复新增一级服务分类时中断流程可能引起的UI异常的问题

UI: 修复收藏条件应用无效及运营统计新增图表UI异常的问题

---

src/ac/parser/topology.go
src/ac/parser/util.go
src/common/metadata/process_bind_info.go
src/scene_server/topo_server/core/operation/object.go
src/scene_server/topo_server/core/operation/types.go
src/scene_server/topo_server/service/object.go
src/web_server/service/object.go

- 修复获取默认资源池目录ID错误的问题
- 修复移除metadata导致导入模型字段失败的问题
- 修复有部分模型权限时无法批量更新这些模型的问题
- 修复无变更时模板要求同步的问题

3.9 bugfix

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202008172134/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202008172134/update_audit_table.go

操作审计upgrader移动到3.9

---

src/scene_server/host_server/service/module.go

修复 hostserver 使用未初始化的结构体的字段的问题

---

src/tools/cmdb_ctl/cmd/conf.go
src/tools/cmdb_ctl/readme.md

增加验证yaml文件工具功能，可以指定文件进行验证

---

src/common/metadata/hostserver.go
src/scene_server/host_server/service/cloudarea.go

- xxxx
- 查询云区域时不同步查询其下的主机数量，加快页面响应速度

查询云区域时不附带查询其下的主机数量

---

src/ui/src/utils/tools.js
src/ui/src/views/index/children/map.vue

fix:ui: 修复编辑模板进程绑定信息保存无效的问题

---

src/ac/parser/util.go

权限解析获取资源池业务和默认目录ID支持多开发商

---

src/ac/parser/topology.go
src/apimachinery/toposerver/inst/api.go
src/apimachinery/toposerver/inst/module.go
src/scene_server/topo_server/service/inst_module.go
src/scene_server/topo_server/service/service_initfunc.go
src/test/topo_server/object_test.go

新加的功能:
查询模块接口，在指定业务下根据集群ids和服务模版ids查询
优化的功能:
xxxx
修复的问题：
xxxx

feature: 查询模块接口，根据集群ids和服务模版ids

---

src/scene_server/host_server/service/findhost.go
src/scene_server/topo_server/service/identifier.go
src/source_controller/coreservice/core/host/searcher/searcher.go

-  主机身份，list_hosts_topo 走 mongodb 从节点获取数据
-  优化list_hosts_topo 获取全量主机的逻辑
- xxxx

V3.9.x can read secondary

---

src/ac/parser/host.go
src/ac/parser/util.go

修复权限解析获取资源池时会包含0开发商的问题

---

src/common/metadata/core_service.go
src/common/metadata/process.go
src/scene_server/proc_server/service/serviceinstance.go
src/source_controller/coreservice/core/process/service_instance.go
src/source_controller/coreservice/service/service_instance.go

优化服务实例查询性能

---

src/common/identification.go
src/common/types/serverInfo.go
src/common/version/version.go

-  新加输出version信息时输出服务名字信息
-  
- xxxx

refactor: --version output service name info  issue #4673

---

src/common/metrics/metrics.go

- xxxx
- 移除 prometheus metric 采集返回的 appCode、realIp、user 字段
- xxxx

prometheus metric 优化

---

src/scene_server/topo_server/service/association.go
src/scene_server/topo_server/service/auditlog.go
src/scene_server/topo_server/service/inst.go

-让查询模型实例和查询模型实例关系的接口，操作审计相关接口走从db

让查询模型实例和查询模型实例关系的接口，操作审计相关接口走从db

---

src/scene_server/operation_server/service/operation.go
src/scene_server/topo_server/service/auditlog.go

运营统计和操作审计相关接口读取数据走从db

---

src/ac/parser/host.go
src/common/auditlog/dynamic_grouping.go
src/common/definitions.go
src/common/metadata/audit.go
src/common/metadata/dynamic_grouping.go
src/scene_server/host_server/service/dynamic_grouping.go

新动态分组增加审计日志

---

src/scene_server/datacollection/collections/hostsnap/hostsnap.go

- datacollection变更字段可以根据环境配置
- xxxx
- xxxx

datacollection变更字段可以根据环境配置

---

src/scene_server/host_server/service/cloudarea.go

- 修复FindManyCloudArea类型转化panic问题

修复FindManyCloudArea类型转化panic问题

---

src/scene_server/cloud_server/logics/synctask.go
src/scene_server/cloud_server/service/account.go
src/scene_server/topo_server/service/resource_directory.go
src/web_server/service/object.go

- fix the panic caused by nil pointer dereference

fix the panic caused by nil pointer dereference

---

src/source_controller/coreservice/core/process/service_category.go

- xxxx
- xxxx
- 解决服务分类二级服务分类名称重复问题

fix: 解决服务分类二级服务分类名称重复问题

---

src/source_controller/coreservice/cache/business/client.go
src/source_controller/coreservice/cache/business/client_logic.go
src/source_controller/coreservice/cache/topo_tree/path.go

查询拓扑节点路径的接口过滤掉不存在的模块

---

src/scene_server/host_server/service/findhost.go
src/scene_server/host_server/service/host.go
src/scene_server/topo_server/service/identifier.go
src/scene_server/topo_server/service/inst.go
src/scene_server/topo_server/service/object.go

- 让list_biz_hosts,search_objects,search_hostidentifier,search_inst_association_topo,search_host走从db

让list_biz_hosts,search_objects,search_hostidentifier,search_inst_association_topo,search_host走从db

---

src/scene_server/datacollection/collections/middleware/handler.go

- 修正不正确的采集器上报数据处理逻辑
之前的处理逻辑是：“1.取db数据 2.取采集数据 3.数据对比，不同之处写入db数据对象中 4.db数据对象写入mongodb.”
现在的逻辑是：“1.取db数据 2.取采集数据 3.数据对比，不同之处写入新建的condition对象中 4.将condition对象更新进mongodb.”
**_本次改动后，condition中不可能出现采集器数据中没有的字段。_**
close #4679

fix: 修正处理采集器上报数据的逻辑，避免数据回滚问题。

---

src/scene_server/datacollection/datacollection/middleware/handler.go

- 修正不正确的采集器上报数据处理逻辑
之前的处理逻辑是：“1.取db数据 2.取采集数据 3.数据对比，不同之处写入db数据对象中 4.db数据对象写入mongodb.”
现在的逻辑是：“1.取db数据 2.取采集数据 3.数据对比，不同之处写入新建的condition对象中 4.将condition对象更新进mongodb.”
**_本次改动后，condition中不可能出现采集器数据中没有的字段。_**

修正不正确的采集器上报数据处理逻辑

---

src/scene_server/host_server/service/findhost.go
src/scene_server/host_server/service/host.go
src/scene_server/topo_server/service/association.go
src/scene_server/topo_server/service/identifier.go
src/scene_server/topo_server/service/inst.go
src/scene_server/topo_server/service/object.go

- search_inst
find_instance_association
list_biz_hosts
search_objects
search_hostidentifier
search_inst_association_topo
search_host
读取数据时走从db

让接口读取数据走从db

---

src/ui/src/views/resource/index.vue

fix:ui: 修复主机页面资源池目录不显示的问题

---

src/scene_server/proc_server/service/servicecategory.go

服务分类名称重复创建后报错提示优化

---

src/scene_server/auth_server/logics/list_instance.go
src/scene_server/auth_server/logics/list_instance_by_policy.go
src/scene_server/auth_server/service/gen_method.go
src/scene_server/auth_server/service/pull_resource.go
src/scene_server/auth_server/types/types.go

权限中心回调接口支持按名字查询实例

---

src/apimachinery/discovery/discovery.go
src/apimachinery/discovery/discovery_mock.go
src/apimachinery/discovery/empty_server.go
src/apiserver/service/filter.go
src/apiserver/service/match/example.md
src/apiserver/service/match/match_server.go
src/apiserver/service/type.go
src/apiserver/service/url.go
src/common/types/manager.go

-  新加支持根据服务名发现服务功能
- xxxx
- xxxx

feature: add discovery thiry other server by name issue #4675

---

src/scene_server/host_server/service/host.go
src/source_controller/coreservice/core/instances/instance.go

- modify host property update batch error log print and error return

fix: modify host property update batch error log print and error return

---

src/common/definitions.go
src/common/http/rest/contexts.go
src/common/util/lib.go
src/scene_server/cloud_server/app/server.go
src/scene_server/datacollection/app/server.go
src/scene_server/topo_server/app/server.go
src/scene_server/topo_server/core/settemplate/sync_status.go
src/source_controller/coreservice/cache/topo_tree/path.go
src/source_controller/coreservice/service/service.go
src/test/txn/txn_test.go

- coreService将通用的http filter加回来
- 修复获取拓扑节点路径的接口在集群的上一级为业务的时候不设置集群名字的问题

V3.9.x bugfix

---

scripts/init.py
src/scene_server/topo_server/app/server.go
src/web_server/app/server.go

- 将es在websever和toposerver的配置抽取出来，进行公共配置

对es的配置进行修改

---

scripts/init.py
src/scene_server/admin_server/app/server.go
src/scene_server/admin_server/command/command.go
src/scene_server/datacollection/app/server.go
src/scene_server/event_server/app/server.go
src/scene_server/topo_server/app/server.go
src/source_controller/coreservice/core/association/mock_test.go
src/source_controller/coreservice/core/instances/mock_test.go
src/source_controller/coreservice/core/model/mock_test.go
src/source_controller/coreservice/service/service.go
src/storage/dal/mongo/config.go
src/storage/dal/mongo/local/mongo.go
src/storage/dal/mongo/local/mongo_test.go
src/test/test.go
src/tools/cmdb_ctl/app/config/config.go

v3.5.x中添加mongo中的socket超时时间的配置

---

src/ac/parser/serviceinstance.go
src/common/metadata/process.go
src/scene_server/proc_server/service/service.go
src/scene_server/proc_server/service/serviceinstance.go
src/source_controller/coreservice/core/process/service_instance.go

- 支持通过集群模版查询服务实例列表
- xxxx
- xxxx

feature: 支持通过集群模版查询服务实例列表

---

src/apimachinery/procserver/service/api.go
src/apimachinery/procserver/service/instance.go
src/test/proc_server/service_template_test.go

- xxxx
- xxxx
- 补充通过集群模版查询服务实例列表集成测试用例

补充通过集群模版查询服务实例列表集成测试用例

---

src/scene_server/auth_server/logics/list_instance.go

权限中心搜索关键字不区分大小写

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202010151455/add_bizid_on_common_attr.go
src/scene_server/admin_server/upgrader/y3.9.202010151455/pkg.go

- 为缺少bk_biz_id字段的公共属性增加bk_biz_id字段且值为0 
close issue #4755

为缺少bk_biz_id字段的公共属性增加bk_biz_id字段且值为0 

---

src/scene_server/admin_server/upgrader/y3.9.202010131456/migrate_history.go

optimize: 动态分组数据迁移规则更新. issue #4759

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/x20.10.16.11/add_cloudid_index.go
src/scene_server/admin_server/upgrader/x20.10.16.11/pkg.go

主机表和云区域表增加bk_cloud_id索引

---

src/ui/src/components/host-topo-path/host-topo-path.vue
src/ui/src/components/search/enum.vue
src/ui/src/components/search/list.vue
src/ui/src/components/search/longchar.vue
src/ui/src/components/search/singlechar.vue
src/ui/src/components/search/timezone.vue
src/ui/src/magicbox/magicbox.scss
src/ui/src/store/modules/api/object-model-property.js
src/ui/src/views/business-topology/host/host-list-options.vue
src/ui/src/views/cloud-resource/children/task-account-selector.vue
src/ui/src/views/dynamic-group/form/form-property-selector.vue
src/ui/src/views/dynamic-group/form/form.vue
src/ui/src/views/dynamic-group/index.vue
src/ui/src/views/index/children/host-search.vue
src/ui/src/views/model-manage/children/index.vue
src/ui/src/views/model-manage/index.vue
src/ui/src/views/resource/children/host-list.vue
src/ui/src/views/resource/children/host-options.vue

- 业务拓扑表格字段显示仅固定ID/IP/云区域字段
- 动态分组表单组件交互优化
- 修复云资源发现新建任务账号禁用提示语错位的问题
- 修复动态分组选择属性筛选功能无效的问题
- 模型管理跳转主机资源池时切换到'全部'页签
- 修复资源池复制业务拓扑数据失败的问题
- 修复实例筛选出现重复的ID属性的问题
- 修复首页mac os环境下快捷搜索无效的问题

UI: bug修复与动态分组优化

---

src/storage/dal/redis/client.go
src/storage/dal/redis/commands.go
src/storage/dal/redis/test/commands_test.go

add redis command Lrem

---

src/ac/parser/framework.go
src/ac/parser/host.go
src/ac/parser/hostapply.go
src/ac/parser/settemplate.go

优化从URL中匹配bizID的方式,使其匹配更精准

---

src/ui/src/components/loading/loading.vue
src/ui/src/components/search/index.js
src/ui/src/components/search/service-template.vue
src/ui/src/store/modules/api/cloud.js
src/ui/src/store/modules/api/service-template.js
src/ui/src/views/cloud-area/index.vue
src/ui/src/views/dynamic-group/form/form-operator-selector.vue
src/ui/src/views/dynamic-group/form/form-property-list.vue
src/ui/src/views/dynamic-group/form/form.vue

- 动态分组查询条件模块属性支持服务模板筛选
- 云区域主机数量异步获取
- 修复动态分组范围类的查询条件编辑时表单渲染错误的问题

UI: 动态分组支持服务模板查询、云区域主机数量异步获取

---

src/ac/parser/topolatest.go
src/apimachinery/toposerver/association/apis.go
src/apimachinery/toposerver/association/association.go
src/common/metadata/association.go
src/scene_server/topo_server/core/operation/association.go
src/scene_server/topo_server/service/association.go
src/scene_server/topo_server/service/service_business_initfunc.go
src/scene_server/topo_server/service/service_initfunc.go
src/test/topo_server/asst_test.go
src/test/topo_server/topo_server_suite_test.go

- 增加查询实例所有关联接口(将实例视为关联源模型和关联目标模型)
#4595

feature: 增加查询实例所有关联接口(将实例视为关联源模型和关联目标模型)。

---

src/storage/dal/redis/client.go
src/storage/dal/redis/commands.go
src/storage/dal/redis/test/commands_test.go

- add redis commands Rename, RenameNX

add redis commands Rename, RenameNX

---

src/common/metadata/hostserver.go
src/scene_server/host_server/logics/app.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/service/module.go

跨业务转移主机限制只能在空闲机池间转移

---

src/scene_server/admin_server/service/migrate.go
src/scene_server/admin_server/service/service.go
src/scene_server/admin_server/upgrader/register.go

- 指定执行的migrate版本
- xxxx
- xxxx

feature: execute migrate specify version issue #4757

---

src/scene_server/admin_server/upgrader/register.go

- xxxx
- xxxx
-  修复adminserver 编译错误

fix: make error issue #4688

---

src/ac/parser/processinstance.go
src/apimachinery/procserver/process/api.go
src/apimachinery/procserver/process/instance.go
src/common/metadata/process.go
src/scene_server/proc_server/service/processinstance.go
src/scene_server/proc_server/service/service.go
src/test/proc_server/no_service_template_test.go

- 新增查询某业务下进程ID对应进程详情的接口
close issue #4773

feature: 新增查询某业务下进程ID对应进程详情的接口

---

src/common/metadata/dynamic_grouping.go

动态分组校验服务模板查询只能用ID数组的形式

---

scripts/init.py
src/scene_server/datacollection/app/options/options.go
src/scene_server/datacollection/app/server.go
src/scene_server/datacollection/datacollection/datacollection.go
src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go

- 添加changeRangePercent配置项，当数值型变动大于该波动值时进行修改
- 添加qps，burst 配置项，进行请求处理限流

对datacollection在采集数据时进行防抖处理优化

---

src/ui/src/components/service/instance-table.vue
src/ui/src/dictionary/iam-auth.js
src/ui/src/views/business-topology/host/across-business-module-selector.vue
src/ui/src/views/business-topology/host/host-list-options.vue
src/ui/src/views/business-topology/host/host-list.vue
src/ui/src/views/host-operation/children/create-service-instance.vue
src/ui/src/views/host-operation/children/host-attrs-auto-apply.vue
src/ui/src/views/host-operation/index.vue
src/ui/src/views/resource/children/host-list.vue

UI: 跨业务转移主机

---

src/ui/src/views/status/404.vue

ui: 404页面去除无意义的刷新操作

---

src/web_server/service/service.go

- 将webserver的404错误重定向到定制的404页面

将webserver的404错误重定向到定制的404页面

---

src/storage/driver/redis/redis.go

-  
- xxxx
- 修复当配置redis前置中关于redis的配置不是第一个InitClient的时候无法连接导对应redis的问题

fix: redis driver default client bug issue #4789

---

src/source_controller/coreservice/event/flow.go

- xxxx
- xxxx
- fix redis hmset not support map[string]string type issue.

fix: redis hmset not support map[string]string type issue.

---

src/common/blog/blog.go
src/common/querybuilder/validate.go
src/common/util/array.go
src/framework/common/struct_tags.go
src/scene_server/event_server/watcher/lua.go
src/scene_server/topo_server/service/inst_business.go
src/source_controller/coreservice/cache/host/lua.go
src/source_controller/coreservice/event/lua.go
src/storage/dal/mongo/local/mongo.go
src/storage/stream/event/watch.go

修复reflect.TypeOf()未判断结果是否为nil导致后续调用函数panic的问题

---

src/common/metrics/metrics.go

- xxxx
- xxxx
- metrics 添加 appcode 字段

metrics 添加 appcode 字段

---

src/apimachinery/coreservice/association/api.go
src/apimachinery/coreservice/association/association.go
src/common/metadata/association.go
src/scene_server/topo_server/core/operation/association.go
src/scene_server/topo_server/service/association.go
src/source_controller/coreservice/service/association.go
src/source_controller/coreservice/service/service_initfunc.go

- 修改批量删除关联实例的实现逻辑，并为其增加审计功能。
close #4743

refactor: 修改批量删除关联实例的实现逻辑，并为其增加审计功能。

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202010211805/add_host_lock_table.go
src/scene_server/admin_server/upgrader/y3.9.202010211805/pkg.go

- 升级程序增加cc_HostLock表
close issue #4786

feature: 升级程序增加cc_HostLock表

---

src/ac/extensions/model.go
src/common/util/model.go
src/scene_server/host_server/service/host.go
src/scene_server/topo_server/core/operation/attribute.go
src/source_controller/coreservice/service/auditlog.go
src/source_controller/coreservice/service/instances_dependence.go

- 优化批量更新主机属性的操作，解决因db操作超时而失败的问题 issue #4794
close issue #4794

fix: 优化批量更新主机属性的操作，解决因db操作超时而失败的问题 issue #4794

---

src/scene_server/topo_server/service/association.go

refactor: 增加错误处理内容

---

src/ui/src/views/dynamic-group/form/form.vue

ui: 动态分组表单兼容旧数据的显示

---

src/ui/src/store/modules/api/audit.js
src/ui/src/views/business/details.vue
src/ui/src/views/general-model/details.vue

update:ui: 审计详情接口变更

---

src/apimachinery/toposerver/inst/api.go
src/apimachinery/toposerver/inst/common.go
src/apiserver/service/url.go
src/common/metadata/audit.go
src/scene_server/topo_server/core/operation/audit.go
src/scene_server/topo_server/service/auditlog.go
src/scene_server/topo_server/service/service_initfunc.go
src/test/topo_server/inst_test.go

支持根据操作审计id批量查询审计详情

---

src/scene_server/admin_server/upgrader/x08.09.18.01/upgrader.go
src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go

- 修复3.2有存量主机数据时因为ip字段不匹配导致数据升级失败的问题

修复3.2有存量主机数据时数据升级失败的问题

---

src/scene_server/datacollection/collections/hostsnap/hostsnap.go
src/scene_server/datacollection/collections/hostsnap/window.go

修改间隔时间窗口为整时开启

---

src/ac/parser/chain.go
src/ac/parser/cloud.go
src/ac/parser/framework.go
src/ac/parser/host.go
src/ac/parser/parser.go
src/ac/parser/processtemplate.go
src/ac/parser/servicetemplate.go
src/ac/parser/settemplate.go
src/ac/parser/topolatest.go
src/ac/parser/topology.go

- 当需要获取到body里的属性的时候，再调用回调方法去获取，否则不对body进行解析

apiserver中鉴权的body性能优化

---

src/common/backbone/configcenter/cc.go
src/common/backbone/configcenter/viper.go
src/source_controller/coreservice/app/server.go
src/source_controller/coreservice/event/flow.go
src/storage/stream/event/utils.go
src/storage/stream/event/watch.go

fix: 修复flow watch内存泄漏的问题

---

src/apimachinery/discovery/server.go
src/apimachinery/discovery/server_test.go
src/common/definitions.go
src/common/metadata/process.go
src/common/util/net.go
src/source_controller/coreservice/event/gc.go

- 负载均衡策略优化
- 优化flow watch gc策略

optimize: 负载均衡策略优化

---

src/common/backbone/backbone.go

- 待http server监听成功后再注册服务地址到zk上，避免无效的服务地址注册到zk

待http server监听成功后再注册服务地址到zk上，避免无效的服务地址注册到zk

---

src/scene_server/cloud_server/cloudsync/cloudsync.go
src/scene_server/cloud_server/cloudsync/hostsyncor.go
src/scene_server/cloud_server/cloudsync/taskprocessor.go
src/scene_server/cloud_server/common/util.go

- xxxx
- xxxx
- 云同步的写操作使用相应环境的开发商 ,修复云同步任务历史记录以及云主机查询不到的问题
clost issue #4797

fix: 云同步的写操作使用相应环境的开发商 issue #4797

---

scripts/init.py
src/common/definitions.go
src/scene_server/admin_server/configures/checkconf.go
src/scene_server/admin_server/configures/conf.go
src/scene_server/datacollection/collections/hostsnap/window.go
src/web_server/middleware/user/plugins/method/open_source/userinfo.go

- 当配置变更不符合要求时，关闭admin_server服务，配置无法刷新到zk中

配置发现功能在adminserver侧做参数校验

---

scripts/Makefile
src/common/version/version.go
src/scene_server/admin_server/upgrader/configadmin.go

- 网站title配置根据版本进行初始化，版本由编译参数决定为企业版或者社区版 issue #4817
close issue #4817

feature: title配置根据版本进行初始化

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202011021415/create_unique_index.go
src/scene_server/admin_server/upgrader/y3.9.202011021415/pkg.go
src/storage/dal/mongo/local/mongo.go

feature:add unique index issue #4769

---

src/source_controller/coreservice/event/gc.go

optimize: optimize event flow gc function.

---

src/scene_server/host_server/logics/host.go
src/scene_server/host_server/service/transfer.go
src/source_controller/coreservice/core/core.go
src/source_controller/coreservice/core/host/transfer.go
src/source_controller/coreservice/core/host/transfer/manager.go
src/source_controller/coreservice/core/host/transfer/transfer.go
src/source_controller/coreservice/core/process/base.go
src/source_controller/coreservice/core/process/service_instance.go
src/source_controller/coreservice/service/host.go
src/source_controller/coreservice/service/service_instance.go

主机转移使用批量操作

---

src/ui/config/index.js
src/ui/index.html
src/ui/src/components/layout/header.vue

添加帮助文档URL配置

---

scripts/init.py
src/web_server/app/options/options.go
src/web_server/app/server.go
src/web_server/service/index.go

增加帮助文档地址配置

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202011021501/change_attr_bkosType_editable.go
src/scene_server/admin_server/upgrader/y3.9.202011021501/pkg.go

操作系统类型设置为可编辑

---

src/ui/src/components/modal/permission.vue
src/ui/src/dictionary/iam-auth.js
src/ui/src/setup/permission.js
src/ui/src/views/audit/children/audit-business-options.vue
src/ui/src/views/audit/children/audit-host-options.vue
src/ui/src/views/audit/children/audit-other-options.vue
src/ui/src/views/audit/children/audit-resource-options.vue
src/ui/src/views/audit/index.vue
src/ui/src/views/business-topology/host/across-business-module-selector.vue
src/ui/src/views/business-topology/host/host-selector-new/host-selector-custom.vue
src/ui/src/views/resource/children/host-options.vue

- 操作审计默认查询时间为当天
- 修复跨业务转移主机无权限操作时不显示权限窗口的问题
- 修复模块新增主机时手动输入ip不同云区域下相同IP仅录入一条数据的问题

UI: 权限解析优化/IP选择器优化/操作审计查询优化

---

src/ac/parser/chain.go

权限解析body时删除获取biz时的校验

---

src/common/definitions.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/logics/import.go
src/source_controller/coreservice/cache/host/host.go
src/source_controller/coreservice/core/host/cloudarea.go
src/source_controller/coreservice/core/instances/validator_unique.go

调整主机唯一校验规则

---

src/ac/parser/topology.go

修改查看审计详情的api鉴权

---

src/scene_server/datacollection/collections/hostsnap/window.go

- 启动datacollection时，在创建窗口时，如果采用第二种策略，会导致睡一会儿，阻塞datacollection的创建，解决方法把睡的代码放到协程里

修复datacollection睡眠状态没有正常启动

---

src/scene_server/auth_server/logics/list_instance.go

修复权限中心主机回调接口主机查询分页失败的问题

---

src/storage/stream/event/watch.go

- optimize watch error handle when the resume token is not exist in the oplog, when not events occurs happens in a collection.

optimize: optimize watch error handle when the resume token is not exist.

---

src/storage/driver/mongodb/README.md
src/storage/driver/mongodb/monogdb.go
src/storage/driver/mongodb/table.go

- Table(name string ) 获取name 对应的Table
- TBxxx() 直接获取对应的Table 的对象
- xxxx
- xxxx

feature: add Table and TBxxx get Table object issue #4847

---

src/common/metadata/process.go
src/scene_server/proc_server/service/processinstance.go
src/scene_server/proc_server/service/serviceinstance.go

去掉操作进程或服务实例所触发的自动更新服务实例名称逻辑

---

src/ac/parser/serviceinstance.go
src/apimachinery/coreservice/process/api.go
src/apimachinery/coreservice/process/process.go
src/apimachinery/procserver/service/api.go
src/apimachinery/procserver/service/instance.go
src/common/metadata/process.go
src/scene_server/proc_server/service/service.go
src/scene_server/proc_server/service/serviceinstance.go
src/source_controller/coreservice/core/core.go
src/source_controller/coreservice/core/process/service_instance.go
src/source_controller/coreservice/service/service_instance.go
src/source_controller/coreservice/service/service_process_initfunc.go
src/test/proc_server/no_service_template_test.go

- 增加更新服务实例的接口
close issue #4830

feature: 增加更新服务实例的接口 issue #4830

---

src/scene_server/topo_server/service/object_attribute.go
src/source_controller/coreservice/core/host/transfer/manager.go
src/source_controller/coreservice/core/model/attribute_curd.go
src/source_controller/coreservice/core/model/attribute_private.go

修复多开发商情况下一个业务会有多个相同的自定义字段的问题

---

src/apiserver/app/server.go
src/common/backbone/backbone.go
src/common/backbone/configcenter/viper.go
src/scene_server/admin_server/app/server.go
src/scene_server/admin_server/command/command.go
src/storage/driver/mongodb/monogdb.go
src/storage/driver/redis/redis.go
src/tools/cmdb_ctl/cmd/snapshot.go

调整获取redis和mongo配置代码

---

src/scene_server/admin_server/upgrader/y3.9.202008172134/update_audit_table.go
src/scene_server/topo_server/service/auditlog.go

操作审计允许根据bk_obj_id查询

---

src/source_controller/coreservice/core/host/searcher/searcher.go

- list_biz_hosts接口返回数据为空时，返回值为空数组

list_biz_hosts接口返回数据为空时，返回值为空数组

---

src/scene_server/topo_server/service/inst_business.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/thirdparty/hooks/topology.go
src/thirdparty/hooks/validator.go

-  add validate create business hook and object unique validator hooks.

optimize: add validate create business hook and object unique validator hooks.

---

src/common/metadata/process.go

- 修复服务模版同步pid文件路径、启动优先级信息失败的问题

修复服务模版同步pid文件路径、启动优先级信息失败的问题

---

src/scene_server/topo_server/service/inst_business.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/thirdparty/hooks/topology.go
src/thirdparty/hooks/types.go
src/thirdparty/hooks/validator.go

- add validate create business hook and object unique validator hooks

optimize: add validate create business hook and object unique validator hooks

---

src/source_controller/coreservice/core/instances/instance.go
src/thirdparty/hooks/process.go

添加设置进程VIP的hook

---

src/web_server/logics/host.go
src/web_server/service/host.go

- 
- xxxx
- 修复导入主机时候，自定义字段无法导出的问题 
close #4866

fix: import host not custom fields issue #4866

---

src/ac/parser/topology.go
src/apimachinery/toposerver/inst/api.go
src/apimachinery/toposerver/inst/common.go
src/common/metadata/toposerver.go
src/scene_server/topo_server/service/association.go
src/scene_server/topo_server/service/service_initfunc.go
src/test/topo_server/business_test.go

- 增加查询业务topo树简要信息的接口
close issue #4855

feature: 增加查询业务topo树简要信息的接口 issue #4855

---

scripts/init.py
src/scene_server/cloud_server/app/options/options.go
src/scene_server/cloud_server/app/server.go
src/scene_server/cloud_server/cloudsync/taskprocessor.go

- 增加云同步任务的同步周期配置 
close issue #4873

feature: 增加云同步任务的同步周期配置 issue #4873

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202011021415/create_unique_index.go
src/scene_server/admin_server/upgrader/y3.9.202011192014/change_unique_index.go
src/scene_server/admin_server/upgrader/y3.9.202011192014/pkg.go

fix: cc_PropertyGroup unique index error issue #4769

---

src/common/metadata/process.go
src/scene_server/proc_server/service/serviceinstance.go
src/source_controller/coreservice/core/process/service_instance.go

服务实例创建时可自定义名称

---

src/web_server/logics/excel.go
src/web_server/logics/excel_util.go

将主机导出excel中的'业务'修改为'业务名'。

---

src/source_controller/coreservice/core/process/process_template.go

- fix the wrong field name of template id in db query condition

fix: fix the wrong field name of template id in db query condition

---

src/common/definitions.go
src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go

清除docker_server_version和docker_client_version相关逻辑

---

src/scene_server/topo_server/core/inst/association.go
src/scene_server/topo_server/core/model/attribute.go
src/scene_server/topo_server/core/model/classification.go
src/scene_server/topo_server/core/model/group.go
src/scene_server/topo_server/core/model/object.go
src/scene_server/topo_server/core/model/unique.go
src/scene_server/topo_server/core/operation/association.go
src/scene_server/topo_server/core/operation/attribute.go
src/scene_server/topo_server/core/operation/classification.go
src/scene_server/topo_server/core/operation/graphics.go
src/scene_server/topo_server/core/operation/group.go
src/scene_server/topo_server/core/operation/identifier.go
src/scene_server/topo_server/core/operation/inst.go
src/scene_server/topo_server/core/operation/inst_business.go
src/scene_server/topo_server/core/operation/inst_module.go
src/scene_server/topo_server/core/operation/inst_set.go
src/scene_server/topo_server/core/operation/object.go
src/scene_server/topo_server/core/operation/unique.go
src/scene_server/topo_server/service/object_association.go

-
- style toposerver code 
- xxxx
close #4892

V3.9.x topo context

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202011251014/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202011251014/proc_bind_change.go

- v3.9.x 新加修改成绩bind info 相关升级
- xxxx
- xxxx

v3.9.x 新加修改成绩bind info 相关升级

---

src/common/metadata/process.go
src/scene_server/proc_server/service/processtemplate.go

- 进程服务模版列表接口支持只传进程模版id数组批量获取进程模版详情

进程服务模版列表接口支持只传进程模版id数组批量获取进程模版详情

---

src/ui/src/components/search/service-template.vue
src/ui/src/store/modules/api/service-template.js
src/ui/src/views/business-topology/children/create-module.vue
src/ui/src/views/service-template/index.vue
src/ui/src/views/set-template/children/service-template-selector.vue

UI: 服务模板列表数量同步查询变更为异步查询

---

src/common/metadata/audit.go

审计查询接口，时间字段调整为必填字段

---

src/source_controller/cacheservice/cache/business/client.go
src/source_controller/cacheservice/event/flow.go

optimize: code optimize

---

src/ui/src/components/model-instance/audit-history.vue
src/ui/src/views/audit/children/audit-business-options.vue
src/ui/src/views/audit/children/audit-host-options.vue
src/ui/src/views/audit/children/audit-other-options.vue
src/ui/src/views/audit/children/audit-resource-options.vue
src/ui/src/views/history/index.vue

UI: 操作审计查询时间范围限制不可清空

---

scripts/init.py
src/scene_server/admin_server/configures/checkconf.go
src/scene_server/operation_server/logics/logics.go
src/web_server/app/options/options.go
src/web_server/app/server.go
src/web_server/service/index.go

运营统计功能添加开关用于把定时收集数据功能关闭

---

src/ac/parser/servicetemplate.go
src/apimachinery/procserver/service/api.go
src/apimachinery/procserver/service/template.go
src/common/metadata/core_service.go
src/scene_server/proc_server/service/service.go
src/scene_server/proc_server/service/servicetemplate.go
src/source_controller/coreservice/service/count.go
src/test/proc_server/service_template_test.go

- 增加批量查询服务模版计数信息的接口
close issue #4888

feature: 增加批量查询服务模版计数信息的接口 issue #4888

---

src/common/metadata/process_bind_info.go

- proc, proc template bind info allowed empty 
- xxxx
- xxxx
close  #4909

feature: proc, proc template bind info allowed empty issue #4909

---

src/scene_server/proc_server/logics/processinstance.go
src/scene_server/proc_server/service/processinstance.go
src/source_controller/coreservice/core/instances/instance.go
src/thirdparty/hooks/process.go

将查询进程的具体操作从service拆出到logics

---

src/apimachinery/rest/client.go
src/common/http/rest/contexts.go
src/common/http/rest/metric.go
src/common/http/rest/rest.go
src/common/metrics/metrics.go
src/scene_server/event_server/distribution/distributer.go
src/scene_server/event_server/distribution/event.go
src/storage/dal/mongo/local/metric.go
src/storage/dal/mongo/local/mongo.go

- add mongodb, rest response metrics

optimize: add mongodb, rest response metrics

---

src/scene_server/proc_server/service/servicetemplate.go

修复不能按服务模版名查找筛选服务模版列表的问题

---

src/scene_server/topo_server/service/set_template.go

- xxxx
-  优化 /findmany/topo/set_template/{set_template_id}/bk_biz_id/{bk_biz_id}/service_templates/with_statistics   处理逻辑
- xxxx

优化toposerver

---

src/ac/parser/host.go
src/common/metadata/common.go
src/scene_server/host_server/logics/module.go
src/test/host_server/host_abnormal_test.go
src/test/host_server/host_server_suite_test.go
src/test/host_server/host_test.go

从业务归还主机到主机池，支持选择目标目录

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202011171550/change_process_attr.go
src/scene_server/admin_server/upgrader/y3.9.202012011450/change_proc_attr_index.go
src/scene_server/admin_server/upgrader/y3.9.202012011450/pkg.go

- 调整进程属性字段的展示顺序
- 将启动等待时长的最小值设为0

调整进程属性字段的展示顺序，将启动等待时长的最小值设为0

---

src/scene_server/topo_server/core/settemplate/settemplate.go

优化集群模板对比和同步接口

---

src/scene_server/auth_server/logics/util.go
src/scene_server/auth_server/service/service.go
src/source_controller/coreservice/core/instances/instance.go
src/thirdparty/hooks/process.go

修复存在多个开发商的资源池时authserver查询到错误的资源池ID的问题

---

src/scene_server/topo_server/core/settemplate/settemplate.go
src/scene_server/topo_server/core/settemplate/sync_status.go

- xxxx
- xxxx
- 修复toposerver 未透传coreservice 错误

refactor: error code topo  issue #4912

---

src/web_server/logics/excel.go
src/web_server/logics/excel_commet_sheet.go
src/web_server/logics/excel_util.go
src/web_server/logics/fields.go
src/web_server/logics/netdevice.go
src/web_server/logics/netproperty.go

主机导出支持选择字段

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202011201146/remove_redundant_items.go
src/scene_server/admin_server/upgrader/y3.9.202011301723/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202011301723/remove_default_field.go
src/scene_server/topo_server/core/operation/association_mainline_inst.go

清除自定义层级实例的default字段

---

src/scene_server/topo_server/service/inst_business.go

修复同时用多个用户条件查询业务时仅使用了其中一个字段的问题

---

src/ui/src/components/export-fields/export-fields.vue
src/ui/src/views/service-template/children/operational.vue

- 导出主机可选字段不显示ID和业务拓扑
- 服务模板重复点击提交问题优化

UI: 导出主机可选字段不显示ID和业务拓扑及服务模板重复点击提交问题优化

---

src/ui/src/components/ui/auth/auth-queue.js
src/ui/src/views/business-topology/host/across-business-module-selector.vue

optimize:ui: 优化前端鉴权性能

---

src/apimachinery/cacheservice/cache/host/api.go
src/apimachinery/cacheservice/cache/host/cache.go
src/apimachinery/coreservice/host/api.go
src/apimachinery/coreservice/host/host.go
src/scene_server/host_server/service/host.go
src/source_controller/cacheservice/service/cache.go
src/source_controller/cacheservice/service/service_initfunc.go
src/source_controller/coreservice/service/host.go
src/source_controller/coreservice/service/service_initfunc.go

- 将coreservice中的主机快照数据接口迁移到cacheservice

optimize: 将coreservice中的主机快照数据接口迁移到cacheservice

---

src/Makefile
src/storage/stream/event/watch.go
src/storage/stream/loop/loop_watch.go
src/storage/stream/stream.go
src/storage/stream/types/types.go

feature: add loop watch stream to support handle event with one by one or batch policy.

---

src/apiserver/service/healthz.go
src/common/metric/client.go
src/common/metric/type.go
src/scene_server/admin_server/service/service.go
src/scene_server/auth_server/service/health.go
src/scene_server/cloud_server/service/health.go
src/scene_server/datacollection/service/service.go
src/scene_server/event_server/service/service.go
src/scene_server/host_server/service/service.go
src/scene_server/operation_server/service/service.go
src/scene_server/proc_server/service/service.go
src/scene_server/synchronize_server/service/service.go
src/scene_server/task_server/service/service.go
src/scene_server/topo_server/service/health.go
src/source_controller/cacheservice/service/health.go
src/source_controller/coreservice/service/health.go
src/web_server/service/service.go

healthz 添加version

---

src/web_server/logics/excel.go
src/web_server/logics/excel_util.go

- 之前在webserver中直接调用了coreservice接口，没有经过鉴权。
本次修正了这个错误，调用经过apiserver鉴权的场景层接口。
close #4876

fix: 修正不正确的excel逻辑内接口调用

---

src/ac/parser/host.go
src/scene_server/host_server/logics/module.go
src/test/host_server/host_abnormal_test.go
src/test/host_server/host_test.go

主机转移至资源池接口兼容未填写主机池目录的场景

---

src/scene_server/topo_server/core/operation/association_mainline_object.go
src/scene_server/topo_server/core/operation/import_association.go
src/scene_server/topo_server/core/settemplate/settemplate.go
src/scene_server/topo_server/core/settemplate/sync_status.go
src/scene_server/topo_server/service/association.go
src/scene_server/topo_server/service/set_template.go

style:  topo   issue #4912

---

src/scene_server/admin_server/app/server.go
src/scene_server/admin_server/configures/conf.go
src/scene_server/admin_server/service/migrate.go
src/scene_server/admin_server/service/service.go

- 增加刷新配置的api，在不重启adminserver的情况下更新配置中心的配置
close issue #4946

feature: 增加刷新配置的api，在不重启adminserver的情况下更新配置中心的配置 issue #4946

---

src/ac/parser/cache.go
src/ac/parser/chain.go
src/ac/parser/topolatest.go
src/apiserver/service/filter.go
src/apiserver/service/url.go
src/common/http/rest/contexts.go
src/common/util/array.go
src/source_controller/cacheservice/cache/cache.go
src/source_controller/cacheservice/cache/topology/client.go
src/source_controller/cacheservice/cache/topology/key.go
src/source_controller/cacheservice/cache/topology/logic.go
src/source_controller/cacheservice/cache/topology/readme.md
src/source_controller/cacheservice/cache/topology/topology.go
src/source_controller/cacheservice/cache/topology/types.go
src/source_controller/cacheservice/cache/topology/watch.go
src/source_controller/cacheservice/service/cache.go
src/source_controller/cacheservice/service/service.go
src/source_controller/cacheservice/service/service_initfunc.go

- 新增查询业务的简明拓扑信息接口，该接口为缓存接口，包含了从业务，自定义层级，集群到模块的完整拓扑信息。

feature: add new api to get brief business topology from cache.

---

scripts/prepare_cfg.py
scripts/refresh_config.sh
src/scene_server/admin_server/service/migrate.go

增加刷新配置的shell工具脚本

---

src/ac/parser/cache.go
src/apimachinery/cacheservice/cache/topology/api.go
src/apimachinery/cacheservice/cache/topology/cache.go
src/common/metrics/metrics.go
src/scene_server/topo_server/service/cache.go
src/scene_server/topo_server/service/service_initfunc.go
src/source_controller/cacheservice/cache/business/client.go
src/source_controller/cacheservice/cache/business/client_logic.go
src/source_controller/cacheservice/cache/business/custom_level.go
src/source_controller/cacheservice/service/cache.go
src/source_controller/cacheservice/service/service_initfunc.go

- optimize: move topo path related cache api to cache service directly.

optimize: move topo path related cache api to cache service directly.

---

src/ui/src/views/host-details/children/info.vue

主机详情业务拓扑链接跳转优化

---

src/common/http/rest/contexts.go
src/web_server/service/service.go

optimize: code optimize.

---

src/ui/src/components/filters/property-selector.vue
src/ui/src/views/service-template/children/operational.vue
src/ui/src/views/service-template/index.vue
src/ui/src/views/set-template/children/service-template-selector.vue
src/ui/src/views/set-template/index.vue

- 主机筛选条件字段不显示业务拓扑
- 服务模板删除进程显示同步实例提示
- 集群模板编辑时添加模板支持全选和不显示列表中的编辑按钮
- 服务模板列表不显示编辑按钮

UI: 体验问题修复

---

src/apiserver/service/limiter.go
src/common/backbone/configcenter/cc.go
src/common/registerdiscover/zkregdiscv.go

- 优化zk重连操作
- 修复清空zk上的限流规则后没有被同步的问题
- 修复zk上的cc配置没有持续被watch的问题

zk配置watch问题修复

---

src/web_server/service/host.go
src/web_server/service/util.go

- 修复主机导出时的空指针引用panic和登陆版本获取错误的问题

修复主机导出时的空指针引用panic和登陆版本获取错误的问题

---

src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/core/instances/instance_crud.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/source_controller/coreservice/core/instances/validator.go
src/source_controller/coreservice/core/instances/validator_unique.go

优化模型实例的创建和更新操作

---

src/web_server/logics/excel_util.go

- 修复excel导入数据里用户类型值为中英文时的正则校验失败问题

修复excel导入数据里用户类型值为中英文时的正则校验失败问题

---

src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
src/storage/driver/mongodb/table.go

… issue #4757
- xxxx
- xxxx
- fix: v3.2.21 upgrade v3.9.11 process template bind info not  upgrade

fix: v3.2.21 upgrade v3.9.11 process template bind info not upgrade

---

src/scene_server/topo_server/service/inst.go

- 添加校验禁止用通用模型实例接口查询biz, module, set, host, plat, process

添加校验禁止用通用模型实例接口查询biz, module, set, host, plat, process

---

src/web_server/logics/excel.go
src/web_server/logics/excel_util.go
src/web_server/logics/util.go

- 去掉excel导出字段业务拓扑里的业务级别
- 去掉下载主机excel模版里云区域字段
- excel导出的云区域ID字段标注为--

excel导出字段优化

---

src/source_controller/coreservice/core/instances/instance_validate.go
src/thirdparty/hooks/validator.go

添加判断主机云区域更新操作是否合法的hook

---

src/ui/src/views/service-instance/children/clone-to-other.vue
src/ui/src/views/service-instance/create.vue

optimize:ui: 转移主机新增服务实例默认折叠

---

src/scene_server/topo_server/core/operation/association.go
src/scene_server/topo_server/core/operation/inst.go
src/scene_server/topo_server/core/operation/inst_business.go
src/scene_server/topo_server/core/operation/inst_module.go
src/scene_server/topo_server/core/operation/inst_set.go
src/scene_server/topo_server/core/operation/types.go
src/scene_server/topo_server/core/settemplate/worker.go
src/scene_server/topo_server/service/inst.go
src/scene_server/topo_server/service/inst_business.go
src/scene_server/topo_server/service/inst_module.go
src/scene_server/topo_server/service/inst_set.go

删除实例操作性能优化

---

resources/language/default/web.json
resources/language/en/web.json
src/common/definitions.go
src/web_server/logics/host.go
src/web_server/service/host.go

- excel导出主机支持大批量导出
close issue #4982

feature: excel导出主机支持大批量导出 issue #4982

---

src/source_controller/cacheservice/event/watch/client.go
src/source_controller/cacheservice/event/watch/watch.go

修复查询上一次最后的事件的条件错误的问题

---

src/source_controller/coreservice/core/instances/instance_validate.go

修复主机云区域更新校验传值顺序错误的问题

---

src/ui/package.json
src/ui/src/components/model-manage/field-group/preview-field.vue
src/ui/src/components/search/longchar.vue
src/ui/src/components/search/singlechar.vue
src/ui/src/components/search/table.vue
src/ui/src/components/service/instance-table.vue
src/ui/src/components/ui/form/form-multiple.vue
src/ui/src/components/ui/form/form.vue
src/ui/src/components/ui/form/organization.vue
src/ui/src/views/host-operation/children/create-service-instance.vue
src/ui/src/views/index/children/host-search.vue
src/ui/src/views/resource/children/host-list.vue
src/ui/src/views/resource/children/host-options.vue
src/ui/src/views/resource/transfer/transfer-menu.vue
src/ui/src/views/service-instance/create.vue
src/ui/src/views/service-template/children/operational.vue
src/ui/src/views/service-template/children/process-form.vue
src/ui/src/views/service-template/index.vue

- 主机搜索字符类型支持粘贴
- 修复首页云区域混合搜索判断错误的问题
- 修复服务分类模板分类筛选错误的问题
- 修复资源池业务拓扑复制数据为空的问题
- 修复转移主机目录可重复点击的问题
- 修复模板模块新增服务实例第一内外网IP设置不正确的问题

UI: 3.9.15缺陷修复

---

src/ui/src/views/business-topology/host/host-list.vue

修复业务拓扑下跨业务转主机错误

---

src/web_server/logics/association.go

修复导出带有关联关系主机excel失败的问题

---

src/apimachinery/rest/request.go
src/apiserver/service/http.go

optimize: add record time latency log function.

---

src/storage/dal/mongo/local/mongo.go
vendor/gopkg.in/mgo.v2/session.go

- xxxx
- xxxx
- mongodb 执行语句超时后，mgo session 一直无法使用的问题
close   #5019

fix: mgo driver session i/o time issue #5019

---

src/source_controller/coreservice/core/instances/validator.go
src/source_controller/coreservice/core/instances/validator_unique.go

修复批量更新带有部分联合唯一键字段时失败的问题

---

src/apimachinery/coreservice/cloud/api.go
src/apimachinery/coreservice/common/api.go
src/apimachinery/coreservice/event/api.go
src/apimachinery/coreservice/hostapplyrule/api.go
src/apimachinery/coreservice/label/api.go
src/apimachinery/coreservice/mainline/api.go
src/apimachinery/coreservice/process/api.go
src/apimachinery/coreservice/process/process.go
src/apimachinery/coreservice/settemplate/api.go
src/apimachinery/toposerver/settemplate/settemplate.go
src/common/metadata/core_service.go
src/common/metadata/process.go
src/scene_server/proc_server/logics/processinstance.go
src/scene_server/proc_server/service/processinstance.go
src/scene_server/proc_server/service/serviceinstance.go
src/source_controller/coreservice/core/core.go
src/source_controller/coreservice/core/host/cloudarea.go
src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/core/process/base.go
src/source_controller/coreservice/core/process/process_instance_relation.go
src/source_controller/coreservice/core/process/service_instance.go
src/source_controller/coreservice/service/count.go
src/source_controller/coreservice/service/process_instance_relation.go
src/source_controller/coreservice/service/service_instance.go
src/source_controller/coreservice/service/service_process_initfunc.go

- 创建服务实例接口性能优化
优化方式：
- 改为并发新增服务实例
- 改为批量新增进程实例
- 改为批量新增进程服务实例关系
- 改为并发更新模型实例
- 优化进程创建更新时的唯一校验逻辑
- 优化服务实例名称构造更新逻辑
close issue #5021

创建服务实例接口性能优化

---

src/scene_server/datacollection/collections/hostsnap/hostsnap.go

调整主机快照更新逻辑，只更新有效数据

---

src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/source_controller/coreservice/service/service.go
src/thirdparty/hooks/validator.go

添加校验业务字段的hook

---

src/scene_server/topo_server/core/operation/inst_business.go
src/scene_server/topo_server/service/inst_business.go
src/scene_server/topo_server/service/service_initfunc.go

去除物理删除业务实例的代码

---

src/common/watch/cursor.go
src/scene_server/event_server/distribution/distributer.go
src/scene_server/event_server/distribution/event.go
src/scene_server/event_server/watcher/watch.go
src/source_controller/cacheservice/cache/topology/watch.go

优化事件订阅的日志输出

---

src/common/metadata/hostserver.go
src/scene_server/datacollection/app/server.go
src/scene_server/host_server/service/host.go

- host property clone api support clone with host id.

feature: host property clone api support clone with host id.

---

src/auth/extensions/classification.go
src/auth/extensions/host.go

修复同步权限中心数据时的查询逻辑bug

---

src/scene_server/datacollection/collections/hostsnap/hostsnap.go

主机静态快照数据形态调整

---

src/storage/stream/loop/loop_watch.go

事件不需要重试时将retryCount归零

---

src/source_controller/cacheservice/event/watch/client.go

修复不带fields监听事件时查询删除事件详情失败的问题

---

src/common/metadata/audit.go
src/source_controller/coreservice/core/auditlog/audit.go

- 操作审计新增appcode与request id字段，用于回溯对账
背景：现在有平台用admin等虚拟账号，进行操作，出问题时，无法追溯，对账。

操作审计新增appcode与request id字段

---

src/source_controller/coreservice/core/process/service_instance.go

修复主机转移到带模版的模块下重复创建进程实例的问题

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/x21.02.26.11/add_instass_index.go
src/scene_server/admin_server/upgrader/x21.02.26.11/pkg.go

- 给实例关联表增加索引
增加索引过程中出现的问题，处理方式可参考 issue #5072

给实例关联表增加索引

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202102261105/add_instass_proc_index.go
src/scene_server/admin_server/upgrader/y3.9.202102261105/pkg.go

- 给实例关联表和进程模版表增加索引
增加索引过程中出现的问题，处理方式可参考 issue #5072

给实例关联表和进程模版表增加索引

---

src/source_controller/coreservice/core/instances/instance_validate.go

- 主线模型实例创建更新时，对bk_parent_id字段进行校验

主线模型实例创建更新时，对bk_parent_id字段进行校验

---

src/scene_server/host_server/service/host.go
src/web_server/logics/excel_util.go

主机可导出'录入方式'和'录入时间'字段

---

src/common/metadata/host_apply_rule.go
src/scene_server/host_server/service/host.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/thirdparty/hooks/validator.go

主机更新时允许更新绑定了自动应用的字段

---

src/ac/extensions/business.go
src/scene_server/topo_server/service/inst_business.go

调整查询业务无权限错误返回

---

src/ac/extensions/model.go
src/common/definitions.go
src/common/http/rest/contexts.go
src/common/util/model.go
src/common/watch/types.go
src/scene_server/host_server/logics/host.go
src/scene_server/topo_server/core/operation/attribute.go
src/scene_server/topo_server/core/operation/group.go
src/source_controller/cacheservice/cache/topology/key.go
src/source_controller/cacheservice/cache/topology/watch.go
src/source_controller/cacheservice/event/flow/flow.go
src/source_controller/cacheservice/event/watch/client.go
src/source_controller/cacheservice/service/cache.go
src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/core/model/attribute_private.go
src/source_controller/coreservice/service/instances_dependence.go
src/storage/dal/mongo/local/mongo.go
src/storage/stream/event/watch.go
src/storage/stream/types/types.go
src/thirdparty/hooks/process.go

- 第一次watch如果有例如token过期的错误则不用token拉取事件
- watch失败时返回真实错误码而非-1

第一次watch如果有例如token过期的错误则不用token拉取事件

---

src/apiserver/service/url.go

- 修复无法创建模型的问题
- 修复无法显示实例关联关系的问题

修复无法创建模型和无法显示实例关联关系的问题

---

src/scene_server/proc_server/service/processinstance.go

修复进程编辑后报唯一校验失败而无法保存的问题

---

src/scene_server/proc_server/service/processinstance.go

点分五位获取进程实例信息接口支持按进程字段排序

---

src/apiserver/service/url.go

调整object接口的路由匹配方式

---

src/common/metadata/process.go
src/common/querybuilder/types.go
src/scene_server/auth_server/logics/parser.go
src/scene_server/proc_server/logics/processinstance.go

修复解析到$not的条件为字符串的问题

---

src/ui/src/components/model-instance/audit-history.vue
src/ui/src/views/host-details/index.vue

- 主机实时状态功能下线，监控系统接管
- 修复实例详情变更记录搜索为空时显示错误的问题

UI：主机实时状态功能下线

---

src/apimachinery/apiserver/api.go

修复模型属性无法导出的问题

---

src/common/metadata/attribute.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202103031533/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202103031533/remove_bk_cpu_mhz_field.go
src/scene_server/datacollection/collections/hostsnap/hostsnap.go
src/scene_server/datacollection/collections/hostsnap/window.go

- 去掉CPU频率字段bk_cpu_mhz的采集，模型字段及主机实例上的字段

去掉CPU频率字段bk_cpu_mhz的采集，模型字段及主机实例上的字段

---

src/common/metadata/core_service.go
src/common/metadata/process.go
src/scene_server/proc_server/service/servicetemplate.go
src/source_controller/coreservice/core/process/service_template.go

查询服务模版列表接口支持按模版名称精确或模糊匹配查找

---

src/common/mapping.go
src/source_controller/coreservice/core/instances/instance_validate.go

- 优化主线模型实例校验逻辑
- 修复新增自定义层级后，原业务下的集群及模块不可见的问题

修复新增自定义层级后，原业务下的集群及模块不可见的问题

---

src/scene_server/topo_server/core/settemplate/sync_status.go
src/source_controller/coreservice/core/host/transfer/transfer.go

optimize: log optimize.

---

src/common/watch/types.go
src/storage/stream/types/types.go

修复初始化事件表的时候StartAtTime为空时panic的问题

---

src/common/registerdiscover/zkregdiscv.go

修复zk节点丢失后不能重新注册的问题

---

src/common/metadata/process_bind_info.go

- 进程模板新增绑定信息，同步时使用默认值新增进程中的绑定信息

进程模板新增绑定信息，同步时使用默认值新增进程中的绑定信息

---

src/ac/parser/topolatest.go

修复导出模型失败的问题

---

src/source_controller/coreservice/core/instances/instance.go
src/thirdparty/hooks/process.go

调整更新进程bind info的hook

---

src/apimachinery/rest/client.go
src/apimachinery/rest/request.go
src/apimachinery/util/type.go

- set request tolerance latency time with a options.

optimize: set request tolerance latency time with a options.

---

src/common/watch/cursor.go
src/common/watch/cursor_test.go
src/common/watch/types.go
src/scene_server/admin_server/service/migrate.go
src/source_controller/cacheservice/cache/topology/key.go
src/source_controller/cacheservice/event/flow/flow.go
src/storage/stream/event/watch.go
src/storage/stream/types/types.go
src/tools/cmdb_ctl/cmd/watch.go

TimeStamp不使用指针类型防止空指针异常

---

src/source_controller/cacheservice/event/flow/flow.go
src/thirdparty/monitor/meta/type.go

调整事件生成入库逻辑

---

src/storage/dal/mongo/local/mongo.go
src/storage/driver/mongodb/table.go

fix： 根据代码review修改提交. issue #5085

---

src/storage/dal/mongo/local/mongo.go

调整索引重复的判断逻辑

---

src/scene_server/cloud_server/cloudsync/taskscheduler.go
src/source_controller/cacheservice/cache/business/custom_level.go
src/source_controller/cacheservice/cache/business/module_set.go
src/source_controller/cacheservice/cache/host/host.go
src/source_controller/cacheservice/event/flow/event.go
src/source_controller/cacheservice/event/flow/flow.go
src/source_controller/cacheservice/event/flow/gc.go
src/source_controller/cacheservice/event/watch/watch.go
src/storage/stream/event/list_watch.go
src/storage/stream/event/watch.go
src/thirdparty/monitor/monitor.go
src/thirdparty/monitor/plugins/blueking/blueking.go
src/thirdparty/monitor/plugins/blueking/gsecmdline.go

- change the watch event startup mode with asynchronize policy.
- optimize the conflict cursor handle policy in event flow function

optimize: change the watch event startup mode with asynchronize policy.

---

src/storage/driver/mongodb/instancemapping/inst_mapping.go

-  实例id与模型id 的对应关系的索引表
- xxxx
- xxxx

feature: add instance objectID mapping handle  issue #5085

---

src/storage/driver/mongodb/instancemapping/inst_mapping.go

- do some coding style optimizes

style: instance mapping funcs coding style optimize

---

src/apimachinery/rest/request.go
src/scene_server/host_server/logics/module.go
src/scene_server/host_server/service/host.go
src/scene_server/host_server/service/module.go
src/storage/stream/event/watch.go
src/storage/stream/loop/loop_watch.go

- 调整查询内置模块的方式，不带模块名
- fix loop watch share observer issue which will cause skip re-watch operation because of the is-master check is shared.

fix: fix loop watch share observer issue and code optimize.

---

src/storage/stream/loop/loop_watch.go

- fix loop watch share observer issue

fix: fix loop watch share observer issue 

---

src/common/tablenames.go

optimize: table names about object sharding tables prefix

---

src/common/metadata/host.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202103231621/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202103231621/update_host_empty_special_field.go

- 主机IP等特殊字段转换为数组时如果为空则值置为nil，非空则去除前后空格和逗号

主机IP等特殊字段转换为数组时如果为空则值置为nil，非空则去除前后空格和逗号

---

docs/overview/installation.md

-  更新monstache 使用文档
- xxxx
- xxxx

docs: update monstache doc issue #5085

---

src/common/auditlog/attribute_group.go
src/common/auditlog/object.go
src/common/auditlog/object_attribute.go
src/common/auditlog/object_classification.go
src/scene_server/datacollection/collections/porter.go

fix: 部分审计日志逻辑存在panic风险

---

src/apimachinery/coreservice/model/api.go
src/apimachinery/coreservice/model/model.go
src/common/index/instance.go
src/common/metadata/core_service.go
src/scene_server/admin_server/logics/index.go
src/scene_server/topo_server/service/association.go
src/scene_server/topo_server/service/object.go
src/source_controller/coreservice/core/core.go
src/source_controller/coreservice/core/model/model.go
src/source_controller/coreservice/core/model/model_tables.go
src/source_controller/coreservice/core/model/unique_crud.go
src/source_controller/coreservice/service/model.go
src/source_controller/coreservice/service/service_initfunc.go
src/storage/dal/types/types.go
src/test/test.go

- 将新加表和事务放到事务执行之前
- xxxx
- xxxx

V3.9.x feature instasst migrate

---

src/common/index/index.go
src/common/metadata/host.go
src/tools/cmdb_ctl/cmd/unique.go

添加升级前校验实例数据是否满足唯一索引校验的工具

---

src/scene_server/datacollection/collections/hostsnap/hostsnap.go

- 主机快照采集支持在多IP的情况下获取各IP对应的mac地址

主机快照采集支持在多IP的情况下获取各IP对应的mac地址

---

src/ui/src/components/model-instance/relation/create.vue
src/ui/src/components/model-instance/relation/list-table.vue
src/ui/src/store/modules/api/object-association.js
src/ui/src/views/host-details/children/association-create.vue
src/ui/src/views/host-details/children/association-list-table.vue

模型实例关联接口参数调整

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202104011012/add_bk_cpu_architecture_attr.go
src/scene_server/admin_server/upgrader/y3.9.202104011012/pkg.go

主机模型的内置字段添加“CPU架构”

---

src/ui/src/components/host-apply/conflict-resolve.vue
src/ui/src/components/layout/dynamic-navigation.vue
src/ui/src/components/model-manage/field-group/field-detail/index.vue
src/ui/src/components/model-manage/field-group/field-view.vue
src/ui/src/components/model-manage/field-group/preview-field.vue
src/ui/src/components/ui/details/details.vue
src/ui/src/components/ui/form/form-multiple.vue
src/ui/src/components/ui/form/form.vue
src/ui/src/router/business-interceptor.js
src/ui/src/router/index.js
src/ui/src/setup/preload.js
src/ui/src/views/business-topology/children/form-service-category.vue
src/ui/src/views/business-topology/children/node-extra-info-service-template.vue
src/ui/src/views/business-topology/children/node-extra-info-set-template.vue
src/ui/src/views/business-topology/children/node-extra-info.vue
src/ui/src/views/business-topology/children/service-node-info.vue
src/ui/src/views/general-model/index.vue
src/ui/src/views/host-apply/conflict-list.vue
src/ui/src/views/host-apply/property-confirm.vue
src/ui/src/views/service-template/children/process-form.vue
src/ui/src/views/set-sync/sync-index.vue

- 业务拓扑模块节点信息添加属性自动应用标识
- 业务导航权限列表静默刷新
- 粘性布局闪烁的问题
- 部分字段预览失败的问题

UI: 模块信息属性自动应用标识

---

src/ac/parser/host.go
src/common/metadata/hostcontroller.go
src/common/metadata/hostserver.go
src/common/querybuilder/types.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/logics/hostsearch.go
src/scene_server/host_server/logics/module.go
src/scene_server/host_server/logics/set.go
src/scene_server/host_server/service/findhost.go
src/scene_server/host_server/service/module.go
src/scene_server/host_server/service/service_initfunc.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/source_controller/coreservice/service/hostmodule.go

1. 根据自定义层级实例信息查询主机所属的关系。
2. 根据主机的信息，构建查询条件，查询主机详情与其所属拓扑的信息。
3. 新增支持contain,exist,not_exists查询操作符，其中contain操作符为正则查询，且大小写不敏感

feature: 新增查询主机关系、主机详情与主机所属拓扑功能接口

---

src/common/metadata/process.go
src/scene_server/proc_server/service/serviceinstance.go

查询服务模版差异接口支持部分比较而提前返回差异结果

---

src/ac/iam/adaptor.go
src/ac/iam/initial_action_groups.go
src/ac/iam/initial_actions.go
src/ac/iam/types.go
src/ac/meta/meta.go
src/apiserver/service/filter.go

注册进程事件监听权限到权限中心

---

src/storage/dal/mongo/local/mongo.go

- 调整mongodb查询接口支持左高右低优先级的多字段排序
```
原先的sort选项设置的是个map，多个字段的优先级是无序的；调整后，支持多字段有序优先级排序
sort值为"host_id, -host_name"和sort值为"host_id:1, host_name:-1"是一样的，都代表先按host_id递增排序，再按host_name递减排序
```

调整mongodb查询接口支持左高右低优先级的多字段排序

---

src/common/metadata/process.go
src/common/querybuilder/types.go
src/scene_server/proc_server/service/processinstance.go
src/test/proc_server/no_service_template_test.go

点分五位查询进程的接口支持按进程属性筛选查询

---

docs/overview/installation.md
src/common/index/instance.go

- xxxx
-  更新文档
- 更新实例表索引
- xxxx

Feature instasst

---

src/scene_server/datacollection/collections/hostsnap/hostsnap.go

主机快照采集对mac地址进行去重

---

src/common/backbone/notice.go
src/common/registerdiscover/zkregdiscv.go
src/common/zkclient/zkclient.go
src/web_server/middleware/user/plugins/method/open_source/userinfo.go

修复在zk连接失败的情况下多次重连产生多个连接的问题

---

src/common/metadata/process.go
src/scene_server/proc_server/service/serviceinstance.go

- 服务模板同步对比接口返回值带上service_template_id

服务模板同步对比接口返回值带上service_template_id

---

src/ui/src/components/model-instance/property.vue
src/ui/src/store/modules/view/host-details.js
src/ui/src/utils/tools.js
src/ui/src/views/business-topology/children/node-extra-info-service-template.vue
src/ui/src/views/host-details/children/property.vue

- 实例时间字段格式化，避免提交UTC格式
- 属性自动应用启停判断修正

UI: 实例时间字段格式化、属性自动应用启停判断修正

---

src/common/watch/watch.go
src/scene_server/admin_server/upgrader/x19.05.16.01/add_default_category.go
src/source_controller/cacheservice/event/flow/flow.go

修复创建默认服务分类所在的upgrader失败时重复创建多个服务分类的问题

---

src/ac/extensions/model.go
src/ac/parser/topolatest.go
src/apimachinery/apiserver/api.go
src/apimachinery/apiserver/apiserver.go
src/scene_server/topo_server/service/object.go
src/source_controller/coreservice/core/instances/instance.go
src/web_server/service/object.go

修复导入模型权限解析报错的问题

---

docs/overview/installation.md

- monstache 同步mongodb 数据到es支持多租户 
- xxxx
- xxxx

monstache 同步mongodb 数据到es支持多租户

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202104121004/inner_object_index.go
src/scene_server/admin_server/upgrader/y3.9.202104121004/mapping.go
src/scene_server/admin_server/upgrader/y3.9.202104121004/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202104121004/split_inst_table.go

- xxxx
-  更新upgrade 数据的版本的时间
- xxxx

更新upgrade 数据的版本的时间

---

src/scene_server/admin_server/logics/index.go
src/scene_server/admin_server/upgrader/y3.9.202104121004/drop_plat_vpcid_index.go
src/scene_server/admin_server/upgrader/y3.9.202104121004/pkg.go
src/thirdparty/monitor/meta/type.go

- 删除运区域bk_vpc_id 的唯一索引
- admin 定时执行索引任务出现问题，收集报警
- xxxx
- xxxx

index提供报警和调整运区域唯一索引

---

src/scene_server/admin_server/upgrader/y3.9.202104011012/add_bk_cpu_architecture_attr.go
src/scene_server/topo_server/core/operation/inst_module.go

- 添加主机模型的“CPU架构”字段之前校验它所在的属性分组是否存在

添加主机模型的“CPU架构”字段之前校验它所在的属性分组是否存在

---

src/source_controller/coreservice/core/instances/instance_validate.go

validUpdateInstanceData接口的ignore keys校验必须是内置模型，包括主线模型

---

src/scene_server/datacollection/collections/hostsnap/hostsnap.go

- 主机快照采集改为ip与mac地址一一对应，如果ip没有对应的mac则置空

主机快照采集改为ip与mac地址一一对应，如果ip没有对应的mac则置空

---

src/scene_server/topo_server/core/operation/inst.go

修复非主机业务资源下点击列表排序无法排序问题 issue #5139

---

src/source_controller/coreservice/core/mainline/manager.go

- 修复获取拓扑路径接口使用metadata查询主线模型实例的问题

修复获取拓扑路径接口使用metadata查询主线模型实例的问题

---

src/source_controller/coreservice/core/model/model.go

fix: do not drop sharding tables in coreservices. issue #5203

---

src/scene_server/topo_server/service/fulltextsearch.go

- 修复es全文检索不到含_或.字符的问题，并能够检索到含有([等特殊字符的内容

修复es全文检索不到含_或.字符的问题，并能够检索到含有([等特殊字符的内容

---

src/common/metadata/audit.go
src/scene_server/topo_server/service/auditlog.go

支持通过bk_obj_id查询实例关联的操作审计

---

src/ui/src/views/audit/children/audit-resource-options.vue

操作审计查询实例关联添加模型条件

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202104211151/change_set_unique_index.go
src/scene_server/admin_server/upgrader/y3.9.202104211151/pkg.go

开放不同自定义层级下集群同名限制

---

src/web_server/logics/excel.go
src/web_server/logics/util.go

bugfix 修复导出用户类型字段顺序与录入顺序不同问题 Issue#5210

---

src/scene_server/admin_server/upgrader/y3.9.202104121004/split_inst_table.go
src/source_controller/cacheservice/event/watch/client.go
src/storage/dal/mongo/local/mongo.go
src/storage/dal/types/types.go

- dal  新加list 方法
- 优化现有FindOptions 使用方法
- xxxx

feature: dal add function list issue #5192

---

docs/overview/installation.md
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202104221702/drop_plat_vpcid_index.go
src/scene_server/admin_server/upgrader/y3.9.202104221702/inner_object_index.go
src/scene_server/admin_server/upgrader/y3.9.202104221702/mapping.go
src/scene_server/admin_server/upgrader/y3.9.202104221702/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202104221702/split_inst_table.go

- 不同模型实例使用不同es索引
- 修改upgrader 版本
- xxxx
- xxxx

Feature instasst monstache

---

src/common/metadata/common.go
src/common/metadata/query.go
src/common/time/time.go
src/scene_server/topo_server/core/operation/inst.go
src/scene_server/topo_server/core/operation/types.go
src/scene_server/topo_server/service/inst.go
src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/service/host.go

查询实例接口支持按时间查询

---

src/ui/package.json
src/ui/src/components/filters/utils.js
src/ui/src/components/model-manage/field-group/index.vue
src/ui/src/components/property-selector/index.vue
src/ui/src/components/search/date.vue
src/ui/src/components/search/longchar.vue
src/ui/src/components/search/mixins/active.js
src/ui/src/components/search/singlechar.vue
src/ui/src/components/search/time.vue
src/ui/src/router/query.js
src/ui/src/views/audit/index.vue
src/ui/src/views/general-model/index.vue
src/ui/src/views/index/children/full-text-search.vue

- 优化普通模型实例查询交互
- 优化操作审计loading效果
- 修复新增模型字段分组索引不正确的问题
- 修复全文检索显示实例模型名称为undefined的问题

UI: 全文检索&字段分组bugfix;操作审计&实例查询优化

---

src/ac/iam/iam.go
src/apimachinery/rest/client.go
src/apimachinery/rest/request.go
src/apimachinery/util/type.go
src/scene_server/auth_server/sdk/client/client.go
src/thirdparty/esbserver/esb.go
src/thirdparty/secrets/secrets.go

-  新增支持自定义metric buckets
-  新增支持自定义维度label采集

feature: 调整并新增apimachinery中2个metrics功能

---

src/source_controller/cacheservice/event/flow/flow.go

fix: 修复删除事务在部分场景下无法正常入库的问题

---

src/common/metadata/audit.go
src/scene_server/topo_server/service/auditlog.go

审计按资源名查询支持默认按精确查询功能

---

src/common/lock/lock.go
src/source_controller/coreservice/core/model/attribute.go
src/source_controller/coreservice/core/model/model.go

- xxxx
- xxxx
- 单词拼写错误, looked, 应为locked

[typo] 单词拼写错误, looked, 应为locked

---

src/thirdparty/monitor/plugins/blueking/blueking.go

convertToReportMsg兼容dimension为空的情况

---

src/common/metadata/common.go
src/common/metadata/hostserver.go
src/common/metadata/query.go
src/scene_server/host_server/logics/app.go
src/scene_server/host_server/logics/dynamic_grouping.go
src/scene_server/host_server/logics/hostsearch.go
src/scene_server/host_server/logics/module.go
src/scene_server/host_server/logics/object.go
src/scene_server/host_server/logics/set.go
src/scene_server/host_server/logics/special.go
src/scene_server/host_server/service/findhost.go
src/scene_server/host_server/service/host.go
src/scene_server/topo_server/core/operation/types.go

页面主机搜索接口支持按时间搜索

---

src/common/auditlog/instance.go
src/scene_server/host_server/util/util.go
src/scene_server/proc_server/service/servicecategory.go
src/scene_server/topo_server/core/inst/inst.go
src/scene_server/topo_server/core/model/object.go
src/scene_server/topo_server/core/operation/association_mainline_inst.go
src/scene_server/topo_server/core/operation/inst.go
src/scene_server/topo_server/service/set_template.go
src/source_controller/cacheservice/cache/business/client_logic.go
src/source_controller/cacheservice/cache/business/custom_level.go
src/source_controller/coreservice/core/datasynchronize/util.go
src/source_controller/coreservice/core/hostapplyrule/rule.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/source_controller/coreservice/core/mainline/manager.go
src/source_controller/coreservice/core/process/service_instance.go
src/tools/cmdb_ctl/cmd/topo.go

下线遗留的metadata兼容逻辑

---

src/ac/parser/event.go
src/common/metadata/inst.go
src/common/watch/cursor.go
src/scene_server/admin_server/service/migrate.go
src/scene_server/event_server/identifier/hostcache.go
src/scene_server/event_server/identifier/identifier.go
src/source_controller/cacheservice/event/flow/flow.go
src/source_controller/cacheservice/event/identifier/converter.go
src/source_controller/cacheservice/event/identifier/doc.go
src/source_controller/cacheservice/event/identifier/event.go
src/source_controller/cacheservice/event/identifier/handler.go
src/source_controller/cacheservice/event/identifier/identifier.go
src/source_controller/cacheservice/event/key.go
src/source_controller/cacheservice/event/metric.go
src/source_controller/cacheservice/event/util.go
src/source_controller/cacheservice/event/watch/client.go
src/source_controller/cacheservice/event/watch/watch.go
src/source_controller/cacheservice/service/service.go
src/source_controller/coreservice/core/host/identifier/identifier.go
src/storage/dal/mongo/local/txn_manager.go
src/storage/stream/event/utils.go
src/storage/stream/event/watch.go
src/storage/stream/types/types.go
src/thirdparty/monitor/meta/type.go

1. 新增主机身份事件服务
2. 调整主机身份接口协议，清理了无用的相关字段， issue #5183
3. event_server调整了主机身份事件推送相关功能
4. 修复事务中设置事务ttl时间位置错误的问题
5. watch服务，新增支持按需返回事件详情字段配置功能
num: 1010080961861911651

feature: 新增主机身份事件服务功能

---

src/common/definitions.go
src/common/metadata/process.go
src/common/metadata/set_template.go
src/common/metadata/set_template_request.go
src/common/util/valid.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/source_controller/coreservice/core/process/service_template.go
src/source_controller/coreservice/core/settemplate/set_template.go
src/test/topo_server/resource_dir_test.go

- 业务拓扑名称（包括模板）校验规则调整
close #5255

业务拓扑名称（包括模板）校验规则调整 close #5255

---

src/ui/src/components/search/date.vue
src/ui/src/components/search/time.vue
src/ui/src/components/ui/form/form.vue
src/ui/src/store/modules/view/host-details.js

- 修复新建模型实例布尔类型组件显示异常的问题
- 修复主机模型后添加的属性在编辑中页面不实时生效的问题
- 修复时间/日期搜索组件为空时，数据错误的问题

UI: 修复组件显示效果/主机页面数据刷新问题

---

src/source_controller/coreservice/service/hostfavourite.go

fix: hostFavourite只有部分字段能更新

---

src/tools/cmdb_ctl/cmd/unique.go

- 实例分表升级前进行校验的小工具添加对模型ID和字段ID的校验

实例分表升级前进行校验的小工具添加对模型ID和字段ID的校验

---

src/ui/src/components/property-selector/index.vue
src/ui/src/components/ui/form/form.vue
src/ui/src/mixins/edit-multiple-host.js
src/ui/src/mixins/form.js
src/ui/src/views/business/index.vue
src/ui/src/views/general-model/index.vue
src/ui/src/views/model-manage/children/verification-detail/index.vue
src/ui/src/views/model-manage/children/verification.vue
src/ui/src/views/resource/children/host-options.vue
src/ui/src/views/service-instance/children/clone-to-source.vue

ui: 下线唯一校验must_check相关逻辑

---

src/common/metadata/process.go
src/common/metadata/process_bind_info.go
src/scene_server/proc_server/logics/processinstance.go
src/scene_server/proc_server/logics/servicetemplate.go
src/scene_server/proc_server/service/processinstance.go
src/scene_server/proc_server/service/service.go
src/scene_server/proc_server/service/serviceinstance.go
src/scene_server/proc_server/service/servicetemplate.go

- 添加查询服务模板的待同步标识的接口
close #5198

添加查询服务模板的待同步标识的接口

---

src/ac/iam/iam.go
src/apiserver/service/filter.go
src/scene_server/auth_server/sdk/auth/calculate.go
src/source_controller/coreservice/service/hostfavourite.go

optimize: code log format optimize

---

src/common/metadata/attribute.go
src/source_controller/coreservice/core/instances/instance_validate.go

修复批量编辑时间类型字段时报错的问题

---

src/ac/iam/initial_common_actions.go

feature:
- delete event pushing action from developer action list

feature: delete event pushing action from developer action list. issue #5272

---

src/common/util/conv.go
src/scene_server/host_server/service/module.go

- fix float type convert to int slice failed issue.

fix: fix float type convert to int slice failed issue.

---

src/apimachinery/coreservice/instance/api.go
src/apimachinery/coreservice/instance/instance.go
src/common/metadata/object_controller.go
src/scene_server/auth_server/logics/fetch_instance_info.go
src/source_controller/cacheservice/event/flow/flow.go
src/source_controller/cacheservice/event/watch/client.go
src/source_controller/coreservice/core/cloud/synctask.go
src/source_controller/coreservice/core/instances/instance_crud.go
src/source_controller/coreservice/service/instances.go
src/source_controller/coreservice/service/service_initfunc.go
src/storage/driver/mongodb/instancemapping/inst_mapping.go
src/storage/stream/event/watch.go
src/storage/stream/types/types.go

模型实例事件监听使用产生事件的数据表查询删除详情

---

src/source_controller/coreservice/core/model/model.go
src/source_controller/coreservice/core/model/model_crud.go

optimize: code review optimize(add more informations to error)

optimize: code review optimize(add more informations to error)

---

src/scene_server/admin_server/upgrader/history/x18.12.12.05/remove_deleted_inst_asst.go
src/scene_server/admin_server/upgrader/y3.10.202104221702/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202010281615/update_inst_time_val.go
src/scene_server/admin_server/upgrader/y3.9.202011172152/remove_field.go
src/test/host_server/host_ip_array_test.go

feature: style code  issue #5085

---

src/ac/extensions/types.go
src/apimachinery/coreservice/model/model.go
src/scene_server/admin_server/upgrader/y3.10.202104221702/pkg.go
src/scene_server/topo_server/service/object.go
src/source_controller/cacheservice/cache/business/cache.go
src/source_controller/cacheservice/cache/business/client.go
src/source_controller/cacheservice/cache/business/client_logic.go
src/source_controller/cacheservice/cache/business/custom_level.go
src/source_controller/cacheservice/cache/business/types.go
src/source_controller/cacheservice/event/watch/client.go
src/source_controller/coreservice/core/association/instance.go
src/source_controller/coreservice/core/instances/instance_crud.go
src/source_controller/coreservice/core/mainline/manager.go

optimize: code review optimize.

---

src/scene_server/cloud_server/cloudsync/taskprocessor.go

adjust cloud sync time

---

src/ac/iam/adaptor.go
src/ac/iam/initial_action_groups.go
src/ac/iam/initial_actions.go
src/ac/iam/initial_common_actions.go
src/ac/iam/types.go
src/ac/meta/meta.go
src/common/watch/cursor.go
src/source_controller/cacheservice/event/flow/event.go
src/source_controller/cacheservice/event/key.go
src/source_controller/cacheservice/event/util.go

下线set template事件功能

---

src/ui/src/views/dynamic-group/form/form.vue

update:ui: 调整动态分组时间类型参数格式

---

src/common/metadata/common.go
src/common/metadata/dynamic_grouping.go
src/common/time/time.go
src/scene_server/host_server/logics/set.go
src/scene_server/host_server/service/dynamic_grouping.go

动态分组支持按时间查询

---

src/scene_server/topo_server/core/operation/inst.go

fix: condition covered when do date range search action. issue #5302 （v3.9.x版本）

---

src/scene_server/admin_server/upgrader/configadmin.go

strings.ReplaceAll替换为strings.Replace

---

src/tools/cmdb_ctl/cmd/unique.go

唯一校验小工具添加对不校验空值的唯一校验的提示

---

src/source_controller/cacheservice/event/flow/flow.go

mongodb事件监听遇到cursor重复时查找并去除重复的事件

---

src/scene_server/topo_server/service/fulltextsearch.go

- 调整es检索接口协议，优化入参和结果
- 接口入参
```json
{
"page": {
"start": 0,
"limit": 2
},
"bk_obj_id": "",
"query_string": "*a*",
"filter": [
"host",
"biz",
"instance",
"model"
]
}
```
- 接口返回结果
```json
{
"result": true,
"bk_error_code": 0,
"bk_error_msg": "success",
"permission": null,
"data": {
"total": 38,
"aggregations": [
{
"key": "biz",
"kind": "instance",
"count": 1
},
{
"key": "host",
"kind": "instance",
"count": 1
}
],
"hits": [
{
"source": {
"bk_biz_developer": "",
"bk_biz_id": 2,
"bk_biz_maintainer": "admin",
"bk_biz_name": "蓝鲸",
"bk_biz_productor": "",
"bk_biz_tester": "",
"bk_supplier_account": "0",
"create_time": "2021-05-13T05:44:21.664Z",
"default": 0,
"language": "1",
"last_time": "2021-05-13T05:44:21.664Z",
"life_cycle": "2",
"operator": "",
"time_zone": "Asia/Shanghai"
},
"highlight": { …
```

调整es检索接口协议，优化入参和结果

---

src/scene_server/topo_server/service/auditlog.go

- 修改查询审计列表逻辑中对传参的判断逻辑，拆分新老参数判断方式

feature 修改查询审计列表对传参判断逻辑

---

src/ui/src/components/service/process-bind-info-value.vue
src/ui/src/components/ui/form/user.vue
src/ui/src/views/audit/children/audit-business-options.vue
src/ui/src/views/audit/children/audit-host-options.vue
src/ui/src/views/audit/children/audit-other-options.vue
src/ui/src/views/audit/children/audit-resource-options.vue
src/ui/src/views/audit/children/audit-user-selector.vue
src/ui/src/views/audit/index.vue
src/ui/src/views/dynamic-group/form/form.vue
src/ui/src/views/resource-manage/index.vue

- 操作审计账号查询条件增加包含/不包含选项
- 操作审计资源名称条件统一为包含形式
- 服务模板进程绑定信息样式问题修复

操作审计账号查询条件增加包含/不包含选项

---

src/ui/package.json
src/ui/src/views/business-topology/host/host-list-options.vue
src/ui/src/views/business-topology/host/host-list.vue
src/ui/src/views/dynamic-group/form/form.vue
src/ui/src/views/host-operation/index.vue

UI: 优化业务拓扑操作按钮组合

---

src/common/backbone/backbone.go
src/common/backbone/configcenter/viper.go
src/common/index/index.go
src/scene_server/admin_server/app/options/options.go
src/scene_server/admin_server/app/server.go
src/scene_server/admin_server/logics/index.go
src/scene_server/admin_server/service/index.go
src/scene_server/admin_server/upgrader/register.go
src/scene_server/topo_server/service/object.go
src/thirdparty/monitor/monitor.go

- adminserver 支持报警模块
-
- 优化索引和表与模型对比逻辑
- xxxx

refactor: sync index and table issue #5292

---

src/ui/src/views/business-topology/children/topology-tree.vue

修复原地转移到空闲模块主机数错误问题

---

src/common/definitions.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/configadmin.go
src/scene_server/admin_server/upgrader/y3.9.202105261459/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202105261459/update_config_admin.go

模板/拓扑节点名称校验规则更新

---

src/common/definitions.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202106031151/add_unix_property.go
src/scene_server/admin_server/upgrader/y3.9.202106031151/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202106031151/update_process_pri_range.go
src/scene_server/datacollection/collections/hostsnap/hostsnap.go

- cmdb 主机模型内置属性【操作系统类型】增加 UNIX

cmdb 主机模型内置属性【操作系统类型】增加 UNIX

---

src/common/definitions.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/configadmin.go
src/scene_server/admin_server/upgrader/y3.10.202105261459/pkg.go
src/scene_server/admin_server/upgrader/y3.10.202105261459/update_config_admin.go

3.9的upgrader在3.10中新增一个
PR：https://github.com/Tencent/bk-cmdb/pull/5294

模板/拓扑节点名称校验规则更新（v3.10）

---

docs/apidoc/v3.1/host_relation.md
docs/apidoc/v3.2/host_relation.md
helm/bk-cmdb/CONTRIBUTING.md
src/common/metric/README.md
src/scene_server/admin_server/upgrader/x18.12.12.01/add_aix_property.go

- cmdb工具中增加对db的操作，目前支持查找，删除和显示指定db的所有collections。#5324
- xxxx
- xxxx

feature: add db operation for tools

---

docs/overview/installation.md

- xxxx
-  update monstache doc
- xxxx

 update monstache doc

---

src/storage/dal/mongo/local/mongo.go
src/storage/dal/types/types.go
src/tools/cmdb_ctl/cmd/unique.go

修复小工具聚合查询单次超过内存限制的问题，优化输出格式

---

src/scene_server/admin_server/logics/index.go

- xxxx
- xxxx
-  blog output log  panic

fix: blog output log  panic

---

src/ac/parser/servicetemplate.go

查询服务模版同步状态的接口添加auth parser

---

src/ui/src/components/ui/details/details.vue
src/ui/src/components/ui/form/form-multiple.vue
src/ui/src/components/ui/form/form.vue
src/ui/src/components/ui/index.js
src/ui/src/components/ui/other/sticky-layout.vue
src/ui/src/views/service-template/children/process-form.vue

fix:ui: 修复表单/表单详情按钮组在部分分辨率下抖动的问题

---

src/common/metadata/dynamic_grouping.go

创建动态分组时把主机的云区域字段按照int类型处理

---

src/ac/parser/topolatest.go

- new instance api auth parser

fix: new instance api auth parser

---

src/ui/src/components/audit-history/details-table.vue
src/ui/src/mixins/edit-multiple-host.js

UI: 修复操作审计详情未显示业务自定义字段的问题

---

src/scene_server/admin_server/service/migrate.go
src/scene_server/admin_server/upgrader/y3.10.202104221702/split_inst_table.go

- xxxx
- xxxx
- 修复实例分表后，数据升级过程中，实例数据随机丢失的问题

修复实例分表后，数据升级过程中，实例数据随机丢失的问题

---

src/scene_server/admin_server/service/migrate.go
src/scene_server/admin_server/upgrader/y3.10.202104221702/mapping.go
src/scene_server/admin_server/upgrader/y3.10.202104221702/split_inst_table.go

- xxxx
- 修改ObjectBase mapping 索引
- xxxx

refactor: change ObjectBase mapping table index

---

src/common/metadata/common.go
src/common/metadata/page.go
src/scene_server/topo_server/service/association.go
src/scene_server/topo_server/service/inst.go
src/test/topo_server/asst_test.go
src/test/topo_server/inst_test.go

- Fix instance api about new limits policies

Fix instance api about new limits policies

---

src/scene_server/topo_server/service/inst.go
src/web_server/logics/association.go
src/web_server/logics/excel.go
src/web_server/logics/excel_util.go

- xxxx
- xxxx
- fix import/export not invalid bug

feature: import/export not invalid

---

src/scene_server/topo_server/core/operation/association.go

- fix instance association object limit

fix: instance association object limit

---

src/ac/parser/topolatest.go
src/ac/parser/util.go

修复主机和主线模型与通用模型实例关联时鉴权失败的问题

---

src/ac/parser/topology.go
src/common/http/rest/contexts.go
src/common/metadata/toposerver.go
src/scene_server/topo_server/core/operation/inst_business.go
src/scene_server/topo_server/service/inst_business.go
src/scene_server/topo_server/service/service_initfunc.go

- 新增接口find_brief_biz_topo_node_relation

feature: add new api find_brief_biz_topo_node_relation

---

src/ui/src/service/model/import-export.js
src/ui/src/views/model-manage/children/index.vue

ui: 调整模型属性导入导出URL

---

src/ui/src/views/service-template/children/process-form.vue

ui: 服务模板进程别名放开编辑修改限制

---

src/scene_server/proc_server/service/serviceinstance.go
src/scene_server/topo_server/service/object.go

- xxxx
- xxxx
- 修复导入模型属性的时候提示未知错误的问题
- 修复模块下没有服务实例，修改服务模板后同步无效问题

导入模型属性的时候提示未知错误

---

src/ac/parser/topolatest.go

- xxxx
- xxxx
- 修导出关联关系出现错误的问题

fix: import object attribute has unknown error issue #5358

---

src/ac/parser/topolatest.go

- xxxx
- xxxx
- 修复导入主机在有iam 情况下提示http failed 的问题

fix: import host http error failed,log no matched rules  

---

src/scene_server/admin_server/service/dataid.go
src/tools/cmdb_ctl/cmd/zk.go

修复zk小工具获取非json数据失败的问题

---

src/ui/src/components/filters/store.js

optimize:ui: 主机表格显示字段由切换显示筛选字段变更为追加显示

---

src/ui/src/views/business-topology/host/host-list-options.vue

update:ui: 修改业务拓扑移出菜单显示判断逻辑

---

scripts/init.py
src/common/backbone/configcenter/viper.go
src/scene_server/admin_server/upgrader/y3.9.202106031151/pkg.go
src/thirdparty/monitor/config/config.go
src/thirdparty/monitor/monitor.go
src/thirdparty/monitor/plugins/blueking/blueking.go
src/thirdparty/monitor/plugins/blueking/gsecmdline.go

- 1、新增event_health接口。
2、升级gescmdline命令
3、具体注意事项见issue ： #5369
- xxxx
- xxxx

feature:  增加 事件链路检查和升级gsecmdline命令

---

src/ui/src/api/combine-request.js
src/ui/src/components/loading/index.vue
src/ui/src/store/modules/api/object-common-inst.js
src/ui/src/views/resource-manage/children/classify-panel.vue
src/ui/src/views/resource-manage/children/instance-count.vue
src/ui/src/views/resource-manage/children/use-instance-count.js
src/ui/src/views/resource-manage/index.vue

异步分片获取资源目录中的模型实例数

---

src/common/index/association.go
src/scene_server/admin_server/app/server.go
src/scene_server/admin_server/logics/index.go
src/scene_server/admin_server/service/index.go
src/scene_server/admin_server/service/service.go

- 新加http 触发索引同步api
- x
- 修复db 表索引落地，业务侧定义的唯一校验缺失的问题

feature: sync db table index issue #5085

---

src/ui/src/views/service-template/children/process-form.vue

fix:ui: 修复进程模板取消编辑后列表未恢复原值的问题

---

src/ui/src/components/model-instance/relation/list-table.vue
src/ui/src/components/model-instance/relation/list.vue
src/ui/src/components/search/mixins/active.js
src/ui/src/store/modules/view/host-details.js
src/ui/src/views/host-details/children/association-create.vue
src/ui/src/views/host-details/children/association-list-table.vue
src/ui/src/views/host-details/children/association-list.vue
src/ui/src/views/host-details/children/association.vue

- 实例关联列表展开点击热区优化
- 修复模型存在多个关联时，实例关联列表显示错误的问题
- 修复主机筛选UI层级异常的问题

UI: 修复模型存在多个关联时，实例关联列表显示错误的问题

---

src/scene_server/topo_server/core/operation/association.go

- 关联关系创建时对于coreservice层的err返回未进行校验处理
issue #5387

bugfix 添加关联关系接口增加err判断逻辑

---

src/ac/parser/host.go
src/scene_server/host_server/service/host.go

- SearchHostWithAsstDetail函数鉴权逻辑调整
issue #5394

bugfix 调整SearchHostWithAsstDetail函数鉴权逻辑

---

src/ui/src/components/modal/permission-main.vue
src/ui/src/dictionary/iam-auth.js
src/ui/src/setup/permission.js
src/ui/src/views/general-model/index.vue

feature:ui: 通用模型实例鉴权参数调整

---

src/scene_server/topo_server/service/set_template.go

 更新集群模板接口更新同步状态改为并发执行

---

src/ac/iam/client.go
src/ac/iam/iam.go

删除权限中心action之前先删除相关的权限策略

---

src/storage/stream/loop/loop_watch.go
src/storage/stream/types/types.go

feature: add stop loop watch function for with one or with batch event.

---

src/scene_server/admin_server/logics/index.go

style: add log  issue #5223

---

src/ui/src/views/model-manage/index.vue

feat: 模型页面中的实例数hover按需获取

---

src/ui/.eslintrc.js
src/ui/src/views/model-manage/index.vue
src/ui/src/views/model-topology/children/create-relation.vue
src/ui/src/views/service-template/children/operational.vue
src/ui/src/views/service-template/template.vue

- 服务模板实例标签加同步状态小红点
- 模型管理页增加“全部”入口
- 兼容新版eslint-config-tencent

服务模板实例标签加同步状态小红点和模型管理页增加“全部”入口

---

src/ui/src/views/business-topology/host/host-list-options.vue

update:ui: 调整显示业务主机追加至业务模块菜单逻辑

---

docs/overview/installation.md

refactor: doc monstache

---

src/ui/src/components/filters/store.js
src/ui/src/components/search/bool.vue
src/ui/src/components/search/date.vue
src/ui/src/components/search/enum.vue
src/ui/src/components/search/float.vue
src/ui/src/components/search/foreignkey.vue
src/ui/src/components/search/int.vue
src/ui/src/components/search/list.vue
src/ui/src/components/search/longchar.vue
src/ui/src/components/search/module.vue
src/ui/src/components/search/objuser.vue
src/ui/src/components/search/organization.vue
src/ui/src/components/search/service-template.vue
src/ui/src/components/search/set.vue
src/ui/src/components/search/singlechar.vue
src/ui/src/components/search/table.vue
src/ui/src/components/search/time.vue
src/ui/src/components/search/timezone.vue
src/ui/src/views/business-topology/children/create-module.vue
src/ui/src/views/business-topology/children/create-set.vue
src/ui/src/views/business-topology/children/topology-tree.vue
src/ui/src/views/business-topology/host/host-list.vue
src/ui/src/views/business/index.vue
src/ui/src/views/cloud-account/children/account-form.vue
src/ui/src/views/general-model/index.vue
src/ui/src/views/host-details/index.vue
src/ui/src/views/index/children/full-text-search/use-item.js
src/ui/src/views/resource/children/host-list.vue

- 业务列表筛选组件切换为通用搜索组件
- 创建集群、模块时，对应模板列表按最后更新时间排序
- 修复云账户编辑时连通测试通过无法保存的问题
- 修复非业务主机详情选项卡UI异常的问题
- 修复筛选主机并查看详情后返回筛选条件丢失的问题
- 修复创建拓扑自定义层级节点时出现ID字段的问题

UI: 修复云账户编辑时连通测试通过无法保存的问题

---

src/common/index/collections/modulehostconfig.go
src/common/index/collections/serviceinstance.go
src/scene_server/admin_server/service/migrate.go

- 
- 更新服务实例，主机与拓扑关系表的索引
- xxxx
- 
- 
- #5411

更新服务实例，主机与拓扑关系表的索引

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/service/migrate.go
src/scene_server/admin_server/upgrader/y3.9.202106291420/index.go
src/scene_server/admin_server/upgrader/y3.9.202106291420/pkg.go

- xxxx
- 更新服务实例，主机和拓扑关系表的的索引
-
- xxxx

更新服务实例，主机和拓扑关系表的的索引

---

src/common/definitions.go
src/ui/src/setup/validate.js

- 开放属性字段字符限制
close issue #5415

minor 开放字符数限制及修改前端校验规则

---

src/source_controller/coreservice/core/hostapplyrule/plan.go

- xxxx
- 主机应用预览接口性能优化
- xxxx
- 通过减少查询主机字段，减少了db查询时间，减少了数据包的大小，减少了数据包的传输时间。
close issue  #5404

优化主机属性自动应用预览接口

---

src/ui/src/components/host-apply/property-confirm-table.vue

UI: 转移主机属性自动应用预览主机详情优化为异步加载

---

src/common/definitions.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/history/y3.7.201912171427/add_set_template_version.go
src/scene_server/admin_server/upgrader/history/y3.8.202004241035/fix_set_template_version_time_empty.go
src/scene_server/admin_server/upgrader/y3.10.202107011735/drop_set_template_version_column.go
src/scene_server/admin_server/upgrader/y3.10.202107011735/pkg.go
src/scene_server/topo_server/core/operation/inst_set.go
src/scene_server/topo_server/core/settemplate/settemplate.go
src/scene_server/topo_server/core/settemplate/sync_status.go
src/scene_server/topo_server/service/set_template.go

- 增加删除集群模板version的upgrader
- xxxx
- xxxx

feature 增加删除集群模板version的upgrader

---

src/web_server/middleware/user/plugins/method/blueking/userinfo.go
src/web_server/service/util.go

修复获取用户列表接口不能正确查询数据的问题

---

src/ui/src/components/model-instance/relation/create.vue
src/ui/src/components/model-instance/relation/list-table.vue
src/ui/src/components/model-instance/relation/list.vue
src/ui/src/views/host-details/children/association-create.vue
src/ui/src/views/host-details/children/association-list-table.vue
src/ui/src/views/host-details/children/association-list.vue

UI: 修复实例关联列表错误的显示了实例自身的问题

---

src/ui/src/components/model-instance/relation/create.vue
src/ui/src/components/model-instance/relation/list-table.vue
src/ui/src/views/host-details/children/association-list-table.vue

ui: 修复关联列表取消关联参数缺失的问题

---

src/ui/src/components/model-instance/relation/list-table.vue
src/ui/src/views/host-details/children/association-create.vue
src/ui/src/views/host-details/children/association-list-table.vue

UI: 修复取消关联主线模型实例后取消关联失败的问题

---

src/ui/src/components/ui/form/form.vue
src/ui/src/setup/validate.js
src/ui/src/views/business-topology/children/create-module.vue
src/ui/src/views/business-topology/children/create-node.vue
src/ui/src/views/service-template/children/operational.vue

ui: 调整拓扑节点名称长度限制为256个字符

---

src/common/definitions.go

调整主线拓扑名称的长度

---

src/common/registerdiscover/zkregdiscv.go

定时检查zk节点注册情况并保证节点注册正常

---

src/ui/src/components/model-manage/field-group/field-detail/char.vue
src/ui/src/components/model-manage/field-group/preview-field.vue
src/ui/src/components/service/instance-table.vue
src/ui/src/components/ui/form/form-multiple.vue
src/ui/src/components/ui/form/form.vue
src/ui/src/components/ui/form/longchar.vue
src/ui/src/components/ui/form/singlechar.vue
src/ui/src/components/ui/selector/input-select.vue
src/ui/src/setup/regular-remote-validate.js
src/ui/src/setup/string-remote-validate.js
src/ui/src/setup/validate.js
src/ui/src/utils/tools.js
src/ui/src/views/business-topology/children/create-node.vue
src/ui/src/views/business-topology/children/service-instances.vue
src/ui/src/views/host-details/children/property.vue
src/ui/src/views/service-instance/children/clone-to-source.vue
src/ui/src/views/service-template/children/process-form.vue

ui: 模型字段自定义校验规则调整为远程校验

---

src/web_server/service/regular.go
src/web_server/service/service.go

- 增加验证正则表达式本身合法性
- 批量对内容进行正则校验接口
https://github.com/Tencent/bk-cmdb/issues/5438
- xxxx
- xxxx

增加验证正则表达式本身合法性、批量对内容进行正则校验接口

---

src/scene_server/admin_server/upgrader/y3.10.202104221702/split_inst_table.go

调整upgrader中生成唯一索引的规则

---

src/ui/src/components/export-file/export.vue
src/ui/src/views/index/children/full-text-search/item-model.vue

ui: 修复导出实例取消按钮无效的问题

---

src/ui/src/components/search/date.vue
src/ui/src/components/search/time.vue
src/ui/src/components/ui/other/property-value.vue
src/ui/src/filters/host.js
src/ui/src/magicbox/magicbox.scss
src/ui/src/views/business-topology/host/host-list-options.vue
src/ui/src/views/business-topology/host/host-list.vue
src/ui/src/views/cloud-area/index.vue
src/ui/src/views/cloud-resource/children/task-details-history.vue
src/ui/src/views/host-details/children/property.vue
src/ui/src/views/index/children/full-text-search/item-model.vue
src/ui/src/views/model-manage/children/relation.vue
src/ui/src/views/operation/index.vue
src/ui/src/views/resource/children/host-list.vue
src/ui/src/views/resource/children/host-options.vue
src/ui/src/views/set-template/sync-history.vue

- 修复模型关联列表id下划线未完整显示的问题
- 修复主机详情用户类型字段UI显示异常的问题
- 修复重命名云区域时可能出现更新失败的问题
- 修复日期面板偶现的被遮挡问题
- 修复复制主机集群名、模块名不完整的问题
- 修复主机属于多模块时，集群、模块相关字段显示不正确的问题

UI: 修复一些UI显示问题

---

src/ac/parser/topolatest.go

- 该接口为原有接口漏掉了鉴权，加上鉴权后，可能不向下兼容，需要用户关注。

批量删除实例接口添加鉴权

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.10.202107161611/pkg.go
src/scene_server/admin_server/upgrader/y3.10.202107161611/proc_bind_change.go

更新了port绑定信息

---

src/source_controller/cacheservice/cache/host/host.go
src/source_controller/cacheservice/event/flow/flow.go
src/source_controller/cacheservice/event/flow/instance_flow.go
src/source_controller/cacheservice/event/watch/client.go
src/tools/cmdb_ctl/cmd/watch.go
src/tools/cmdb_ctl/readme.md

删除事件详情的时间类型按json的格式进行序列化

---

src/source_controller/coreservice/core/association/instance.go

修复新建实例自关联的关联关系时对该实例获取两次锁导致失败的问题

---

src/ui/src/views/model-manage/index.vue

fix: 全部视图下将停用模型放置到同组的末尾

---

src/common/metadata/hostserver.go
src/scene_server/host_server/logics/instance.go
src/scene_server/host_server/service/findhost.go

- list_biz_hosts接口新增支持按模块属性查询数据
- list_biz_hosts_topo接口新增支持按集群、模块属性查数据
close #5481

查询业务主机接口添加按集群和模块属性过滤主机的过滤条件

---

src/web_server/logics/util.go

- fix empty username display when exporting excel

fix empty username display when exporting excel

---

src/ui/src/views/model-manage/children/index.vue

perf: 模型详情实例数量获取优化

---

src/ui/.eslintrc.js
src/ui/src/views/business-topology/children/topology-tree.vue
src/ui/src/views/resource/transfer/host-store.js

- 主机详情返回到业务拓扑主机列表条件保留问题修复
- eslint行尾空格规则与问题修复

主机详情返回到业务拓扑主机列表条件保留问题修复

---

src/apimachinery/toposerver/inst/inst.go
src/common/metadata/process.go
src/common/pattern.go
src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
src/scene_server/task_server/service/task.go

- 修改正则表达式，增加对0.0.0.0的判断
issue #5529

bugfix 修正ip正则校验表达式，增加对ip为0.0.0.0的判别

---

src/ui/src/components/service/form/process-form-property-ip.vue
src/ui/src/components/service/form/process-form-property-table.vue
src/ui/src/components/ui/form/list.vue
src/ui/src/views/service-template/children/process-form-property-ip.vue
src/ui/src/views/service-template/children/process-form-property-table.vue

fix: 进程绑定信息校验和显示异常问题修复

---

src/common/definitions.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202107301510/add_solaris_property.go
src/scene_server/admin_server/upgrader/y3.9.202107301510/pkg.go
src/scene_server/datacollection/collections/hostsnap/hostsnap.go

- 在主机类型枚举中增加Solaris类型 (https://github.com/Tencent/bk-cmdb/issues/5535)

feature: add os type solaris

---

src/ui/.gitignore
src/ui/builder/config/index.js
src/ui/package.json
src/ui/src/views/host-operation/children/create-service-instance.vue
src/ui/src/views/service-instance/create.vue
src/ui/src/views/service-template/children/process-form-property-table.vue

feat: 进程绑定IP允许为空

---

src/common/metadata/process.go
src/common/metadata/process_bind_info.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202107311844/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202107311844/set_proc_bind_ip_not_reuqired.go
src/scene_server/proc_server/service/processinstance.go
src/thirdparty/hooks/process/process.go

进程绑定IP允许为空

---

src/ac/parser/topolatest.go

topo节点获取主机/服务实例数量接口添加ac路由

---

src/scene_server/topo_server/core/operation/association_mainline_inst.go

修复查询拓扑数量接口在集群下没有模块的情况下传nil查询报错的问题

---

src/ui/src/components/model-instance/relation/create.vue
src/ui/src/views/host-details/children/association-create.vue

fix: 取消不允许自关联限制

---

src/scene_server/topo_server/service/inst.go
src/web_server/logics/excel.go

- 仅导出实例的自关联模型，在实例关联了多个模型实例时报错的问题
issue #5543

feature 调整导出实例时对仅导出自关联模型时的逻辑

---

src/common/metadata/set_template_request.go
src/scene_server/topo_server/core/settemplate/sync_status.go

- 调整集群模板状态表查询逻辑，使返回结果与预期返回相同
issue #5536

feature 调整集群模板状态表查询逻辑

---

src/ui/.gitignore
src/ui/src/setup/validate.js

fix: 修复批量创建集群名称校验问题

---

src/ui/src/components/model-instance/relation/create.vue
src/ui/src/components/model-instance/relation/index.vue
src/ui/src/components/model-instance/relation/list-table.vue
src/ui/src/components/model-instance/relation/list.vue
src/ui/src/views/host-details/children/association-list-table.vue
src/ui/src/views/host-details/children/association-list.vue

refactor: 模型和主机自关联显示优化

---

src/ui/src/store/modules/api/object-main-line-module.js
src/ui/src/views/business-topology/children/topology-tree.vue
src/ui/src/views/business-topology/host/host-selector-new/index.vue
src/ui/src/views/host-apply/children/topology-tree.vue

fix: 调整接口调用修复拓扑关联数据缺失问题

---

src/ui/src/components/search/singlechar.vue
src/ui/src/views/general-model/index.vue
src/ui/src/views/model-manage/children/index.vue

fix:query mode switch error

---

src/ui/src/components/model-manage/_create-model.vue
src/ui/src/views/dynamic-group/form/form-fields-selector.vue
src/ui/src/views/model-topology/index.new.vue

- 修复模型关系新建层级时重复点击创建按钮仍然可以创建的问题

fix:disable the operate button on form is submiting

---

src/ui/src/views/general-model/index.vue

fix: 修复模型实例详情错误出现loading的问题

---

src/ui/src/components/filters/filter-form.vue
src/ui/src/components/filters/filter-tag.vue
src/ui/src/components/filters/operator-selector.vue
src/ui/src/components/filters/utils.js
src/ui/src/components/ui/form/form-multiple.vue
src/ui/src/components/ui/form/form.vue
src/ui/src/views/service-template/children/process-form.vue

- 主机字符字段支持模糊搜索
- 字段表单提示修改为hover显示

主机字符字段支持模糊搜索

---

src/scene_server/topo_server/core/settemplate/sync_status.go

查询集群模板同步状态兼容集群下无模块的情况

---

src/ui/src/views/business/index.vue

- 资源-业务-业务名称搜索时没有默认使用模糊搜索匹配的问题

fix:set default query mode to be fuzzy

---

src/ac/auth.go
src/ac/iam/client.go
src/ac/iam/iam.go
src/ac/iam/viewer.go
src/scene_server/topo_server/service/object.go

修改通用模型名称时，同步模型名到IAM

---

src/scene_server/topo_server/service/association.go
src/scene_server/topo_server/service/inst_business.go

解决topo相关代码合并冲突

---

src/scene_server/task_server/service/task.go

taskserver清除一个月之前的冗余任务

---

src/ui/src/components/model-manage/field-group/field-detail/index.vue

feat: 通用模型内置字段名称暂统一为不可修改

---

src/source_controller/cacheservice/event/flow/instance_flow.go
src/source_controller/cacheservice/event/watch/client.go

修复主线模型事件在redis中找不到详情信息后去db查不到的问题

---

src/scene_server/topo_server/logics/logics.go
src/scene_server/topo_server/logics/model/group.go
src/scene_server/topo_server/service/object_group.go

- xxxx
- 优化toposerver中model/group相关结构与代码逻辑
- xxxx

feature 优化toposerver中model/group相关结构与代码逻辑

---

src/ui/jsconfig.json
src/ui/package.json
src/ui/src/components/filters/utils.js
src/ui/src/views/business/index.vue

V3.9.x fix correct case sensitive of biz name query

---

src/ui/src/views/history/index.vue

fix(deleted history): correct the data load of deleted history

---

src/common/metadata/common.go
src/scene_server/topo_server/core/operation/association_mainline_inst.go
src/source_controller/coreservice/core/association/instance.go
src/source_controller/coreservice/core/association/model.go
src/source_controller/coreservice/core/core.go
src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/service/association_dependence.go
src/source_controller/coreservice/service/instances_dependence.go
src/source_controller/coreservice/service/model_dependencs.go

- coreservice优化count逻辑
close #5600

refactor: improve coreservice count implementation

---

src/ui/src/components/filters/filter-tag-ip.vue

feat: optimize ip overflow tooltip

---

src/ui/src/components/filters/filter-tag-form.vue
src/ui/src/views/dynamic-group/form/form-property-list.vue

fix: 修复动态分组条件操作符未显示问题

---

src/scene_server/topo_server/core/operation/association_mainline_inst.go

- 修复获取topo节点主机数量接口缺陷
close #5621

fix: topo node host count

---

src/source_controller/coreservice/core/hostapplyrule/plan.go

修复主机属性自动应用的逻辑失效缺陷问题

---

src/ac/iam/iam.go
src/ac/iam/viewer.go
src/scene_server/auth_server/logics/list_instance_by_policy.go
src/scene_server/auth_server/sdk/auth/calculate.go
src/scene_server/auth_server/sdk/auth/count.go
src/scene_server/auth_server/sdk/types/auth.go

属性鉴权支持多个属性in的操作

---

src/ui/src/views/operation/index.vue

fix: 修复运营统计页面数据异常导致显示无权限的问题

---

src/ui/src/components/modal/permission.vue
src/ui/src/components/ui/auth/auth.vue
src/ui/src/setup/permission.js
src/ui/src/views/general-model/index.vue

feat: 主机和通用模型实例权限申请只显示无权限的实例优化

---

src/ui/src/components/export-file/export-property.vue
src/ui/src/components/export-file/state.js
src/ui/src/views/business-topology/host/host-list-options.vue
src/ui/src/views/general-model/index.vue
src/ui/src/views/resource/children/host-options.vue

feat: 资源导出默认勾选上表头配置的属性列

---

src/scene_server/topo_server/core/settemplate/sync_status.go

修复集群模板同步状态会把同步人设置为当前用户的问题

---

src/source_controller/coreservice/core/instances/instance.go

- 修复对于大量主机（主机数量大于500并且服务模板中进程模板数量大于10）转移场景下，出现panic，close #5633

fix: 修复对于大量主机（主机数量大于500并且服务模板中进程模板数量大于10）转移场景下，出现panic

---

src/ac/iam/viewer.go
src/scene_server/admin_server/iam/synciam.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.10.202109131607/migrate_iam_sysinstances.go
src/scene_server/admin_server/upgrader/y3.10.202109131607/pkg.go
src/scene_server/admin_server/upgrader/y3.10.202109131607/util.go

调整同步iam判断是否为master的间隔时间

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.9.202109132155/pkg.go
src/scene_server/admin_server/upgrader/y3.9.202109132155/remove_no_proc_svc_inst.go

调整服务实例改造的upgrader时间

---

src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.10.202109132155/pkg.go
src/scene_server/admin_server/upgrader/y3.10.202109132155/remove_no_proc_svc_inst.go
src/scene_server/topo_server/service/fulltextsearch.go
src/source_controller/coreservice/core/instances/instance_crud.go

服务实例改造upgrader添加到3.10

---

src/scene_server/topo_server/logics/inst/mainline_association.go

- logics/inst/mainline_association中多次append切片导致的内存高占用问题

fix: modify logic to troubleshoot memory leaks

---

src/scene_server/auth_server/logics/list_instance_by_policy.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/service/hostapplyrule.go
src/scene_server/topo_server/logics/inst/inst.go
src/scene_server/topo_server/logics/model/attribute.go
src/scene_server/topo_server/logics/model/object.go
src/scene_server/topo_server/service/inst_business.go
src/storage/dal/mongo/local/mongo.go
src/test/host_server/host_ip_array_test.go
src/test/load/db_load_test.go
src/test/test.go

修复导入模型属性时错误的将id置为0的问题

---

src/scene_server/topo_server/service/inst_business.go

feature: batch update business properties

---

docs/overview/installation.md

- 无
- 优化安装文档说明，官方发布的实际是源码包，需要用户自行编译。
- 无

docs: Release is a source code package, not a binary package

---

src/scene_server/admin_server/logics/object.go

- 修正主线模型的判断条件，不以业务拓扑分组为判断条件，使该分组下的通用模型能正常同步到IAM

修正主线模型的判断条件，不以业务拓扑分组为判断条件，使该分组下的通用模型能正常同步到IAM

---

src/scene_server/admin_server/upgrader/y3.10.202109131607/migrate_iam_sysinstances.go

upgrade添加跳过未注册动作的升级操作

---

src/common/metadata/audit.go

- 修复审计下无法查询动态分组的问题
issue #5652

fix: solved the dynamic_group can't be searched in auditlog

---

src/common/index/collections/process.go
src/common/metadata/process.go
src/scene_server/admin_server/imports.go
src/scene_server/admin_server/upgrader/y3.10.202109181134/migrate_svc_inst_id_to_proc.go
src/scene_server/admin_server/upgrader/y3.10.202109181134/pkg.go
src/scene_server/proc_server/logics/processinstance.go
src/scene_server/proc_server/service/processinstance.go
src/scene_server/proc_server/service/serviceinstance.go
src/source_controller/coreservice/core/process/service_instance.go

- 将服务实例下进程的唯一校验规则放到唯一索引中处理
close  #5648

将服务实例下进程的唯一校验规则放到唯一索引中处理

---

src/ui/src/dictionary/iam-auth.js
src/ui/src/setup/permission.js
src/ui/src/views/general-model/index.vue

fix: 通用模型实例鉴权问题修复

---

src/ui/src/views/history/index.vue
src/ui/src/views/host-operation/children/create-service-instance.vue
src/ui/src/views/operation/index.vue

- 修复查询主机删除历史bk_obj_id参数问题
- 修复模块中添加主机在有模板无进程创建服务实例时出错的问题
- 修复运营统计实例图表未显示问题

fix: 修复查询主机删除历史和模块添加主机及运营统计实例图表未显示问题

---

src/ui/src/components/filters/utils.js

feat: 转义主机模糊搜索条件值

---

src/scene_server/topo_server/service/inst_business.go

修复无权限事返回异常错误的问题

---

src/ui/src/components/ui/auth/auth-queue.js

- 修复由于resource_id_ex参数对比导致的鉴权问题

fix: 修复由于resource_id_ex参数对比导致的鉴权问题

---

src/scene_server/topo_server/logics/settemplate/settemplate.go
src/scene_server/topo_server/logics/settemplate/worker.go

- 修复了同步集群模板实例时事务提交失败导致的报错
issue #5668

fix: transaction error by unmodified module executing asynchronous task in sync set_template

---

src/ui/src/components/model-instance/relation/graphics.vue
src/ui/src/views/host-details/children/association-graphics.new.vue

fix: 修复自关联模型拓扑数据展示不全的问题

---

src/scene_server/host_server/service/transfer.go

修复模块中主机均无服务实例时无法转移到空闲机的问题

---

src/scene_server/topo_server/logics/inst/mainline_association.go

- 修复主机自动应用中host_apply_rule_count数据不正确的问题
issue #5699

fix 修复主机自动应用中host_apply_rule_count数据不正确的问题

---

src/ui/src/components/ui/selector/clipboard.vue
src/ui/src/store/modules/api/instance-label.js
src/ui/src/views/business-topology/service-instance/instance/dialog/label-dialog.vue

fix: 修复服务实例标签编辑会失败的缺陷

---

src/ui/src/components/import-file/import-relation.vue

fix: 修复实例导入未显示错误详情的问题

---

src/ui/src/components/filters/filter-form.vue
src/ui/src/components/filters/filter-tag-form.vue
src/ui/src/components/search/biz.vue
src/ui/src/components/search/index.js
src/ui/src/components/search/mixins/autocomplete-biz.js
src/ui/src/components/search/mixins/autocomplete.js

- 添加业务名输入联想组件在主机搜索业务名“包含”条件时使用

feat: 添加业务名输入联想组件在主机搜索业务名“包含”条件时使用

---

src/ac/parser/topolatest.go
src/apimachinery/apiserver/api.go
src/apimachinery/apiserver/apiserver.go
src/scene_server/topo_server/service/inst.go
src/scene_server/topo_server/service/service_business_initfunc.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/source_controller/coreservice/core/model/attribute.go
src/source_controller/coreservice/core/model/model_private.go
src/web_server/logics/inst.go

- 优化主机批量导入后台接口逻辑，将主机批量导入接口独立出来，同时优化导入实例后返回结果结构，方便用户识别那些主机异常了。
issue #5723

feature adjust import instance interface

---

src/ac/parser/topolatest.go

修复前端业务主机高级筛选页面模糊匹配集群/模块名接口权限解析失败的问题

---

src/scene_server/event_server/distribution/distributer.go

调整eventserver失败或无事件时等待时间为5秒

---

docs/wiki/db_upgrade.md

fix: remove name from docs

---

src/ui/src/components/filters/filter-fast-search.vue
src/ui/src/components/filters/filter-form.vue
src/ui/src/components/filters/filter-tag-form.vue
src/ui/src/components/filters/store.js

fix: 修复主机搜索时因页码未重置导致无结果的问题

---

src/ac/iam/iam.go
src/ac/iam/initial_action_groups.go

实例权限拆分时仅更新iam中已注册的操作对应的分组

---

src/ui/src/views/model-topology/index.new.vue

fix: 修复模型拓扑图“无位置节点”为空时报错导致交互异常问题

---

src/ui/src/components/modal/permission-resource-name.js
src/ui/src/components/model-instance/relation/create.vue
src/ui/src/components/model-instance/relation/list-table.vue
src/ui/src/components/ui/auth/auth.vue
src/ui/src/hooks/instance/association.js
src/ui/src/service/instance/association.js
src/ui/src/service/instance/instance.js
src/ui/src/utils/query-builder-operator.js
src/ui/src/views/business-topology/children/service-node-info.vue
src/ui/src/views/general-model/details.vue
src/ui/src/views/general-model/index.vue
src/ui/src/views/host-details/children/association-create.vue
src/ui/src/views/host-details/children/association-list-table.vue

- 切换实例查询接口为info和ccount分开查询的接口
- 修复了模型实例时间与日期类型字段查询不正确的问题

perf: 切换实例查询接口为info和count分开查询的接口

---

src/apimachinery/coreservice/transaction/client.go
src/common/metadata/transaction.go
src/source_controller/coreservice/service/transaction.go
src/storage/dal/dal.go
src/storage/dal/mongo/local/transaction.go
src/storage/dal/mongo/local/txn_manager.go

事务写冲突时进行重试

---

src/ui/src/views/business-topology/host/across-business-module-selector.vue
src/ui/src/views/resource/children/host-options.vue

feat: 跨业务转主机的业务选择列表支持按有权限的优先排序

---

src/ui/src/components/audit-history/details-slider.vue
src/ui/src/components/audit-history/details-table.vue
src/ui/src/components/model-instance/audit-history.vue
src/ui/src/store/modules/api/audit.js
src/ui/src/views/business/details.vue
src/ui/src/views/general-model/details.vue
src/ui/src/views/history/index.vue
src/ui/src/views/host-details/index.vue

feat: 修改实例变更记录查询接口支持变更记录权限独立

---

src/ac/parser/topology.go
src/apiserver/service/url.go
src/common/metadata/audit.go
src/scene_server/topo_server/service/auditlog.go
src/scene_server/topo_server/service/service_initfunc.go

- 提供新接口给资源池的变更记录功能使用，鉴权方式与操作审计不同，根据用户是否有实例查看权限进行鉴权。
issue #5758

feature 提供新实例审计查询接口给前端资源池变更记录使用

---

src/common/zkclient/zkclient.go

zk连接时判断是否已连接成功防止重复进行连接

---

src/source_controller/coreservice/core/host/transfer/manager.go
src/source_controller/coreservice/core/host/transfer/transfer.go

增加转移主机时对业务是否归档的判断

---

src/apimachinery/coreservice/transaction/client.go
src/common/auditlog/host.go
src/scene_server/cloud_server/cloudsync/hostsyncor.go
src/scene_server/datacollection/collections/hostsnap/hostsnap.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/logics/import.go
src/scene_server/host_server/service/host.go
src/scene_server/host_server/service/hostapplyrule.go
src/scene_server/host_server/service/transfer.go
src/source_controller/coreservice/core/hostapplyrule/plan.go
src/source_controller/coreservice/core/instances/dependences.go
src/source_controller/coreservice/core/instances/instance.go
src/source_controller/coreservice/core/instances/instance_validate.go
src/source_controller/coreservice/core/instances/validator.go
src/source_controller/coreservice/service/instances_dependence.go

- 编辑主机接口性能优化
1. 实例校验中查询模型属性和唯一校验的逻辑改为批量查询
2. 主机实例操作审计改为批量操作
- 页面转移主机接口调整为按主机最终模块聚合批量转移
- 主机自动应用仅更新有变化的主机

编辑主机接口性能优化

---

src/common/metadata/common.go
src/common/paraparse/app.go
src/common/querybuilder/types.go
src/common/querybuilder/validate.go
src/scene_server/host_server/service/dynamic_grouping.go
src/scene_server/topo_server/logics/inst/inst.go
src/source_controller/coreservice/core/instances/instance.go

- 实例查询接口支持时间查询，包含实例查询和实例数量查询两个接口
- 修复动态分组查询时间错误 
close #5711

实例查询接口支持时间查询并修复动态分组查询时间问题

---

src/scene_server/topo_server/service/inst_module.go
src/scene_server/topo_server/service/inst_set.go

resolove conflict

---

src/common/auditlog/host.go

修复主机审计获取业务ID失败的问题

---

src/ui/src/components/batch-selection-column/index.vue

修复业务批量编辑全选控件错位问题

---

src/ui/src/components/filters/general-model-filter-form.vue
src/ui/src/components/filters/general-model-filter-tag-form.vue
src/ui/src/components/filters/general-model-filter-tag-item.vue
src/ui/src/components/filters/general-model-filter-tag.vue
src/ui/src/components/filters/general-model-filter.js
src/ui/src/components/filters/general-model-property-selector.js
src/ui/src/components/filters/general-model-property-selector.vue
src/ui/src/components/filters/utils.js
src/ui/src/components/search/singlechar.vue
src/ui/src/utils/query-builder-operator.js
src/ui/src/views/general-model/index.vue

feat: 通用模型实例查看页支持高级筛选

---

src/scene_server/topo_server/core/operation/group.go
src/source_controller/coreservice/core/model/model_attribute_group.go
src/source_controller/coreservice/core/model/model_attribute_group_private.go

- 修复业务下属性分组更新时跨业务检验重名问题
issue #5828

bugfix 修复业务下属性分组更新时跨业务检验重名问题

---

src/ui/src/components/ui/form/form-multiple.vue
src/ui/src/mixins/edit-multiple-host.js

修复批量修改业务属性需要点击两次才能修改的 BUG

---

src/ui/.husky/commit-msg
src/ui/.husky/pre-commit
src/ui/commitlint.config.js
src/ui/package.json

- 增加提交文件 eslint 检查
- 增加 pre-ci 检查配置
- 增加提交信息检查
- 增加敏感信息扫描

chore: 优化代码检查

---

docs/overview/source_compile.md

修改下载与编译文档go版本要求

---

src/ui/src/components/import-file/import-relation.vue

fix: 修复资源目录批量导入实例时报错未提示的问题

---

src/ac/parser/serviceinstance.go

修复获取服务模板同步状态权限解析失败的问题

---

src/ac/parser/host.go
src/common/metadata/core_service.go
src/common/metadata/hostserver.go
src/common/util/model.go
src/scene_server/host_server/logics/host.go
src/scene_server/host_server/logics/module.go
src/scene_server/host_server/service/module.go
src/scene_server/host_server/service/service_initfunc.go
src/source_controller/coreservice/core/host/transfer/manager.go
src/source_controller/coreservice/core/host/transfer/transfer.go
src/source_controller/coreservice/core/instances/dependences.go
src/source_controller/coreservice/core/instances/validator.go
src/source_controller/coreservice/core/model/attribute_private.go
src/source_controller/coreservice/service/instances_dependence.go

增加支持多个业务的空闲机模块中的主机转移到同一个业务的空闲机模块

---

src/scene_server/topo_server/core/operation/import_association.go
src/scene_server/topo_server/service/object_association.go
src/web_server/logics/host.go

- 修复导入主机判断excel表格数量问题以及导入关联关系返回错误不正确问题
close #5816 #5819

bugfix 修复导入主机判断excel表格数量问题以及导入关联关系返回错误不正确问题

---

src/ui/src/views/service-template/children/operational.vue

fix: 修复服务模板新建进程参数类型错误的问题
