TencentBlueKing/bk-cmdb

src/ui/src/components/import-file/import-relation.vue
=> fix: 修复主机导入报错提示错误的问题

src/ui/src/components/filters/general-model-filter.js, src/ui/src/utils/query-builder-operator.js, src/ui/src/views/general-model/index.vue
=> fix: 修复通用模型实例高级筛选的问题

src/ac/iam/adaptor.go
=> 模型实例查询跳过鉴权

src/ui/src/components/ui/auth/auth.vue
=> fix: 修复无法转移主机至其他业务的问题

src/common/metadata/attribute.go
=> table类型的校验允许类型为interface或map数组

src/scene_server/host_server/service/transfer.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/host/transfer/manager.go, src/source_controller/coreservice/core/host/transfer/transfer.go, src/source_controller/coreservice/core/hostapplyrule/plan.go, src/source_controller/coreservice/service/host_apply_rule.go
- 转移主机属性自动应用仅判断目标模块，如果转移目标模块没有主机属性自动应用则无需显示该选项
=> feature 转移主机属性自动应用仅判断目标模块

src/scene_server/topo_server/logics/inst/inst.go
- 修复查询实例拓扑返回实例中缺少bk_inst_name问题
close #5881
=> bugfix 修复查询实例拓扑返回实例中缺少bk_inst_name问题

src/scene_server/admin_server/upgrader/y3.9.202112071130/migrate_api_task.go
=> api task的迁移支持status为字符串的情况

src/ui/package.json, src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/store/modules/api/object-model-field-group.js
=> fix: 修复模型字段分组排序失效的问题

src/ac/parser/topolatest.go, src/apimachinery/toposerver/object/api.go, src/apimachinery/toposerver/object/group.go, src/common/metadata/object_controller.go, src/scene_server/topo_server/core/operation/group.go, src/scene_server/topo_server/service/object_group.go, src/scene_server/topo_server/service/service_business_initfunc.go, src/source_controller/coreservice/core/model/model_attribute_group.go
- 提供交换模型属性分组位置的接口供前端使用
close #5873
=> feature 提供交换模型属性分组位置的接口供前端使用

src/scene_server/topo_server/service/object.go
=> bugfix 批量创建模型返回正确结果

src/ac/parser/host.go, src/scene_server/host_server/logics/host.go, src/scene_server/host_server/service/findhost.go, src/scene_server/host_server/service/service_initfunc.go
- 新增根据主机id查询对应服务模版实例id的接口
close #5905
=> feature 新增根据主机id查询对应服务模版实例id的接口

src/source_controller/coreservice/core/model/model.go
=> 禁止创建bk打头的模型，用于后续创建内置模型，避免冲突

src/source_controller/coreservice/core/host/transfer/transfer.go, src/thirdparty/hooks/validator.go
=> 添加校验主机转移参数是否正确的hook

src/scene_server/topo_server/core/operation/inst_business.go
- 平台管理场景下，管理员在变更空闲机池或者下面模块
close #5913
=> 业务空闲机与资源池解耦

src/source_controller/coreservice/core/host/transfer/transfer.go, src/source_controller/coreservice/core/hostapplyrule/plan.go
=> 主机转移时自动应用调整为按相同的更新数据进行批量更新

src/apiserver/service/filter.go, src/apiserver/service/service.go
- apiserver中新增metric采集项，统计无权限的访问量
=> apiserver中新增metric采集项，统计无权限的访问量

src/ui/src/views/service-template/children/operational.vue, src/ui/src/views/service-template/children/process.vue
=> fix: 修复克隆模板编辑更新时出现数据混乱的问题

resources/language/default/web.json, resources/language/en/web.json, src/web_server/logics/excel_util.go
- 补充excel导入时针对组织的内容校验，防止panic发生
=> feature 补充导入组织内容校验

resources/language/default/web.json, resources/language/en/web.json, src/thirdparty/esbserver/user/api.go, src/thirdparty/esbserver/user/esbserv.go, src/web_server/logics/department.go, src/web_server/logics/excel.go, src/web_server/logics/excel_util.go, src/web_server/logics/host.go, src/web_server/logics/inst.go, src/web_server/logics/util.go, src/web_server/service/host.go, src/web_server/service/inst.go, src/web_server/service/object.go, src/web_server/service/util.go
=> feature 解决版本冲突

scripts/init.py, src/apimachinery/rest/request.go, src/apimachinery/util/client.go, src/apiserver/app/server.go, src/apiserver/service/auth.go, src/apiserver/service/http.go, src/common/backbone/backbone.go, src/common/rdapi/rdfunc.go, src/common/util/lib.go, src/scene_server/admin_server/configures/checkconf.go, src/scene_server/admin_server/service/service.go, src/scene_server/auth_server/service/service.go, src/scene_server/cloud_server/service/service.go, src/scene_server/datacollection/service/service.go, src/scene_server/event_server/service/service.go, src/scene_server/host_server/service/service.go, src/scene_server/operation_server/service/service.go, src/scene_server/proc_server/service/service.go, src/scene_server/synchronize_server/service/service.go, src/scene_server/task_server/service/service.go, src/scene_server/topo_server/service/service.go, src/source_controller/cacheservice/service/service.go, src/source_controller/coreservice/service/service.go, src/thirdparty/logplatform/config.go, src/thirdparty/logplatform/opentelemetry/config.go, src/thirdparty/logplatform/opentelemetry/tracer.go, src/thirdparty/logplatform/opentelemetry/util.go, src/web_server/service/host.go, src/web_server/service/service.go
=> 接入监控opentelementry

src/ui/package.json, src/ui/src/views/business-set/index.vue
=> 删除完整页后自动翻页逻辑优化

readme.md
=> 在线体验cmdb升级为3.10.x并支持登陆

src/web_server/logics/excel.go
=> bugfix 修复导入时获取excel内容逻辑

src/ui/src/components/service/form/process-form-property-table.vue, src/ui/src/utils/tools.js, src/ui/src/views/service-template/children/process-form-property-table.vue
- 进程绑定信息中的IP统一为必填及调整保存进程信息接口入参
=> fix: 进程绑定信息中的IP统一为必填及调整保存进程信息接口入参

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.10.202202181012/pkg.go, src/scene_server/admin_server/upgrader/y3.10.202202181012/update_footer_and_title_info.go
- 调整前端title和footer，title为蓝鲸智云。
close #5968
=> 网页title和footer规范化诉求

src/ac/iam/iam.go, src/source_controller/cacheservice/event/watch/client.go, src/source_controller/cacheservice/event/watch/watch.go
=> 修复migrate iam时删除老模型实例action时更新action group失败的问题

src/scene_server/topo_server/core/model/object.go, src/scene_server/topo_server/core/operation/object.go
- 允许修改模型所属的模型分组, close #5990 。
=> 允许修改模型所属的模型分组

src/scene_server/topo_server/core/model/object.go
=> 增加业务层面的分组id合法性校验

src/ac/iam/adaptor.go, src/ac/iam/initial_action_groups.go, src/ac/iam/initial_actions.go, src/ac/iam/types.go, src/ac/meta/meta.go, src/ac/parser/serviceinstance.go, src/common/watch/cursor.go, src/scene_server/proc_server/service/service.go, src/source_controller/cacheservice/event/flow/event.go, src/source_controller/cacheservice/event/key.go, src/source_controller/cacheservice/event/util.go, src/storage/dal/mongo/local/mongo.go
- resource_watch接口添加业务集的事件监听功能
=> resource_watch接口添加业务集的事件监听功能

src/scene_server/topo_server/logics/model/object.go
=> 增加支持更改模型分组能力

src/scene_server/admin_server/service/dataid.go
=> 修复dataid注册失败的问题

src/scene_server/event_server/sync/hostidentifier/hostIdentifier.go, src/scene_server/event_server/sync/hostidentifier/task.go
=> 同步主机身份添加metrics采集

src/common/definitions.go, src/common/index/collections/hostbase.go, src/common/index/index.go, src/common/metadata/host.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.10.202104221702/split_inst_table.go, src/scene_server/admin_server/upgrader/y3.10.202203031512/add_agent_id_and_ipv6_attr.go, src/scene_server/admin_server/upgrader/y3.10.202203031512/pkg.go, src/source_controller/coreservice/core/instances/validator_unique.go, src/storage/dal/mongo/local/mongo.go, src/tools/cmdb_ctl/cmd/migrate_check.go
=> 添加内外网IPv6字段和agent id字段

src/web_server/logics/excel.go, src/web_server/logics/excel_util.go
=> bugfix 修复导出主机时空指针报错问题

src/ui/src/components/audit-history/details-slider.vue
=> fix: 修复模型实例审计详情查看报错的问题

src/common/backbone/configcenter/viper.go
=> 调整mongo最大连接数为3000

src/ui/src/views/set-sync/sync-index.vue
=> fix(集群模板): 确认同步按钮添加loading防止重复操作

src/scene_server/topo_server/logics/inst/business.go
=> feature: 主机池和业务空闲机池解耦

src/common/auditlog/service_instance.go, src/scene_server/proc_server/service/serviceinstance.go
=> 修复因为map并发读写导致的同步服务模板失败的问题

src/source_controller/cacheservice/event/flow/flow.go
=> 修复watch主机删除事件时ip为数组类型的问题

src/common/definitions.go, src/common/metadata/dataid.go, src/scene_server/admin_server/service/dataid.go
=> 兼容gse的注册stream接口变动

src/scene_server/host_server/service/host.go
=> 修复更新主机事务问题

src/ui/src/views/business-set-topology/children/topology-tree.vue, src/ui/src/views/business-topology/children/node-extra-info-service-template.vue
- 修复业务集视图下节点信息中主机自动应用状态展示错误问题
- 检查业务集视图的拓扑地址参数合法性解决请求接口报错问题
=> 修复业务集视图下主机自动应用状态展示错误和拓扑地址参数合法性检查

src/apimachinery/util/client.go, src/apimachinery/util/type.go, src/apiserver/service/http.go, src/common/definitions.go, src/common/http/rest/rest.go, src/thirdparty/monitor/meta/type.go, src/web_server/middleware/requestid.go
=> 各组件http请求context新增timeout机制，避免请求长时间执行不退出

scripts/init.py, src/ac/iam/iam.go, src/apimachinery/util/client.go, src/apimachinery/util/type.go, src/apiserver/app/server.go, src/common/backbone/backbone.go, src/common/backbone/http.go, src/common/backbone/type.go, src/common/http/httpclient/client.go, src/common/http/httpclient/forwardclient.go, src/common/resource/esb/esb.go, src/common/ssl/ssl.go, src/scene_server/admin_server/app/server.go, src/scene_server/auth_server/app/server.go, src/scene_server/datacollection/app/server.go, src/scene_server/event_server/app/server.go, src/scene_server/host_server/app/server.go, src/scene_server/operation_server/app/server.go, src/scene_server/proc_server/app/server.go, src/scene_server/proc_server/logics/logics.go, src/scene_server/proc_server/service/service.go, src/scene_server/topo_server/app/server.go, src/thirdparty/elasticsearch/esclient.go, src/thirdparty/logplatform/opentelemetry/config.go, src/thirdparty/logplatform/opentelemetry/tracer.go, src/web_server/app/server.go, src/web_server/middleware/user/plugins/method/blueking/userinfo.go, src/web_server/service/login.go, src/web_server/service/proxy.go
=> 各服务支持https

src/ac/parser/host.go, src/common/metadata/hostserver.go, src/scene_server/host_server/logics/host.go, src/scene_server/host_server/service/findhost.go, src/scene_server/host_server/service/service_initfunc.go
- 查询主机及其对应topo增加自定义层级查询条件
close #5891
=> feature 查询主机及其对应topo增加自定义层级查询条件

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.10.202204271725/pkg.go, src/scene_server/admin_server/upgrader/y3.10.202204271725/service_template_host_apply.go
=> 修改upgrade版本

src/test/host_server/host_apply_test.go
=> 修复测试用例分页校验不通过的问题

LICENSE.txt
=> 调整LICENSE文件的版权时间为2017-2022

src/ui/package.json, src/ui/src/api/combine-request.js, src/ui/src/components/business-scope/settings-form.vue, src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/components/search/service-template.vue, src/ui/src/services/service-template/index.js, src/ui/src/store/modules/api/host-apply.js, src/ui/src/views/business-topology/children/create-module.vue, src/ui/src/views/host-apply/children/topology-tree.vue, src/ui/src/views/set-template/children/service-template-selector.vue
- 修复编辑业务集业务范围未生效的问题 #6108 
- 修复新建的模型字段分组无法正常折叠的问题 #6103 
- 修复unzip-js依赖readable-stream版本问题 #6104 
- 适配接口分页限制 #6109
=> fix: 修复3.10.16_alpha1版本issues

src/ui/src/views/host-details/children/service-instance-table.vue, src/ui/src/views/host-details/children/service-list.vue
=> feat: 主机详情页的服务实例标签与拓扑显示优化为直接全部显示

src/ui/src/views/business-synchronous/children/service-instance-details.vue, src/ui/src/views/business-topology/children/create-node.vue
- 修复服务模板同步实例变更对比溢出文本样式问题
- 修复创建拓扑节点中的下拉框触发区域变小导致点击失效的问题
=> 修复服务模板同步实例变更对比溢出文本样式和创建拓扑节点中的下拉框触发失效的问题

src/source_controller/coreservice/core/hostapplyrule/plan.go
- xxxx
- xxxx
- 修复主机属性自动应用时间类型比较问题 close #6134
=> 修复主机属性自动应用时间类型比较问题

src/ui/src/components/filters/filter-form.vue, src/ui/src/components/filters/filter-tag-form.vue, src/ui/src/components/filters/operator-selector.vue
=> feat: 主机搜索的模块与集群名称支持模糊搜索

src/ui/src/views/service-template/children/template-instance.vue, src/ui/src/views/set-template/children/template-intance.vue
=> feat: 服务与集群模板实例列表页添加单个实例的删除入口

docs/support-file/helm/Chart.yaml, docs/support-file/helm/README.md, docs/support-file/helm/templates/_helpers.tpl, docs/support-file/helm/templates/adminserver/adminserver-dpl.yaml, docs/support-file/helm/templates/adminserver/configmap.yaml, docs/support-file/helm/templates/apiserver/apiserver-dpl.yaml, docs/support-file/helm/templates/authserver/authserver-dpl.yaml, docs/support-file/helm/templates/bklogconfig.yaml, docs/support-file/helm/templates/cacheservice/cacheservice-dpl.yaml, docs/support-file/helm/templates/cert-configmap.yaml, docs/support-file/helm/templates/cloudserver/cloudserver-dpl.yaml, docs/support-file/helm/templates/coreservice/coreservice-dpl.yaml, docs/support-file/helm/templates/datacollection/datacollection-dpl.yaml, docs/support-file/helm/templates/eventserver/eventserver-dpl.yaml, docs/support-file/helm/templates/hostserver/hostserver-dpl.yaml, docs/support-file/helm/templates/operationserver/operationserver-dpl.yaml, docs/support-file/helm/templates/procserver/procserver-dpl.yaml, docs/support-file/helm/templates/servicemonitor.yaml, docs/support-file/helm/templates/synchronizeserver/synchronizeserver-dpl.yaml, docs/support-file/helm/templates/taskserver/taskserver-dpl.yaml, docs/support-file/helm/templates/toposerver/toposerver-dpl.yaml, docs/support-file/helm/templates/webserver/webserver-dpl.yaml, docs/support-file/helm/values.yaml
=> update helm chart

src/common/metadata/attribute.go, src/scene_server/topo_server/service/object_attribute.go, src/source_controller/coreservice/core/hostapplyrule/plan.go
=> 设置不可编辑字段+IPv6字段+CPU架构字段不可用于主机自动应用

docs/support-file/helm/Chart.yaml, docs/support-file/helm/templates/job/migrateOldDataID-job.yaml
=> 添加注册老的dataid到gse的job

LICENSE.txt
=> 调整LICENSE文件的版权时间

src/apimachinery/cacheservice/cache/host/api.go, src/apimachinery/cacheservice/cache/host/cache.go, src/common/metadata/cache.go, src/scene_server/datacollection/collections/hostsnap/hostsnap.go, src/source_controller/cacheservice/cache/host/client.go, src/source_controller/cacheservice/cache/host/host.go, src/source_controller/cacheservice/service/cache.go
=> 明确ip缓存是静态寻址场景

src/common/metadata/inst.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.10.202205182148/pkg.go, src/scene_server/admin_server/upgrader/y3.10.202205182148/update_business_set.go
- 修改业务集结构体运维人员字段名称为bk_biz_maintainer
=> 修改业务集结构体运维人员字段名称为bk_biz_maintainer

src/scene_server/host_server/logics/object.go
=> 修复查询自定义层级节点下的主机失败的问题

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/services/service-template/index.js
- 调整获取服务模板接口分页限制入参
- scss变量定义位置解决编译问题
=> fix: 调整获取服务模板接口分页限制入参和scss变量定义位置解决编译问题

src/ac/extensions/types.go, src/ac/parser/framework.go, src/common/metadata/metadata.go, src/common/metadata/process.go, src/common/util/conv.go, src/common/util/conv_test.go, src/scene_server/host_server/logics/instance.go, src/scene_server/host_server/service/cloudarea.go, src/scene_server/host_server/service/findhost.go, src/scene_server/host_server/service/host.go, src/scene_server/proc_server/service/servicetemplate.go, src/scene_server/synchronize_server/logics/synchronize.go, src/scene_server/topo_server/logics/inst/business.go, src/scene_server/topo_server/logics/operation/import_association.go, src/test/topo_server/inst_test.go, src/test/topo_server/object_test.go
**注意：会影响到所有调用该工具函数的地方，需要全量回归测试**
=> 去除util.GetInt64ByInterface里将string转为int64的逻辑

resources/language/default/import_instance.json, resources/language/en/import_instance.json, src/scene_server/host_server/logics/import.go, src/web_server/logics/excel.go, src/web_server/logics/excel_util.go, src/web_server/logics/fields.go, src/web_server/logics/host.go
=> feature 新增导入主机支持填写云区域

src/common/metadata/fulltextsearch.go, src/scene_server/topo_server/service/fulltextsearch.go, src/tools/monstache/etc/config.toml, src/tools/monstache/plugin.go
- 添加业务集的全文检索功能，不包含资源范围
issues #6105
=> add biz set fulltext searching

src/ac/parser/host.go, src/common/metadata/hostserver.go, src/scene_server/host_server/logics/import.go, src/scene_server/host_server/service/host.go, src/scene_server/host_server/service/service_initfunc.go
=> 添加新增主机到业务空闲机接口

src/thirdparty/gse/client/gseclient.go
=> 修改thrift连接为短链去调用

src/scene_server/datacollection/collections/hostsnap/hostsnap.go
=> 修复主机信息上报mac场景时的panic

src/common/index/collections/servicetemplateattr.go, src/common/index/collections/settemplateattr.go, src/common/metadata/process.go, src/common/metadata/process_request.go, src/common/metadata/set_template.go, src/common/tablenames.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.10.202206081408/init_template_attribute.go, src/scene_server/admin_server/upgrader/y3.10.202206081408/pkg.go, src/source_controller/coreservice/core/process/service_template_attr.go
=> 添加创建集群模板和服务模板配置字段表的upgrader

src/apimachinery/coreservice/process/api.go, src/apimachinery/coreservice/process/process.go, src/common/metadata/core_service.go, src/common/metadata/process.go, src/common/metadata/process_request.go, src/scene_server/proc_server/service/service.go, src/scene_server/proc_server/service/servicetemplate.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/process/service_template_attr.go, src/source_controller/coreservice/service/service_process_initfunc.go, src/source_controller/coreservice/service/service_template.go
=> 新增服务模版配置字段接口

src/ui/src/components/audit-history/details-slider.vue
=> fix: 修复审计数据因模型被删除而无法查看的问题

src/apimachinery/apiserver/api.go, src/apimachinery/apiserver/apiserver.go, src/web_server/logics/excel_util.go, src/web_server/logics/host.go
- 修改导出主机/主机模板时查询云区域的接口
close #6179
=> fix 修改导出主机/主机模板时查询云区域的接口

src/tools/monstache/plugin.go, src/tools/monstache/vendor/github.com/rwynn/monstache/monstache.go
=> 修复全文检索es数据无法删除问题

src/ac/parser/servicetemplate.go, src/ac/parser/settemplate.go, src/apimachinery/coreservice/settemplate/api.go, src/apimachinery/coreservice/settemplate/settemplate.go, src/common/metadata/core_service.go, src/common/metadata/set_template.go, src/common/metadata/set_template_request.go, src/scene_server/topo_server/service/service_settemplate_initfunc.go, src/scene_server/topo_server/service/set_template.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/settemplate/set_template_attr.go, src/source_controller/coreservice/service/service_set_template_initfunc.go, src/source_controller/coreservice/service/set_template.go
=> 新增集群模版配置字段接口

src/auth/parser/host.go, src/common/metadata/hostserver.go, src/scene_server/datacollection/collections/porter.go, src/scene_server/host_server/service/host.go, src/scene_server/host_server/service/service.go
=> feature: add count biz host cpu num api

src/common/index/association.go
- 添加实例关联的唯一索引，不允许创建相同的两个实例间的同一关联
=> feature: add instance association unique index

docs/support-file/helm/Chart.lock, docs/support-file/helm/Chart.yaml, docs/support-file/helm/templates/adminserver/adminserver-dpl.yaml, docs/support-file/helm/templates/apiserver/apiserver-dpl.yaml, docs/support-file/helm/templates/authserver/authserver-dpl.yaml, docs/support-file/helm/templates/authserver/ingress.yaml, docs/support-file/helm/templates/cacheservice/cacheservice-dpl.yaml, docs/support-file/helm/templates/cloudserver/cloudserver-dpl.yaml, docs/support-file/helm/templates/coreservice/coreservice-dpl.yaml, docs/support-file/helm/templates/datacollection/datacollection-dpl.yaml, docs/support-file/helm/templates/eventserver/eventserver-dpl.yaml, docs/support-file/helm/templates/hostserver/hostserver-dpl.yaml, docs/support-file/helm/templates/operationserver/operationserver-dpl.yaml, docs/support-file/helm/templates/procserver/procserver-dpl.yaml, docs/support-file/helm/templates/synchronizeserver/synchronizeserver-dpl.yaml, docs/support-file/helm/templates/taskserver/taskserver-dpl.yaml, docs/support-file/helm/templates/toposerver/toposerver-dpl.yaml, docs/support-file/helm/templates/webserver/ingress.yaml, docs/support-file/helm/templates/webserver/webserver-dpl.yaml, docs/support-file/helm/values.yaml
=> 修改appVersion为3.10.17

docs/support-file/helm/templates/authserver/ingress.yaml, docs/support-file/helm/templates/webserver/ingress.yaml
=> 修改ingress内容

src/ac/parser/settemplate.go, src/apimachinery/coreservice/settemplate/api.go, src/apimachinery/coreservice/settemplate/settemplate.go, src/common/metadata/object_controller.go, src/common/metadata/set_template_request.go, src/scene_server/topo_server/service/service_settemplate_initfunc.go, src/scene_server/topo_server/service/set_template.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/process/service_template.go, src/source_controller/coreservice/core/settemplate/set_template_attr.go, src/source_controller/coreservice/service/service_set_template_initfunc.go, src/source_controller/coreservice/service/set_template.go
=> 添加操作集群模板全量信息的接口

src/source_controller/coreservice/core/model/attribute_curd.go
=> 删除集群/模块属性时同时删除集群/服务模板的配置字段

src/scene_server/topo_server/logics/inst/module.go, src/scene_server/topo_server/logics/inst/set.go
- 新增集群/模块时，用模板配置的字段进行初始化
- 更新集群/模块时，不允许更新模板中配置的字段
=> 集群/服务模板新增字段配置能力相关调整

scripts/init.py, src/common/metadata/inst.go, src/scene_server/event_server/app/options/options.go, src/scene_server/event_server/app/server.go, src/scene_server/event_server/service/sync.go, src/scene_server/event_server/sync/hostidentifier/common.go, src/scene_server/event_server/sync/hostidentifier/config.go, src/scene_server/event_server/sync/hostidentifier/event.go, src/scene_server/event_server/sync/hostidentifier/hostIdentifier.go, src/scene_server/event_server/sync/hostidentifier/task.go, src/scene_server/event_server/types/const.go, src/source_controller/cacheservice/event/identifier/converter.go, src/source_controller/coreservice/core/host/identifier/identifier.go, src/thirdparty/apigw/apigw.go, src/thirdparty/apigw/apigwutil/common.go, src/thirdparty/apigw/gse/api.go, src/thirdparty/apigw/gse/common.go, src/thirdparty/apigw/gse/service.go
- 主机身份下发功能接入apigw新接口并兼容旧thrift接口
=> 主机身份下发功能接入apigw新接口并兼容旧thrift接口

src/common/metadata/process_request.go, src/scene_server/proc_server/service/servicetemplate.go
=> 创建服务模板全量信息协议调整

src/ui/src/components/model-instance/relation/list-table.vue, src/ui/src/views/host-details/children/association-list-table.vue
=> fix: 修复查询模型关联实例分页数据id超出上限的问题

src/ac/parser/event.go, src/common/metadata/eventserver.go, src/scene_server/event_server/service/service.go, src/scene_server/event_server/service/sync.go
=> 添加推送主机身份接口

src/ui/src/components/property-config/details.vue, src/ui/src/components/property-config/index.vue, src/ui/src/components/ui/details/editable-property.vue, src/ui/src/components/ui/form/user.vue, src/ui/src/components/ui/other/grid-item.vue, src/ui/src/setup/validate.js
- 模板配置值超长文本展示优化
- 修复模板配置字段人员选择器交互异常问题
=> fix: 修复模板配置字段人员选择器交互异常问题和配置值超长文本展示优化

src/common/util/time.go, src/source_controller/coreservice/core/process/service_template_attr.go, src/source_controller/coreservice/core/settemplate/set_template_attr.go
- 修复服务/集群模板时间类型同步问题 close #6233
=> 修复服务/集群模板时间类型同步问题

src/common/index/collections/servicetemplateattr.go, src/common/index/collections/settemplateattr.go, src/scene_server/admin_server/upgrader/y3.10.202206081408/init_template_attribute.go
=> 修改集群/服务模版索引为新的数据结构

src/ui/src/components/audit-history/details-slider.vue, src/ui/src/components/export-file/index.js, src/ui/src/components/filters/filter-form.vue, src/ui/src/components/import-file/index.js, src/ui/src/components/instance/details/index.js, src/ui/src/components/service/form/form-multiple.vue, src/ui/src/components/service/form/form.vue, src/ui/src/views/dynamic-group/form/form.vue
=> fix: 修复侧滑在内嵌窗口中可能导致页面位移的问题

src/scene_server/topo_server/logics/inst/module.go, src/scene_server/topo_server/logics/inst/set.go
=> 更新集群/模块接口兼容时间类型的模板属性

src/scene_server/topo_server/logics/settemplate/settemplate.go, src/scene_server/topo_server/logics/settemplate/sync_status.go
=> 修复模糊匹配集群实例问题

src/ui/src/magicbox/magicbox.scss
=> fix: 修复在新版组件库下业务拓扑树的缩进问题

src/ui/src/magicbox/magicbox.scss, src/ui/src/views/host-apply/children/topology-tree.vue, src/ui/src/views/host-apply/index.vue
- 修复自动应用当模块所属模板已配置规则时跳转查看的模板规则数据未更新问题
=> fix: 修复自动应用当模块所属模板已配置规则时跳转查看的模板规则数据未更新问题

src/ui/src/views/business-topology/host/host-list-options.vue, src/ui/src/views/resource/children/host-options.vue
=> fix: 导出选中主机接口入参调整

src/ui/src/components/ui/details/editable-property.vue, src/ui/src/components/ui/form/date.vue, src/ui/src/components/ui/form/property-form-element.vue, src/ui/src/components/ui/form/time.vue
=> fix: 日期与时间类型属性编辑保存交互优化

src/kube/types/spec.go, src/kube/types/types.go
=> 添加容器相关的spec和常量

src/ui/src/service/business-set/index.js
=> fix: 修复业务集列表无权限申请操作无法点击的问题

src/ui/src/components/ui/form/form.vue, src/ui/src/store/modules/api/object-main-line-module.js, src/ui/src/views/business/index.vue, src/ui/src/views/general-model/index.vue
=> fix: 业务名称使用拓扑实例名称校验规则及添加主线模型统一判断方法

docs/support-file/helm/README.md, docs/support-file/helm/templates/NOTES.txt, docs/support-file/helm/templates/_helpers.tpl, docs/support-file/helm/values.yaml
- 删除chart password默认值, 要求密码启动时必填
=> 删除chart password默认值, 要求密码启动时必填

docs/overview/source_compile.md
=> 修改切换成go mod后的编译文档

src/ac/iam/adaptor.go, src/ac/iam/gen_id.go, src/ac/iam/initial_action_groups.go, src/ac/iam/initial_actions.go, src/ac/iam/types.go, src/ac/meta/resource.go
=> 添加容器数据相关权限

src/common/auditlog/container.go, src/common/metadata/audit.go
=> 添加容器相关的操作审计

src/common/criteria/enumor/column.go, src/common/util/time.go, src/common/util/valid.go, src/filter/README.md, src/filter/expression.go, src/filter/expression_test.go, src/filter/operaor_test.go, src/filter/operator.go, src/filter/rule.go, src/filter/rule_test.go
=> feature: add common query filter

src/kube/orm/tool.go, src/kube/orm/tool_test.go
=> 更新操作支持根据传入的参数更新

src/ac/iam/adaptor.go, src/ac/iam/gen_id.go, src/ac/iam/initial_action_groups.go, src/ac/iam/initial_actions.go, src/ac/iam/initial_instance_selections.go, src/ac/iam/initial_resources.go, src/ac/iam/types.go, src/ac/meta/meta.go, src/ac/parser/event.go, src/common/watch/cursor.go, src/common/watch/types.go, src/common/watch/watch.go, src/kube/types/types.go, src/scene_server/auth_server/service/gen_method.go, src/source_controller/cacheservice/event/bsrelation/event.go, src/source_controller/cacheservice/event/flow/details.go, src/source_controller/cacheservice/event/flow/event.go, src/source_controller/cacheservice/event/flow/flow.go, src/source_controller/cacheservice/event/flow/handler.go, src/source_controller/cacheservice/event/flow/inst_asst_flow.go, src/source_controller/cacheservice/event/flow/instance_flow.go, src/source_controller/cacheservice/event/flow/parser.go, src/source_controller/cacheservice/event/flow/workload_flow.go, src/source_controller/cacheservice/event/identifier/event.go, src/source_controller/cacheservice/event/key.go, src/source_controller/cacheservice/event/util.go, src/storage/dal/mongo/local/mongo.go
=> feature: add container management resource watch

src/ac/parser/host.go, src/ac/parser/topology.go, src/common/metadata/hostcontroller.go, src/kube/types/container.go, src/kube/types/namespace.go, src/kube/types/node.go, src/kube/types/pod.go, src/kube/types/topo.go, src/kube/types/workload.go, src/scene_server/host_server/service/host.go, src/scene_server/topo_server/service/container.go, src/scene_server/topo_server/service/node.go, src/scene_server/topo_server/service/pod.go, src/source_controller/coreservice/service/namespace.go, src/source_controller/coreservice/service/workload.go
=> 容器数据纳管功能调整

src/ac/parser/topology.go, src/kube/types/namespace.go, src/kube/types/query.go, src/kube/types/types.go, src/kube/types/workload.go, src/scene_server/topo_server/service/node.go, src/scene_server/topo_server/service/service_kube_initfunc.go
=> 添加查询容器mapstr字段类型kv所有的值

scripts/Makefile
=> 修改编译时的DOCS_DIR路径

src/common/metadata/dataid.go, src/scene_server/admin_server/service/dataid.go
- 往gse注册redis主机快照上报信息时支持传redis sentinel密码
=> 往gse注册redis主机快照上报信息时支持传redis sentinel密码

src/scene_server/host_server/logics/module.go
=> 将空闲机池下的主机转移至资源池

docs/support-file/helm/templates/adminserver/adminserver-dpl.yaml, docs/support-file/helm/templates/apiserver/apiserver-dpl.yaml, docs/support-file/helm/templates/authserver/authserver-dpl.yaml, docs/support-file/helm/templates/cacheservice/cacheservice-dpl.yaml, docs/support-file/helm/templates/cloudserver/cloudserver-dpl.yaml, docs/support-file/helm/templates/coreservice/coreservice-dpl.yaml, docs/support-file/helm/templates/datacollection/datacollection-dpl.yaml, docs/support-file/helm/templates/eventserver/eventserver-dpl.yaml, docs/support-file/helm/templates/hostserver/hostserver-dpl.yaml, docs/support-file/helm/templates/monstache/monstache-dpl.yaml, docs/support-file/helm/templates/operationserver/operationserver-dpl.yaml, docs/support-file/helm/templates/procserver/procserver-dpl.yaml, docs/support-file/helm/templates/synchronizeserver/synchronizeserver-dpl.yaml, docs/support-file/helm/templates/taskserver/taskserver-dpl.yaml, docs/support-file/helm/templates/toposerver/toposerver-dpl.yaml, docs/support-file/helm/templates/webserver/webserver-dpl.yaml
- monstache的pod配置resources资源
- 修改indent为nindent
=> monstache的pod配置resources资源

src/common/metadata/dynamic_grouping.go
=> 动态分组不等于场景下校验失败

src/source_controller/coreservice/core/operation/operation.go
=> 修复运营统计自定义实例统计设置枚举类型字段后无数据显示

docs/support-file/helm/templates/adminserver/configmap.yaml, docs/support-file/helm/values.yaml, scripts/init.py, src/thirdparty/logplatform/opentelemetry/config.go, src/thirdparty/logplatform/opentelemetry/tracer.go
=> 添加bkDataToken配置用于新的调用链上报

src/ui/src/views/business-topology/children/topology-tree.vue, src/ui/src/views/business-topology/host/across-business-module-selector.vue, src/ui/src/views/business-topology/host/host-selector-new/host-selector-topology.vue, src/ui/src/views/business-topology/host/module-selector.vue, src/ui/src/views/host-apply/children/topology-tree.vue
=> feat: 修改业务拓扑为直接使用接口数据不再自行排序

docs/support-file/config/templates/server#conf#common.yaml
=> esb配置文件缩进调整

docs/support-file/config/templates/server#conf#redis.yaml
=> 修改redis配置文件模版为sentinel模式

docs/support-file/config/templates/server#conf#common.yaml
=> 修改帮助文档变量地址

src/ac/parser/chain.go, src/ac/parser/kube.go, src/apimachinery/coreservice/kube/api.go, src/apimachinery/coreservice/kube/kube.go, src/common/definitions.go, src/kube/types/pod.go, src/scene_server/topo_server/service/pod.go, src/scene_server/topo_server/service/service_kube_initfunc.go, src/source_controller/coreservice/service/pod.go, src/source_controller/coreservice/service/service_kube_initfunc.go
=> feature: add delete pod api

src/apiserver/service/url.go, src/kube/types/pod.go
=> 删除apiserver多余的kube正则匹配

src/ui/src/views/host-apply/children/topology-tree.vue
=> fix: 解决service目录变更合并代码后引用路径错误问题

src/ui/src/components/modal/permission-resource-name.js, src/ui/src/router/business-interceptor.js, src/ui/src/views/index.js, src/ui/src/views/status/non-exist-business.vue
- 业务无权限或不存在提示调整为显示在主内容区域避免无法切换业务
=> feat: 业务无权限或不存在提示调整为显示在主内容区域避免无法切换业务

src/ac/parser/topolatest.go
=> 修复删除不存在的模型属性分组panic的问题.

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/setup/preload.js, src/ui/src/store/modules/api/object-model-classify.js, src/ui/src/store/modules/api/object-model.js, src/ui/src/views/index/children/full-text-search/use-item.js, src/ui/src/views/model-manage/children/model-details/index.vue, src/ui/src/views/model-manage/children/model-details/verification.vue, src/ui/src/views/model-topology/index.new.vue, src/ui/src/views/resource-manage/index.vue
- 修复主线模型相关功能点的判断逻辑及创建主线模型的分组设置为未分类
=> fix: 修复主线模型相关功能点的判断逻辑及创建主线模型的分组设置为未分类

src/common/auditlog/container.go, src/kube/types/cluster.go, src/kube/types/cronjob.go, src/kube/types/daemonset.go, src/kube/types/deployment.go, src/kube/types/gamedeployment.go, src/kube/types/gamestatefulset.go, src/kube/types/job.go, src/kube/types/k8s_types.go, src/kube/types/namespace.go, src/kube/types/pod.go, src/kube/types/pods_workload.go, src/kube/types/spec.go, src/kube/types/statefulset.go, src/kube/types/workload.go, src/scene_server/topo_server/logics/container/kube.go, src/scene_server/topo_server/service/namespace.go, src/scene_server/topo_server/service/workload.go, src/source_controller/coreservice/service/namespace.go, src/source_controller/coreservice/service/service_kube_initfunc.go, src/source_controller/coreservice/service/workload.go
=> 容器数据纳管代码调整

src/ac/parser/host.go, src/apimachinery/coreservice/host/api.go, src/apimachinery/coreservice/host/host.go, src/apimachinery/hostserver/apis.go, src/apimachinery/hostserver/hostserver.go, src/apiserver/service/url.go, src/common/definitions.go, src/common/metadata/hostserver.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.10.202209231617/add_cloud_host_related_attr.go, src/scene_server/admin_server/upgrader/y3.10.202209231617/pkg.go, src/scene_server/auth_server/logics/permissions_to_apply.go, src/scene_server/host_server/logics/host.go, src/scene_server/host_server/logics/module.go, src/scene_server/host_server/service/cloud_host.go, src/scene_server/host_server/service/host.go, src/scene_server/host_server/service/module.go, src/scene_server/host_server/service/service_initfunc.go, src/source_controller/coreservice/core/host/transfer/transfer.go, src/test/host_server/host_test.go
=> feature: add cloud host related apis

src/scene_server/topo_server/logics/inst/inst.go, src/scene_server/topo_server/service/inst.go
=> excel导入实例数据时，添加事务

src/ui/src/views/resource/children/host-options.vue
- 修复资源池主机转移到业务时按权限排序业务导致的权限异常问题
=> fix: 修复资源池主机转移到业务时按权限排序业务导致的权限异常问题

src/ui/src/views/resource-manage/children/classify-panel.vue
=> fix: 修复资源目录中添加到导航不限制时内置模型失效的问题

src/common/watch/cursor.go, src/source_controller/cacheservice/event/flow/event.go, src/source_controller/cacheservice/event/flow/parser.go, src/storage/dal/mongo/local/mongo.go
=> bugfix: fix kube watch related bugs.

src/ui/src/service/container/cluster.js, src/ui/src/service/container/container.js, src/ui/src/service/container/host.js, src/ui/src/service/container/namespace.js, src/ui/src/service/container/node.js, src/ui/src/service/container/pod.js, src/ui/src/service/container/property.js, src/ui/src/service/container/workload.js, src/ui/src/service/topology/instance.js
=> chore: 统一修改容器接口地址中kube的位置

src/ui/src/components/filters/property-selector.vue, src/ui/src/components/filters/store.js
=> feat: 暂不支持node的map类型字段作为条件搜索

src/web_server/logics/host.go, src/web_server/logics/inst.go
- xxxx
- xxxx
- 导入主机关联数据时，页面勾选部分模型，会出现事务报错
=> excel导入主机关联数据时，勾选部分模型出现事务报错

src/scene_server/host_server/service/cloud_host.go, src/test/host_server/host_test.go
- 新增云主机时，如果有内网IP+云区域和业务均相同的主机，则更新该主机
=> 新增云主机时，如果有内网IP+云区域和业务均相同的主机，则更新该主机

src/apimachinery/taskserver/task/task.go, src/common/http/rest/contexts.go, src/scene_server/task_server/logics/task.go, src/scene_server/task_server/service/queue.go, src/scene_server/task_server/service/service.go, src/scene_server/task_server/service/task.go
- taskserver异步任务相关逻辑优化 
close #6401
=> taskserver异步任务相关逻辑优化 

src/ac/extensions/biz_set.go, src/ac/extensions/instance.go, src/ac/extensions/types.go
=> 修复导入业务集关联关系

src/apimachinery/coreservice/kube/api.go, src/common/metadata/hostcontroller.go, src/kube/orm/tool.go, src/kube/orm/tool_test.go, src/kube/types/cronjob.go, src/kube/types/daemonset.go, src/kube/types/deployment.go, src/kube/types/gamedeployment.go, src/kube/types/gamestatefulset.go, src/kube/types/job.go, src/kube/types/namespace.go, src/kube/types/pods_workload.go, src/kube/types/statefulset.go, src/kube/types/topo.go, src/kube/types/types.go, src/kube/types/validate.go, src/kube/types/workload.go, src/scene_server/host_server/service/favourite.go, src/scene_server/host_server/service/host.go, src/scene_server/topo_server/service/container.go, src/scene_server/topo_server/service/namespace.go, src/scene_server/topo_server/service/node.go, src/scene_server/topo_server/service/pod.go, src/scene_server/topo_server/service/workload.go, src/source_controller/coreservice/service/namespace.go, src/source_controller/coreservice/service/workload.go, src/test/topo_server/namespace_test.go, src/test/topo_server/workload_test.go
=> 修改容器数据纳管review点

src/ui/package.json, src/ui/src/views/index/children/footer.vue
=> fix: 修复设置平台信息处的xss问题

src/filter/expression.go, src/kube/types/namespace.go, src/kube/types/pod.go, src/kube/types/workload.go, src/scene_server/topo_server/logics/kube/kube.go, src/scene_server/topo_server/service/kube_public.go, src/scene_server/topo_server/service/namespace.go, src/scene_server/topo_server/service/pod.go, src/scene_server/topo_server/service/workload.go, src/test/topo_server/namespace_test.go, src/test/topo_server/pod_test.go, src/test/topo_server/workload_test.go
=> 调整容器数据纳管代码

src/ui/src/service/container/container.js, src/ui/src/service/topology/instance.js, src/ui/src/service/utils.js, src/ui/src/views/business-topology/children/topology-tree.vue, src/ui/src/views/business-topology/pod/pod-list.vue, src/ui/src/views/host-details/children/pod-list.vue, src/ui/src/views/host-details/index.vue, src/ui/src/views/pod-details/children/container-list.vue
=> chore: 更新容器数据纳管相关接口参数

src/common/auditlog/host.go, src/common/definitions.go, src/common/metadata/audit.go, src/scene_server/topo_server/service/auditlog.go
=> 支持通过ipv6字段查询主机审计

src/ui/src/service/instance/association.js, src/ui/src/views/business-topology/service-instance/common/host-selector.vue, src/ui/src/views/host-details/children/association.vue, src/ui/src/views/host-details/children/property.vue, src/ui/src/views/index/children/full-text-search/use-item.js
=> fix: 全文检索和模型关联IPv6展示优化

src/source_controller/coreservice/service/namespace.go, src/source_controller/coreservice/service/workload.go
- 当namespace和workload查询不到上一级拓扑时返回错误
=> 当namespace和workload查询不到上一级拓扑时返回错误

src/common/auditlog/hostmodule.go
- 修复分配到业务、归还到资源池、转移模块的操作主机对应的实例显示为空问题
=> 修复分配到业务、归还到资源池、转移模块的操作主机对应的实例显示为空问题

src/scene_server/event_server/sync/hostidentifier/task.go, src/thirdparty/apigw/gse/common.go
=> 下发hostid文件时当路径文件不存在时自动创建

src/ui/src/views/model-manage/children/collapse-group-title.vue, src/ui/src/views/model-manage/index.vue
=> 修复模型字段分组展示报错的问题

src/ui/src/components/service/form/process-form-property-ip.vue, src/ui/src/magicbox/index.js, src/ui/src/views/business-topology/host/host-selector-new/host-selector-custom.vue, src/ui/src/views/index/children/full-text-search/search-bar.vue
- 放宽全文检索字符限制
- 选择主机自定义输入支持ipv6
=> fix: 放宽全文检索字符限制及选择主机自定义输入支持ipv6

src/common/index/compare.go, src/scene_server/admin_server/upgrader/history/x18.10.30.01/association.go, src/scene_server/admin_server/upgrader/history/x18.12.12.05/remove_deleted_inst_asst.go, src/scene_server/admin_server/upgrader/history/x19.09.03.05/create_inst_name_index.go, src/scene_server/admin_server/upgrader/history/x19.09.03.05/create_object_id_index.go, src/scene_server/admin_server/upgrader/history/x19.10.22.02/add_host_index.go, src/scene_server/admin_server/upgrader/history/y3.6.201909062359/create_table.go, src/scene_server/admin_server/upgrader/history/y3.6.201910091234/settemplate_sync_status.go, src/scene_server/admin_server/upgrader/history/y3.7.201911141719/init_host_property_apply.go, src/scene_server/admin_server/upgrader/history/y3.8.202001172032/create_audit_log_table.go, src/scene_server/admin_server/upgrader/history/y3.8.202006021120/add_service_instance_index.go, src/scene_server/admin_server/upgrader/y3.10.202109181134/migrate_svc_inst_id_to_proc.go, src/scene_server/admin_server/upgrader/y3.9.202002131522/add_cloud_host_index.go, src/scene_server/admin_server/upgrader/y3.9.202002131522/add_plat_index.go, src/scene_server/admin_server/upgrader/y3.9.202010151650/add_cloudid_index.go, src/scene_server/admin_server/upgrader/y3.9.202010211805/add_host_lock_table.go, src/scene_server/admin_server/upgrader/y3.9.202011192014/change_unique_index.go, src/scene_server/admin_server/upgrader/y3.9.202101061721/add_del_archive_index.go, src/scene_server/admin_server/upgrader/y3.9.202102011055/add_os_type_index.go, src/scene_server/admin_server/upgrader/y3.9.202102261105/add_instass_proc_index.go, src/scene_server/admin_server/upgrader/y3.9.202104211151/change_set_unique_index.go, src/scene_server/admin_server/upgrader/y3.9.202106291420/index.go, src/scene_server/admin_server/upgrader/y3.9.202106291420/pkg.go, src/test/topo_server/set_template_test.go
=> upgrader中创建索引时兼容已经创建过的重复索引

src/common/ipv6base.go, src/common/metadata/host.go, src/common/paraparse/host.go, src/common/querybuilder/types.go, src/scene_server/datacollection/collections/hostsnap/hostsnap.go
=> ipv6支持简写和全写的精确查询

src/ac/parser/event.go, src/common/metadata/eventserver.go, src/scene_server/event_server/service/service.go, src/scene_server/event_server/service/sync.go
=> 新增获取推送主机身份结果接口

src/common/definitions.go, src/web_server/middleware/user/plugins/method/blueking/userinfo.go
- cmdb多环境场景下会概率性出现循环登陆问题
- 由于父子域场景下cookie中会携带多个token，cmdb在验证的时候会概率性取到错误token。导致验证失败
=> bugfix:cmdb多环境场景下会概率性出现循环登陆问题(v3.10.x)

scripts/Makefile, src/common/version/version.go
=> 编译出来的二进制增加go版本号

src/ui/package.json, src/ui/src/components/layout/header.vue, src/ui/src/i18n/constants.js, src/ui/src/i18n/index.js, src/ui/src/magicbox/index.js
=> feat: 导航中添加语言切换功能

src/ui/src/views/host-operation/index.vue
=> fix: 移除主机转移失败重试的逻辑解决转移提示异常的问题

src/scene_server/host_server/logics/object.go
- 修复用自定义拓扑的实例id查询主机时, 如果没有查到自定义拓扑实例导致查询死循环的问题
=> 修复用自定义拓扑的实例id查询主机时, 如果没有查到自定义拓扑实例导致查询死循环的问题

src/ac/iam/adaptor.go, src/ac/iam/initial_action_groups.go, src/ac/iam/initial_actions.go, src/ac/iam/types.go, src/ac/meta/meta.go, src/common/watch/cursor.go, src/source_controller/cacheservice/event/flow/event.go, src/source_controller/cacheservice/event/key.go, src/source_controller/cacheservice/event/util.go, src/storage/dal/mongo/local/mongo.go
=> 添加watch云区域功能

src/scene_server/topo_server/logics/model/attribute.go, src/scene_server/topo_server/service/object_attribute.go
=> 修复创建字段时，分组不存在时没有创建默认分组的问题

src/scene_server/topo_server/core/operation/import_association.go, src/web_server/logics/excel_util.go, src/web_server/service/util.go
- xxxx
- xxxx
- 修复导出带用户数据实例时，webserver panic问题
- excel导入关联关系时，对映射关系进行校验
- excel新增主机时，无法识别字段
=> excel导入关联关系时，校验映射关系

src/scene_server/datacollection/collections/hostsnap/hostsnap.go
=> ipv6单栈时支持mac地址上报

src/ui/src/components/filters/filter-fast-search.vue, src/ui/src/components/filters/filter-form.vue, src/ui/src/components/filters/filter-tag-ip.vue, src/ui/src/components/filters/property-selector.vue, src/ui/src/components/filters/store.js, src/ui/src/components/filters/utils.js, src/ui/src/setup/validate.js, src/ui/src/views/index/children/host-search.vue
=> feat: 主机按IP搜索支持IPv6

src/apimachinery/hostserver/apis.go, src/apimachinery/hostserver/hostserver.go, src/common/metadata/hostserver.go, src/common/paraparse/host.go, src/kube/types/topo.go, src/scene_server/host_server/logics/dynamic_grouping.go, src/scene_server/host_server/logics/hostsearch.go, src/scene_server/host_server/service/host.go, src/test/host_server/host_abnormal_test.go, src/test/host_server/host_test.go, src/test/proc_server/proc_server_suite_test.go, src/test/topo_server/node_test.go, src/test/topo_server/pod_test.go, src/web_server/logics/host.go
CMDB 业务-业务拓扑页面以及 资源-主机页面支持ipv6查询与筛选
- xxxx
- xxxx
=> feature:主机搜索支持IPv6字段

src/apimachinery/coreservice/model/api.go, src/apimachinery/coreservice/model/model.go, src/common/metadata/update.go, src/scene_server/topo_server/service/object_attribute.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/model/attribute.go, src/source_controller/coreservice/core/model/attribute_curd.go, src/source_controller/coreservice/service/model.go, src/source_controller/coreservice/service/service_initfunc.go
=> 修复调整模型字段接口业务自定义字段未按照业务判断的问题

src/source_controller/coreservice/core/process/service_template.go
=> 修复更新服务模板接口校验名称按之前的名称校验的问题

docs/support-file/changelog/release.md
=> ipv6 alpha11 版本日志

docs/apidoc/cc/en/create_object_attribute.md, docs/apidoc/cc/en/update_object_attribute.md, docs/apidoc/cc/zh_hans/create_object_attribute.md, docs/apidoc/cc/zh_hans/update_object_attribute.md, src/source_controller/coreservice/core/model/attribute_curd.go
- xxxx
- 更新模型属性创建，更新的esb文档
- 修复枚举引用，枚举多选无法编辑的问题
=> 修复枚举引用，枚举多选无法编辑问题

src/ac/iam/initial_action_groups.go, src/ac/iam/initial_actions.go, src/ac/iam/types.go
=> 暂时去掉项目查看权限

src/ui/src/views/project/index.vue
=> fix: 项目页面查看权限暂时无需限制

docs/support-file/changelog_user/en/v3.10.20_2022-09-28.md, docs/support-file/changelog_user/en/v3.10.4_2021-08-02.md, docs/support-file/changelog_user/en/v3.10.7_2021-10-27.md
=> 更新v3.10.23之前的所有v3.10.x版本日志

src/ac/iam/adaptor.go, src/ac/iam/initial_action_groups.go, src/ac/iam/initial_actions.go, src/ac/iam/types.go
=> 新增空间级查看权限注册点

src/ui/src/views/project/index.vue
=> 项目页面按钮权限异常

src/ui/src/views/dynamic-group/form/form-property-list.vue
=> 动态分组中，枚举多选和枚举引用无法拉到选项值

src/ui/src/components/model-manage/field-group/field-detail/enum.vue, src/ui/src/components/model-manage/field-group/field-detail/index.vue, src/ui/src/views/dynamic-group/form/form-property-list.vue
=> fix: 动态分组表单元素宽度超出问题修复

src/ui/src/components/layout/header.vue
=> 版本日志列表按日期降序

src/ac/extensions/base.go, src/ac/iam/adaptor.go, src/ac/iam/gen_id.go, src/ac/iam/initial_action_groups.go, src/ac/iam/initial_actions.go, src/ac/iam/types.go, src/ac/meta/resource.go, src/ac/parser/topolatest.go, src/common/http/rest/contexts.go, src/scene_server/topo_server/service/association.go, src/scene_server/topo_server/service/auth.go, src/scene_server/topo_server/service/fulltextsearch.go, src/scene_server/topo_server/service/graphics.go, src/scene_server/topo_server/service/inst.go, src/scene_server/topo_server/service/object.go, src/scene_server/topo_server/service/object_association.go, src/scene_server/topo_server/service/object_attribute.go, src/scene_server/topo_server/service/object_group.go, src/scene_server/topo_server/service/unique.go
=> 添加toposerver空间级查看权限

src/ui/src/components/ui/flex-tag/index.vue, src/ui/src/components/ui/form/organization.vue, src/ui/src/components/ui/other/org-value.vue
- 组织名称/分隔符之间保留一个空格
- 模型引用值标签展示超出时显示省略符同时tips内容仅展示省略项
=> V3.10.23体验问题修复

src/scene_server/topo_server/service/fulltextsearch.go
=> 调整全文检索接口返回内容

resources/language/default/common.json, resources/language/en/common.json, src/scene_server/topo_server/logics/model/object.go, src/source_controller/coreservice/core/model/attribute_curd.go, src/web_server/logics/object.go, src/web_server/service/object.go
- 导出模型字段后，不包含ismultiple字段。编辑字段后，导入更新模型字段提示ismultiple参数校验不通过问题
issues #6682
=> 修复无法导入模型字段

src/ui/src/components/layout/header.vue, src/ui/src/components/model-manage/field-group/field-detail/index.vue, src/ui/src/components/model-manage/field-group/preview-field.vue, src/ui/src/components/ui/form/enummulti.vue, src/ui/src/components/ui/form/enumquote.vue, src/ui/src/components/ui/form/organization.vue, src/ui/src/components/ui/form/timezone.vue, src/ui/src/i18n/index.js, src/ui/src/utils/tools.js
- 组件样式调整
- 版本日志版本位置顺序问题，中英文切换问题
- 组织组件空格间距问题
=> v3.10.23验收问题处理

src/ui/src/components/audit-history/details-slider.vue
=> fix: 修复操作审计详情是否使用表格展示的问题

src/ui/src/views/resource-manage/children/classify-panel.vue
=> fix: 修复资源目录搜索时实例数异常问题

src/source_controller/coreservice/core/model/attribute_curd.go
- 导出模型字段后，不包含ismultiple字段。编辑字段后，导入更新模型字段提示ismultiple参数校验不通过问题
issues #6682
=> V3.10.x fix import modelfield

src/ui/src/components/instance/details/index.js, src/ui/src/components/layout/dynamic-navigation.vue, src/ui/src/components/modal/permission.vue, src/ui/src/components/model-instance/relation/create.vue, src/ui/src/components/ui/auth/auth-mask.vue, src/ui/src/components/ui/auth/auth.vue, src/ui/src/dictionary/iam-auth.js, src/ui/src/service/association/index.js, src/ui/src/setup/permission.js, src/ui/src/store/modules/api/auth.js, src/ui/src/views/business-topology/router.config.js, src/ui/src/views/host-details/children/association-create.vue, src/ui/src/views/host-details/children/association-list.vue, src/ui/src/views/model-association/index.vue, src/ui/src/views/model-manage/index.vue, src/ui/src/views/model-manage/style.scss, src/ui/src/views/resource-manage/children/classify-panel.vue, src/ui/src/views/status/permission.vue
- 去除入口预鉴权，统一在主内容区展示无权限申请
- 新建关联时自动去除已有权限条目
- 申请实例查看权限时，如果没有模型查看权限则自动带上
=> fix: 空间级查看权限体验问题优化

src/ac/extensions/base.go, src/ac/iam/adaptor.go, src/ac/iam/gen_id.go, src/ac/parser/topolatest.go, src/common/metadata/association.go, src/scene_server/topo_server/logics/model/association.go, src/scene_server/topo_server/service/association.go, src/scene_server/topo_server/service/service_business_initfunc.go
- 新加查询关联关系使用数量接口
- 添加根据业务id查询模型实例关联关系接口
- 模型实例不关联资源列表
- 鉴权失败时只将没有权限的返回
- 修复云区域和自定义模型实例跳转权限中心失败问题
=> 修复空间级查看权限问题

src/common/definitions.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.10.202303072103/add_freebsd_property.go, src/scene_server/admin_server/upgrader/y3.10.202303072103/pkg.go, src/scene_server/datacollection/collections/hostsnap/hostsnap.go
=> feature: add os type FreeBSD

src/web_server/logics/host.go
- 导入不存在的关联关系可以导入成功问题
issues [6615](https://github.com/TencentBlueKing/bk-cmdb/issues/6615)
=> fix: 导入不存在的关联关系可以导入成功问题

docs/support-file/config/templates/server#conf#common.yaml, docs/support-file/helm/values.yaml
- 修改下发window机器的主机身份文件所有者默认值为SYSTEM
=> 修改下发window机器的主机身份文件所有者默认值为SYSTEM

src/scene_server/host_server/service/cloud_host.go, src/test/host_server/host_test.go
- 新增云主机接口支持根据云供应商+云主机ID判断主机是否需要更新
=> 新增云主机接口支持根据云供应商+云主机ID判断主机是否需要更新

src/apimachinery/coreservice/coreservice.go, src/apimachinery/coreservice/model_quote/api.go, src/apimachinery/coreservice/model_quote/model.go, src/common/definitions.go, src/common/metadata/core_service.go, src/common/metadata/filter.go, src/scene_server/admin_server/upgrader/y3.10.202303272150/add_model_quote_relation.go, src/source_controller/coreservice/service/model_quote.go, src/source_controller/coreservice/service/service_initfunc.go
- 新增data-service的创建、删除、查询模型引用关系的接口
=> feature: add model quote relation core service apis.

src/scene_server/admin_server/service/dataid.go
=> 将新旧dataid往gse注册的streamTo分开

src/ui/src/components/model-instance/model-instance-selector.vue, src/ui/src/components/model-manage/field-group/field-detail/index.vue, src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/components/ui/form/organization.vue
- 新建字段侧拉框样式根据规范修改
- 枚举多选组件未展示数字略缩问题
=> v3.10.24验收问题

src/ui/src/components/ui/flex-tag/index.vue
=> fix: 标签展示组件样式优化

src/ui/src/dictionary/property-constants.js
=> fix: 去掉枚举引用新建入口

src/apimachinery/apiserver/apiserver.go, src/apimachinery/apiserver/model_quote/api.go, src/apimachinery/apiserver/model_quote/instance.go, src/apimachinery/coreservice/model_quote/api.go, src/apimachinery/coreservice/model_quote/instance.go, src/common/metadata/core_service.go, src/common/metadata/create.go, src/common/metadata/filter.go, src/common/metadata/model_quote.go, src/source_controller/coreservice/service/model_quote.go
=> feature: add quoted instance api machinery.

src/apimachinery/adminserver/adminserver.go, src/apimachinery/adminserver/api.go, src/apimachinery/clientset.go, src/apimachinery/util/type.go, src/test/test.go
=> fix: test suite migrate timeout.

resources/language/default/common.json, resources/language/en/common.json, src/common/util/valid.go, src/web_server/logics/object.go, src/web_server/service/object.go
- 浮点类型字段导出后导入失败
- 导入导出不支持默认值
close #6771 #6775
=> fix: attribute export & import problems. 

src/ui/src/components/ui/form/inner-table/index.vue, src/ui/src/components/ui/form/inner-table/inner-table.vue, src/ui/src/components/ui/form/property-form-element.vue, src/ui/src/components/ui/index.js, src/ui/src/dictionary/property-constants.js, src/ui/src/shims-vue.d.ts, src/ui/src/store/index.js, src/ui/src/store/modules/api/table-instance.ts, src/ui/src/views/host-details/children/property.vue
**###** 新加的功能:
- xxxx
- xxxx
- xxxx
=> feat: 模型实例新增表格字段

src/ac/extensions/base.go, src/ac/extensions/extensions.go, src/ac/parser/topology.go, src/apiserver/service/filter.go, src/apiserver/service/service.go, src/common/http/rest/contexts.go, src/common/http/rest/metric.go, src/scene_server/topo_server/service/inst_business.go
以查询业务接口作为demo，后续需要将新增和存量接口改为在场景层鉴权
=> 区分是否在apiserver鉴权的接口

src/source_controller/coreservice/core/instances/validator_util.go
=> fix: fill lost float field value failed.

src/scene_server/topo_server/service/quoted_instance.go, src/scene_server/topo_server/service/service_model_quote_initfunc.go, src/source_controller/coreservice/service/model_quote/quoted_inst.go, src/source_controller/coreservice/service/model_quote/quoted_inst_validate.go, src/source_controller/coreservice/service/service_initfunc.go, src/web_server/service/table.go
=> feature: add update quoted instance api.

src/ui/src/components/model-manage/field-group/field-detail/index.vue, src/ui/src/views/index/children/full-text-search/item-instance.vue, src/ui/src/views/index/children/full-text-search/item-model.vue, src/ui/src/views/index/children/full-text-search/result-list.vue
=> feat: 全文检索展示表格类型字段

src/web_server/logics/excel_util.go, src/web_server/logics/fields.go
=> 调整查询属性接口, 修复查询不到表格类型字段的问题

src/apimachinery/coreservice/model/api.go, src/apimachinery/coreservice/model/model.go, src/common/index/index.go, src/common/index/instance.go, src/scene_server/admin_server/logics/index.go, src/scene_server/topo_server/service/object.go, src/scene_server/topo_server/service/object_attribute.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/model/model_crud.go, src/source_controller/coreservice/core/model/model_tables.go, src/source_controller/coreservice/service/model.go, src/source_controller/coreservice/service/service_initfunc.go
=> 创建表格字段的实例表

src/web_server/logics/excel_util.go
- 表格字段枚举多选类型没有转换问题
- 当只有一行表格数据导入失败问题
=> 修复excel表格字段相关问题

src/scene_server/topo_server/logics/model/attribute.go, src/source_controller/coreservice/core/model/attribute.go, src/source_controller/coreservice/core/model/model_crud.go
=> feature: operate instance when attribute deleted.

src/source_controller/coreservice/core/instances/validator_util.go
- 修复创建实例时，没有传设置了默认值的数据类型字段时会报错的问题
=> 修复创建实例时，没有传设置了默认值的数据类型字段时会报错的问题

src/web_server/logics/excel_util.go
=> 修复枚举多选没值时，导出失败问题

src/common/metadata/fulltextsearch.go, src/scene_server/topo_server/service/fulltextsearch.go, src/thirdparty/elasticsearch/esclient.go, src/tools/monstache/plugin.go
=> feat: 表格字段全文检索改造

src/tools/monstache/plugin.go
=> fix: 修复全文检索文档_id错误的问题

src/ui/package.json, src/ui/src/components/model-instance/model-instance-selector.vue, src/ui/src/components/model-manage/field-group/field-detail/enum.vue, src/ui/src/components/model-manage/field-group/field-detail/inner-table/field-settings-model.vue, src/ui/src/components/model-manage/field-group/field-detail/inner-table/index.vue, src/ui/src/components/model-manage/field-group/table-default-settings.vue, src/ui/src/components/ui/form/inner-table/data-row.vue, src/ui/src/components/ui/form/inner-table/index.vue, src/ui/src/setup/validate.js, src/ui/src/utils/tools.js
=> feat: 模型表格字段体验问题修复

src/web_server/logics/excel.go, src/web_server/logics/excel_util.go, src/web_server/logics/fields.go
=> 优化excel表格导入导出代码

src/web_server/logics/excel.go, src/web_server/logics/host.go
=> 修复选择主机id导出时没有分页的问题

src/tools/monstache/plugin.go
=> feat: 优化全文检索逻辑

src/web_server/logics/excel.go, src/web_server/logics/excel_util.go, src/web_server/service/host.go, src/web_server/service/inst.go
- 导出数据改为内存操作
- 不可编辑的字段框进行合并
- 修复主机导出缺少部分关联关系数据问题
=> 处理excel的表格字段问题

src/ui/src/components/model-instance/property.vue, src/ui/src/components/model-manage/field-group/field-detail/index.vue, src/ui/src/components/model-manage/field-group/field-detail/inner-table/field-settings-model.vue, src/ui/src/components/model-manage/field-group/table-default-settings.vue, src/ui/src/components/ui/button/icon-text-button.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/components/ui/form/inner-table/data-row.vue, src/ui/src/components/ui/form/inner-table/index.vue, src/ui/src/views/host-details/children/property.vue
=> fix: 表格字段默认值设置和不可编辑状态问题修复

src/web_server/logics/excel.go, src/web_server/logics/excel_util.go, src/web_server/logics/host.go
- 修复excel是表格字段时，把所有配置设置到表格第一个字段的问题
=> 修复excel是表格字段时，把所有配置设置到表格第一个字段的问题

src/common/metadata/attribute.go
=> fix: int & float validate failed.

src/common/metadata/attribute.go, src/source_controller/coreservice/service/model_quote/quoted_inst_validate.go
=> fix: create instance bug

src/ui/src/components/ui/auth/auth.vue, src/ui/src/components/ui/form/inner-table/data-row.vue, src/ui/src/components/ui/form/inner-table/index.vue
- 鉴权组件闪现锁式手型的问题
- 修复创建实例时表格字段默认值问题
=> 修复创建实例时表格字段默认值问题

src/scene_server/host_server/logics/import.go, src/scene_server/topo_server/logics/inst/inst.go, src/scene_server/topo_server/logics/model/attribute.go, src/source_controller/coreservice/core/model/model_attribute_group.go
=> 修复当表格字段是必填时导入实例数据报错的问题

src/scene_server/topo_server/logics/model/attribute.go
=> 优化导入属性时按顺序处理

src/ui/src/components/model-manage/field-group/field-detail/index.vue, src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/hooks/use-sideslider.js
=> feat: 实现侧滑关闭规范的通用方法

src/scene_server/topo_server/service/object_attribute.go
=> 修复枚举多选无法编辑问题

src/ui/src/components/model-manage/field-group/field-detail/enum.vue, src/ui/src/components/ui/form/enummulti.vue
=> fix: 修复枚举类型字段配置和保存时可能报错的问题

src/web_server/logics/excel_util.go
- 修复excel导入实例数据，页面提示成功，实际未成功
close #6954
=> 修复excel导入数据成功实际数据没有导入成功

src/ui/src/components/filters/filter-form.vue
=> 高级筛选过滤内外网ipv6条件

docs/support-file/config/templates/server#conf#common.yaml, docs/support-file/helm/templates/adminserver/configmap.yaml, docs/support-file/helm/values.yaml
=> 新增调用gse apigw相关配置

resources/language/default/placeholder.json, resources/language/default/property.json, resources/language/en/placeholder.json, resources/language/en/property.json, src/common/metadata/classification.go, src/source_controller/coreservice/service/model.go
=> fix: 提示词和模型分类的国际化修复

src/source_controller/coreservice/service/model.go
=> feat: 添加对枚举值多选的国际化支持

src/apiserver/service/url.go, src/common/definitions.go, src/common/metadata/attribute.go, src/common/metadata/field_template.go, src/common/metadata/unique.go, src/common/tablenames.go, src/source_controller/coreservice/service/model.go
=> 增加字段模版结构体和常量

src/ac/iam/adaptor.go, src/ac/iam/gen_id.go, src/ac/iam/initial_action_groups.go, src/ac/iam/initial_actions.go, src/ac/iam/initial_instance_selections.go, src/ac/iam/initial_resources.go, src/ac/iam/types.go, src/ac/meta/resource.go, src/scene_server/auth_server/logics/parser.go, src/scene_server/auth_server/logics/util.go, src/scene_server/auth_server/service/gen_method.go
=> feature: init field template auth resource

src/apimachinery/coreservice/coreservice.go, src/apimachinery/coreservice/field_template/api.go, src/apimachinery/coreservice/field_template/field_template.go, src/common/metadata/field_template.go, src/scene_server/topo_server/service/capability/capability.go, src/scene_server/topo_server/service/field_template/field_template.go, src/scene_server/topo_server/service/field_template/service.go, src/scene_server/topo_server/service/service_initfunc.go, src/source_controller/coreservice/service/field_template/field_template.go, src/source_controller/coreservice/service/field_template/service.go, src/source_controller/coreservice/service/service_initfunc.go
=> feature: add list field template api.

src/ui/src/views/index/children/full-text-search/result-list.vue
=> 修复全文检索缺少方法引用的问题

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/views/global-config/children/module-builder.vue, src/ui/src/views/model-manage/children/model-details/index.vue
=> fix: 修复构建未找到sass变量的问题

src/ui/package.json
=> fix: 锁定postcss-preset-env版本

pkg/filter/expression.go, pkg/tools/filter/gen.go, src/ac/extensions/base.go, src/ac/extensions/extensions.go, src/ac/meta/meta.go, src/ac/parser/field_template.go, src/ac/parser/topolatest.go, src/apimachinery/coreservice/field_template/api.go, src/apimachinery/coreservice/field_template/attribute_template.go, src/apiserver/service/url.go, src/common/http/rest/contexts.go, src/common/http/rest/metric.go, src/common/metadata/field_template.go, src/scene_server/topo_server/service/field_template/attribute_template.go, src/scene_server/topo_server/service/field_template/service.go, src/source_controller/coreservice/service/field_template/attribute_template.go
=> 新增查询字段模板中的字段的接口

src/ac/parser/topology.go, src/common/definitions.go, src/common/index/collections/field_template_relation.go, src/common/metadata/field_template.go, src/scene_server/admin_server/upgrader/y3.10.202305121010/add_field_template.go
=> 调整字段组合模版关联表中的模型id

docs/support-file/config/templates/server#conf#common.yaml
=> 调整调用gse的thrift接口证书

src/ac/parser/field_template.go, src/apimachinery/coreservice/field_template/api.go, src/apimachinery/coreservice/field_template/attribute_template.go, src/apimachinery/coreservice/field_template/field_template.go, src/apimachinery/coreservice/field_template/unique_template.go, src/common/metadata/field_template.go, src/common/valid/valid.go, src/scene_server/topo_server/logics/field_template/field_template.go, src/scene_server/topo_server/logics/logics.go, src/scene_server/topo_server/service/field_template/field_template.go, src/scene_server/topo_server/service/field_template/service.go, src/scene_server/topo_server/service/field_template/unique_template.go, src/source_controller/coreservice/service/field_template/attribute_template.go, src/source_controller/coreservice/service/field_template/field_template.go, src/source_controller/coreservice/service/field_template/service.go, src/source_controller/coreservice/service/field_template/unique_template.go
=> 添加创建字段模版和查询字段模版唯一校验接口

src/apimachinery/coreservice/field_template/api.go, src/apimachinery/coreservice/field_template/relation.go, src/common/metadata/field_template.go, src/scene_server/topo_server/service/field_template/object_relation.go, src/scene_server/topo_server/service/field_template/service.go, src/source_controller/coreservice/service/field_template/object_relation.go, src/source_controller/coreservice/service/field_template/service.go
- 新增查询字段模板与模型的关联关系的接口
- 新增根据模型查询字段模板的接口
- 新增根据字段模板查询模型的接口
=> 新增字段模板与模型的关联关系相关的查询接口

src/scene_server/host_server/service/transfer.go
=> fix: fix format missing field

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/components/ui/form/organization.vue, src/ui/src/views/business/index.vue, src/ui/src/views/general-model/index.vue, src/ui/src/views/model-manage/index.vue, src/ui/src/views/project/index.vue
=> fix: 优化代码解决异常报错

src/common/metadata/field_template.go, src/scene_server/topo_server/logics/field_template/field_template.go, src/scene_server/topo_server/service/field_template/field_template.go
=> 字段模版属性字段支持按顺序保存

src/scene_server/proc_server/service/service.go, src/source_controller/coreservice/core/instances/validator_util.go, src/source_controller/coreservice/service/service_initfunc.go
- 修复组织和列表类型默认值转换错误，导致实例创建失败的问题
=> 修复组织和列表类型默认值转换错误，导致实例创建失败的问题

docs/support-file/config/templates/server#conf#common.yaml, docs/support-file/helm/Chart.lock, docs/support-file/helm/Chart.yaml, docs/support-file/helm/templates/adminserver/configmap.yaml, docs/support-file/helm/values.yaml, scripts/init.py, src/scene_server/event_server/app/server.go, src/thirdparty/apigw/apigwutil/common.go
=> 调整apigw配置获取方式

src/common/index/collections/model_quote_relation.go, src/scene_server/admin_server/upgrader/y3.10.202304012150/add_model_quote_relation.go, src/source_controller/coreservice/service/service_initfunc.go
=> 修复表格字段upgrade执行失败问题

src/apimachinery/coreservice/model/api.go, src/apimachinery/coreservice/model/model.go, src/scene_server/topo_server/service/field_template/object_relation.go, src/source_controller/coreservice/service/model.go, src/source_controller/coreservice/service/service_initfunc.go
=> fix: read model paging bug.

src/scene_server/auth_server/app/app.go, src/scene_server/auth_server/app/server.go, src/scene_server/auth_server/logics/fetch_instance_info.go, src/scene_server/auth_server/logics/list_attr_value.go, src/scene_server/auth_server/logics/list_instance.go, src/scene_server/auth_server/logics/parser.go, src/scene_server/auth_server/logics/permissions_to_apply.go, src/scene_server/auth_server/sdk/auth/authorize.go, src/scene_server/auth_server/sdk/auth/calculate.go, src/scene_server/auth_server/sdk/operator/policy_test.go, src/scene_server/auth_server/service/auth.go, src/scene_server/auth_server/service/gen_method.go, src/scene_server/auth_server/service/pull_resource.go, src/scene_server/auth_server/service/service.go
=> 处理authserver超长函数

src/apiserver/main.go, src/apiserver/service/auth.go, src/apiserver/service/healthz.go, src/apiserver/service/limiter.go, src/scene_server/event_server/app/server.go, src/scene_server/event_server/service/service.go
=> ci: reformat code

src/web_server/app/options/options.go, src/web_server/app/server.go, src/web_server/service/index.go
=> 将esb地址返回给前端

src/ui/builder/config/index.js, src/ui/index.html, src/ui/src/api/index.js, src/ui/src/api/jsonp.js, src/ui/src/i18n/index.js, src/ui/src/setup/build-in-vars.js
- 添加cookieDomain配置
- 添加esbUrl配置并在切换语言时使用相关接口
=> 切换语言cookie设置优化

docs/support-file/config/templates/server#conf#common.yaml
=> 添加bkDomain配置渲染变量

src/source_controller/coreservice/core/model/attribute.go, src/source_controller/coreservice/core/model/attribute_curd.go
=> 枚举、枚举多选、枚举引用类型忽略default字段

src/source_controller/coreservice/service/field_template/attribute_template.go
=> 字段组合模版属性为枚举多选类型时忽略default值

src/ui/src/api/index.js, src/ui/src/api/jsonp.js, src/ui/src/components/ui/other/sync-status.vue, src/ui/src/views/field-template/children/model-sync-status.vue, src/ui/src/views/field-template/children/search-select.vue, src/ui/src/views/field-template/children/sync-results.vue, src/ui/src/views/field-template/children/use-model-sync-status.js, src/ui/src/views/field-template/details.vue, src/ui/src/views/field-template/index.vue
- 字段组合模板列表页搜索
- hover绑定模型查看详细状态
=> 字段组合模板列表页搜索和hover绑定模型查看详细状态功能

src/ui/src/views/field-template/children/field-diff.vue, src/ui/src/views/field-template/children/use-field.js
=> feat: 字段组合模板字段对比内容展示功能

src/ui/src/components/modal/permission-resource-name.js, src/ui/src/dictionary/iam-auth.js, src/ui/src/service/field-template/index.js, src/ui/src/views/field-template/children/bind-model.vue, src/ui/src/views/field-template/children/field-preview-drawer.vue, src/ui/src/views/field-template/children/search-select.vue, src/ui/src/views/field-template/details-field.vue, src/ui/src/views/field-template/details-model.vue, src/ui/src/views/field-template/details.vue, src/ui/src/views/field-template/edit-binding.vue, src/ui/src/views/field-template/index.vue, src/ui/src/views/model-manage/children/model-details/index.vue
=> feat: 字段组合模板权限完善

src/ui/src/views/dynamic-group/form/form.vue
=> fix: 点击提交不弹二次确认框

src/scene_server/topo_server/service/field_template/field_template.go
- 调用CreateFieldTemplateAttrs时处理返回的err
=> 调用CreateFieldTemplateAttrs时处理返回的err

src/scene_server/topo_server/logics/field_template/compare_attr.go
=> 修复字段组合模版对比问题

src/source_controller/coreservice/core/model/unique_crud.go
=> 修复不传模版id可以更新唯一校验的问题

src/scene_server/task_server/service/task.go, src/scene_server/topo_server/logics/field_template/compare_attr.go, src/scene_server/topo_server/logics/field_template/compare_unique.go
=> fix: some field template bugs.

src/ui/src/components/model-manage/field-group/field-detail/config.vue, src/ui/src/components/model-manage/field-group/field-detail/index.vue, src/ui/src/components/model-manage/field-group/field-view.vue, src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/service/field-template/index.js
=> feat: 模型字段页中来自模板的字段的交互功能

src/source_controller/coreservice/core/model/attribute_curd.go
=> 修复无法更新来自字段模版的模型属性的问题

src/web_server/service/field_template.go
=> 修复用模型查询字段模板时，模型没有关联的模板时返回了全部模板的问题

src/common/valid/valid.go, src/scene_server/topo_server/logics/model/attribute.go, src/source_controller/coreservice/core/model/attribute_curd.go
=> 修复字段组合模版同步相关问题

src/scene_server/topo_server/logics/field_template/compare_attr.go
=> feat: ui compare template id

src/scene_server/topo_server/service/field_template/attribute_template.go, src/scene_server/topo_server/service/field_template/service.go, src/web_server/service/field_template.go
=> 单独查询模版属性数量接口不鉴权

src/ac/parser/field_template.go
=> 添加查询字段模板属性数量url

src/ui/src/components/business-scope/preview.vue, src/ui/src/components/import-file/import-relation.vue, src/ui/src/components/search/foreignkey.vue, src/ui/src/views/general-model/index.vue
- 批量导入失败后刷新列表页
- 当云区域数量超过1000时，在主机的高级筛选中，部分云区域可能无法搜索到
=> fix: bug修复

src/ui/src/service/field-template/index.js, src/ui/src/views/field-template/index.vue
=> fix: 字段组合模板获取字段数量接口地址调整和模板名称样式优化

src/ui/src/views/field-template/bind.vue, src/ui/src/views/field-template/children/basic-form.vue, src/ui/src/views/field-template/children/bind-model.vue, src/ui/src/views/field-template/children/unique-diff.vue, src/ui/src/views/field-template/create-basic.vue, src/ui/src/views/field-template/create-field-settings.vue, src/ui/src/views/field-template/edit-basic.vue, src/ui/src/views/field-template/edit-binding.vue, src/ui/src/views/field-template/edit-field-settings.vue, src/ui/src/views/field-template/index.vue
=> fix: 修复字段组合模板唯一校验对比展示及编辑模板草稿问题

src/web_server/app/options/options.go, src/web_server/app/server.go, src/web_server/service/index.go
=> 将paas前端地址返回给前端

src/ui/builder/config/index.js, src/ui/index.html, src/ui/src/i18n/index.js
=> feat: 添加desktopUrl配置

docs/support-file/helm/Chart.yaml
=> 修改3.10.28-beta1的chart版本号

src/scene_server/topo_server/service/field_template/field_template.go, src/source_controller/coreservice/service/field_template/field_template.go
- 添加绑定解绑接口鉴权
- 修复解绑时没有解除唯一校验绑定的问题
=> 处理绑定解绑接口相关问题

src/source_controller/coreservice/service/field_template/unique_template.go
=> 唯一校验禁止添加枚举多选类型

src/ui/src/setup/duplicate-remote-validate.js, src/ui/src/setup/validate.js, src/ui/src/views/field-template/children/basic-form.vue, src/ui/src/views/field-template/edit-basic.vue
=> fix: 字段组合模板名称重复性检查优化

src/common/metadata/field_template.go, src/scene_server/topo_server/logics/field_template/compare.go, src/scene_server/topo_server/logics/field_template/compare_attr.go
=> 修复字段组合模版相关问题

src/ui/src/components/ui/flex-tag/index.vue, src/ui/src/i18n/lang/en.json, src/ui/src/views/field-template/children/field-diff.vue
=> fix: 字段组合模板问题修复

docs/support-file/changelog/release.md, docs/support-file/helm/Chart.yaml
=> 新增v3.10.27-feature-field-template-alpha5版本日志

src/ui/src/views/host-details/children/property.vue
=> fix: 修复业务集下主机详情样式异常问题

src/ui/src/views/field-template/edit-basic.vue
=> fix: 修改保存模板权限为编辑权限

src/common/metadata/process_bind_info.go, src/storage/dal/mongo/local/txn_manager.go
=> 进程绑定信息中enable为nil时调整为false

src/ui/src/components/model-manage/field-group/field-detail/index.vue
=> fix: 新建字段不显示枚举引用类型

src/scene_server/host_server/service/host.go
=> fix: search_host delete 500 limit

src/apiserver/service/http.go
=> 优化apiserver日志

src/common/util/lib.go, src/thirdparty/esbserver/esb.go, src/thirdparty/esbserver/esbutil/common.go, src/thirdparty/esbserver/login/api.go, src/thirdparty/esbserver/login/esbserv.go, src/web_server/common/definitions.go, src/web_server/middleware/login.go, src/web_server/service/service.go
=> 添加用户是否有应用访问权限检验

src/ui/src/views/model-manage/children/model-import-export/model-import-pane/index.vue, src/ui/src/views/model-manage/children/model-import-export/model-import-pane/model-import-editor.vue, src/ui/src/views/model-manage/children/model-import-export/step-pane.vue
=> fix: 模型管理中无法导入模型

src/ui/src/router/business-interceptor.js
- 修复业务拓扑三级路由(主机详情)未正确展示无权限页面的问题
=> fix: 修复业务拓扑三级路由(主机详情)未正确展示无权限页面的问题

src/scene_server/topo_server/logics/model/attribute.go
=> 修复表格类型删除列字段后报错问题

docs/support-file/helm/README.md
=> 修改helm chart文档链接

src/source_controller/coreservice/core/process/service_template.go
- xxxx
- xxxx
-修复进程模版相关接口鉴权时，查不到服务模版导致的鉴权问题
=> 修复进程模版相关接口鉴权时，查不到服务模版导致的鉴权问题

src/scene_server/topo_server/service/fulltextsearch.go
- xxxx
- xxxx
- 修复全文检索场景极小概率panic问题
=> 修复全文检索场景极小概率panic问题

src/scene_server/topo_server/logics/settemplate/sync_status.go
- xxxx
- xxxx
-修复集群模版实例展示列表总数错误的问题
=> 修复集群模版实例展示列表总数错误的问题

src/scene_server/topo_server/service/object_attribute.go
- xxxx
- xxxx
- 修复删除模型属性字段场景下错误的获取主机自动应用规则的问题
=> 修复删除模型属性字段场景下错误的获取主机自动应用规则的问题

src/thirdparty/esbserver/user/api.go, src/thirdparty/esbserver/user/esbserv.go, src/web_server/logics/department.go, src/web_server/logics/excel.go, src/web_server/logics/excel_util.go, src/web_server/logics/host.go, src/web_server/logics/inst.go, src/web_server/logics/netdevice.go, src/web_server/logics/netproperty.go, src/web_server/logics/util.go, src/web_server/service/host.go, src/web_server/service/inst.go, src/web_server/service/util.go
- xxxx
- xxxx
- 修复无法导出组织字段数据提示不存，实际该组织存在
=> 修复无法导出组织字段数据提示不存，实际该组织存在

src/scene_server/datacollection/collections/hostsnap/hostsnap.go
=> 调整主机磁盘容量计算方式

src/ui/src/hooks/use-sideslider.js, src/ui/src/views/dynamic-group/form/form.vue
=> fix: 修复动态分组二次确认弹窗错误

src/scene_server/topo_server/logics/inst/association.go, src/scene_server/topo_server/logics/logics.go, src/scene_server/topo_server/logics/operation/import_association.go
- xxxx
- excel导入关联关系时，对关联关系映射进行校验
- xxxx
=> excel导入关联关系时，对关联关系映射进行校验

scripts/Makefile, src/common/version/version.go, src/scene_server/admin_server/logics/index.go, src/scene_server/admin_server/upgrader/history/v3.0.8/addPresetObjects.go
ci使用的admin-server不进行同步表和索引的定时任务，防止和清库操作冲突
=> fix: ci failed

src/scene_server/host_server/service/service_initfunc.go, src/scene_server/proc_server/service/serviceinstance.go
=> 修复当不传模块id时，查询不到业务下的服务实例的问题

src/common/definitions.go, src/web_server/middleware/user/plugins/method/blueking/userinfo.go
- xxxx
- xxxx
- bugfix:cmdb多环境场景下会概率性出现循环登陆问题
=> bugfix:cmdb多环境场景下会概率性出现循环登陆问题

src/ac/parser/host.go
=> 修复 find_module_host_relation 鉴权失败的问题

docs/support-file/changelog/release.md
=> 添加v3.10.26-feature-auth-alpha4版本日志

src/ui/package.json, src/ui/src/components/ui/form/organization.vue
=> fix: 流水线编译报错修复

src/common/metadata/process_bind_info.go
=> 修复服务模板IP选项不可以置空的问题

docs/support-file/changelog/release.md
=> 添加v3.10.26-feature-auth-alpha5版本日志

src/ui/src/components/business-scope/preview.vue, src/ui/src/components/import-file/import-relation.vue, src/ui/src/components/search/foreignkey.vue, src/ui/src/views/dynamic-group/preview/preview.vue, src/ui/src/views/general-model/index.vue
- 修复预览动态分组查询对象是集群时异常的问题
- 修复云区域下拉选择超过1000条时获取不到的问题
=> cherry-pick已修复的问题

src/common/util/array.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.11.202309050900/delete_host_apply_rule.go, src/scene_server/admin_server/upgrader/y3.11.202309050900/pkg.go, src/scene_server/proc_server/service/servicetemplate.go, src/scene_server/topo_server/service/inst_module.go, src/source_controller/coreservice/core/hostapplyrule/rule.go, src/source_controller/coreservice/core/model/model.go
- 1. 删除模块和服务模板时，自动删除模块上的主机自动应用；
- 2. 编写upgrade，将之前删除的模块对应的自动应用规则删除
=> 1. 删除模块和服务模板时，自动删除模块上的主机自动应用；2. 编写upgrade，将之前删除的模块对应的自动应用规则删除

src/web_server/service/excel/core/host_func.go
- 修复没有自定义拓扑时，导出主机失败问题 close #7378
=> 修复没有自定义拓扑时，导出主机失败问题

src/web_server/service/excel/operator/inst/importer/importer.go
- 修复导入更新实例没有更新成功的问题 close #7392
=> 修复导入更新实例没有更新成功的问题

src/common/metadata/update.go, src/scene_server/topo_server/logics/model/attribute.go, src/source_controller/coreservice/core/model/attribute.go
- xxxx
- xxxx
- 修复表格类型字段，上下移动表格列后，点击保存不生效的问题
=> fix: table attribute update header order failed #7383

src/scene_server/event_server/sync/hostidentifier/common.go, src/scene_server/event_server/sync/hostidentifier/hostIdentifier.go
- 主机身份下发时，对安装1.0agent的window机器的文件owner特殊处理
=> 主机身份下发时，对安装1.0agent的window机器的文件owner特殊处理

docs/support-file/helm/templates/adminserver/adminserver-dpl.yaml, docs/support-file/helm/templates/apiserver/apiserver-dpl.yaml, docs/support-file/helm/templates/authserver/authserver-dpl.yaml, docs/support-file/helm/templates/cacheservice/cacheservice-dpl.yaml, docs/support-file/helm/templates/cloudserver/cloudserver-dpl.yaml, docs/support-file/helm/templates/coreservice/coreservice-dpl.yaml, docs/support-file/helm/templates/datacollection/datacollection-dpl.yaml, docs/support-file/helm/templates/eventserver/eventserver-dpl.yaml, docs/support-file/helm/templates/hostserver/hostserver-dpl.yaml, docs/support-file/helm/templates/operationserver/operationserver-dpl.yaml, docs/support-file/helm/templates/procserver/procserver-dpl.yaml, docs/support-file/helm/templates/synchronizeserver/synchronizeserver-dpl.yaml, docs/support-file/helm/templates/taskserver/taskserver-dpl.yaml, docs/support-file/helm/templates/toposerver/toposerver-dpl.yaml, docs/support-file/helm/templates/webserver/webserver-dpl.yaml
=> 调整chart探针默认配置

src/scene_server/topo_server/service/object_association.go
- 修复find_object_association接口没有权限可以查询到数据问题
=> 修复find_object_association接口没有权限可以查询到数据问题

src/ui/src/views/host-details/children/service-list.vue, src/ui/src/views/index/children/host-search.vue
=> fix: v3.11.2-alpha1 bugfix2

src/ui/src/components/search/float.vue, src/ui/src/components/search/int.vue, src/ui/src/components/ui/form/float.vue, src/ui/src/components/ui/form/int.vue
=> fix: 更新props 属性默认为对象返回值写法

src/ui/src/views/host-details/index.vue
=> fix: 来自资源池主机详情不展示node信息

src/common/index/compare.go
=> 修复map类型不一致导致索引重复创建的问题

src/scene_server/admin_server/upgrader/y3.12.202309211735/init_shared_cluster_table.go
=> 容器数据纳管问题修复

src/common/index/compare.go
=> 修复map类型不一致导致索引重复创建的问题 

src/source_controller/coreservice/core/instances/instance_validate.go, src/thirdparty/hooks/validator.go
=> 添加IsSkipValidateKeyHook的hook

src/scene_server/datacollection/collections/porter.go
=> 修复删除redis数据失败导致数据积压的问题

src/scene_server/topo_server/service/kube/public.go
=> 修复容器接口鉴权问题

src/ui/src/service/container/common.js
=> fix: 容器节点字段名称补充

src/apiserver/service/http.go
=> 告警信息添加app_code、user、rid

docs/support-file/helm/templates/job/bootstrap-job.yaml, docs/support-file/helm/templates/job/migrate-dataid-job.yaml, docs/support-file/helm/templates/job/migrate-db-job.yaml, docs/support-file/helm/templates/job/migrate-old-dataid-job.yaml
=> 调整job消失时间和运行时机

docs/support-file/helm/templates/job/bootstrap-job.yaml, docs/support-file/helm/templates/job/migrate-dataid-job.yaml, docs/support-file/helm/templates/job/migrate-db-job.yaml, docs/support-file/helm/templates/job/migrate-old-dataid-job.yaml
=> 调整job消失时间和运行时机 (#7436)

src/ui/.babelrc, src/ui/.gitignore, src/ui/builder/webpack/index.js, src/ui/builder/webpack/optimization.js, src/ui/builder/webpack/plugins.js, src/ui/package.json, src/ui/src/magicbox/index.js, src/ui/src/views/service-category/index.vue
=> pref: 提升构建性能

src/web_server/service/excel/operator/inst/importer/importer.go
- 修复导入实例超过100条时报错导入重复的问题 close #7453
=> 修复导入实例超过100条时报错导入重复的问题

docs/support-file/helm/Chart.yaml
=> 添加3.13.2版本chart

src/ui/src/dictionary/storage-keys.js, src/ui/src/store/modules/view/field-template.js
=> perf: 字段模版存储草稿方式变为sessionStorage方式

docs/support-file/config/templates/server#conf#common.yaml, docs/support-file/helm/templates/adminserver/configmap.yaml, docs/support-file/helm/values.yaml, scripts/init.py, src/scene_server/host_server/service/findhost.go
=> 新增“业务访问”的7个API增加开关设置

src/common/backbone/configcenter/viper.go
=> perf: optimize viper parser & add unmarshalKey method

src/ui/src/views/business-topology/pod/pod-list.vue, src/ui/src/views/host-details/children/property.vue
- 空样式规范
- 容器节点信息字段复制时出现多个提示的问题
=> fix: ui bugfix

src/ac/iam/viewer.go
=> 修复创建模型时偶现的注册权限中心重复的问题

src/scene_server/admin_server/iam/synciam.go
=> 表格字段模型不注册到权限中心

src/scene_server/admin_server/iam/synciam.go
=> 合入3.11.x分支代码

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.12.202310302130/add_business_set.go, src/scene_server/admin_server/upgrader/y3.12.202310302130/pkg.go
=> 创建默认业务集：“全业务-蓝盾测试部署专用”

src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/store/modules/api/object-model-classify.js, src/ui/src/views/model-manage/children/model-details/index.vue, src/ui/src/views/model-manage/index.vue
=> feat: 模型可以拖拽排序

src/common/logics/model.go
=> 修复权限注册时，多获取了表格模型导致失败的问题

src/ui/src/views/model-manage/index.vue
=> fix: 模型排序参数值优化

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.12.202311061800/add_sort_number_column.go, src/scene_server/admin_server/upgrader/y3.12.202311061800/pkg.go, src/source_controller/coreservice/core/model/model_crud.go
=> 修复模型调整顺序失效问题

src/ui/src/components/ui/form/form-multiple.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/mixins/form.js, src/ui/src/store/modules/view/host-details.js, src/ui/src/views/service-template/children/process-form.vue
=> fix: 修复实例详情未展示创建人创建时间等字段

src/apimachinery/apiserver/api.go, src/common/definitions.go, src/web_server/service/excel/operator/inst/exporter/inst_func.go, src/web_server/service/excel/operator/inst/exporter/param.go
- 调用SearchPlatformSetting失败问题
- 根据ip导出失效问题
- 调整每页为500
=> 修复导出数据相关问题

src/web_server/service/excel/core/field_func.go
=> 获取用户名称时串行处理

resources/language/default/enum.json, resources/language/en/enum.json, src/apimachinery/apiserver/api.go, src/common/definitions.go, src/common/logics/model.go, src/web_server/service/excel/core/field_func.go, src/web_server/service/excel/operator/inst/exporter/inst_func.go, src/web_server/service/excel/operator/inst/exporter/param.go
=> 合入3.11.x代码

src/ac/extensions/model.go
=> 按模型ID鉴权时跳过内置模型

src/ac/iam/initial_resource_creator_actions.go
=> 创建模型时，赋予模型查看权限

src/common/auditlog/cloud_account.go, src/common/auditlog/cloud_sync_task.go, src/common/auditlog/object.go, src/common/auditlog/object_classification.go, src/common/metadata/audit.go, src/common/metadata/classification.go, src/common/metadata/cloud.go, src/common/metadata/object.go, src/scene_server/topo_server/service/object.go
=> 修复某些审计记录和查询失败的问题

src/ui/builder/utils/grab-api-loader.js, src/ui/builder/utils/grab-api-plugin.js, src/ui/src/components/filters/store.js, src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/views/model-manage/children/model-details/index.vue
=> 主机固定展示的列配置优化

src/ui/src/components/modal/permission-resource-name.js, src/ui/src/dictionary/iam-auth.js, src/ui/src/views/field-template/children/field-manage.vue, src/ui/src/views/resource/children/host-options.vue
- 资源主机删除操作添加预鉴权
- 修复申请云资源发现任务权限时未正确展示资源名称的问题
=> 资源主机删除操作添加预鉴权及云资源发现任务权限资源名称未展示问题

src/common/auditlog/cloud_account.go, src/common/auditlog/cloud_sync_task.go, src/common/auditlog/object.go, src/common/auditlog/object_classification.go, src/common/metadata/audit.go, src/common/metadata/classification.go, src/common/metadata/cloud.go, src/common/metadata/object.go, src/scene_server/topo_server/service/object.go, src/source_controller/coreservice/service/model.go, src/web_server/service/excel/operator/model/operator.go
=> V3.11.x合入V3.12.x

src/ui/builder/utils/grab-api-loader.js, src/ui/src/components/model-manage/field-group/index.vue
=> fix: 修复模型列配置异常数据报错的问题

src/ui/src/views/host-details/children/info.vue, src/ui/src/views/resource/children/host-options.vue
- 复制管控区域IPv6添加中括号
- 修复容器主机拓扑展示与跳转问题
=> 复制管控区域IPv6添加中括号

docs/support-file/changelog/release.md, docs/support-file/helm/Chart.yaml
=> 添加3.12.3-feature-auth-alpha8版本日志

src/ui/src/views/dynamic-group/preview/preview-result.vue
=> fix: 空间级更换动态分组预览主机搜索接口

src/ui/src/components/ui/dot-menu/dot-menu.vue
=> fix: dot-menu传参问题

src/scene_server/host_server/service/hostapplyrule.go, src/scene_server/host_server/service/transfer.go, src/source_controller/coreservice/core/hostapplyrule/plan.go, src/source_controller/coreservice/core/hostapplyrule/rule.go, src/source_controller/coreservice/core/instances/instance_validate.go, src/source_controller/coreservice/service/service.go, src/thirdparty/hooks/validator.go
=> 添加主机状态相关hooks

src/ui/src/components/model-instance/relation/create.vue, src/ui/src/components/model-instance/relation/list-table.vue, src/ui/src/views/host-details/children/association-create.vue, src/ui/src/views/host-details/children/association-list-table.vue, src/ui/src/views/model-manage/index.vue, src/ui/src/views/model-manage/style.scss
=> 模型拖动排序和关联鉴权优化

src/ac/extensions/model.go, src/scene_server/topo_server/service/object.go
- 修复查询模型多鉴了内置和主线模型的问题 close #7558
=> 修复查询模型多鉴了内置和主线模型的问题

src/ui/src/setup/worker-task.js, src/ui/src/views/model-manage/index.vue
=> fix: 修复新添加模型的权限数据异常问题

src/source_controller/cacheservice/cache/host/host.go, src/source_controller/cacheservice/cache/host/lua.go
=> 修复设置agentID缓存数据错误问题

docs/support-file/config/templates/server#conf#common.yaml, docs/support-file/helm/templates/_helpers.tpl, docs/support-file/helm/templates/adminserver/configmap.yaml, src/web_server/app/options/options.go, src/web_server/app/server.go, src/web_server/service/index.go
=> 更新bkDesktopUrl配置为bkComponentApiUrl配置

src/ui/builder/config/index.js, src/ui/index.html, src/ui/src/components/layout/header.vue, src/ui/src/i18n/index.js, src/ui/src/setup/build-in-vars.js, src/ui/src/views/dynamic-group/index.vue, src/ui/src/views/model-association/index.vue, src/ui/src/views/model-manage/index.vue
=> chore: 更新文档中心地址

docs/support-file/dockerfile/adminserver/dockerfile, docs/support-file/dockerfile/apiserver/dockerfile, docs/support-file/dockerfile/authserver/dockerfile, docs/support-file/dockerfile/cacheservice/dockerfile, docs/support-file/dockerfile/cloudserver/dockerfile, docs/support-file/dockerfile/coreservice/dockerfile, docs/support-file/dockerfile/datacollection/dockerfile, docs/support-file/dockerfile/eventserver/dockerfile, docs/support-file/dockerfile/hostserver/dockerfile, docs/support-file/dockerfile/migrate/dockerfile, docs/support-file/dockerfile/monstache/dockerfile, docs/support-file/dockerfile/operationserver/dockerfile, docs/support-file/dockerfile/procserver/dockerfile, docs/support-file/dockerfile/synchronizeserver/dockerfile, docs/support-file/dockerfile/taskserver/dockerfile, docs/support-file/dockerfile/toposerver/dockerfile, docs/support-file/dockerfile/webserver/dockerfile
=> 修改dockerfile基础镜像地址

readme.md, readme_en.md
=> 调整功能说明文档地址

src/ui/src/components/ui/details/editable-field.vue, src/ui/src/directives/autofocus.js, src/ui/src/views/dynamic-group/form/form-property-selector.vue, src/ui/src/views/field-template/children/clone-dialog.vue, src/ui/src/views/model-manage/children/model-import-export/model-import-pane/model-package-upload.vue
=> fix: v-autofocus优化

docs/support-file/helm/templates/job/bootstrap-job.yaml
=> 处理resources配置缩进问题

src/common/rdapi/rdfunc.go, src/common/resource/jwt/jwt.go
=> 从配置文件配置项而非公钥文件中获取apigw公钥

src/ac/parser/host.go
- 修复add_host_to_business_idle接口鉴权问题
=> 修复add_host_to_business_idle接口鉴权问题

src/ui/src/views/dynamic-group/form/form.vue
=> fix: 动态分组点击预览弱网情况下没有search

docs/support-file/helm/templates/job/bootstrap-job.yaml, src/ac/parser/host.go
=> 合入3.11.x到3.12.x

docs/overview/upgrade-from-ce.md, docs/support-file/helm/templates/job/auth-job.yaml, docs/support-file/helm/templates/job/bootstrap-job.yaml, docs/support-file/helm/templates/job/migrate-dataid-job.yaml, docs/support-file/helm/templates/job/migrate-db-job.yaml, docs/support-file/helm/templates/job/migrate-old-dataid-job.yaml, docs/wiki/db_upgrade.md, scripts/init_auth.sh, scripts/init_db.sh, scripts/refresh_config.sh, src/ac/parser/parser.go, src/common/rdapi/rdfunc.go, src/scene_server/admin_server/service/authcenter.go, src/thirdparty/apigw/apigwutil/common.go, src/tools/cmdb_ctl/cmd/watch.go
=> cmdb分层问题修复

docs/apidoc/apigw/README.md, docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml, docs/apidoc/apigw/backend/en/get_biz_kube_cache_topo.md, docs/apidoc/apigw/backend/zh/get_biz_kube_cache_topo.md, docs/apidoc/apigw/backend/zh/list_kube_container_by_topo.md, docs/apidoc/apigw/bin/sync-apigateway.sh, docs/apidoc/apigw/definition.yaml, src/Makefile
=> 添加apigw网关同步配置和两个job专用接口文档

docs/support-file/changelog/release.md, docs/support-file/helm/Chart.yaml
=> 添加3.12.4-feature-auth-alpha12版本日志

docs/support-file/changelog_user/ch/v3.13.1_2023-12-27.md, docs/support-file/changelog_user/en/v3.13.1_2023-12-27.md
=> 新增v3.13.1用户版本日志

src/ui/src/components/search/enum.vue, src/ui/src/components/search/enummulti.vue, src/ui/src/components/search/foreignkey.vue, src/ui/src/components/search/list.vue, src/ui/src/components/search/service-template.vue, src/ui/src/components/search/timezone.vue, src/ui/src/components/ui/form/timezone.vue, src/ui/src/components/ui/selector/cloud.vue, src/ui/src/components/ui/selector/service-category.vue, src/ui/src/views/audit/children/audit-action-selector.vue, src/ui/src/views/field-template/children/unique-manage.vue, src/ui/src/views/model-manage/children/model-details/verification-detail.vue
=> fix: 下拉框多选样式/UI更新

src/web_server/service/excel/operator/inst/exporter/inst_func.go, src/web_server/service/excel/operator/inst/exporter/property_func.go, src/web_server/service/excel/operator/inst/importer/inst_func.go
=> 主机导出Excel时，管控区域字段带上ID

src/scene_server/topo_server/service/inst_business_set.go
- issue：https://github.com/TencentBlueKing/bk-cmdb/issues/7683
=> 修复list_business_set接口时间条件设置失效问题

src/source_controller/coreservice/core/model/attribute_curd.go
- xxxx
- xxxx
- 修复不同业务下的自定义字段冲突问题
=> 修复不同业务下的自定义字段冲突问题

src/ui/src/components/ui/form/inner-table/index.vue, src/ui/src/workers/iam.js
- 未开启权限时不发起预鉴权调用
- 业务实例表格字段查询传参优化解决鉴权问题
=> fix: 未开启权限时不发起预鉴权调用及业务表格字段查询传参优化

resources/language/default/web.json, src/web_server/service/excel/operator/inst/importer/importer.go
=> 导入没数据的excel提示「未检测到任何数据需要导入」

src/source_controller/coreservice/core/instances/instance_validate.go, src/source_controller/coreservice/core/model/attribute_curd.go
=> merge v3.11.x into v3.13.x

src/scene_server/proc_server/service/serviceinstance.go
=> merge 3.11.x into 3.13.x

src/ui/src/views/service-template/children/template-config.vue, src/ui/src/views/set-template/children/template-config.vue
=> 修复服务模版中删除进程后，弹框不消失问题

resources/language/default/common.json, resources/language/en/common.json, src/web_server/logics/object.go, src/web_server/service/object.go
=> 修复模型导入属性字段顺序错乱问题

src/test/host_server/host_test.go, src/test/test.go
=> 修复测试用例偶现失败的问题

docs/support-file/config/templates/server#conf#common.yaml, docs/support-file/helm/templates/adminserver/configmap.yaml, docs/support-file/helm/values.yaml, src/common/resource/jwt/jwt.go
=> 新增api-server使用的jwt配置

docs/support-file/dockerfile/apigw/dockerfile, docs/support-file/helm/templates/job/apigw-job.yaml, docs/support-file/helm/values.yaml
=> 添加调用apigw注册网关配置的dockerfile和job

docs/apidoc/apigw/definition.yaml, docs/support-file/changelog/release.md, docs/support-file/helm/Chart.yaml
=> 新增v3.13.2-feature-job-beta1版本日志

src/scene_server/admin_server/service/dataid.go, src/thirdparty/esbserver/gse/api.go
=> 修复注册旧dataid失败问题

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml
=> docs: change job api userVerifiedRequired to false

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml, src/apimachinery/apiserver/api.go, src/apimachinery/apiserver/apiserver.go, src/apiserver/service/count.go, src/apiserver/service/service.go, src/common/metadata/common.go, src/web_server/logics/object.go, src/web_server/middleware/login.go
=> /object/count兼容获取内置模型实例数量的场景

src/web_server/service/index.go
=> 添加前端配置publicPath

docs/apidoc/apigw/backend/zh/add_host_to_resource.md, docs/apidoc/apigw/backend/zh/create_business.md, docs/apidoc/apigw/backend/zh/create_module.md, docs/apidoc/apigw/backend/zh/create_set.md, docs/apidoc/apigw/backend/zh/delete_host.md, docs/apidoc/apigw/backend/zh/delete_module.md, docs/apidoc/apigw/backend/zh/delete_set.md, docs/apidoc/apigw/backend/zh/get_host_base_info.md, docs/apidoc/apigw/backend/zh/search_biz_inst_topo.md, docs/apidoc/apigw/backend/zh/search_business.md, docs/apidoc/apigw/backend/zh/search_inst_by_object.md, docs/apidoc/apigw/backend/zh/search_module.md, docs/apidoc/apigw/backend/zh/search_set.md, docs/apidoc/apigw/backend/zh/transfer_host_module.md, docs/apidoc/apigw/backend/zh/transfer_host_to_faultmodule.md, docs/apidoc/apigw/backend/zh/transfer_host_to_idlemodule.md, docs/apidoc/apigw/backend/zh/transfer_host_to_resourcemodule.md, docs/apidoc/apigw/backend/zh/transfer_resourcehost_to_idlemodule.md, docs/apidoc/apigw/backend/zh/update_business.md, docs/apidoc/apigw/backend/zh/update_host.md, docs/apidoc/apigw/backend/zh/update_module.md, docs/apidoc/apigw/backend/zh/update_set.md
=> 添加老esb接口的apigw文档

.gitignore, src/ui/builder/config/index.js, src/ui/builder/utils/replace-static-url-plugin.js, src/ui/builder/webpack/index.js, src/ui/builder/webpack/plugins.js, src/ui/index.html, src/ui/login.html, src/ui/src/App.vue, src/ui/src/components/instance/association/graphics.js, src/ui/src/public-path.js, src/ui/src/views/model-topology/index.new.vue, src/ui/static/403.html
=> chore: 构建可指定publicPath以支持子目录部署

src/web_server/middleware/user/plugins/method/blueking/userinfo.go, src/web_server/service/util.go
- 修复在获取用户数据时并发读写Hearder导致webserver服务panic的问题
=> 修复在获取用户数据时并发读写Hearder导致webserver服务panic的问题

docs/support-file/helm/templates/apiserver/apiserver-svc.yaml, docs/support-file/helm/templates/apiserver/ingress.yaml, docs/support-file/helm/values.yaml
=> apiserver添加ingress

src/scene_server/topo_server/service/object_association.go, src/web_server/service/excel/core/asst_func.go
- 修复未开启鉴权的情况下下载导入主机Excel模板报错的问题
close #7793
=> 修复未开启鉴权的情况下下载导入主机Excel模板报错的问题

src/common/metadata/inst.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.13.202402181900/pkg.go, src/scene_server/admin_server/upgrader/y3.13.202402181900/update_biz_set_desc_field.go
=> 修改‘业务集描述’字段为bk_biz_set_desc

resources/language/default/common.json, resources/language/en/common.json, src/common/metadata/attribute.go, src/web_server/service/excel/operator/model/operator.go
=> 修复模型导入属性字段顺序错乱、字段所属分组错乱问题

src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.13.202402191140/migrate_inner_classification.go, src/scene_server/admin_server/upgrader/y3.13.202402191140/pkg.go
- 修复内置模型分组下新建模型报错的问题
close #7809
=> 修复内置模型分组下新建模型报错的问题

docs/apidoc/cc/en/list_project.md, docs/apidoc/cc/zh_hans/list_project.md, docs/apidoc/esb-cc/en/search_business.md, docs/apidoc/esb-cc/zh_hans/search_business.md, src/common/metadata/toposerver.go, src/common/paraparse/app.go, src/scene_server/topo_server/service/inst_business.go, src/scene_server/topo_server/service/project.go
=> 修复业务不支持时间类型查询问题

src/ui/src/components/model-instance/property.vue, src/ui/src/utils/tools.js, src/ui/src/views/business/index.vue, src/ui/src/views/host-details/children/property.vue, src/ui/src/views/project/index.vue
=> 修复业务和项目时间类型查询问题及模型实例属性页面中字段默认值展示错误

src/scene_server/datacollection/collections/hostsnap/hostsnap.go
=> 自动发现主机CPU架构字段

docs/apidoc/apigw/backend/en/list_project.md, docs/apidoc/apigw/backend/en/search_business.md, docs/apidoc/apigw/backend/zh/list_project.md, docs/apidoc/apigw/backend/zh/search_business.md
=> search_business接口文档添加time_condition参数

src/ui/src/components/model-instance/property.vue, src/ui/src/views/host-details/children/property.vue
=> fix: 模型实例属性编辑时应不使用默认值

src/ui/src/components/filters/store.js, src/ui/src/components/filters/utils.js, src/ui/src/views/index/children/host-search.vue
=> fix: 高级筛选条件索引设置

src/ui/src/views/business-topology/children/node-extra-info-service-template.vue, src/ui/src/views/business-topology/children/node-extra-info-set-template.vue, src/ui/src/views/business-topology/host/module-selector.vue, src/ui/src/views/index/children/host-search.vue, src/ui/src/views/model-association/index.vue, src/ui/src/views/model-manage/children/model-details/index.vue
- 业务集业务拓扑节点下，点击集群服务模板/模块服务模板跳转报错
- 提示优化
- 首页高级筛选当前页面跳转
=> fix: 业务集业务拓扑节点下，点击集群服务模板/模块服务模板跳转报错

src/common/definitions.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.13.202402281158/add_mac_os_type.go, src/scene_server/admin_server/upgrader/y3.13.202402281158/pkg.go, src/scene_server/datacollection/collections/hostsnap/hostsnap.go
=> 操作系统类型新增"MacOS"

docs/apidoc/apigw/bin/sync-apigateway.sh, docs/apidoc/apigw/definition.yaml
=> 调整apigw注册脚本

src/scene_server/datacollection/collections/hostsnap/hostsnap.go, src/source_controller/cacheservice/cache/host/lua.go
- 当根据agentid消费采集器数据，查不到主机时，设置空字符串缓存
=> 当根据agentid消费采集器数据，查不到主机时，设置空字符串缓存

src/common/http/header/accessor.go, src/common/http/header/util/util.go, src/common/resource/jwt/jwt.go
=> 调整apiserver接收的header头

src/common/querybuilder/types.go, src/common/querybuilder/validate.go
3.10.x修复在QueryFilter中设置时间条件不生效问题
=> 修复在QueryFilter中设置时间条件不生效问题

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml, docs/apidoc/apigw/backend/en/list_kube_cluster.md, docs/apidoc/apigw/backend/en/list_kube_container.md, docs/apidoc/apigw/backend/en/list_kube_namespace.md, docs/apidoc/apigw/backend/en/list_kube_node.md, docs/apidoc/apigw/backend/en/list_kube_pod.md, docs/apidoc/apigw/backend/en/list_kube_workload.md, docs/apidoc/apigw/backend/zh/list_kube_cluster.md, docs/apidoc/apigw/backend/zh/list_kube_container.md, docs/apidoc/apigw/backend/zh/list_kube_namespace.md, docs/apidoc/apigw/backend/zh/list_kube_node.md, docs/apidoc/apigw/backend/zh/list_kube_pod.md, docs/apidoc/apigw/backend/zh/list_kube_workload.md, docs/apidoc/apigw/definition.yaml
=> docs: add list kube resource apigw docs

docs/apidoc/archived/cache/refresh_kube_pod_label_cache.md, docs/support-file/helm/templates/cacheservice/cacheservice-dpl.yaml, scripts/init.py, src/common/util/array.go, src/source_controller/cacheservice/app/options/options.go, src/source_controller/cacheservice/app/server.go, src/source_controller/cacheservice/cache/biz-topo/key/kube.go, src/source_controller/cacheservice/cache/biz-topo/level/kube.go, src/source_controller/cacheservice/cache/biz-topo/topo.go, src/source_controller/cacheservice/cache/biz-topo/watch/kube.go, src/source_controller/cacheservice/cache/biz-topo/watch/watch.go, src/source_controller/cacheservice/cache/cache.go, src/source_controller/cacheservice/cache/custom/cache.go, src/source_controller/cacheservice/cache/custom/cache/cache.go, src/source_controller/cacheservice/cache/custom/cache/count.go, src/source_controller/cacheservice/cache/custom/cache/key.go, src/source_controller/cacheservice/cache/custom/cache/label.go, src/source_controller/cacheservice/cache/custom/cache/shared_ns_rel.go, src/source_controller/cacheservice/cache/custom/cache/string.go, src/source_controller/cacheservice/cache/custom/client.go, src/source_controller/cacheservice/cache/custom/types/types.go, src/source_controller/cacheservice/cache/custom/watch/label.go, src/source_controller/cacheservice/cache/custom/watch/shared_ns_rel.go, src/source_controller/cacheservice/cache/custom/watch/watch.go, src/source_controller/cacheservice/cache/token-handler/single.go, src/source_controller/cacheservice/cache/tools/kube.go, src/source_controller/cacheservice/service/cache.go, src/source_controller/cacheservice/service/service.go, src/source_controller/cacheservice/service/service_initfunc.go, src/storage/dal/mongo/local/mongo.go
- 添加按业务维度的 pod label 的 key 和 value 的缓存
=> 添加按业务维度的 pod label 的 key 和 value 的缓存

src/common/metrics/metrics.go
- webserver统计请求量的metrics添加用户标签
=> webserver统计请求量的metrics添加用户标签

resources/language/default/fieldtype.json, resources/language/default/import_instance.json, resources/language/en/fieldtype.json, resources/language/en/import_instance.json, src/scene_server/topo_server/logics/operation/import_association.go
- 实例Excel导入模板中表格、组织、列表三个字段类型名称显示为中文
- 调整Excel导入关联时实例字段不属于选定的唯一校验时的报错信息
=> excel相关文本优化

src/common/querybuilder/types.go, src/common/querybuilder/validate.go
=> 修复部分接口在filter中设置时间条件不生效问题

src/common/metadata/field_template.go, src/source_controller/coreservice/service/field_template/field_template.go
=> 字段组合模板创建增加超过10000个的数量限制

docs/apidoc/apigw/backend/en/search_set.md, docs/apidoc/apigw/backend/zh/search_set.md
=> 调整search_set接口文档

src/ac/iam/initial_resource_creator_actions.go, src/scene_server/topo_server/service/inst_business_set.go
- 新建业务集后，有对应新建业务集的编辑、删除、查看权限(IAM SaaS >= 1.10.19)
=> 新建业务集后，有对应新建业务集的编辑、删除、查看权限(IAM SaaS >= 1.10.19)

docs/apidoc/esb-cc/en/search_set.md, docs/apidoc/esb-cc/zh_hans/search_set.md, src/common/metadata/toposerver.go, src/scene_server/topo_server/service/inst_set.go
=> search_set接口添加filter查询参数

src/ui/src/assets/scss/model-manage.scss, src/ui/src/components/audit-history/details-slider.vue, src/ui/src/components/columns-config/columns-config.vue, src/ui/src/components/export-file/export.vue, src/ui/src/components/filters/filter-form.vue, src/ui/src/components/filters/general-model-filter-form.vue, src/ui/src/components/import-file/import.vue, src/ui/src/components/import/import.vue, src/ui/src/components/model-instance/relation/create.vue, src/ui/src/components/model-manage/field-group/field-detail/index.vue, src/ui/src/components/model-manage/field-group/field-view.vue, src/ui/src/components/model-manage/field-group/preview-field.vue, src/ui/src/components/ui/details/details.vue, src/ui/src/components/ui/form/form-multiple.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/views/business-set/children/management-form.vue, src/ui/src/views/business-synchronous/children/service-instance-details.vue, src/ui/src/views/cloud-account/children/account-details.vue, src/ui/src/views/cloud-account/children/account-form.vue, src/ui/src/views/cloud-resource/children/task-details-history.vue, src/ui/src/views/cloud-resource/children/task-details-info.vue, src/ui/src/views/cloud-resource/children/task-details.vue, src/ui/src/views/cloud-resource/children/task-form.vue, src/ui/src/views/dynamic-group/form/form.vue, src/ui/src/views/field-template/children/field-diff-details-drawer.vue, src/ui/src/views/field-template/children/model-field-selector.vue, src/ui/src/views/host-details/children/association-create.vue, src/ui/src/views/service-template/children/process-form.vue
=> fix: 抽屉两边间距样式规范更新 

src/ui/src/assets/scss/_mixins.scss, src/ui/src/components/condition-picker/property-selector.vue, src/ui/src/components/filters/filter-tag-ip.vue, src/ui/src/components/host-topo-path/host-topo-path.vue, src/ui/src/components/ui/flex-tag/index.vue, src/ui/src/components/ui/form/longchar.vue, src/ui/src/components/ui/form/search-input.vue, src/ui/src/magicbox/magicbox.scss, src/ui/src/views/business-set-topology/children/topology-tree.vue, src/ui/src/views/business-topology/children/create-set.vue, src/ui/src/views/business-topology/children/topology-tree.vue, src/ui/src/views/dynamic-group/form/form-property-selector.vue, src/ui/src/views/dynamic-group/form/form.vue, src/ui/src/views/field-template/children/bind-model.vue
=> fix: 滚动条样式规范更新

src/ui/src/components/ui/other/user-value.vue, src/ui/src/views/dynamic-group/form/form.vue, src/ui/src/views/dynamic-group/preview/preview-result.vue
=> fix: “集群”的动态分组预览时，出现重复的集群

resources/language/default/property.json, resources/language/default/property_group.json, resources/language/en/property_group.json, src/common/definitions.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.13.202403151855/migrate_host_message.go, src/scene_server/admin_server/upgrader/y3.13.202403151855/pkg.go
=> 修改主机字段分组和字段的相关文案

src/ui/.npmrc, src/ui/package.json, src/ui/src/components/search/float.vue, src/ui/src/components/search/int.vue, src/ui/src/components/ui/form/float.vue, src/ui/src/components/ui/form/int.vue, src/ui/src/views/field-template/index.vue
=> 数值输入框上下调整时值默认从0开始

docs/apidoc/apigw/definition.yaml, docs/support-file/changelog/release.md, docs/support-file/helm/Chart.yaml
=> 新增3.13.5版本日志

docs/support-file/config/templates/server#conf#common.yaml, docs/support-file/helm/values.yaml, src/apimachinery/util/type.go, src/apiserver/app/server.go, src/common/http/httpclient/forwardclient.go, src/web_server/middleware/user/plugins/method/blueking/userinfo.go
- tls的insecureSkipVerify代码默认为false
=> tls的insecureSkipVerify代码默认为false

src/common/metrics/metrics.go
=> 调整metrics指标

docs/apidoc/cc/en/create_dynamic_group.md, docs/apidoc/cc/en/execute_dynamic_group.md, docs/apidoc/cc/en/get_dynamic_group.md, docs/apidoc/cc/en/search_dynamic_group.md, docs/apidoc/cc/en/update_dynamic_group.md, docs/apidoc/cc/zh_hans/create_dynamic_group.md, docs/apidoc/cc/zh_hans/execute_dynamic_group.md, docs/apidoc/cc/zh_hans/get_dynamic_group.md, docs/apidoc/cc/zh_hans/search_dynamic_group.md, docs/apidoc/cc/zh_hans/update_dynamic_group.md
=> 调整动态分组能力增强相关文档

src/ui/src/App.vue, src/ui/src/store/modules/global.js
=> fix: 修复appHeight未兼容公告栏的问题

src/ui/src/assets/scss/common.scss, src/ui/src/components/search/objuser.vue, src/ui/src/components/ui/form/user.vue, src/ui/src/views/audit/children/audit-host-options.vue, src/ui/src/views/audit/children/audit-user-selector.vue, src/ui/src/views/audit/index.vue, src/ui/src/views/service-template/children/process-form-property-table.vue, src/ui/src/views/service-template/children/process-form.vue, src/ui/src/views/service-template/children/process.vue, src/ui/src/views/service-template/children/template-config.vue
- 搜索时人员允许填入不存在的
- 服务模板支持查看进程详情
=> 搜索时人员允许填入不存在的及服务模板支持查看进程详情

src/ui/.npmrc, src/ui/src/components/ui/selector/clipboard.vue, src/ui/src/dictionary/ip-with-cloud-symbol.js, src/ui/src/views/business-topology/host/host-list-options.vue, src/ui/src/views/resource/children/host-options.vue
=> 主机列表复制字段交互优化

src/ui/src/App.vue, src/ui/src/api/index.js, src/ui/src/components/model-instance/property.vue, src/ui/src/components/model-manage/field-group/index.vue, src/ui/src/views/host-details/children/property.vue
=> 实例详情页中hover字段名称展示字段摘要

src/ui/src/components/ui/selector/business-mix.vue, src/ui/src/service/business-set/index.js
=> fix: 业务(集)选择器排序优化

src/scene_server/event_server/sync/hostidentifier/common.go, src/scene_server/event_server/sync/hostidentifier/hostIdentifier.go
=> 限制下发hostid文件大小

src/scene_server/topo_server/service/inst_business_set.go
=> 查询业务集简要信息接口支持排序

src/ui/src/views/field-template/details.vue
- 当模板被模型绑定后，hover详情内的删除按钮时出现tooltips提示
=> feat: 当模板被模型绑定后，hover详情内的删除按钮时出现tooltips提示

pkg/filter/rule.go
- 修复query filter中value没有填时报错的问题
=> 修复query filter中value没有填时报错的问题

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml, docs/apidoc/apigw/backend/en/batch_update_host_all_properties.md, docs/apidoc/apigw/backend/zh/batch_update_host_all_properties.md, docs/apidoc/apigw/definition.yaml, docs/support-file/helm/templates/job/apigw-job.yaml, docs/support-file/helm/values.yaml
=> 新增更新主机接口文档

src/apiserver/service/service.go, src/common/definitions.go, src/common/metadata/cloud.go, src/common/metadata/hostserver.go, src/common/util/lib.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.13.202404101100/add_unassigned_cloud_area.go, src/scene_server/admin_server/upgrader/y3.13.202404101100/change_default_area_default_field.go, src/scene_server/admin_server/upgrader/y3.13.202404101100/pkg.go, src/scene_server/admin_server/upgrader/y3.13.202404101100/update_cloud_area_place_holder.go, src/scene_server/host_server/service/cloudarea.go, src/scene_server/host_server/service/host.go, src/scene_server/host_server/service/service_initfunc.go, src/source_controller/coreservice/core/instances/instance_crud.go, src/web_server/service/excel/operator/inst/importer/importer.go
=> 新增“未分配”管控区域

src/web_server/middleware/login.go, src/web_server/service/login.go, src/web_server/service/service.go
=> 新增校验登录态接口is_login

src/ui/src/views/dynamic-group/form/form.vue
=> fix: 动态分组无法编辑/保存

src/scene_server/event_server/service/sync.go, src/scene_server/event_server/sync/hostidentifier/hostIdentifier.go, src/scene_server/event_server/sync/hostidentifier/task.go
=> 通过接口下发hostid，超过文件大小限制返回错误

src/ui/src/views/model-manage/children/model-import-export/model-import-pane/model-package-upload.vue
=> fix: 导入模型拖拽文件没有校验

src/ui/src/components/batch-selection-column/index.vue
- 项目/业务下勾选第一个实例后，当前页最后一个实例也一起勾选了
=> fix: 项目/业务下勾选第一个实例后，当前页最后一个实例也一起勾选了

src/ui/src/api/index.js
=> fix: 修正小窗登录地址

src/ui/src/views/dynamic-group/preview/preview-result.vue, src/ui/src/views/dynamic-group/store.js
=> fix: 动态分组“集群”预览有时间/日期字段接口报错

src/ui/package.json, src/ui/src/views/service-template/children/template-config.vue
=> fix: 查看服务模版进程配置可以快速切换

src/ui/src/components/filters/filter-form.vue, src/ui/src/views/index/children/host-search.vue, src/ui/src/views/resource/children/host-list.vue
=> fix: 修复主机IP搜索是否模糊参数设置

src/ui/src/views/dynamic-group/form/form.vue, src/ui/src/views/dynamic-group/preview/preview-result.vue
=> fix: 动态分组去掉折叠

src/source_controller/cacheservice/cache/biz-topo/logics/topo/queue.go
=> 修复容器拓扑缓存逻辑panic的问题

src/ui/src/components/model-instance/property.vue, src/ui/src/components/ui/form/float.vue, src/ui/src/components/ui/form/form-multiple.vue, src/ui/src/components/ui/form/form.vue, src/ui/src/components/ui/form/int.vue, src/ui/src/components/ui/form/longchar.vue, src/ui/src/components/ui/form/singlechar.vue, src/ui/src/components/ui/other/default-value-picker.vue, src/ui/src/mixins/edit-multiple-host.js, src/ui/src/utils/tools.js, src/ui/src/views/business-set/children/management-form.vue, src/ui/src/views/business-set/details.vue, src/ui/src/views/business/details.vue, src/ui/src/views/business/index.vue, src/ui/src/views/general-model/details.vue, src/ui/src/views/general-model/index.vue, src/ui/src/views/host-details/children/property.vue, src/ui/src/views/project/details.vue, src/ui/src/views/project/index.vue, src/ui/src/views/resource/children/host-options.vue
=> feat: 编辑场景下，对资源实例字段输入型默认值填入样式优化

src/ui/package.json, src/ui/src/views/business-topology/host/host-list.vue, src/ui/src/views/general-model/index.vue, src/ui/src/views/resource/children/host-list.vue
=> feat: 主机和通用实例表格支持shift一次性选择多个项

src/scene_server/host_server/logics/hostsearch.go
- 校验search_host接口传入的condition参数
=> 校验search_host接口传入的condition参数

resources/language/default/property.json, resources/language/en/property.json, src/common/definitions.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.13.202405080955/add_cloud_region_zone_attr.go, src/scene_server/admin_server/upgrader/y3.13.202405080955/pkg.go
=> 新增“云地域”、“云可用区”字段

src/ui/package.json
- 升级bk-magic-vue版本解决表格shift选择体验问题
=> fix: 升级bk-magic-vue版本解决表格shift选择体验问题

src/common/valid/attribute/attribute.go, src/scene_server/topo_server/logics/model/attribute.go, src/source_controller/coreservice/core/model/attribute_curd.go, src/source_controller/coreservice/service/field_template/attribute_template.go
=> 仅校验枚举类型字段的isMultiple字段

src/ui/package.json
- 锁定@swc/core版本解决workspace协议错误
=> fix: 锁定@swc/core版本解决workspace协议错误

src/ui/src/components/layout/header.vue, src/ui/src/utils/login-helper.js
=> feat: 退出添加注销token参数

docs/support-file/helm/templates/adminserver/configmap.yaml, docs/support-file/helm/values.yaml, src/web_server/app/options/options.go, src/web_server/app/server.go, src/web_server/service/index.go
=> 添加bkRepoUrl配置

docs/support-file/config/templates/server#conf#migrate.yaml, docs/support-file/helm/templates/adminserver/configmap.yaml, docs/support-file/helm/templates/job/migrate-old-dataid-job.yaml, docs/support-file/helm/values.yaml, scripts/init.py, src/scene_server/admin_server/app/options/options.go, src/scene_server/admin_server/app/server.go, src/scene_server/admin_server/service/dataid.go, src/scene_server/admin_server/service/service.go, src/thirdparty/apigw/gse/api.go, src/thirdparty/apigw/gse/common.go, src/thirdparty/apigw/gse/service.go, src/thirdparty/dataid/dataid.go, src/thirdparty/esbserver/gse/api.go, src/thirdparty/esbserver/gse/esbserv.go
- 将gse数据路由相关的esb接口切换为apigw接口，同时兼容了原调用esb接口的做法
=> 将gse数据路由相关的esb接口切换为apigw接口

src/ui/src/components/filters/store.js, src/ui/src/service/property/property.js, src/ui/src/store/modules/api/object-model-property.js, src/ui/src/views/dynamic-group/store.js
=> feat: 不展示未知的字段类型

src/common/resource/apigw/apigw.go, src/scene_server/event_server/app/server.go, src/thirdparty/apigw/apigw.go, src/web_server/app/server.go, src/web_server/service/service.go
=> apigw支持配置所需的应用

src/ui/src/service/global-config.js
=> fix: 修正页脚中的版本信息

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml
=> apigw不校验用户登录态

docs/support-file/helm/templates/adminserver/configmap.yaml, docs/support-file/helm/values.yaml, src/web_server/app/options/options.go, src/web_server/app/server.go, src/web_server/service/index.go
- 将bkRepoUrl配置更新为bkSharedResUrl
=> 将bkRepoUrl配置更新为bkSharedResUrl

docs/support-file/changelog_user/ch/v3.13.9_2024-06-17.md, docs/support-file/changelog_user/en/v3.13.9_2024-06-17.md
=> docs: 添加v3.13.9用户版本日志

src/scene_server/host_server/service/transfer.go
=> 修复主机转移未记录审计的问题

src/ui/src/router/business-interceptor.js, src/ui/src/service/business/search.js
=> fix: 业务归档后再点击业务会显示空白

src/ui/src/components/host-apply/property-confirm-table.vue, src/ui/src/components/instance/association/index.vue, src/ui/src/components/model-instance/relation/list-table.vue, src/ui/src/utils/util.js, src/ui/src/views/host-details/children/association-list-table.vue, src/ui/src/views/host-details/index.vue
=> 优化显示主机详情标题

src/ui/src/components/business-scope/preview.vue, src/ui/src/views/business-set-topology/children/service-instance/process/options.vue, src/ui/src/views/business-topology/service-instance/process/options.vue, src/ui/src/views/business/archived.vue, src/ui/src/views/history/index.vue, src/ui/src/views/model-association/index.vue, src/ui/src/views/service-template/index.vue, src/ui/src/views/set-template/children/template-instance.vue, src/ui/src/views/set-template/index.vue, src/ui/src/views/set-template/sync-history.vue
=> fix: 搜索框点击搜索图标后触发搜索

src/ui/src/components/model-instance/property.vue, src/ui/src/utils/tools.js, src/ui/src/views/host-details/children/property.vue
=> fix: 容器纳管下的模型字段hover去除字段展示功能

src/ui/src/views/business-set/children/management-form.vue, src/ui/src/views/set-template/sync-history.vue
=> fix: 集群模板同步历史点击enter触发不了搜索

src/ui/src/views/business-set/children/management-form.vue
=> fix: 业务集兼容业务类型范围值为非数组情况

src/ui/package.json
=> chore: 升级bkui组件库依赖

src/ui/src/store/modules/global-config.js
=> fix: 平台管理保存接口去除site和footer字段

src/ac/iam/initial_resource_creator_actions.go, src/scene_server/topo_server/logics/inst/project.go
=> 增加新建项目关联权限

src/common/paraparse/host.go
=> 主机模糊查询优化并增加IP数量限制

resources/language/default/placeholder.json, resources/language/en/placeholder.json, src/source_controller/coreservice/service/model.go, src/source_controller/coreservice/service/translate.go
=> 进程监听信息的tooltip显示支持中英文切换

src/scene_server/topo_server/service/kube/public.go, src/source_controller/coreservice/service/kube/node.go, src/source_controller/coreservice/service/kube/pod.go
=> 修复容器拓扑显示的主机数量与实际不符问题

src/web_server/logics/object.go
=> 修改资源目录中业务条目显示的数量为“未归档的业务数”

src/scene_server/host_server/logics/import.go
- add_host_to_resource、add_host_to_resource_pool接口支持添加单ipv6主机
=> add_host_to_resource、add_host_to_resource_pool接口支持添加单ipv6主机

src/common/metadata/dynamic_grouping.go
=> 更新动态分组支持的类型对应的操作符

src/ui/index.html, src/ui/src/utils/change-document-title.js
=> fix: 优化使用远程配置title的展示

src/ui/src/assets/scss/common.scss
=> perf: 优化table初始化时empty样式闪过

src/ui/src/components/ui/other/default-value-picker.vue, src/ui/src/utils/query-builder-operator.js, src/ui/src/utils/tools.js
主机和通用模型实例及动态分组统一支持大小写(不)敏感操作符（对主机参数特殊处理）
字段默认值显示优化
=> 主机和通用模型实例及动态分组统一支持大小写(不)敏感操作符（对主机参数特殊处理）

src/ui/src/components/model-instance/property.vue, src/ui/src/views/host-details/children/property.vue
=> feat: 实例详情字段信息中增加“用户提示”的展示

src/ui/src/components/instance/association/graphics-config.js, src/ui/src/components/instance/association/index.vue, src/ui/src/service/instance/association.js
=> fix: 修复模型实例关联拓扑图箭头指向问题

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml, docs/apidoc/apigw/definition.yaml, docs/support-file/helm/templates/job/apigw-job.yaml, docs/support-file/helm/values.yaml
=> apigw接口添加100的单接口QPS限制

src/web_server/logics/object.go
3.10修改资源目录中业务条目显示的数量为“未归档的业务数”
=> 3.10修改资源目录中业务条目显示的数量为“未归档的业务数”

resources/language/default/inst.json, resources/language/en/inst.json, src/source_controller/coreservice/multilingual/buildin_instance.go
=> 翻译”未分配“管控区域名称

docs/smart/web/app_desc.yaml
=> 调整SaaS配置文件

src/ui/src/components/export-file/export-task.vue, src/ui/src/components/export-file/export.vue, src/ui/src/components/export-file/state.js, src/ui/src/hooks/model/property.js, src/ui/src/views/business/index.vue, src/ui/src/views/project/index.vue
- 项目和业务导出按钮文案变更
- 项目导出去掉“项目图标”字段
- 项目和业务导出按钮文案变更
- 导出英文样式优化
=> fix: 项目导出去掉“项目图标”字段

src/ui/src/components/export-file/export-property.vue, src/ui/src/components/export-file/index.js, src/ui/src/components/export-file/state.js
=> fix: 导出字段选择变更加入二次退出确认

src/ui/src/directives/cursor.js, src/ui/src/setup/permission.js, src/ui/src/utils/query-builder-operator.js, src/ui/src/views/dynamic-group/form/form.vue, src/ui/src/views/index/index.vue
- 动态分组contains/contains(CS)保存/回显处理
- 首页全文检索未开启点击报错
=> fix: 动态分组contains/contains(CS)保存/回显处理

src/ui/src/components/filters/filter-form.vue, src/ui/src/components/filters/general-model-filter-form.vue, src/ui/src/directives/scroll.js
=> perf: scroll指令优化

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml
=> apigw新增批量创建模块接口

src/common/metadata/dynamic_grouping.go
- 动态分组新增contains和contains_s操作符
=> 动态分组新增contains和contains_s操作符

docs/apidoc/cc/zh_hans/list_kube_node.md, src/common/resource/jwt/jwt.go
=> 调整list_kube_node文档

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml, src/apimachinery/apiserver/api.go, src/apimachinery/apiserver/apiserver.go, src/apiserver/service/service.go, src/scene_server/topo_server/service/object.go, src/scene_server/topo_server/service/service_business_initfunc.go, src/web_server/logics/object.go
=> 模型实例页面查询实例数接口不鉴权

src/common/metadata/audit.go
- xxxx
- xxxx
- 修复操作审计—>其他Tab，操作对象=模型分组、模型，动作有误问题
=> 修复操作审计—>其他Tab，操作对象=模型分组、模型，动作有误问题

docs/support-file/helm/templates/coreservice/coreservice-dpl.yaml, docs/support-file/helm/values.yaml, pkg/id-gen/types.go, src/common/metadata/audit.go, src/common/metadata/configadmin.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/service/configadmin.go, src/scene_server/admin_server/upgrader/y3.13.202408071435/pkg.go, src/scene_server/admin_server/upgrader/y3.13.202408071435/update_config_admin.go, src/source_controller/coreservice/app/options/options.go, src/source_controller/coreservice/app/server.go, src/storage/dal/mongo/config.go, src/storage/dal/mongo/local/mongo.go
=> 支持通过平台管理配置ID生成器的步长和起始ID

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml, pkg/synchronize/types/protocol.go, pkg/synchronize/types/resource.go, src/ac/iam/adaptor.go, src/ac/iam/gen_id.go, src/ac/iam/initial_action_groups.go, src/ac/iam/initial_actions.go, src/ac/iam/types.go, src/ac/meta/resource.go, src/apimachinery/coreservice/synchronize/api.go, src/apimachinery/coreservice/synchronize/synchronize.go, src/apiserver/service/filter.go, src/apiserver/service/service.go, src/common/util/array.go, src/common/util/conv.go, src/scene_server/topo_server/service/service_initfunc.go, src/scene_server/topo_server/service/synchronize/service.go, src/scene_server/topo_server/service/synchronize/synchronize.go, src/source_controller/coreservice/core/core.go, src/source_controller/coreservice/core/synchronize/biz.go, src/source_controller/coreservice/core/synchronize/host.go, src/source_controller/coreservice/core/synchronize/instance.go, src/source_controller/coreservice/core/synchronize/synchronize.go, src/source_controller/coreservice/core/synchronize/util.go, src/source_controller/coreservice/service/service.go, src/source_controller/coreservice/service/service_initfunc.go, src/source_controller/coreservice/service/synchronize/service.go, src/source_controller/coreservice/service/synchronize/synchronize.go
=> 支持同步时带ID创建数据

src/ui/src/views/index/index.vue
=> fix: 首页了解更多链接优化

src/ui/package.json
=> chore: 依赖升级

docs/smart/web/extra-data/configure/readme.md, docs/smart/web/extra-data/configure/web.yaml.tmpl
=> 调整节点管理地址smart包配置

src/thirdparty/esbserver/gse/api.go
- fix:修复当streamTo不存在时，esb接口查询报错的问题
=> fix:修复当streamTo不存在时，esb接口查询报错的问题

docs/smart/web/extra-data/configure/readme.md, docs/smart/web/extra-data/configure/web.yaml.tmpl
=> 调整smart包环境变量

src/ui/src/components/layout/header.vue, src/ui/src/mixins/app.js, src/ui/src/utils/util.js, src/ui/src/views/dynamic-group/index.vue, src/ui/src/views/index/index.vue, src/ui/src/views/model-association/index.vue, src/ui/src/views/model-manage/index.vue
=> perf: 文档链接规范优化

src/ui/src/components/layout/header.vue
=> fix: 导航栏规范

src/scene_server/proc_server/service/serviceinstance.go
- 修复procserver map并发读写panic的问题
=> 修复procserver map并发读写panic的问题

src/ui/src/magicbox/magicbox.scss, src/ui/src/views/host-apply/children/topology-tree.vue, src/ui/src/views/index/children/full-text-search/search-bar.vue
- 批量删除未启动主机 集群跟模块同步置灰不能勾选
- 首页全文检索未输入任何值的时候自动聚焦输入框
- info组件title样式优化
=> fix:批量删除未启动主机 集群跟模块同步置灰不能勾选

src/ui/src/components/filters/filter-form.vue, src/ui/src/components/filters/filter-tag-form.vue, src/ui/src/components/filters/general-model-filter-form.vue, src/ui/src/components/filters/utils.js, src/ui/src/components/search/singlechar.vue, src/ui/src/utils/util.js
=> 高级筛选int/float支持 $in操作符

src/common/metadata/configadmin.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/service/configadmin.go, src/scene_server/admin_server/service/dataid.go, src/scene_server/admin_server/upgrader/configadmin.go, src/scene_server/admin_server/upgrader/y3.14.202410100930/pkg.go, src/scene_server/admin_server/upgrader/y3.14.202410100930/updateAdminConfigc.go, src/scene_server/datacollection/app/server.go
=> 平台配置业务快照名称配置修改为业务ID

src/scene_server/proc_server/service/servicetemplate.go
- 修复服务模板主机自动应用在备份负责人仅保留一个的情况下不生效的问题
=> 修复服务模板主机自动应用在备份负责人仅保留一个的情况下不生效的问题

src/common/index/collections/kube.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.13.202410091435/add_pod_table_node_index.go, src/scene_server/admin_server/upgrader/y3.13.202410091435/pkg.go
=> pod表临时添加nodeID索引

src/apimachinery/coreservice/transaction/client.go
=> 事务重试失败时返回错误

src/scene_server/auth_server/logics/fetch_instance_info.go, src/scene_server/auth_server/service/gen_method.go
- 集群和模块支持fetch_instance_info权限回调方法
用于job无权限跳转URL获取集群模块名称
=> 集群和模块支持fetch_instance_info权限回调方法

src/ui/src/views/business-set/index.vue, src/ui/src/views/field-template/children/use-template.js, src/ui/src/views/general-model/index.vue
=> fix: info样式优化

src/ui/src/components/filters/filter-form.vue, src/ui/src/components/filters/general-model-filter-form.vue, src/ui/src/dictionary/property-constants.js
=> fix: ID搜索为正整数

src/scene_server/event_server/sync/hostidentifier/common.go, src/scene_server/event_server/sync/hostidentifier/hostIdentifier.go, src/scene_server/event_server/sync/hostidentifier/task.go
=> 修复下发主机身份文件逻辑死循环问题

src/ui/src/api/custom-header.js, src/ui/src/api/index.js, src/ui/src/components/ui/selector/business-mix.vue, src/ui/src/utils/util.js, src/ui/src/workers/utils.js
=> 平台全量业务选择器卡顿优化

src/source_controller/coreservice/core/hostapplyrule/plan.go
=> fix: 增加自定义多选枚举字段主机应用

src/scene_server/event_server/app/app.go, src/scene_server/event_server/app/options/options.go, src/scene_server/event_server/app/server.go, src/scene_server/event_server/service/service.go
- 删除eventserver中无用的mongo client
=> 删除eventserver中无用的mongo client

src/ac/parser/topology.go
=> 修改audit dict接口鉴权

src/common/metadata/attribute.go, src/source_controller/coreservice/core/hostapplyrule/plan.go
- 自定义多选枚举字段主机自动应用后，主机转移失败
--bug=133146161
=> fix: 自定义多选枚举字段主机自动应用后，主机转移失败

src/ui/src/views/business-set/index.vue
=> fix: 表格操作列宽度兼容英文

src/ui/src/views/host-apply/index.vue
=> fix: 主机自动应用偶现选择模块后点击跳转创建没反应

docs/smart/web/app_desc.yaml
=> saas的描述文件调整

src/ui/src/components/model-manage/_create-model.vue, src/ui/src/components/ui/form/organization.vue
- 组织组件非多选字段结构改为数组
- 新建模型隐藏容器分组
=> fix: 组织组件非多选字段结构改为数组

docs/apidoc/inner/admin-server/get_sharding_db_config.md, docs/apidoc/inner/admin-server/get_tenant_db_relation.md, docs/apidoc/inner/admin-server/update_sharding_db_config.md, src/common/metadata/audit.go, src/scene_server/admin_server/app/server.go, src/scene_server/admin_server/service/service.go, src/scene_server/admin_server/service/sharding.go, src/storage/dal/mongo/config.go, src/storage/dal/mongo/local/mongo.go, src/storage/dal/mongo/local/types.go, src/storage/dal/mongo/sharding/mongo.go
=> 新增分库配置项相关接口

src/ui/src/setup/preload.js
=> chore: 修改自定义的http请求头名称

docs/apidoc/apigw/definition.yaml, docs/support-file/helm/backend/templates/job/auth-job.yaml, docs/support-file/helm/backend/templates/job/bootstrap-job.yaml, docs/support-file/helm/backend/templates/job/migrate-dataid-job.yaml, docs/support-file/helm/backend/templates/job/migrate-db-job.yaml, docs/support-file/helm/backend/templates/job/migrate-old-dataid-job.yaml, scripts/init_auth.sh, scripts/init_db.sh, scripts/refresh_config.sh, src/common/http/header/header.go, src/scene_server/admin_server/service/authcenter.go
- header中X-Bkcmdb-Supplier-Account调整为X-Bk-Tenant-Id
=> header中X-Bkcmdb-Supplier-Account调整为X-Bk-Tenant-Id

docs/apidoc/apigw/backend/en/batch_create_quoted_inst.md, docs/apidoc/apigw/backend/en/list_set_template_related_service_template.md, docs/apidoc/apigw/backend/zh/list_set_template_related_service_template.md, docs/apidoc/cc/en/list_set_template_related_service_template.md, docs/apidoc/cc/zh_hans/list_service_instance_by_set_template.md, src/common/metadata/attribute.go, src/common/metadata/audit.go, src/common/metadata/set_template.go, src/scene_server/topo_server/logics/settemplate/worker.go, src/scene_server/topo_server/service/internal_task.go, src/source_controller/coreservice/core/settemplate/set_template.go, src/source_controller/coreservice/service/field_template/field_template.go
=> TopoServer集群模版及模块引用逻辑调整

docs/apidoc/apigw/backend/en/batch_create_kube_node.md, docs/apidoc/apigw/backend/en/batch_create_kube_pod.md, docs/apidoc/apigw/backend/en/batch_delete_kube_cluster.md, docs/apidoc/apigw/backend/en/batch_delete_kube_pod.md, docs/apidoc/apigw/backend/en/create_kube_cluster.md, docs/apidoc/apigw/backend/en/list_kube_cluster.md, src/apimachinery/coreservice/field_template/attribute_template.go, src/common/metadata/field_template.go, src/common/metadata/inst.go, src/kube/types/cluster.go, src/kube/types/node.go, src/kube/types/pod.go, src/source_controller/coreservice/core/kube/kube.go, src/source_controller/coreservice/core/model/attribute_curd.go, src/source_controller/coreservice/service/field_template/attribute_template.go, src/source_controller/coreservice/service/field_template/field_template.go, src/source_controller/coreservice/service/field_template/unique_template.go, src/source_controller/coreservice/service/kube/cluster.go, src/source_controller/coreservice/service/kube/pod.go
=> TopoServer字段组合模版及容器部分上层调整

docs/apidoc/apigw/backend/en/create_service_instance.md, docs/apidoc/apigw/backend/en/list_process_related_info.md, docs/apidoc/apigw/backend/en/list_service_instance.md, docs/apidoc/apigw/backend/en/list_service_instance_by_host.md, docs/apidoc/apigw/backend/en/list_service_instance_by_set_template.md, docs/apidoc/apigw/backend/en/list_service_instance_detail.md, docs/apidoc/apigw/backend/zh/create_service_instance.md, docs/apidoc/apigw/backend/zh/list_process_related_info.md, docs/apidoc/apigw/backend/zh/list_service_instance.md, docs/apidoc/apigw/backend/zh/list_service_instance_by_host.md, docs/apidoc/apigw/backend/zh/list_service_instance_by_set_template.md, docs/apidoc/apigw/backend/zh/list_service_instance_detail.md, docs/apidoc/cc/en/create_service_instance.md, docs/apidoc/cc/en/list_process_related_info.md, docs/apidoc/cc/en/list_service_instance.md, docs/apidoc/cc/en/list_service_instance_by_set_template.md, docs/apidoc/cc/en/list_service_instance_detail.md, docs/apidoc/cc/zh_hans/create_service_instance.md, docs/apidoc/cc/zh_hans/list_process_related_info.md, docs/apidoc/cc/zh_hans/list_service_instance.md, docs/apidoc/cc/zh_hans/list_service_instance_by_host.md, docs/apidoc/cc/zh_hans/list_service_instance_detail.md, src/common/metadata/process.go, src/scene_server/admin_server/command/import.go, src/scene_server/proc_server/logics/processinstance.go, src/scene_server/proc_server/service/processinstance.go, src/scene_server/proc_server/service/serviceinstance.go, src/source_controller/coreservice/core/process/process_template.go, src/source_controller/coreservice/core/process/service_category.go, src/source_controller/coreservice/core/process/service_instance.go
- 业务逻辑支持多租户，调整procServer服务实例及业务集
=> 支持多租户procServer服务实例及业务集上层调整

docs/wiki/container-support.md
=> 完善快速体验cmdb文档

src/apimachinery/apiserver/api.go, src/apimachinery/apiserver/apiserver.go, src/apimachinery/apiserver/biz.go, src/test/business/business_test.go, src/test/topo_server/business_test.go, src/web_server/service/excel/core/inst_func.go, src/web_server/service/excel/core/object_func.go
=> 业务逻辑支持多租户，调整webserver

src/ac/extensions/types.go, src/ac/parser/util.go, src/apimachinery/adminserver/adminserver.go, src/apimachinery/adminserver/api.go, src/apimachinery/apiserver/api.go, src/apimachinery/apiserver/apiserver.go, src/common/auditlog/audit.go, src/common/metadata/cloud.go, src/scene_server/admin_server/upgrader/history/y3.9.202002131522/upgrade_cloud_area.go, src/test/test.go, src/test/txn/txn_test.go, src/web_server/middleware/user/owner.go, src/web_server/service/excel/core/topo_func.go
=> 多租户完善逻辑：调整遗留的租户相关逻辑

src/apimachinery/procserver/process/api.go, src/apimachinery/procserver/process/instance.go, src/common/metadata/object.go, src/common/metadata/process.go, src/scene_server/host_server/logics/host.go, src/scene_server/proc_server/service/processtemplate.go, src/test/proc_server/biz_set_test.go
- 添加procServer业务集进程实例、服务实例测试用例
=> 添加procServer业务集进程实例、服务实例测试用例

scripts/tongsuo.sh
- xxxx
- xxxx
macos 系统下安装tongsuo， 显示铜锁已经安装过的问题
=> fix: macos install tongsuo bug

src/ui/src/utils/tools.js
=> fix: 新建自定义模型，实例修改自定义字段为数字0不显示

src/common/definitions.go, src/scene_server/admin_server/imports.go, src/scene_server/admin_server/upgrader/y3.14.202502101200/addKernelVersionField.go, src/scene_server/admin_server/upgrader/y3.14.202502101200/pkg.go, src/scene_server/datacollection/collections/hostsnap/hostsnap.go
=> 主机模型-增加“操作系统内核版本”字段

src/web_server/service/object.go
=> 修复导出模型时的目录穿越问题

src/web_server/service/object.go
=> 3.13修复导出模型时的目录穿越问题

docs/apidoc/apigw/backend/bk_apigw_resources_bk-cmdb.yaml, docs/apidoc/apigw/definition.yaml, docs/support-file/helm/backend/templates/job/apigw-job.yaml, docs/support-file/helm/backend/values.yaml
=> apigw文档缩进调整

src/web_server/service/count.go
=> fix: batch searching hostID by moduleID

docs/support-file/helm/backend/templates/adminserver/adminserver-dpl.yaml, docs/support-file/helm/backend/templates/adminserver/configmap.yaml, docs/support-file/helm/backend/templates/apiserver/apiserver-dpl.yaml, docs/support-file/helm/backend/templates/authserver/authserver-dpl.yaml, docs/support-file/helm/backend/templates/cacheservice/cacheservice-dpl.yaml, docs/support-file/helm/backend/templates/cloudserver/cloudserver-dpl.yaml, docs/support-file/helm/backend/templates/coreservice/coreservice-dpl.yaml, docs/support-file/helm/backend/templates/datacollection/datacollection-dpl.yaml, docs/support-file/helm/backend/templates/eventserver/eventserver-dpl.yaml, docs/support-file/helm/backend/templates/hostserver/hostserver-dpl.yaml, docs/support-file/helm/backend/templates/monstache/monstache-dpl.yaml, docs/support-file/helm/backend/templates/operationserver/operationserver-dpl.yaml, docs/support-file/helm/backend/templates/procserver/procserver-dpl.yaml, docs/support-file/helm/backend/templates/servicemonitor.yaml, docs/support-file/helm/backend/templates/synchronizeserver/synchronizeserver-dpl.yaml, docs/support-file/helm/backend/templates/taskserver/taskserver-dpl.yaml, docs/support-file/helm/backend/templates/toposerver/toposerver-dpl.yaml, docs/support-file/helm/backend/values.yaml
=> docs: 更改容器化charts

docs/smart/web/app_desc.yaml, go.mod, go.sum, src/apimachinery/rest/request.go, src/apimachinery/rest/wrapper.go, src/apiserver/service/http.go, src/common/http/header/accessor.go, src/common/http/header/header.go, src/common/json/tool.go, src/common/metrics/metrics.go, src/thirdparty/apigw/cmdb/api.go, src/ui/src/api/custom-header.js, src/web_server/middleware/login.go, src/web_server/middleware/user/public.go, src/web_server/middleware/user/user.go, src/web_server/service/login.go, src/web_server/service/service.go, src/web_server/service/user.go
=> 优化json key替换逻辑

src/apimachinery/hostserver/apis.go, src/apimachinery/hostserver/hostserver.go, src/common/metadata/hostcontroller.go, src/common/metadata/hostserver.go, src/scene_server/host_server/service/findhost.go, src/test/host_server/host_dynamicgroup_test.go, src/test/host_server/host_relation_test.go, src/test/host_server/host_server_suite_test.go, src/test/test.go
=> 补充测试用例hostserver

docs/support-file/helm/backend/templates/adminserver/adminserver-dpl.yaml, docs/support-file/helm/backend/templates/apiserver/apiserver-dpl.yaml, docs/support-file/helm/backend/templates/authserver/authserver-dpl.yaml, docs/support-file/helm/backend/templates/cacheservice/cacheservice-dpl.yaml, docs/support-file/helm/backend/templates/cloudserver/cloudserver-dpl.yaml, docs/support-file/helm/backend/templates/coreservice/coreservice-dpl.yaml, docs/support-file/helm/backend/templates/datacollection/datacollection-dpl.yaml, docs/support-file/helm/backend/templates/eventserver/eventserver-dpl.yaml, docs/support-file/helm/backend/templates/hostserver/hostserver-dpl.yaml, docs/support-file/helm/backend/templates/monstache/monstache-dpl.yaml, docs/support-file/helm/backend/templates/operationserver/operationserver-dpl.yaml, docs/support-file/helm/backend/templates/procserver/procserver-dpl.yaml, docs/support-file/helm/backend/templates/taskserver/taskserver-dpl.yaml, docs/support-file/helm/backend/templates/toposerver/toposerver-dpl.yaml
=> docs: remove topoKey for charts

src/ui/src/service/auth.js, src/ui/src/store/modules/api/object-model-classify.js, src/ui/src/views/model-manage/children/collapse-group-title.vue, src/ui/src/views/model-manage/children/model-operation-list.vue, src/ui/src/views/model-manage/index.vue
=> feat: 优化cmdb模块数据量大时页面打开慢

docs/support-file/helm/backend/templates/job/auth-job.yaml, docs/support-file/helm/backend/values.yaml
=> 添加charts中iam-job配置项

src/apimachinery/discovery/discovery.go, src/apimachinery/discovery/discovery_mock.go, src/apimachinery/discovery/server.go, src/scene_server/cloud_server/app/server.go, src/scene_server/cloud_server/cloudsync/cloudsync.go, src/scene_server/cloud_server/cloudsync/taskscheduler.go, src/scene_server/datacollection/app/server.go, src/scene_server/datacollection/collections/hash.go, src/scene_server/topo_server/logics/settemplate/settemplate.go
=> 一致性哈希支持发现不同环境的服务

docs/support-file/helm/backend/templates/adminserver/adminserver-dpl.yaml, docs/support-file/helm/backend/templates/apiserver/apiserver-dpl.yaml, docs/support-file/helm/backend/templates/authserver/authserver-dpl.yaml, docs/support-file/helm/backend/templates/cacheservice/cacheservice-dpl.yaml, docs/support-file/helm/backend/templates/cloudserver/cloudserver-dpl.yaml, docs/support-file/helm/backend/templates/coreservice/coreservice-dpl.yaml, docs/support-file/helm/backend/templates/datacollection/datacollection-dpl.yaml, docs/support-file/helm/backend/templates/eventserver/eventserver-dpl.yaml, docs/support-file/helm/backend/templates/hostserver/hostserver-dpl.yaml, docs/support-file/helm/backend/templates/job/apigw-job.yaml, docs/support-file/helm/backend/templates/job/auth-job.yaml, docs/support-file/helm/backend/templates/job/bootstrap-job.yaml, docs/support-file/helm/backend/templates/job/migrate-dataid-job.yaml, docs/support-file/helm/backend/templates/job/migrate-db-job.yaml, docs/support-file/helm/backend/templates/job/migrate-old-dataid-job.yaml, docs/support-file/helm/backend/templates/monstache/monstache-dpl.yaml, docs/support-file/helm/backend/templates/operationserver/operationserver-dpl.yaml, docs/support-file/helm/backend/templates/procserver/procserver-dpl.yaml, docs/support-file/helm/backend/templates/synchronizeserver/synchronizeserver-dpl.yaml, docs/support-file/helm/backend/templates/taskserver/taskserver-dpl.yaml, docs/support-file/helm/backend/templates/toposerver/toposerver-dpl.yaml, docs/support-file/helm/backend/values.yaml, docs/support-file/helm/web/templates/webserver/webserver-dpl.yaml, docs/support-file/helm/web/values.yaml
=> feat: chart包支持imagePullSecret

src/common/http/header/accessor.go, src/common/metadata/configadmin.go, src/scene_server/datacollection/app/server.go, src/web_server/app/server.go, src/web_server/service/service.go
=> 添加兼容3.13版本的逻辑

docs/smart/web/extra-data/configure/web.yaml.tmpl, docs/support-file/helm/web/templates/webserver/configmap.yaml, docs/support-file/helm/web/values.yaml, src/common/definitions.go, src/common/metadata/webserver.go, src/storage/dal/mongo/local/mongo.go, src/storage/dal/mongo/local/mongo_test.go, src/web_server/app/options/options.go, src/web_server/app/server.go, src/web_server/middleware/user/plugins/method/opensource/userinfo.go, src/web_server/middleware/user/plugins/method/skip/userinfo.go, src/web_server/middleware/user/public.go, src/web_server/service/index.go, src/web_server/service/user.go
=> 添加前端DisplayName组件需要的参数
